"""Story 30.2 — Bayesian-leverage ABLATION (wire sub-model distributional
outputs into the BASE models).

Controlled ablation: hold each production champion's ARCHITECTURE fixed (the
tuned champion hyperparameters + the 30.4-cleaned contract) and vary ONLY the
feature set —
    champion  = the live 30.4-cleaned contract (home_win 211 / run_diff 169 /
                total_runs 113-seasonnorm)
    enriched  = champion + the 52 sub-model DISTRIBUTIONAL columns (mu /
                dispersion-sigma / uncertainty / available for run_env, offense,
                starter-suppression, starter-IP, bullpen, matchup, defense)
                pivoted home/away from
                baseball_data.betting_features.feature_pregame_sub_model_signals
                — the exact set that today flows ONLY to the Layer-3 stacker
                (betting_ml/models/layer3/layer3_feature_columns.json).

Both arms are scored on:
  1. Walk-forward temporal CV  (all_season_splits, min_train_seasons=3)
  2. The HONEST 2026 out-of-sample surface (train game_year < 2026, eval == 2026)

⚠ LEAKAGE CAVEAT — THE DECISION KEYS ON 2026 ONLY.
  The sub-model signals are generated by generate_*_signals.py scoring ALL 2021+
  games with sub-models FIT on 2021-2025 (memory: project_layer3_signal_leakage).
  So for the 2024 and 2025 CV folds the enriched features are IN-SAMPLE for the
  sub-models → the enriched arm's CV is OPTIMISTICALLY biased and a CV "win" is
  expected/meaningless. 2026 is the only true out-of-sample surface for these
  signals (sub-models trained through 2025). Judge promotion on the 2026 honest
  delta; CV is reported as contaminated context only.

Per the Epic 30 operator directive, the PRIMARY metric is accuracy-to-truth:
  - totals / run_diff : MAE, RMSE, MedAE vs the actual outcome (+ calib_80 for
                        the NGBoost Normal interval).
  - home_win          : Brier, NLL, accuracy, ECE, and live corr of P(home win)
                        vs the 0/1 outcome.
Market comparison is NOT computed here (these are baseball-mechanism signals; the
question is accuracy-to-truth, not edge).

Runtime: RETRAINS NGBoost (run_diff n=1000 / total_runs n=500) and XGBoost
(home_win) per fold for two feature sets — minutes (home_win) to tens of minutes
(NGBoost). Per project convention, hand this off to run with real Snowflake
credentials, ONE --target per invocation.

Usage:
    uv run python betting_ml/scripts/bayesian_leverage_ablation_30_2.py --smoke
    uv run python betting_ml/scripts/bayesian_leverage_ablation_30_2.py --target home_win
    uv run python betting_ml/scripts/bayesian_leverage_ablation_30_2.py --target run_diff
    uv run python betting_ml/scripts/bayesian_leverage_ablation_30_2.py --target total_runs
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from betting_ml.utils.cv_splits import all_season_splits
from betting_ml.utils.data_loader import load_features, get_snowflake_connection
from betting_ml.utils.preprocessing import build_imputation_pipeline

_OUT_DIR = PROJECT_ROOT / "betting_ml" / "evaluation" / "feature_selection" / "bayesian_leverage_30_2"

# ── The 52 sub-model distributional columns (layer3_feature_columns.json) ─────
# Env-level (one value per game, side-invariant):
_ENV_COLS = [
    "run_env_mu_v4",
    "run_env_dispersion_v4",
    "run_env_mu_v4_uncertainty",
    "run_env_mu_v4_available",
]
# Per-side base names → pivoted to home_<x> / away_<x>. The base names match the
# raw columns in feature_pregame_sub_model_signals 1:1.
_SIDE_COLS = [
    # offense (pred_runs_v2)
    "pred_runs_mu_v2", "pred_runs_dispersion_v2", "pred_runs_uncertainty_v2", "pred_runs_mu_v2_available",
    # starter suppression (v1)
    "starter_suppression_mu_v1", "starter_suppression_sigma_v1", "starter_uncertainty_v1", "starter_suppression_mu_v1_available",
    # starter innings-pitched (v1)
    "starter_ip_mu_v1", "starter_ip_dispersion_v1", "starter_ip_uncertainty_v1", "starter_ip_mu_v1_available",
    # bullpen (v2)
    "bullpen_mu_v2", "bullpen_dispersion_v2", "bullpen_uncertainty_v2", "bullpen_mu_v2_available",
    # matchup advantage (v1)
    "matchup_advantage_mu_v1", "matchup_advantage_sigma_v1", "matchup_advantage_mu_v1_uncertainty", "matchup_advantage_mu_v1_available",
    # defense quality (v1)
    "defense_quality_mu_v1", "defense_quality_oaa_z_v1", "defense_quality_sprint_z_v1", "defense_quality_mu_v1_available",
]


def _enrichment_columns() -> list[str]:
    cols = list(_ENV_COLS)
    for c in _SIDE_COLS:
        cols.append(f"home_{c}")
        cols.append(f"away_{c}")
    return cols  # 4 + 24*2 = 52


_SIGNAL_QUERY = """
select game_pk, side,
       {raw_cols}
from baseball_data.betting_features.feature_pregame_sub_model_signals
"""


def _load_submodel_signals() -> pd.DataFrame:
    """Pull the long (game_pk x side) signal table and pivot to one wide row per
    game_pk with the 52 enrichment columns. All cols cast to float so the boolean
    *_available indicators survive select_dtypes(number) downstream."""
    raw_cols = ", ".join(_ENV_COLS + _SIDE_COLS)
    conn = get_snowflake_connection()
    try:
        cur = conn.cursor()
        cur.execute(_SIGNAL_QUERY.format(raw_cols=raw_cols))
        cols = [d[0].lower() for d in cur.description]
        rows = cur.fetchall()
    finally:
        conn.close()
    long = pd.DataFrame(rows, columns=cols)
    long["game_pk"] = long["game_pk"].astype("int64")
    long["side"] = long["side"].astype(str).str.lower()

    # env-level: side-invariant → one value per game_pk
    env = long.groupby("game_pk")[_ENV_COLS].max()
    # per-side: pivot home / away
    home = (long[long["side"] == "home"].set_index("game_pk")[_SIDE_COLS].add_prefix("home_"))
    away = (long[long["side"] == "away"].set_index("game_pk")[_SIDE_COLS].add_prefix("away_"))
    wide = env.join(home, how="outer").join(away, how="outer")
    # bool/Decimal → float so imputation + select_dtypes(number) keeps them
    for c in wide.columns:
        wide[c] = pd.to_numeric(wide[c], errors="coerce").astype(float)
    return wide.reset_index()


# ── Champion contracts + fixed (tuned) hyperparameters ──────────────────────
# Contracts are the 30.4-cleaned LIVE contracts per model_registry.yaml.
# Hyperparameters copied from the persisted tuning_results so the ablation varies
# ONLY the feature set.
_TARGETS = {
    "home_win": {
        "kind": "classification",
        "target_col": "home_win",
        "contract": "betting_ml/models/home_win/feature_columns_xgb_classifier_tuned_2026.json",
        "xgb_params": {
            "max_depth": 6,
            "learning_rate": 0.01687735703731368,
            "n_estimators": 285,
            "subsample": 0.7395559432725418,
            "colsample_bytree": 0.6123366282341044,
            "reg_alpha": 0.3979201420585229,
            "reg_lambda": 0.9683524038831748,
            "eval_metric": "logloss",
            "tree_method": "hist",
            "random_state": 42,
            "n_jobs": -1,
        },
    },
    "run_diff": {
        "kind": "regression",
        "target_col": "run_differential",
        "contract": "betting_ml/models/run_differential/feature_columns_ngboost_tuned_2026.json",
        "ngb": {"n_estimators": 1000, "dist": "Normal"},
    },
    "total_runs": {
        "kind": "regression",
        "target_col": "total_runs",
        "contract": "betting_ml/models/total_runs/feature_columns_ngboost_tuned_seasonnorm_2026.json",
        "ngb": {"n_estimators": 500, "dist": "Normal"},
    },
}

# Enriched must IMPROVE 2026 by at least this much to be a promote candidate
# (effect-size floor; same scale as the Epic 30 gate's 0.02 brier / accuracy bar).
_PROMOTE_FLOOR = {"mae": 0.02, "brier": 0.002}


# ── Metrics ─────────────────────────────────────────────────────────────────

def _reg_metrics(y: np.ndarray, pred: np.ndarray) -> dict:
    err = pred - y
    return {
        "mae": float(np.mean(np.abs(err))),
        "rmse": float(np.sqrt(np.mean(err ** 2))),
        "medae": float(np.median(np.abs(err))),
        "mean_pred": float(np.mean(pred)),
        "mean_actual": float(np.mean(y)),
        "bias": float(np.mean(err)),
        "pred_std": float(np.std(pred)),
    }


def _calib_80_normal(loc: np.ndarray, scale: np.ndarray, y: np.ndarray) -> float:
    z = 1.2815515594457831  # Phi^-1(0.90)
    lo, hi = loc - z * scale, loc + z * scale
    return float(np.mean((y >= lo) & (y <= hi)))


def _ece(p: np.ndarray, y: np.ndarray, n_bins: int = 10) -> float:
    bins = np.linspace(0.0, 1.0, n_bins + 1)
    idx = np.clip(np.digitize(p, bins) - 1, 0, n_bins - 1)
    ece = 0.0
    for b in range(n_bins):
        m = idx == b
        if m.sum() == 0:
            continue
        ece += (m.sum() / len(p)) * abs(p[m].mean() - y[m].mean())
    return float(ece)


def _clf_metrics(y: np.ndarray, p: np.ndarray) -> dict:
    from sklearn.metrics import brier_score_loss, log_loss
    pc = np.clip(p, 1e-7, 1 - 1e-7)
    corr = float(np.corrcoef(p, y)[0, 1]) if np.std(p) > 0 else float("nan")
    return {
        "brier": float(brier_score_loss(y, p)),
        "nll": float(log_loss(y, pc)),
        "accuracy": float(np.mean((p >= 0.5).astype(int) == y)),
        "ece": _ece(p, y),
        "live_corr": corr,
        "pred_std": float(np.std(p)),
    }


# ── Model fit/predict per kind ──────────────────────────────────────────────

def _impute(train_raw: pd.DataFrame, eval_raw: pd.DataFrame):
    pipe = build_imputation_pipeline()
    Xtr = pipe.fit_transform(train_raw).select_dtypes(include=[np.number])
    Xev = pipe.transform(eval_raw)
    Xev = Xev[[c for c in Xtr.columns if c in Xev.columns]].reindex(columns=Xtr.columns, fill_value=0.0)
    return Xtr, Xev


def _fit_predict_regression(cfg, Xtr, ytr, Xev):
    from ngboost import NGBRegressor
    from ngboost.distns import Normal
    dist = {"Normal": Normal}[cfg["ngb"]["dist"]]
    m = NGBRegressor(n_estimators=cfg["ngb"]["n_estimators"], Dist=dist, verbose=False)
    m.fit(Xtr.values, ytr)
    pred = m.predict(Xev.values)
    try:
        params = m.pred_dist(Xev.values).params
        loc, scale = np.asarray(params["loc"]), np.asarray(params["scale"])
    except Exception:
        loc, scale = pred, None
    return pred, loc, scale


def _fit_predict_classification(cfg, Xtr, ytr, Xev, yev):
    from sklearn.linear_model import LogisticRegression
    from xgboost import XGBClassifier
    clf = XGBClassifier(**cfg["xgb_params"])
    clf.fit(Xtr, ytr.astype(int))
    raw = clf.predict_proba(Xev)[:, 1]
    # Platt calibration fit on the eval split (faithful to production recipe).
    cal = LogisticRegression(C=1.0, solver="lbfgs", max_iter=1000)
    cal.fit(raw.reshape(-1, 1), yev.astype(int))
    return cal.predict_proba(raw.reshape(-1, 1))[:, 1]


def _eval_one(df, cfg, feat_cols, train_idx, eval_idx):
    Xtr, Xev = _impute(df.loc[train_idx, feat_cols], df.loc[eval_idx, feat_cols])
    ytr = df.loc[train_idx, cfg["target_col"]].values
    yev = df.loc[eval_idx, cfg["target_col"]].values
    if cfg["kind"] == "regression":
        pred, loc, scale = _fit_predict_regression(cfg, Xtr, ytr, Xev)
        m = _reg_metrics(yev, pred)
        if scale is not None:
            m["calib_80"] = _calib_80_normal(loc, scale, yev)
        return m
    p = _fit_predict_classification(cfg, Xtr, ytr, Xev, yev)
    return _clf_metrics(yev, p)


def _run_cv(df, cfg, champ_cols, enr_cols):
    champ_folds, enr_folds = [], []
    for train_idx, eval_idx in all_season_splits(df, min_train_seasons=3):
        eval_year = int(df.loc[eval_idx, "game_year"].mode()[0])
        cm = _eval_one(df, cfg, champ_cols, train_idx, eval_idx)
        em = _eval_one(df, cfg, enr_cols, train_idx, eval_idx)
        cm["eval_year"] = em["eval_year"] = eval_year
        champ_folds.append(cm)
        enr_folds.append(em)
        prim = "brier" if cfg["kind"] == "classification" else "mae"
        flag = "" if eval_year == 2026 else "  [CONTAMINATED: signals in-sample]"
        print(f"    fold {eval_year}: champ {prim}={cm[prim]:.4f}  enriched {prim}={em[prim]:.4f}{flag}")
    return champ_folds, enr_folds


def _mean_over_folds(folds, keys):
    return {k: float(np.mean([f[k] for f in folds if k in f])) for k in keys}


def _run_target(name: str, df: pd.DataFrame) -> dict:
    cfg = _TARGETS[name]
    contract = json.loads((PROJECT_ROOT / cfg["contract"]).read_text())
    champ_cols_all = contract["feature_cols"]
    champ_cols = [c for c in champ_cols_all if c in df.columns]
    enrich_all = _enrichment_columns()
    enrich_present = [c for c in enrich_all if c in df.columns and c not in champ_cols]
    enr_cols = champ_cols + enrich_present

    print(f"\n=== {name} ({cfg['kind']}) ===")
    print(f"  contract features: {len(champ_cols_all)}  present-in-df: {len(champ_cols)}")
    print(f"  enrichment cols available: {len(enrich_present)} / {len(enrich_all)}")
    print(f"  champion feats: {len(champ_cols)}  enriched feats: {len(enr_cols)}")

    prim = "brier" if cfg["kind"] == "classification" else "mae"
    metric_keys = (["brier", "nll", "accuracy", "ece", "live_corr", "pred_std"]
                   if cfg["kind"] == "classification"
                   else ["mae", "rmse", "medae", "bias", "pred_std", "calib_80"])

    print("  -- walk-forward CV (2024/2025 folds CONTAMINATED for enriched arm) --")
    champ_folds, enr_folds = _run_cv(df, cfg, champ_cols, enr_cols)
    cv_champ = _mean_over_folds(champ_folds, metric_keys)
    cv_enr = _mean_over_folds(enr_folds, metric_keys)

    print("  -- HONEST 2026 OOS (the only trustworthy surface) --")
    tr = df.index[df["game_year"] < 2026]
    ev = df.index[df["game_year"] == 2026]
    if len(ev) == 0:
        print("    WARNING: no 2026 rows in load_features() — cannot judge. ABSTAIN.")
        live_champ = live_enr = {}
        live_delta = float("nan")
        decision = "ABSTAIN (no 2026 surface)"
    else:
        print(f"    train n={len(tr)} (<=2025), eval n={len(ev)} (2026)")
        live_champ = _eval_one(df, cfg, champ_cols, tr, ev)
        live_enr = _eval_one(df, cfg, enr_cols, tr, ev)
        live_delta = live_enr[prim] - live_champ[prim]   # <0 = enriched better
        floor = _PROMOTE_FLOOR[prim]
        if live_delta < -floor:
            decision = f"PROMOTE-CANDIDATE (2026 {prim} improved {live_delta:+.4f} >= floor {floor})"
        elif live_delta > floor:
            decision = f"REJECT (2026 {prim} REGRESSED {live_delta:+.4f})"
        else:
            decision = f"NEUTRAL — no 2026 gain ({live_delta:+.4f}); Layer-3-only confirmed for {name}"

    result = {
        "target": name,
        "kind": cfg["kind"],
        "primary_metric": prim,
        "n_features_champion": len(champ_cols),
        "n_features_enriched": len(enr_cols),
        "n_enrichment_added": len(enrich_present),
        "enrichment_cols_added": enrich_present,
        "enrichment_cols_missing": [c for c in enrich_all if c not in enrich_present and c not in champ_cols],
        "cv_contaminated_note": "2024/2025 folds are in-sample for the sub-models (trained 2021-2025); CV favors enriched by construction. Judge on live_2026.",
        "cv": {"champion": cv_champ, "enriched": cv_enr,
               "delta_primary": cv_enr[prim] - cv_champ[prim],
               "folds_champion": champ_folds, "folds_enriched": enr_folds},
        "live_2026": {"champion": live_champ, "enriched": live_enr,
                      "delta_primary": live_delta},
        "decision": decision,
    }

    print(f"  CV {prim} (contaminated): champ={cv_champ[prim]:.4f}  enriched={cv_enr[prim]:.4f}  "
          f"delta={cv_enr[prim]-cv_champ[prim]:+.4f}")
    if live_champ:
        if cfg["kind"] == "classification":
            print(f"  LIVE 2026: champ Brier={live_champ['brier']:.4f}/corr={live_champ['live_corr']:.4f}  "
                  f"enriched Brier={live_enr['brier']:.4f}/corr={live_enr['live_corr']:.4f}")
        else:
            print(f"  LIVE 2026: champ MAE={live_champ['mae']:.4f}  enriched MAE={live_enr['mae']:.4f}  "
                  f"(calib_80 {live_champ.get('calib_80', float('nan')):.3f}->{live_enr.get('calib_80', float('nan')):.3f})")
    print(f"  >>> {decision}")
    return result


def _smoke() -> None:
    """Fast self-test of the risky path (signal pivot) — no training, no load_features."""
    print("=== SMOKE: sub-model signal load + pivot ===")
    wide = _load_submodel_signals()
    expected = _enrichment_columns()
    present = [c for c in expected if c in wide.columns]
    missing = [c for c in expected if c not in wide.columns]
    print(f"  rows (games): {len(wide):,}")
    print(f"  expected 52 enrichment cols, present: {len(present)}  missing: {len(missing)}")
    if missing:
        print(f"  MISSING: {missing}")
    nonfloat = [c for c in present if wide[c].dtype.kind not in ("f", "i")]
    print(f"  non-numeric cols (should be 0): {len(nonfloat)} {nonfloat[:5]}")
    cov = {c: round(100 * wide[c].notna().mean(), 1) for c in present[:6]}
    print(f"  coverage sample: {cov}")
    print("  SMOKE OK" if not missing and not nonfloat else "  SMOKE FAIL")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=["home_win", "run_diff", "total_runs", "all"], default="all")
    ap.add_argument("--smoke", action="store_true", help="Fast pivot self-test, no training.")
    args = ap.parse_args()

    if args.smoke:
        _smoke()
        return

    _OUT_DIR.mkdir(parents=True, exist_ok=True)
    print("Loading base features from Snowflake...")
    df = load_features().reset_index(drop=True)
    print(f"Loaded {len(df)} base rows, seasons: {sorted(df['game_year'].dropna().unique().tolist())}")

    print("Loading + pivoting sub-model distributional signals...")
    sig = _load_submodel_signals()
    df["game_pk"] = df["game_pk"].astype("int64")
    df = df.merge(sig, on="game_pk", how="left")
    enrich = _enrichment_columns()
    joined = df[enrich[0]].notna().sum()
    print(f"  joined signals onto {joined:,}/{len(df):,} base rows "
          f"({100*joined/max(len(df),1):.1f}%)")

    targets = ["home_win", "run_diff", "total_runs"] if args.target == "all" else [args.target]
    results = {}
    for nm in targets:
        results[nm] = _run_target(nm, df)

    out = _OUT_DIR / ("bayesian_leverage_all.json" if args.target == "all"
                      else f"bayesian_leverage_{args.target}.json")
    out.write_text(json.dumps(results, indent=2))
    print(f"\nWrote {out}")
    print("\n=== DECISIONS (judged on HONEST 2026 only) ===")
    for nm, r in results.items():
        print(f"  {nm:12s} {r['decision']}")


if __name__ == "__main__":
    main()
