"""Card 4.8 — Integration smoke test for feature selection and model I/O.

When run directly this script:
  1. Loads the full feature dataset from Snowflake via load_features().
  2. Applies select_features() with default thresholds.
  3. Writes the canonical feature list to betting_ml/evaluation/feature_selection.md.
  4. Verifies all three protected features are retained.
  5. Verifies at least one multicollinear drop was recorded.
  6. Performs a save/load round-trip with a DummyClassifier fitted on retained features.
  7. Prints a summary table.

Exit 0 on success; non-zero with a descriptive message on any assertion failure.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Allow running as a script without installing the package.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from sklearn.dummy import DummyClassifier

from betting_ml.utils.data_loader import load_features
from betting_ml.utils.feature_selection import PROTECTED_FEATURES, select_features
from betting_ml.utils.model_io import load_model, save_model

TARGETS = ["total_runs", "run_differential", "home_win"]

_EVAL_DIR = Path(__file__).resolve().parents[1] / "evaluation"
_FEATURE_SELECTION_MD = _EVAL_DIR / "feature_selection.md"


def _write_feature_selection_md(
    retained: list[str],
    dropped: dict[str, str],
    corr_df,
) -> None:
    """Write the canonical feature list markdown file."""
    _EVAL_DIR.mkdir(parents=True, exist_ok=True)

    near_zero = {k: v for k, v in dropped.items() if v == "near_zero_correlation"}
    multicollinear = {
        k: v for k, v in dropped.items() if v.startswith("multicollinearity:")
    }

    # Build per-feature correlation rows for retained features.
    retained_rows: list[tuple[str, float, float, float, float]] = []
    for feat in sorted(retained):
        r_total = float(corr_df.get("total_runs", {}).get(feat, float("nan")))
        r_diff = float(corr_df.get("run_differential", {}).get(feat, float("nan")))
        r_win = float(corr_df.get("home_win", {}).get(feat, float("nan")))
        max_abs = max(
            abs(r_total) if not np.isnan(r_total) else 0.0,
            abs(r_diff) if not np.isnan(r_diff) else 0.0,
            abs(r_win) if not np.isnan(r_win) else 0.0,
        )
        retained_rows.append((feat, max_abs, r_total, r_diff, r_win))

    retained_rows.sort(key=lambda x: x[1], reverse=True)

    lines: list[str] = [
        "# Feature Selection — Canonical Feature List (Card 4.8)",
        "",
        "Generated by `betting_ml/scripts/validate_feature_selection.py`.",
        "This file is the **input contract** for Cards 4.9–4.11: only retained",
        "features may be passed to `fit()` calls in downstream model cards.",
        "",
        f"- **Total candidates evaluated:** {len(retained) + len(dropped)}",
        f"- **Retained:** {len(retained)}",
        f"- **Dropped (near-zero correlation):** {len(near_zero)}",
        f"- **Dropped (multicollinearity):** {len(multicollinear)}",
        "",
        "---",
        "",
        "## 1. Retained Features",
        "",
        "| Feature | max \\|r\\| | r (total_runs) | r (run_differential) | r (home_win) |",
        "|---|---|---|---|---|",
    ]
    for feat, max_r, r_total, r_diff, r_win in retained_rows:
        protected_marker = " *" if feat in PROTECTED_FEATURES else ""
        lines.append(
            f"| `{feat}`{protected_marker} | {max_r:.4f} "
            f"| {r_total:+.4f} | {r_diff:+.4f} | {r_win:+.4f} |"
        )

    lines += [
        "",
        "_\\* Protected feature — retained regardless of correlation._",
        "",
        "---",
        "",
        "## 2. Dropped — Near-Zero Correlation",
        "",
        "Features with max |r| < 0.02 across all three targets.",
        "",
        "| Feature | max \\|r\\| observed |",
        "|---|---|",
    ]

    # Re-compute max |r| for dropped near-zero features (stored in corr_df).
    for feat in sorted(near_zero):
        vals = [
            abs(corr_df.get(t, {}).get(feat, 0.0)) for t in TARGETS
        ]
        max_r = max(vals)
        lines.append(f"| `{feat}` | {max_r:.4f} |")

    lines += [
        "",
        "---",
        "",
        "## 3. Dropped — Multicollinearity",
        "",
        "Features dropped due to |r| > 0.85 with a retained feature.",
        "",
        "| Feature | Redundant with |",
        "|---|---|",
    ]
    for feat in sorted(multicollinear):
        retained_partner = multicollinear[feat].split(":", 1)[1]
        lines.append(f"| `{feat}` | `{retained_partner}` |")

    _FEATURE_SELECTION_MD.write_text("\n".join(lines) + "\n")
    print(f"  Wrote {_FEATURE_SELECTION_MD}")


def _fail(msg: str) -> None:
    print(f"\nFAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def main() -> None:
    print("=== Card 4.8 — Feature Selection Integration Smoke Test ===\n")

    # Step 1: Load data.
    print("Loading features from Snowflake...")
    df = load_features(min_games_played=15)
    n_total_rows = len(df)
    n_total_cols = len(df.columns)
    print(f"  {n_total_rows:,} rows × {n_total_cols} columns loaded.")

    # Step 2: Run feature selection.
    print("\nRunning select_features() with default thresholds...")
    retained, dropped = select_features(df, targets=TARGETS)
    n_candidates = len(retained) + len(dropped)
    n_near_zero = sum(1 for v in dropped.values() if v == "near_zero_correlation")
    n_multicol = sum(1 for v in dropped.values() if v.startswith("multicollinearity:"))
    print(f"  Candidates evaluated : {n_candidates}")
    print(f"  Retained             : {len(retained)}")
    print(f"  Dropped (near-zero r): {n_near_zero}")
    print(f"  Dropped (multicol.)  : {n_multicol}")

    # Step 3: Build corr dict for the markdown writer (recompute lightweight).
    import pandas as pd

    corr_lookup: dict[str, dict[str, float]] = {}
    all_feats = list(retained) + list(dropped.keys())
    numeric_candidates = [
        c for c in all_feats if c in df.columns and pd.api.types.is_numeric_dtype(df[c])
    ]
    for t in TARGETS:
        if t not in df.columns:
            continue
        y = df[t].astype(float)
        corrs: dict[str, float] = {}
        for c in numeric_candidates:
            x = df[c].astype(float)
            valid = x.notna() & y.notna()
            if valid.sum() < 10:
                corrs[c] = float("nan")
                continue
            import numpy as np
            r = np.corrcoef(x[valid], y[valid])[0, 1]
            corrs[c] = float(r) if not np.isnan(r) else float("nan")
        corr_lookup[t] = corrs

    # Step 4: Write feature_selection.md.
    print("\nWriting betting_ml/evaluation/feature_selection.md...")
    _write_feature_selection_md(retained, dropped, corr_lookup)

    # --- Assertions ---
    print("\nRunning assertions...")

    # Protected features must be retained.
    missing_protected = PROTECTED_FEATURES - set(retained)
    if missing_protected:
        _fail(f"Protected features missing from retained list: {missing_protected}")
    print(f"  [PASS] All protected features retained: {sorted(PROTECTED_FEATURES)}")

    # At least one multicollinear drop.
    if n_multicol < 1:
        _fail("Expected at least one multicollinear drop; none recorded.")
    print(f"  [PASS] At least one multicollinear drop recorded ({n_multicol} total).")

    # Step 5: save/load round-trip with DummyClassifier.
    print("\nPerforming save/load round-trip (DummyClassifier)...")
    feature_cols = [c for c in retained if c in df.columns]
    X = df[feature_cols].fillna(0.0).values
    y = df["home_win"].values
    clf = DummyClassifier(strategy="most_frequent")
    clf.fit(X, y)

    saved_path = save_model(clf, target="home_win", model_name="dummy_smoke", eval_year=2025)
    print(f"  Saved to: {saved_path}")
    loaded_clf = load_model(target="home_win", model_name="dummy_smoke", eval_year=2025)
    preds = loaded_clf.predict(X[:5])
    if len(preds) != 5:
        _fail("Loaded model prediction returned unexpected shape.")
    print("  [PASS] Round-trip save/load and predict succeeded.")

    # Clean up the smoke-test model file.
    import os

    os.remove(saved_path)
    print(f"  Cleaned up {saved_path}")

    # --- Summary table ---
    print("\n" + "=" * 55)
    print("SUMMARY")
    print("=" * 55)
    print(f"  Total features before selection : {n_candidates}")
    print(f"  Retained                        : {len(retained)}")
    print(f"  Dropped (near-zero correlation) : {n_near_zero}")
    print(f"  Dropped (multicollinearity)     : {n_multicol}")
    print()
    for pf in sorted(PROTECTED_FEATURES):
        status = "PASS" if pf in set(retained) else "FAIL"
        print(f"  Protected '{pf}': {status}")
    print("=" * 55)
    print("\nAll checks passed. Exit 0.")


if __name__ == "__main__":
    main()
