import { readFileSync } from "node:fs"
import { join } from "node:path"
import { expect, test, type Page } from "@playwright/test"
import { collectPageErrors, mockApi } from "../support/api-mock"
import { signIn } from "../support/session"
import { expectNoNaN, expectNoPageErrors } from "../support/assertions"
import {
  auctionPool,
  auctionValues,
  bidExplanation,
  dollarsPerSlot,
  formatMoney,
  formatMoneyRange,
  inflation,
  maxBid,
} from "@/lib/auction-optimizer"
import { type Player } from "@/lib/draft-optimizer"

/**
 * NF-C5 — THE AUCTION OPTIMIZER.
 *
 * Two halves, and the first is the important one.
 *
 * ══ 1. THE CROSS-LANGUAGE PIN ═══════════════════════════════════════════════════════════════════
 *
 * The auction math is implemented TWICE by necessity: in Python (`fantasy_engine/auction.py`, which
 * the exporter publishes `aucVal`/`aucLo`/`aucHi` from) and in TS (which recomputes live on every
 * bid, for the user's ACTUAL budget rather than the one the board was quoted at). This repo has
 * been bitten repeatedly by one rule with two implementations — E9.61's two renderers of a player
 * name, NF-EPIC 1's three scorers — so "keep them in sync" is not left to discipline.
 *
 * `quant_sports_intel_models/fantasy_engine/auction_vectors.json` is GENERATED by the Python
 * authority; `test_fantasy_auction_values.py` regenerates it and refuses any drift from the
 * committed bytes, and this file runs the TS through the SAME file. Move either side and one of the
 * two goes red.
 *
 * ⚠️ READ ACROSS THE TREE ON PURPOSE, not copied into `e2e/fixtures/` — the pattern
 * `ESPN_REAL_PASTES` already uses. A local copy would be a fixture that drifts from the one the
 * authority is tested against, which is the whole failure this guards.
 *
 * ══ 2. THE BROWSER FLOW ═════════════════════════════════════════════════════════════════════════
 *
 * The auction screen is a state machine driven for two hours while money moves. Its failures are
 * the kind no static gate sees: a budget that does not decrement, a won player who stays on the
 * board, a max bid that lets a user strand a roster spot.
 */

// ── the golden vectors ──────────────────────────────────────────────────────────────────────────

type Vectors = {
  board: { id: string; vor: number | null; vorP10: number | null; vorP90: number | null }[]
  pools: {
    nTeams: number
    rosterSpots: number
    budget: number
    pool: { total: number; reserve: number; surplus: number }
    values: { id: string; value: number; low: number; high: number; share: number }[]
  }[]
  maxBids: {
    case: string
    value: number
    inflationMultiplier: number
    budgetRemaining: number
    openSlots: number
    eligible: boolean
    maxBid: number
    inflated: number
    affordable: number
    binding: string
  }[]
  inflation: {
    case: string
    dollarsRemaining: number
    slotsRemaining: number
    remainingValues: number[]
    multiplier: number
    valueRemaining: number
  }[]
  dollarsPerSlot: { budgetRemaining: number; openSlots: number; perSlot: number }[]
}

const VECTORS: Vectors = JSON.parse(
  readFileSync(
    join(process.cwd(), "..", "quant_sports_intel_models", "fantasy_engine", "auction_vectors.json"),
    "utf8",
  ),
)

/** The vector board as `Player[]`. Only the fields the auction math reads are meaningful; the rest
 *  satisfy the shared `Player` shape. */
function vectorBoard(): Player[] {
  return VECTORS.board.map((r, i) => ({
    id: r.id,
    name: r.id,
    pos: "RB",
    team: "AAA",
    bye: null,
    rookie: false,
    g: 17,
    pts: null,
    repl: 0,
    vor: r.vor,
    posRank: i + 1,
    ovrRank: i + 1,
    vorP10: r.vorP10,
    vorP90: r.vorP90,
    ptsP10: null,
    ptsP90: null,
    adp: null,
    lowPred: false,
    predNote: null,
  }))
}

test.describe("the TS auction engine agrees with the Python authority", () => {
  test("the golden vectors are non-empty and cover every branch", () => {
    // ⚠️ ANTI-VACUITY FIRST. Every assertion below loops over the vectors; an empty (or truncated)
    // file would make all of them pass on nothing — the NF1.7(a) class, and the reason this repo
    // requires a loop-based guard to assert its own non-vacuity.
    expect(VECTORS.board.length).toBeGreaterThan(4)
    expect(VECTORS.pools.length).toBeGreaterThan(1)
    expect(VECTORS.maxBids.length).toBeGreaterThan(5)
    expect(VECTORS.inflation.length).toBeGreaterThan(3)
    expect(new Set(VECTORS.maxBids.map((c) => c.binding))).toEqual(
      new Set(["value", "affordability", "no_slot", "roster_full"]),
    )
  })

  test("every pool decomposes to the same total, reserve and surplus", () => {
    for (const p of VECTORS.pools) {
      const got = auctionPool(p.nTeams, p.rosterSpots, p.budget)
      expect(
        { total: got.total, reserve: got.reserve, surplus: got.surplus },
        `pool ${p.nTeams}x${p.rosterSpots}@$${p.budget}`,
      ).toEqual(p.pool)
    }
  })

  test("every player prices to the same dollar value and band", () => {
    const board = vectorBoard()
    for (const p of VECTORS.pools) {
      const got = auctionValues(board, auctionPool(p.nTeams, p.rosterSpots, p.budget))
      expect(got.length).toBe(p.values.length)
      for (let i = 0; i < got.length; i++) {
        expect(
          { id: got[i].id, value: got[i].value, low: got[i].low, high: got[i].high },
          `${p.values[i].id} at $${p.budget}`,
        ).toEqual({
          id: p.values[i].id,
          value: p.values[i].value,
          low: p.values[i].low,
          high: p.values[i].high,
        })
        expect(got[i].share).toBeCloseTo(p.values[i].share, 6)
      }
    }
  })

  test("every max bid, and the constraint that produced it, matches", () => {
    for (const c of VECTORS.maxBids) {
      const got = maxBid(c.value, c.inflationMultiplier, c.budgetRemaining, c.openSlots, {
        eligible: c.eligible,
      })
      expect(
        { maxBid: got.maxBid, inflated: got.inflated, affordable: got.affordable, binding: got.binding },
        c.case,
      ).toEqual({
        maxBid: c.maxBid,
        inflated: c.inflated,
        affordable: c.affordable,
        binding: c.binding,
      })
    }
  })

  test("every inflation reading matches", () => {
    for (const c of VECTORS.inflation) {
      const got = inflation(c.dollarsRemaining, c.remainingValues, c.slotsRemaining)
      expect(got.valueRemaining, c.case).toBe(c.valueRemaining)
      expect(got.multiplier, c.case).toBeCloseTo(c.multiplier, 6)
    }
  })

  test("dollars-per-slot matches, including the full-roster case", () => {
    for (const c of VECTORS.dollarsPerSlot) {
      expect(dollarsPerSlot(c.budgetRemaining, c.openSlots)).toBeCloseTo(c.perSlot, 6)
    }
  })
})

// ── the properties, in the browser's own language ───────────────────────────────────────────────

test.describe("the never-strand rule", () => {
  /** ⭐ THE PROPERTY THE OPTIMIZER EXISTS TO GUARANTEE, asserted over a GRID rather than at a few
   *  points — the failure mode is an off-by-one at the `openSlots - 1` boundary, which hand-picked
   *  cases are exactly the wrong instrument to find. Mirrors the Python grid test. */
  test("bidding the max always leaves a dollar for every remaining slot", () => {
    let feasibleChecked = 0
    for (const budget of [0, 1, 3, 9, 17, 40, 88, 200]) {
      for (const slots of [1, 2, 3, 6, 9, 16]) {
        for (const value of [1, 5, 40, 300]) {
          const bid = maxBid(value, 1, budget, slots)
          expect(bid.maxBid).toBeGreaterThanOrEqual(0)
          expect(bid.maxBid).toBeLessThanOrEqual(budget)

          // States that arrive ALREADY stranded ($1 in hand, 2 spots) cannot be undone by this
          // rule and must not be blamed on it; the obligation there is "do not make it worse".
          if (budget < slots) {
            expect(bid.maxBid, `spent from an already-stranded roster: $${budget}/${slots}`).toBe(0)
            continue
          }
          feasibleChecked++
          const leftAfter = budget - bid.maxBid
          const slotsAfter = slots - (bid.maxBid > 0 ? 1 : 0)
          expect(
            leftAfter,
            `stranded a slot: $${budget} with ${slots} open → bid $${bid.maxBid}`,
          ).toBeGreaterThanOrEqual(slotsAfter)
          // ...and the rule must not be satisfied by refusing to bid at all: a `maxBid` hardcoded
          // to 0 would pass every clause above.
          expect(bid.maxBid).toBeGreaterThanOrEqual(1)
        }
      }
    }
    expect(feasibleChecked, "the grid contained no feasible states — it asserted nothing").toBeGreaterThan(50)
  })

  test("the cap is inert while there is slack, and total at the end", () => {
    expect(maxBid(40, 1, 200, 16).binding).toBe("value")
    expect(maxBid(40, 1, 200, 16).maxBid).toBe(40)
    expect(maxBid(40, 1, 20, 6).binding).toBe("affordability")
    expect(maxBid(40, 1, 20, 6).maxBid).toBe(15)
  })
})

test.describe("inflation reads the room the right way round", () => {
  /** ⚠️ THE DIRECTION IS THE WHOLE SIGNAL and the half most often got backwards. A room that
   *  OVERPAYS leaves less money chasing the same value, so what remains gets CHEAPER. */
  test("overpaying deflates the rest of the board; bargains inflate it", () => {
    const values = [60, 40, 30, 20, 10, ...Array(20).fill(1)]
    const slots = values.length
    expect(inflation(values.reduce((a, b) => a + b, 0), values, slots).multiplier).toBeCloseTo(1, 6)

    const total = values.reduce((a, b) => a + b, 0)
    expect(inflation(total - 80, values.slice(1), slots - 1).multiplier).toBeLessThan(1)
    expect(inflation(total - 40, values.slice(1), slots - 1).multiplier).toBeGreaterThan(1)
  })

  test("the un-draftable tail never reaches the denominator", () => {
    const scoped = inflation(120, [50, 40, 30, ...Array(500).fill(1)], 3)
    expect(scoped.valueRemaining).toBe(120)
    expect(scoped.multiplier).toBeCloseTo(1, 6)
  })

  test("a degenerate room reports a neutral multiplier, never an infinity", () => {
    // `Infinity` is a `number` in JS, so it survives every `!= null` guard and renders as '∞'
    // beside a dollar sign — the `fullSeasonRate` lesson, one surface over.
    for (const m of [inflation(0, [], 0), inflation(500, [], 10), inflation(500, [10, 20], 0)]) {
      expect(Number.isFinite(m.multiplier)).toBe(true)
      expect(m.multiplier).toBe(1)
    }
  })
})

test.describe("the shared money formatter", () => {
  /** ⭐ ONE function across the board column, the bid panel and the nomination list. Three inline
   *  `$${x.toFixed(0)}` expressions are three rule sets that drift (E9.61). */
  test("a missing value is an em-dash, never $NaN or $0", () => {
    // "we have no value for him" and "he is worth nothing" are different facts.
    expect(formatMoney(null)).toBe("—")
    expect(formatMoney(undefined)).toBe("—")
    expect(formatMoney(Number.NaN)).toBe("—")
    expect(formatMoney(Number.POSITIVE_INFINITY)).toBe("—")
    expect(formatMoney(0)).toBe("$0")
    expect(formatMoney(37.4)).toBe("$37")
  })

  test("a degenerate band collapses to one figure instead of reading as a bug", () => {
    expect(formatMoneyRange(12, 12)).toBe("$12")
    expect(formatMoneyRange(8, 21)).toBe("$8–$21")
    expect(formatMoneyRange(null, 21)).toBe("—")
  })
})

test.describe("the why-this-bid sentence", () => {
  const infl = (m: number) => inflation(m * 100, [100], 1)

  test("names the binding constraint rather than restating the value", () => {
    const capped = maxBid(40, 1, 20, 6)
    const why = bidExplanation(capped, infl(1), 20)
    expect(why).toContain("Capped by your budget")
    expect(why).toContain("$40")

    expect(bidExplanation(maxBid(40, 1, 150, 0), infl(1), 150)).toContain("roster is full")
    expect(bidExplanation(maxBid(40, 1, 150, 5, { eligible: false }), infl(1), 150)).toContain(
      "No open slot",
    )
  })

  test("says which way the room has moved, in the room's own units", () => {
    expect(bidExplanation(maxBid(40, 1.25, 200, 16), infl(1.25), 200)).toContain("money left")
    expect(bidExplanation(maxBid(40, 0.8, 200, 16), infl(0.8), 200)).toContain("overspent")
  })

  test("never quotes a dollar figure the bid did not use", () => {
    // The sentence explains a number on screen; an unexplained gap between them is exactly the
    // kind of thing a user is right not to trust.
    const bid = maxBid(40, 1, 20, 6)
    const why = bidExplanation(bid, infl(1), 20)
    const reserved = 20 - bid.affordable
    expect(why).toContain(formatMoney(reserved))
  })
})

// ── the browser ─────────────────────────────────────────────────────────────────────────────────

/** Sign in as a subscriber, open the auction tool and start it on the default preset. */
async function startAuction(page: Page) {
  const errors = collectPageErrors(page)
  await signIn(page, { groups: ["subscriber"] })
  const mock = await mockApi(page, { entitlement: "entitled", leagues: "none" })
  await page.goto("/fantasy/auction")

  await expect(page.getByRole("heading", { name: "Auction Optimizer" })).toBeVisible()
  await page.getByRole("button", { name: "Start auction" }).click()
  await expect(page.getByTestId("auction-budget-remaining")).toBeVisible()
  return { errors, mock }
}

/** The first candidate row's "won for" control — the way a completed auction is recorded. */
async function recordWin(page: Page, price: number, rowIndex = 0) {
  const row = page.getByTestId("auction-candidate").nth(rowIndex)
  await expect(row).toBeVisible()
  const name = (await row.getByTestId("auction-candidate-name").textContent())?.trim() ?? ""
  await row.getByTestId("auction-price-input").fill(String(price))
  await row.getByTestId("auction-win-button").click()
  return name
}

test.describe("driving an auction", () => {
  test("the screen opens with a full budget and prices at par", async ({ page }) => {
    const { errors } = await startAuction(page)

    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$200")
    // ⭐ THE FACE-VALIDITY CHECK. Values are built to exhaust exactly this pool, so before a single
    // dollar is spent the multiplier must sit at par. Anything else means the denominator is wrong.
    const mult = Number(
      ((await page.getByTestId("auction-inflation").textContent()) ?? "").replace("x", ""),
    )
    expect(mult).toBeGreaterThan(0.9)
    expect(mult).toBeLessThan(1.1)

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("winning a player charges my budget and takes him off the board", async ({ page }) => {
    const { errors } = await startAuction(page)
    const before = await page.getByTestId("auction-candidate").count()
    const name = await recordWin(page, 43)

    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$157")
    await expect(page.getByTestId("auction-roster")).toContainText(name)
    // he is off the candidate list — a won player who stays biddable can be bought twice
    await expect(page.getByTestId("auction-candidate").first()).not.toHaveText(
      new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")),
    )
    expect(await page.getByTestId("auction-candidate").count()).toBeLessThanOrEqual(before)

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("a rival's overpay moves the room's prices, not just their budget", async ({ page }) => {
    const { errors } = await startAuction(page)
    const mult = async () =>
      Number(((await page.getByTestId("auction-inflation").textContent()) ?? "").replace("x", ""))
    const before = await mult()

    // Hand the top player to another team at a deliberate overpay.
    const row = page.getByTestId("auction-candidate").first()
    await row.getByTestId("auction-price-input").fill("120")
    await row.getByTestId("auction-rival-button").click()

    await expect.poll(mult, { message: "an overpay did not move the room's prices" }).toBeLessThan(
      before,
    )
    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("the max bid never lets me strand a roster spot", async ({ page }) => {
    const { errors } = await startAuction(page)

    // Spend almost everything on one player, then check the tool refuses to let the rest of the
    // roster go unfunded.
    await recordWin(page, 185)
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$15")

    const maxBids = await page
      .getByTestId("auction-max-bid")
      .evaluateAll((els) => els.map((e) => Number((e.textContent ?? "").replace(/[^0-9]/g, ""))))
    expect(maxBids.length, "no candidates left to check").toBeGreaterThan(0)
    const openSlots = Number(await page.getByTestId("auction-open-slots").textContent())
    // $15 with N open slots ⇒ the most any single bid may be is 15 - (N - 1).
    for (const b of maxBids) expect(b).toBeLessThanOrEqual(15 - (openSlots - 1))

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("a mid-auction reload keeps the money and the roster", async ({ page }) => {
    // ⭐ THE REASON THE STATE IS PERSISTED AT ALL. An auction runs for two hours in a tab that gets
    // reloaded, backgrounded and killed; losing the MONEY at spot 12 is losing the session.
    //
    // ⚠️ The reload returns to the setup screen and the run is re-entered from there — the same
    // shape the snake optimizer ships (`started` is component state, the SALES are what is
    // persisted). Asserted rather than assumed: it is what the sibling tool does, so the two
    // surfaces behave the same way after a refresh.
    const { errors } = await startAuction(page)
    const name = await recordWin(page, 43)

    await page.reload()
    await page.getByRole("button", { name: "Start auction" }).click()
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$157")
    await expect(page.getByTestId("auction-roster")).toContainText(name)
    expectNoPageErrors(errors)
  })

  test("Undo returns the money and the player", async ({ page }) => {
    const { errors } = await startAuction(page)
    const name = await recordWin(page, 43)
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$157")

    await page.getByRole("button", { name: "Undo" }).click()
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$200")
    await expect(page.getByTestId("auction-roster")).not.toContainText(name)
    expectNoPageErrors(errors)
  })
})

test.describe("layout", () => {
  /** ⚠️ A grid `1fr` track's automatic minimum is its MIN-CONTENT width, and Tailwind `truncate`
   *  sets `white-space: nowrap` — so a long "why this bid" sentence grows the track, overflows the
   *  container and gives the whole page a horizontal scrollbar with the roster panel pushed off
   *  screen. Measured on the snake optimizer at 2129px before its `min-w-0` fix.
   *
   *  ⭐ ASSERTS THE PAGE, and separately the SCROLLING CONTAINER. A table that scrolls inside its
   *  own `overflow-x-auto` box is fine and leaves the document tidy — so a page-level check alone
   *  cannot see a container that has blown out, and a container check alone cannot see the page
   *  overflow this test is named for (NF-C6b). */
  for (const vp of [
    { name: "desktop", width: 1512, height: 900 },
    { name: "mobile", width: 390, height: 844 },
  ]) {
    test(`a long why-this-bid reason never widens the page — ${vp.name}`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height })
      await startAuction(page)
      await expect(page.getByTestId("auction-candidate").first()).toBeVisible()

      const overflow = await page.evaluate(
        () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
      )
      expect(overflow, "the page scrolls sideways").toBeLessThanOrEqual(1)
    })
  }
})
