import { readFileSync } from "node:fs"
import { join } from "node:path"
import { expect, test, type Page } from "@playwright/test"
import { collectPageErrors, mockApi } from "../support/api-mock"
import { signIn } from "../support/session"
import { expectNoNaN, expectNoPageErrors } from "../support/assertions"
import {
  auctionPool,
  auctionValues,
  bidExplanation,
  dollarsPerSlot,
  formatMoney,
  formatPointsRange,
  inflation,
  maxBid,
} from "@/lib/auction-optimizer"
import { type Player } from "@/lib/draft-optimizer"

/**
 * NF-C5 — THE AUCTION OPTIMIZER.
 *
 * Two halves, and the first is the important one.
 *
 * ══ 1. THE CROSS-LANGUAGE PIN ═══════════════════════════════════════════════════════════════════
 *
 * The auction math is implemented TWICE by necessity: in Python (`fantasy_engine/auction.py`, which
 * the exporter publishes `aucVal`/`aucLo`/`aucHi` from) and in TS (which recomputes live on every
 * bid, for the user's ACTUAL budget rather than the one the board was quoted at). This repo has
 * been bitten repeatedly by one rule with two implementations — E9.61's two renderers of a player
 * name, NF-EPIC 1's three scorers — so "keep them in sync" is not left to discipline.
 *
 * `quant_sports_intel_models/fantasy_engine/auction_vectors.json` is GENERATED by the Python
 * authority; `test_fantasy_auction_values.py` regenerates it and refuses any drift from the
 * committed bytes, and this file runs the TS through the SAME file. Move either side and one of the
 * two goes red.
 *
 * ⚠️ READ ACROSS THE TREE ON PURPOSE, not copied into `e2e/fixtures/` — the pattern
 * `ESPN_REAL_PASTES` already uses. A local copy would be a fixture that drifts from the one the
 * authority is tested against, which is the whole failure this guards.
 *
 * ══ 2. THE BROWSER FLOW ═════════════════════════════════════════════════════════════════════════
 *
 * The auction screen is a state machine driven for two hours while money moves. Its failures are
 * the kind no static gate sees: a budget that does not decrement, a won player who stays on the
 * board, a max bid that lets a user strand a roster spot.
 */

// ── the golden vectors ──────────────────────────────────────────────────────────────────────────

type Vectors = {
  board: { id: string; vor: number | null; vorP10: number | null; vorP90: number | null }[]
  pools: {
    nTeams: number
    rosterSpots: number
    budget: number
    pool: { total: number; reserve: number; surplus: number }
    values: { id: string; value: number; share: number }[]
  }[]
  maxBids: {
    case: string
    value: number
    inflationMultiplier: number
    budgetRemaining: number
    openSlots: number
    eligible: boolean
    maxBid: number
    inflated: number
    affordable: number
    binding: string
  }[]
  inflation: {
    case: string
    dollarsRemaining: number
    slotsRemaining: number
    remainingValues: number[]
    multiplier: number
    valueRemaining: number
  }[]
  dollarsPerSlot: { budgetRemaining: number; openSlots: number; perSlot: number }[]
}

const VECTORS: Vectors = JSON.parse(
  readFileSync(
    join(process.cwd(), "..", "quant_sports_intel_models", "fantasy_engine", "auction_vectors.json"),
    "utf8",
  ),
)

/** The vector board as `Player[]`. Only the fields the auction math reads are meaningful; the rest
 *  satisfy the shared `Player` shape. */
function vectorBoard(): Player[] {
  return VECTORS.board.map((r, i) => ({
    id: r.id,
    name: r.id,
    pos: "RB",
    team: "AAA",
    bye: null,
    rookie: false,
    g: 17,
    pts: null,
    repl: 0,
    vor: r.vor,
    posRank: i + 1,
    ovrRank: i + 1,
    vorP10: r.vorP10,
    vorP90: r.vorP90,
    ptsP10: null,
    ptsP90: null,
    adp: null,
    lowPred: false,
    predNote: null,
  }))
}

test.describe("the TS auction engine agrees with the Python authority", () => {
  test("the golden vectors are non-empty and cover every branch", () => {
    // ⚠️ ANTI-VACUITY FIRST. Every assertion below loops over the vectors; an empty (or truncated)
    // file would make all of them pass on nothing — the NF1.7(a) class, and the reason this repo
    // requires a loop-based guard to assert its own non-vacuity.
    expect(VECTORS.board.length).toBeGreaterThan(4)
    expect(VECTORS.pools.length).toBeGreaterThan(1)
    expect(VECTORS.maxBids.length).toBeGreaterThan(5)
    expect(VECTORS.inflation.length).toBeGreaterThan(3)
    expect(new Set(VECTORS.maxBids.map((c) => c.binding))).toEqual(
      new Set(["value", "affordability", "no_slot", "roster_full"]),
    )
  })

  test("every pool decomposes to the same total, reserve and surplus", () => {
    for (const p of VECTORS.pools) {
      const got = auctionPool(p.nTeams, p.rosterSpots, p.budget)
      expect(
        { total: got.total, reserve: got.reserve, surplus: got.surplus },
        `pool ${p.nTeams}x${p.rosterSpots}@$${p.budget}`,
      ).toEqual(p.pool)
    }
  })

  test("every player prices to the same dollar value", () => {
    const board = vectorBoard()
    for (const p of VECTORS.pools) {
      const got = auctionValues(board, auctionPool(p.nTeams, p.rosterSpots, p.budget))
      expect(got.length).toBe(p.values.length)
      for (let i = 0; i < got.length; i++) {
        expect({ id: got[i].id, value: got[i].value }, `${p.values[i].id} at $${p.budget}`).toEqual({
          id: p.values[i].id,
          value: p.values[i].value,
        })
        expect(got[i].share).toBeCloseTo(p.values[i].share, 6)
      }
    }
  })

  test("the interval columns are carried on the board and never priced", () => {
    // ⭐ THE RETIRED DOLLAR BAND. `vorP10`/`vorP90` are still on `Player` (other surfaces read the
    // points interval), so "we stopped pricing them" has to be asserted rather than assumed — a
    // reader cannot tell from the type. The toy board carries a CROSSED interval (`crossed`:
    // p10 44 > p90 6) precisely so this can be checked: strip every interval column and each
    // player must price BYTE-IDENTICALLY, which is only true if they are not read at all.
    const p = VECTORS.pools[0]
    const pool = auctionPool(p.nTeams, p.rosterSpots, p.budget)
    const withInterval = auctionValues(vectorBoard(), pool)
    const stripped = auctionValues(
      vectorBoard().map((pl) => ({ ...pl, vorP10: null, vorP90: null })),
      pool,
    )
    expect(VECTORS.board.some((r) => r.vorP10 != null && r.vorP90 != null && r.vorP10 > r.vorP90),
      "no crossed interval in the vectors — this test cannot fail").toBe(true)
    expect(stripped).toEqual(withInterval)
  })

  test("every max bid, and the constraint that produced it, matches", () => {
    for (const c of VECTORS.maxBids) {
      const got = maxBid(c.value, c.inflationMultiplier, c.budgetRemaining, c.openSlots, {
        eligible: c.eligible,
      })
      expect(
        { maxBid: got.maxBid, inflated: got.inflated, affordable: got.affordable, binding: got.binding },
        c.case,
      ).toEqual({
        maxBid: c.maxBid,
        inflated: c.inflated,
        affordable: c.affordable,
        binding: c.binding,
      })
    }
  })

  test("every inflation reading matches", () => {
    for (const c of VECTORS.inflation) {
      const got = inflation(c.dollarsRemaining, c.remainingValues, c.slotsRemaining)
      expect(got.valueRemaining, c.case).toBe(c.valueRemaining)
      expect(got.multiplier, c.case).toBeCloseTo(c.multiplier, 6)
    }
  })

  test("dollars-per-slot matches, including the full-roster case", () => {
    for (const c of VECTORS.dollarsPerSlot) {
      expect(dollarsPerSlot(c.budgetRemaining, c.openSlots)).toBeCloseTo(c.perSlot, 6)
    }
  })
})

// ── the properties, in the browser's own language ───────────────────────────────────────────────

test.describe("the never-strand rule", () => {
  /** ⭐ THE PROPERTY THE OPTIMIZER EXISTS TO GUARANTEE, asserted over a GRID rather than at a few
   *  points — the failure mode is an off-by-one at the `openSlots - 1` boundary, which hand-picked
   *  cases are exactly the wrong instrument to find. Mirrors the Python grid test. */
  test("bidding the max always leaves a dollar for every remaining slot", () => {
    let feasibleChecked = 0
    for (const budget of [0, 1, 3, 9, 17, 40, 88, 200]) {
      for (const slots of [1, 2, 3, 6, 9, 16]) {
        for (const value of [1, 5, 40, 300]) {
          const bid = maxBid(value, 1, budget, slots)
          expect(bid.maxBid).toBeGreaterThanOrEqual(0)
          expect(bid.maxBid).toBeLessThanOrEqual(budget)

          // States that arrive ALREADY stranded ($1 in hand, 2 spots) cannot be undone by this
          // rule and must not be blamed on it; the obligation there is "do not make it worse".
          if (budget < slots) {
            expect(bid.maxBid, `spent from an already-stranded roster: $${budget}/${slots}`).toBe(0)
            continue
          }
          feasibleChecked++
          const leftAfter = budget - bid.maxBid
          const slotsAfter = slots - (bid.maxBid > 0 ? 1 : 0)
          expect(
            leftAfter,
            `stranded a slot: $${budget} with ${slots} open → bid $${bid.maxBid}`,
          ).toBeGreaterThanOrEqual(slotsAfter)
          // ...and the rule must not be satisfied by refusing to bid at all: a `maxBid` hardcoded
          // to 0 would pass every clause above.
          expect(bid.maxBid).toBeGreaterThanOrEqual(1)
        }
      }
    }
    expect(feasibleChecked, "the grid contained no feasible states — it asserted nothing").toBeGreaterThan(50)
  })

  test("the cap is inert while there is slack, and total at the end", () => {
    expect(maxBid(40, 1, 200, 16).binding).toBe("value")
    expect(maxBid(40, 1, 200, 16).maxBid).toBe(40)
    expect(maxBid(40, 1, 20, 6).binding).toBe("affordability")
    expect(maxBid(40, 1, 20, 6).maxBid).toBe(15)
  })
})

test.describe("inflation reads the room the right way round", () => {
  /** ⚠️ THE DIRECTION IS THE WHOLE SIGNAL and the half most often got backwards. A room that
   *  OVERPAYS leaves less money chasing the same value, so what remains gets CHEAPER. */
  test("overpaying deflates the rest of the board; bargains inflate it", () => {
    const values = [60, 40, 30, 20, 10, ...Array(20).fill(1)]
    const slots = values.length
    expect(inflation(values.reduce((a, b) => a + b, 0), values, slots).multiplier).toBeCloseTo(1, 6)

    const total = values.reduce((a, b) => a + b, 0)
    expect(inflation(total - 80, values.slice(1), slots - 1).multiplier).toBeLessThan(1)
    expect(inflation(total - 40, values.slice(1), slots - 1).multiplier).toBeGreaterThan(1)
  })

  test("the un-draftable tail never reaches the denominator", () => {
    const scoped = inflation(120, [50, 40, 30, ...Array(500).fill(1)], 3)
    expect(scoped.valueRemaining).toBe(120)
    expect(scoped.multiplier).toBeCloseTo(1, 6)
  })

  test("a degenerate room reports a neutral multiplier, never an infinity", () => {
    // `Infinity` is a `number` in JS, so it survives every `!= null` guard and renders as '∞'
    // beside a dollar sign — the `fullSeasonRate` lesson, one surface over.
    for (const m of [inflation(0, [], 0), inflation(500, [], 10), inflation(500, [10, 20], 0)]) {
      expect(Number.isFinite(m.multiplier)).toBe(true)
      expect(m.multiplier).toBe(1)
    }
  })
})

test.describe("the shared money formatter", () => {
  /** ⭐ ONE function across the board column, the bid panel and the nomination list. Three inline
   *  `$${x.toFixed(0)}` expressions are three rule sets that drift (E9.61). */
  test("a missing value is an em-dash, never $NaN or $0", () => {
    // "we have no value for him" and "he is worth nothing" are different facts.
    expect(formatMoney(null)).toBe("—")
    expect(formatMoney(undefined)).toBe("—")
    expect(formatMoney(Number.NaN)).toBe("—")
    expect(formatMoney(Number.POSITIVE_INFINITY)).toBe("—")
    expect(formatMoney(0)).toBe("$0")
    expect(formatMoney(37.4)).toBe("$37")
  })

  test("the projection's interval is rendered in POINTS, never with a dollar sign", () => {
    // ⭐ THE UNITS ARE THE ASSERTION. This replaced a `formatMoneyRange` that put a `$` in front of
    // the same two numbers — and the edges were not prices (the low was $1 for all 870 rows of the
    // served board, the highs summed to 412% of the room's money). Anything reintroducing a `$`
    // here is reintroducing that claim.
    expect(formatPointsRange(93, 312)).toBe("93–312 pts")
    expect(formatPointsRange(12, 12)).toBe("12 pts")
    expect(formatPointsRange(null, 21)).toBe("—")
    expect(formatPointsRange(93, 312)).not.toContain("$")
  })
})

test.describe("the why-this-bid sentence", () => {
  const infl = (m: number) => inflation(m * 100, [100], 1)

  test("names the binding constraint rather than restating the value", () => {
    const capped = maxBid(40, 1, 20, 6)
    const why = bidExplanation(capped, infl(1), 20)
    expect(why).toContain("Capped by your budget")
    expect(why).toContain("$40")

    expect(bidExplanation(maxBid(40, 1, 150, 0), infl(1), 150)).toContain("roster is full")
    expect(bidExplanation(maxBid(40, 1, 150, 5, { eligible: false }), infl(1), 150)).toContain(
      "No open slot",
    )
  })

  test("says which way the room has moved, in the room's own units", () => {
    expect(bidExplanation(maxBid(40, 1.25, 200, 16), infl(1.25), 200)).toContain("money left")
    expect(bidExplanation(maxBid(40, 0.8, 200, 16), infl(0.8), 200)).toContain("overspent")
  })

  test("never quotes a dollar figure the bid did not use", () => {
    // The sentence explains a number on screen; an unexplained gap between them is exactly the
    // kind of thing a user is right not to trust.
    const bid = maxBid(40, 1, 20, 6)
    const why = bidExplanation(bid, infl(1), 20)
    const reserved = 20 - bid.affordable
    expect(why).toContain(formatMoney(reserved))
  })
})

// ── the browser ─────────────────────────────────────────────────────────────────────────────────

/** Sign in as a subscriber, open the auction tool and start it on the default preset. */
async function startAuction(page: Page) {
  const errors = collectPageErrors(page)
  await signIn(page, { groups: ["subscriber"] })
  const mock = await mockApi(page, { entitlement: "entitled", leagues: "none" })
  await page.goto("/fantasy/auction")

  await expect(page.getByRole("heading", { name: "Auction Optimizer" })).toBeVisible()
  await page.getByRole("button", { name: "Start auction" }).click()
  await expect(page.getByTestId("auction-budget-remaining")).toBeVisible()
  return { errors, mock }
}

/** The first candidate row's "won for" control — the way a completed auction is recorded. */
async function recordWin(page: Page, price: number, rowIndex = 0) {
  const row = page.getByTestId("auction-candidate").nth(rowIndex)
  await expect(row).toBeVisible()
  const name = (await row.getByTestId("auction-candidate-name").textContent())?.trim() ?? ""
  await row.getByTestId("auction-price-input").fill(String(price))
  await row.getByTestId("auction-win-button").click()
  return name
}

test.describe("driving an auction", () => {
  test("the screen opens with a full budget and prices at par", async ({ page }) => {
    const { errors } = await startAuction(page)

    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$200")
    // ⭐ THE FACE-VALIDITY CHECK. Values are built to exhaust exactly this pool, so before a single
    // dollar is spent the multiplier must sit at par. Anything else means the denominator is wrong.
    const mult = Number(
      ((await page.getByTestId("auction-inflation").textContent()) ?? "").replace("x", ""),
    )
    expect(mult).toBeGreaterThan(0.9)
    expect(mult).toBeLessThan(1.1)

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("winning a player charges my budget and takes him off the board", async ({ page }) => {
    const { errors } = await startAuction(page)
    const before = await page.getByTestId("auction-candidate").count()
    const name = await recordWin(page, 43)

    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$157")
    await expect(page.getByTestId("auction-roster")).toContainText(name)
    // he is off the candidate list — a won player who stays biddable can be bought twice
    await expect(page.getByTestId("auction-candidate").first()).not.toHaveText(
      new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")),
    )
    expect(await page.getByTestId("auction-candidate").count()).toBeLessThanOrEqual(before)

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  /** Record a rival win through the "Sold" menu. ⚠️ Radix renders a BUTTON trigger plus a
   *  portalled menu — `selectOption` is a no-op on it, so it is driven by trigger-click then
   *  item-click, per the repo's Radix E2E rule. */
  async function recordRivalWin(page: Page, team: number, price?: number, rowIndex = 0) {
    const row = page.getByTestId("auction-candidate").nth(rowIndex)
    const name = (await row.getByTestId("auction-candidate-name").textContent())?.trim() ?? ""
    if (price != null) await row.getByTestId("auction-price-input").fill(String(price))
    await row.getByTestId("auction-rival-button").click()
    await page.locator(`[data-testid="auction-rival-team"][data-team="${team}"]`).click()
    await expect(page.locator('[data-testid="auction-rival-team"]')).toHaveCount(0)
    return name
  }

  test("a rival's overpay moves the room's prices, not just their budget", async ({ page }) => {
    const { errors } = await startAuction(page)
    const mult = async () =>
      Number(((await page.getByTestId("auction-inflation").textContent()) ?? "").replace("x", ""))
    const before = await mult()

    await recordRivalWin(page, 2, 120)

    await expect.poll(mult, { message: "an overpay did not move the room's prices" }).toBeLessThan(
      before,
    )
    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("a rival win is charged to the team that actually won it", async ({ page }) => {
    // ⭐ THE DEFECT THIS REPLACES, reported live 2026-08-17. "Sold" hardcoded the buyer
    // (`myTeam === 1 ? 2 : 1`), so EVERY rival purchase piled onto ONE team: the room panel was
    // wrong, and past that team's roster size its extra buys became invisible to `openSlots` — the
    // denominator `inflation` divides by.
    //
    // ⚠️ TWO DIFFERENT TEAMS ON PURPOSE. A single rival sale would pass just as well against the
    // hardcoded version, which is the fixture-cannot-fail shape.
    const { errors } = await startAuction(page)
    await recordRivalWin(page, 3, 40)
    await recordRivalWin(page, 5, 25)

    const room = await page.getByTestId("auction-room-team").evaluateAll((rows) =>
      Object.fromEntries(
        rows.map((r) => [
          r.getAttribute("data-team"),
          (r.querySelector('[data-testid="auction-room-remaining"]')?.textContent ?? "").trim(),
        ]),
      ),
    )
    expect(room["3"], "team 3's money did not move").toBe("$160")
    expect(room["5"], "team 5's money did not move").toBe("$175")
    // ...and nobody else was charged. Team 2 is named explicitly because it was the hardcoded one.
    expect(room["2"], "team 2 was charged for a sale it did not win").toBe("$200")
    expect(room["4"]).toBe("$200")
    expectNoPageErrors(errors)
  })

  test("a team with no open roster spot cannot be sold another player", async ({ page }) => {
    // What makes the over-capacity state UNREACHABLE rather than merely clamped: a full team is
    // not offered, so the room's slot count can never be credited with a purchase it cannot hold.
    const { errors } = await startAuction(page)
    await page.getByTestId("auction-candidate").first().getByTestId("auction-rival-button").click()
    const items = page.locator('[data-testid="auction-rival-team"]')
    await expect(items.first()).toBeVisible()
    // Nobody is full at the start, so every rival is selectable — and I am NOT offered, because
    // "I won" is the control for that and two ways to say the same thing is two rule sets.
    const teams = await items.evaluateAll((els) => els.map((e) => e.getAttribute("data-team")))
    expect(teams).not.toContain("1")
    expect(teams.length).toBeGreaterThan(5)
    for (const el of await items.all()) await expect(el).not.toBeDisabled()
    expectNoPageErrors(errors)
  })

  test("the max bid never lets me strand a roster spot", async ({ page }) => {
    const { errors } = await startAuction(page)

    // Spend almost everything on one player, then check the tool refuses to let the rest of the
    // roster go unfunded.
    await recordWin(page, 185)
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$15")

    const maxBids = await page
      .getByTestId("auction-max-bid")
      .evaluateAll((els) => els.map((e) => Number((e.textContent ?? "").replace(/[^0-9]/g, ""))))
    expect(maxBids.length, "no candidates left to check").toBeGreaterThan(0)
    const openSlots = Number(await page.getByTestId("auction-open-slots").textContent())
    // $15 with N open slots ⇒ the most any single bid may be is 15 - (N - 1).
    for (const b of maxBids) expect(b).toBeLessThanOrEqual(15 - (openSlots - 1))

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("the two surfaces that show a max bid always show the SAME max bid", async ({ page }) => {
    // ⭐ THE DEFECT THIS CAUGHT, kept as its own regression. The recommendation panel and the
    // available-players table both render "your max" for a player. The first cut recomputed it
    // inline in the table and applied the affordability cap but NEITHER the inflation multiplier
    // NOR the roster-eligibility check — so the same player showed two different numbers three
    // rows apart, and the one further down the page was the wrong one.
    //
    // ⚠️ RUN AFTER A SALE, deliberately: with a full budget and an untouched roster the two
    // computations agree by accident (inflation is ~1.00 and every position is still eligible), so
    // a fresh screen cannot tell them apart. Spending money is what makes the fixture able to fail.
    const { errors } = await startAuction(page)
    await recordWin(page, 120)

    const panel = await page.getByTestId("auction-candidate").evaluateAll((rows) =>
      rows.map((r) => ({
        name: (r.querySelector('[data-testid="auction-candidate-name"]')?.textContent ?? "").trim(),
        bid: (r.querySelector('[data-testid="auction-max-bid"]')?.textContent ?? "").trim(),
      })),
    )
    expect(panel.length, "no candidates — this test would assert on nothing").toBeGreaterThan(2)

    const table = await page.getByTestId("auction-board-max-bid").evaluateAll((cells) =>
      cells.map((c) => ({
        row: c.closest("tr"),
        bid: (c.textContent ?? "").trim(),
      })).map(({ row, bid }) => ({
        name: (row?.querySelector('a[href^="/fantasy/player/"]')?.textContent ?? "").trim(),
        bid,
      })),
    )
    const byName = new Map(table.map((t) => [t.name, t.bid]))

    let compared = 0
    for (const c of panel) {
      const fromTable = byName.get(c.name)
      if (fromTable === undefined) continue // below the table's 250-row cut
      compared++
      expect(fromTable, `${c.name} shows two different max bids`).toBe(c.bid)
    }
    expect(compared, "no player appeared on both surfaces — nothing was compared").toBeGreaterThan(1)
    expectNoPageErrors(errors)
  })

  // ── recording a nomination that is not on the shortlist ───────────────────────────────────────
  //
  // ⭐ REPORTED LIVE 2026-08-17, and the shape is worth stating because it is not obvious from the
  // code: an auction is driven by NOMINATIONS, and the room nominates whoever it likes. The
  // shortlist panel only ever holds the few names that fit MY roster next, so the board table is
  // where most of a real auction actually gets recorded — and it had no price entry at all. Both
  // its buttons silently wrote a default, so a $3 sale went in the ledger at his value and every
  // number downstream of the money (inflation, every max bid, every team's remaining) drifted from
  // the auction actually happening in the room. Nothing on screen looked wrong.

  /** Every board row, keyed by the player id the controls carry. */
  async function boardRows(page: Page) {
    return page.getByTestId("auction-board-max-bid").evaluateAll((cells) =>
      cells.map((c) => {
        const row = c.closest("tr")
        return {
          id: c.getAttribute("data-player") ?? "",
          name: (row?.querySelector('a[href^="/fantasy/player/"]')?.textContent ?? "").trim(),
        }
      }),
    )
  }

  /** `{ "3": "$160", ... }` — what the room panel says every team has left. */
  async function roomRemaining(page: Page) {
    return page.getByTestId("auction-room-team").evaluateAll((rows) =>
      Object.fromEntries(
        rows.map((r) => [
          r.getAttribute("data-team"),
          (r.querySelector('[data-testid="auction-room-remaining"]')?.textContent ?? "").trim(),
        ]),
      ),
    )
  }

  /**
   * Record a sale from the BOARD table. Returns the number the price box was SHOWING before
   * anything was typed, so a test can prove its own typed price was not the default (the shape
   * where a passing assertion says nothing).
   */
  async function recordFromBoard(
    page: Page,
    opts: { id: string; price?: number; team?: number },
  ): Promise<number> {
    const input = page.locator(`[data-testid="auction-price-input"][data-player="${opts.id}"]`)
    await expect(input).toBeVisible()
    const shown = Number(await input.getAttribute("placeholder"))
    if (opts.price != null) await input.fill(String(opts.price))
    if (opts.team == null) {
      await page.locator(`[data-testid="auction-board-win-button"][data-player="${opts.id}"]`).click()
    } else {
      const row = page.locator(
        `tr:has([data-testid="auction-price-input"][data-player="${opts.id}"])`,
      )
      await row.getByTestId("auction-rival-button").click()
      await page.locator(`[data-testid="auction-rival-team"][data-team="${opts.team}"]`).click()
      await expect(page.locator('[data-testid="auction-rival-team"]')).toHaveCount(0)
    }
    return shown
  }

  /** A board player who is deliberately NOT one of the shortlisted names. */
  async function offShortlistTarget(page: Page, fromRank = 100) {
    const rows = await boardRows(page)
    expect(rows.length, "the board table is empty — nothing to nominate").toBeGreaterThan(fromRank)
    const shortlist = new Set(
      (await page.getByTestId("auction-candidate-name").allTextContents()).map((s) => s.trim()),
    )
    const target = rows.slice(fromRank).find((r) => r.name && !shortlist.has(r.name))
    expect(target, "every board row is on the shortlist — this test cannot fail").toBeTruthy()
    return target!
  }

  test("a nominated player found by search is recorded at what he actually sold for", async ({
    page,
  }) => {
    const { errors } = await startAuction(page)
    const target = await offShortlistTarget(page)

    // The reported workflow, verbatim: search the room's nomination, then record it.
    await page.getByLabel("Search players").fill(target.name)
    await expect.poll(async () => (await boardRows(page)).length).toBeLessThan(50)

    const shown = await recordFromBoard(page, { id: target.id, price: 41, team: 4 })
    // ⚠️ ANTI-VACUITY. If the typed price happened to equal the default, a version that ignores
    // typing entirely would pass this test — the fixture-cannot-fail shape.
    expect(shown, "the typed price equals the default — this proves nothing").not.toBe(41)

    await expect
      .poll(async () => (await roomRemaining(page))["4"], {
        message: "team 4 was not charged the price that was typed",
      })
      .toBe("$159")
    const room = await roomRemaining(page)
    expect(room["3"], "a team that bought nothing was charged").toBe("$200")

    // ...and he leaves the board, because a sold player who stays biddable can be sold twice.
    await expect(
      page.locator(`[data-testid="auction-board-max-bid"][data-player="${target.id}"]`),
    ).toHaveCount(0)

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("a player I win from the board charges my budget exactly what I typed", async ({ page }) => {
    const { errors } = await startAuction(page)
    const target = await offShortlistTarget(page)

    await page.getByLabel("Search players").fill(target.name)
    const shown = await recordFromBoard(page, { id: target.id, price: 37 })
    expect(shown, "the typed price equals the default — this proves nothing").not.toBe(37)

    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$163")
    await expect(page.getByTestId("auction-roster")).toContainText(target.name)

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("an empty price box records the number the box was showing", async ({ page }) => {
    // ⭐ THE TRUTHFUL-PLACEHOLDER PROPERTY. One box sits between two buttons, so if "I won" and
    // "Sold" defaulted to different numbers the greyed-out figure would be right for at most one
    // of them — an input that shows one number and writes another. Both therefore default to the
    // same thing: what he is worth at today's prices.
    //
    // ⚠️ RUN AFTER SPENDING, deliberately. With a full budget the affordability cap is inert, so
    // his value and my max bid are the SAME number and a placeholder showing either would pass.
    // Draining the budget is what makes the two diverge and the assertion able to fail.
    const { errors } = await startAuction(page)
    await recordWin(page, 185)
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$15")

    const target = await offShortlistTarget(page, 0)
    const shown = await recordFromBoard(page, { id: target.id, team: 6 })
    expect(shown, "nothing was showing in the price box").toBeGreaterThan(1)

    await expect
      .poll(async () => (await roomRemaining(page))["6"], {
        message: "the recorded price is not the one the box was showing",
      })
      .toBe(`$${200 - shown}`)
    expectNoPageErrors(errors)
  })

  test("the shortlist and the board share ONE price box", async ({ page }) => {
    // The E9.61 rule on the number a user types: two surfaces offering the same action must not
    // keep two ledgers of it. A price typed against a player is a fact about that player, so it
    // must be the same box wherever he appears — otherwise a user types $3 in one place, clicks
    // the button in the other, and records something they never entered.
    const { errors } = await startAuction(page)
    const name = (await page.getByTestId("auction-candidate-name").first().textContent())?.trim()
    expect(name, "no shortlisted player to cross-check").toBeTruthy()

    await page.getByLabel("Search players").fill(name!)
    const rows = await boardRows(page)
    const target = rows.find((r) => r.name === name)
    expect(target, `${name} is on the shortlist but not on the board`).toBeTruthy()

    await page
      .locator(`tr [data-testid="auction-price-input"][data-player="${target!.id}"]`)
      .fill("57")
    await expect(
      page.locator(
        `[data-testid="auction-candidate"] [data-testid="auction-price-input"][data-player="${target!.id}"]`,
      ),
    ).toHaveValue("57")
    expectNoPageErrors(errors)
  })

  test("a value is ONE dollar figure, and the projection's range is quoted in points", async ({
    page,
  }) => {
    // ⭐ THE RETIRED DOLLAR BAND, asserted on the rendered screen. Reported live 2026-08-17: every
    // player showed a low edge of $1 — Bijan Robinson, Ashton Jeanty, everyone. That was TRUE
    // arithmetic (a 10th-percentile season total is below replacement for every player on the
    // board, because the left tail is availability) and useless as a price, and its other half was
    // worse: the high edges summed to 412% of the money in the room. A dollar is a share of a
    // FIXED pool, so an interval cannot be carried into dollars without a model of how players'
    // seasons move together — which we do not have. The uncertainty is quoted in points instead.
    const { errors } = await startAuction(page)

    const values = await page.getByTestId("auction-value").allTextContents()
    expect(values.length, "no values rendered — this test would assert on nothing").toBeGreaterThan(2)
    for (const v of values) {
      expect(v.trim(), "a dollar RANGE is back on the auction board").toMatch(/^\$\d+$/)
    }
    // ...and the top of the shortlist is not everybody's $1 floor, which is what the defect looked
    // like from the outside.
    expect(Number(values[0].replace("$", ""))).toBeGreaterThan(1)

    const ranges = await page.getByTestId("auction-points-range").allTextContents()
    expect(ranges.length).toBe(values.length)
    for (const r of ranges) {
      expect(r, "the projection's range is being quoted in dollars again").not.toContain("$")
      expect(r.trim()).toMatch(/pts$|^—$/)
    }

    await expectNoNaN(page)
    expectNoPageErrors(errors)
  })

  test("a mid-auction reload keeps the money and the roster", async ({ page }) => {
    // ⭐ THE REASON THE STATE IS PERSISTED AT ALL. An auction runs for two hours in a tab that gets
    // reloaded, backgrounded and killed; losing the MONEY at spot 12 is losing the session.
    //
    // ⚠️ The reload returns to the setup screen and the run is re-entered from there — the same
    // shape the snake optimizer ships (`started` is component state, the SALES are what is
    // persisted). Asserted rather than assumed: it is what the sibling tool does, so the two
    // surfaces behave the same way after a refresh.
    const { errors } = await startAuction(page)
    const name = await recordWin(page, 43)

    await page.reload()
    await page.getByRole("button", { name: "Start auction" }).click()
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$157")
    await expect(page.getByTestId("auction-roster")).toContainText(name)
    expectNoPageErrors(errors)
  })

  test("Undo returns the money and the player", async ({ page }) => {
    const { errors } = await startAuction(page)
    const name = await recordWin(page, 43)
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$157")

    await page.getByRole("button", { name: "Undo" }).click()
    await expect(page.getByTestId("auction-budget-remaining")).toHaveText("$200")
    await expect(page.getByTestId("auction-roster")).not.toContainText(name)
    expectNoPageErrors(errors)
  })
})

test.describe("layout", () => {
  /** ⚠️ A grid `1fr` track's automatic minimum is its MIN-CONTENT width, and Tailwind `truncate`
   *  sets `white-space: nowrap` — so a long "why this bid" sentence grows the track, overflows the
   *  container and gives the whole page a horizontal scrollbar with the roster panel pushed off
   *  screen. Measured on the snake optimizer at 2129px before its `min-w-0` fix.
   *
   *  ⭐ ASSERTS THE PAGE, and separately the SCROLLING CONTAINER. A table that scrolls inside its
   *  own `overflow-x-auto` box is fine and leaves the document tidy — so a page-level check alone
   *  cannot see a container that has blown out, and a container check alone cannot see the page
   *  overflow this test is named for (NF-C6b). */
  for (const vp of [
    { name: "desktop", width: 1512, height: 900 },
    { name: "mobile", width: 390, height: 844 },
  ]) {
    test(`a long why-this-bid reason never widens the page — ${vp.name}`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height })
      await startAuction(page)
      await expect(page.getByTestId("auction-candidate").first()).toBeVisible()

      const overflow = await page.evaluate(
        () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
      )
      expect(overflow, "the page scrolls sideways").toBeLessThanOrEqual(1)
    })
  }
})
