// NF-C-LDA-1 — the overlay's RENDERING. Pure DOM; no network, no state ownership.
//
// ⛔ EVERY NODE IS BUILT WITH `createElement` + `textContent`, NEVER `innerHTML`. Player names,
// team names and league names all originate in ESPN's payload, i.e. in strings other people chose;
// an `innerHTML` here would let a league named `<img onerror=…>` run script inside our panel on a
// page we do not control. `textContent` makes that structurally impossible rather than escaped.
//
// ⭐ THE READ VERDICT IS RENDERED FIRST AND ALWAYS, ABOVE THE ADVICE. A user must be able to see
// that we have stopped reading their draft without inferring it from advice that merely looks
// stale — the two are otherwise identical on screen (see `draft-state.js`).
(function () {
  "use strict";

  var COLOURS = { ok: "#34d399", degraded: "#fbbf24", blocked: "#f87171" };

  function el(tag, style, text) {
    var n = document.createElement(tag);
    if (style) n.setAttribute("style", style);
    if (text !== undefined && text !== null) n.textContent = String(text);
    return n;
  }

  function ensureRoot() {
    var root = document.getElementById("credence-draft-assistant");
    if (root) return root;
    root = el("div", [
      "position:fixed", "right:12px", "bottom:12px", "z-index:2147483647",
      "width:340px", "max-height:78vh", "overflow:auto",
      "font:12px/1.45 ui-sans-serif,system-ui,-apple-system,sans-serif",
      "background:#0b1220", "color:#f9fafb", "border:1px solid #1f2937",
      "border-radius:12px", "padding:12px 13px", "box-shadow:0 10px 34px rgba(0,0,0,.45)"
    ].join(";"));
    root.id = "credence-draft-assistant";
    document.documentElement.appendChild(root);
    return root;
  }

  /**
   * ⭐ THE PICK ECHO. The single most load-bearing line in the panel: it names the pick the advice
   * is ABOUT, so a frozen read is visible by comparing one number against ESPN's own screen. A
   * recommendation with no pick number attached is unfalsifiable by the person reading it.
   */
  function renderHeader(root, view) {
    var v = view.verdict;
    var head = el("div", "display:flex;align-items:baseline;justify-content:space-between;gap:8px");
    head.appendChild(el("div", "font-weight:700;letter-spacing:.02em", "Credence"));
    var badge = el("div",
      "font-weight:600;font-size:11px;text-transform:uppercase;color:" + (COLOURS[v.level] || "#9ca3af"),
      v.level);
    head.appendChild(badge);
    root.appendChild(head);

    var pickLine = view.pickNumber
      ? "Reasoning about pick " + view.pickNumber
      : "No pick number read yet";
    var who = view.onTheClockIsMe === true ? " — YOUR PICK"
            : view.onTheClockIsMe === false ? " — another team is on the clock"
            : "";
    root.appendChild(el("div", "margin-top:6px;font-weight:600;color:#e5e7eb", pickLine + who));

    root.appendChild(el("div", "margin-top:2px;color:" + (COLOURS[v.level] || "#9ca3af"), v.headline));
    if (v.detail) root.appendChild(el("div", "margin-top:2px;color:#9ca3af", v.detail));
  }

  function renderRecommendations(root, view) {
    var data = view.data;
    if (!data) return;
    var recs = data.recommendations || [];
    root.appendChild(el("div", "margin:10px 0 4px;font-weight:700;color:#e5e7eb",
                        recs.length ? "Best pick now" : "No recommendation"));
    if (!recs.length) {
      root.appendChild(el("div", "color:#9ca3af",
        "Nobody on our board is still available for this roster."));
      return;
    }
    for (var i = 0; i < recs.length && i < 6; i++) {
      var r = recs[i];
      var card = el("div", [
        "margin-bottom:6px", "padding:7px 8px", "border-radius:8px",
        "background:" + (i === 0 ? "#111c33" : "#0f1626"),
        "border:1px solid " + (i === 0 ? "#2563eb" : "#1f2937")
      ].join(";"));
      var top = el("div", "display:flex;justify-content:space-between;gap:8px");
      top.appendChild(el("div", "font-weight:600",
        (i + 1) + ". " + (r.name || "—") + "  " + (r.pos || "") +
        (r.team ? " · " + r.team : "")));
      top.appendChild(el("div", "font-weight:700;color:#93c5fd", Math.round(r.score)));
      card.appendChild(top);
      // The "why", verbatim from the engine — the SAME sentence the web app shows, because it is
      // generated by the same function (`fantasy_engine.draft._rationale`, pinned to the TS by
      // `test_nf_c_lda_1_optimizer_parity.py`).
      if (r.why) card.appendChild(el("div", "margin-top:2px;color:#9ca3af", r.why));
      if (r.deferred) {
        card.appendChild(el("div", "margin-top:2px;color:#fbbf24",
          "Low-predictability position — use as a tier, not a precise rank."));
      }
      root.appendChild(card);
    }
  }

  function renderRoster(root, view) {
    var data = view.data;
    if (!data) return;
    var roster = data.my_roster || [];
    var known = data.state && data.state.my_team_known;
    root.appendChild(el("div", "margin:10px 0 4px;font-weight:700;color:#e5e7eb", "Your roster"));
    if (!known) {
      // ⭐ NAMED, not implied. An empty roster because we could not identify the user's team must
      // never render the same as an empty roster because they have not picked yet.
      root.appendChild(el("div", "color:#fbbf24",
        "We can’t tell which team is yours on this page, so this is empty for a reason — the picks "
        + "above rank the board, not your needs."));
      return;
    }
    if (!roster.length) {
      root.appendChild(el("div", "color:#9ca3af", "No picks yet."));
      return;
    }
    var line = roster.map(function (p) { return (p.pos || "?") + " " + (p.name || "?"); }).join(" · ");
    root.appendChild(el("div", "color:#d1d5db", line));
  }

  function renderResolution(root, view) {
    var data = view.data;
    if (!data || !data.resolution) return;
    var r = data.resolution;
    var causes = r.unresolved_by_cause || {};
    var joinFailures = causes.join_failure || 0;
    var bits = ["matched " + r.resolved + " of " + r.considered + " players"];
    // ⚠️ THE THREE CAUSES STAY APART (NF-K1). "we don't project this player" and "our join broke"
    // are different facts, and rendering them identically is what made the same symptom cost two
    // separate investigations.
    if (joinFailures) bits.push(joinFailures + " we could not match (tell us)");
    if (causes.not_projected) bits.push(causes.not_projected + " we don’t project");
    if (causes.position_absent_from_board) {
      bits.push(causes.position_absent_from_board + " at a position our board is missing");
    }
    if (r.collisions) bits.push(r.collisions + " ambiguous names skipped");
    root.appendChild(el("div", "margin-top:10px;padding-top:8px;border-top:1px solid #1f2937;color:#6b7280",
                        bits.join(" · ")));
  }

  function renderFooter(root, view) {
    if (view.message) {
      root.appendChild(el("div", "margin-top:8px;color:#fbbf24", view.message));
    }
    // Honest framing, unconditional: this ranks a projection under the league's own scoring. It is
    // not a market edge and makes no win-rate claim (`best_alpha = 0`).
    root.appendChild(el("div", "margin-top:8px;color:#6b7280;font-size:11px",
      "Projection-based value, ranked for your league’s scoring. Not betting advice and not a "
      + "prediction of results."));
  }

  function render(view) {
    var root = ensureRoot();
    root.textContent = "";
    renderHeader(root, view);
    // ⛔ NO ADVICE IS SHOWN WHILE BLOCKED. If we cannot read the draft we cannot know who is
    // available, and a stale list of "best available" is worse than none — it is wrong in exactly
    // the way the user cannot check.
    if (view.verdict.level !== "blocked") {
      renderRecommendations(root, view);
      renderRoster(root, view);
      renderResolution(root, view);
    }
    renderFooter(root, view);
    return root;
  }

  self.CredenceOverlay = { render: render, ensureRoot: ensureRoot };
})();
