"use client"

// NF3.2 — the fantasy football past-season TRACK RECORD ("receipts"): our projection vs that
// season's preseason ADP vs the realized outcome, one row per player, per season 2019–2025.
//
// 🔓 PUBLIC BY DESIGN — no FantasyGuard, no entitlement check anywhere in this component. It fetches
// only `lib/fantasy-track-record.ts`'s public endpoints, which structurally can never carry the
// current/locked season (see `export_track_record_json.LOCKED_SEASON`). The 2026 section below is a
// static locked CTA card, never a fetch of real 2026 data that gets hidden — see the module docstring
// on `fantasy_public.py` for why that distinction is the whole point.
//
// 🔒 HONEST (NF-D3 / best_alpha=0): the headline banner renders the manifest's `headline` VERBATIM —
// it is built entirely from the freshly-regenerated NF-D3 scorecard's own numbers at export time
// (`export_track_record_json.build_claim`), never authored here. Do not add new superiority copy
// to this file; if the claim needs to change, it changes at the export.
//
// ⭐ NF-TR1 — CALIBRATION LEADS, THE BENCHMARK COMPARISON IS SECONDARY, AND THE CLAIM SHIPS IN TWO
// LAYERS. The page used to open on the ADP comparison, which made a small gap whose own 90%
// interval includes zero (NF-D17: [-0.006, +0.051]) the first thing a visitor read. Now:
//
//    1. `CalibrationLead`   — what the product IS. Static copy, NO measured figure, from
//                             `lib/fantasy-claim-copy.ts` so E9.46's hero reuses it verbatim.
//    2. `ClaimLead`         — the plain-English record, `claim.lead`, rendered verbatim.
//    3. `PositionTable`     — every position's own gap, VISIBLE rather than buried, so the
//                             running-back wash is legible without expanding anything.
//    4. `Disclosures`       — the six required disclosures, visible, in plain words.
//    5. `HowWeMeasured`     — the fine print: the exact approved analyst sentence, the named
//                             benchmark, the metric, the player count, the seasons, the interval.
//
// The ORDER is an acceptance criterion, not a layout preference. Moving the benchmark comparison
// above the calibration block re-makes the claim the product's headline promise.

import { useMemo, useState } from "react"
import Link from "next/link"
import { Lock } from "lucide-react"
import {
  CartesianGrid,
  Cell,
  ReferenceLine,
  ResponsiveContainer,
  Scatter,
  ScatterChart,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts"
import { useAuth } from "@/lib/auth-context"
import { canAccess } from "@/lib/entitlements"
import { useTrackRecordManifest, useTrackRecordSeason } from "@/lib/fantasy-track-record"
import type {
  TrackRecordClaim,
  TrackRecordOtherBenchmark,
  TrackRecordPositionRow,
  TrackRecordRow,
} from "@/lib/fantasy-track-record"
import {
  CALIBRATION_HOOK,
  LEGACY_CLAIM_NOTE,
  METHOD_DISCLOSURE_LABEL,
} from "@/lib/fantasy-claim-copy"
import {
  EmptyBlock,
  FadeBadge,
  FadeLegend,
  GLOSSARY,
  InfoTip,
  LoadingBlock,
  Pagination,
  PosBadge,
  PositionTabs,
  SurfaceHeader,
  num,
  ALL_ROWS,
  PAGE_SIZES,
  SKILL_POSITIONS,
} from "@/components/fantasy/shared"

/** NF-TR1 §1 — what the product IS, before any comparison to anyone.
 *
 *  Deliberately carries NO measured figure (see `lib/fantasy-claim-copy.ts`): this block makes no
 *  claim about model performance, so nothing here needs reconciling against a scorecard. That is
 *  also why it can render before the manifest resolves — the value proposition does not depend on
 *  a fetch, and a visitor who arrives during a slow API still sees what they came for. */
function CalibrationLead() {
  return (
    <div className="mb-6 rounded-lg border border-[#10b981]/25 bg-[#10b981]/[0.04] p-5 sm:p-6">
      <h2 className="mb-3 text-[11px] font-semibold uppercase tracking-wider text-[#10b981]">
        What you get
      </h2>
      <dl className="grid gap-4 sm:grid-cols-2">
        {CALIBRATION_HOOK.map((item) => (
          <div key={item.title}>
            <dt className="text-sm font-semibold text-gray-100">{item.title}</dt>
            <dd className="mt-1 text-[13px] leading-relaxed text-gray-400">{item.detail}</dd>
          </div>
        ))}
      </dl>
    </div>
  )
}

// E9.56c — this is the single most persuasive thing the fantasy product owns, and it was styled as
// a footnote: `text-sm` gray-300 body inside the SAME neutral `#262626`/`#0f0f0f` card as the locked
// upsell directly beneath it, so the page's headline claim and a routine surrounding panel carried
// identical visual weight and nothing on the page read as the lead. It is also now quoted verbatim
// in the locked Rankings/Projections banner and is the reason the operator chose to let search
// engines index those pages — so it is the copy a first-time visitor is most likely to land on.
//
// ⚠️ The TEXT is untouched and must stay that way: it is generated by
// `export_track_record_json.build_claim` from the scorecard's own numbers precisely so a claim
// about model performance cannot be edited into marketing copy (NF-D3). Style it, never rewrite it.
//
// NF-TR1 demoted the emerald frame to `CalibrationLead` above and gave this block a neutral card:
// the SECONDARY claim must not out-rank the primary hook visually. `mb-1` heading + a real body
// paragraph keeps it a genuine lead paragraph rather than the footnote E9.56c found.
function ClaimLead({ lead }: { lead: string }) {
  return (
    <div className="mb-4 rounded-lg border border-[#262626] bg-[#0f0f0f] p-5 sm:p-6">
      <h2 className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-gray-400">
        The honest read
      </h2>
      <p className="max-w-3xl text-base leading-relaxed text-gray-100">{lead}</p>
    </div>
  )
}

/** The deploy-skew render: the artifact predates NF-TR1 and has no `claim` block.
 *
 *  ⚠️ The legacy string is shown as FINE PRINT, never promoted into the lead — see
 *  `LEGACY_CLAIM_NOTE` for why that direction is the safe one. The calibration block above still
 *  leads, so the page satisfies "calibration before benchmark" in BOTH deploy states. */
function LegacyClaim({ headline }: { headline: string }) {
  return (
    <details className="mb-6 rounded-lg border border-[#262626] bg-[#0f0f0f] p-4">
      <summary className="cursor-pointer text-xs font-semibold uppercase tracking-wider text-gray-400">
        {METHOD_DISCLOSURE_LABEL}
      </summary>
      <p className="mt-3 text-[13px] leading-relaxed text-gray-400">{headline}</p>
      <p className="mt-3 text-[12px] leading-relaxed text-gray-500">{LEGACY_CLAIM_NOTE}</p>
    </details>
  )
}

const VERDICT_STYLE: Record<string, string> = {
  ahead: "text-[#10b981]",
  behind: "text-rose-400",
  even: "text-amber-400",
}

/** How a measured gap reads to someone who has never seen a rank correlation.
 *
 *  ⚠️ The WORD comes from the export's own `verdict` (which owns the level-band threshold); only
 *  the phrasing is chosen here. A component that re-derived "even" from `deltaRho` would be a
 *  second copy of that threshold, free to drift from the one the disclosure sentence used — and
 *  then the table and the prose could disagree about whether running back is a wash. */
function verdictWord(verdict: string): string {
  return verdict === "ahead" ? "we ranked closer"
    : verdict === "behind" ? "they ranked closer"
    : "too close to call"
}

/** NF-TR1 §3 — the position-level split, VISIBLE.
 *
 *  ⭐ This is the disclosure that costs us something, so it is the one most likely to end up behind
 *  an expander. It renders unconditionally, above the fine print, because "running back is a wash"
 *  is only an honest disclosure if a reader meets it without going looking. */
function PositionTable({ rows }: { rows: TrackRecordPositionRow[] }) {
  if (rows.length === 0) return null
  return (
    <div className="mb-4 rounded-lg border border-[#262626] bg-[#0f0f0f] p-4">
      <h3 className="mb-1 text-xs font-semibold uppercase tracking-wider text-gray-500">
        Position by position
      </h3>
      <p className="mb-3 text-[11px] leading-relaxed text-gray-600">
        The same comparison, split by position. A positive gap means our preseason order landed
        closer to the final finish than the draft-day consensus did; near zero means the two were
        indistinguishable.
      </p>
      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b border-[#262626] text-[10px] uppercase tracking-wider text-gray-500">
              <th className="px-3 py-2">Position</th>
              <th className="px-3 py-2 text-right">Gap vs. draft-day consensus</th>
              <th className="px-3 py-2">Reads as</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.position} className="border-b border-[#1a1a1a] last:border-0">
                <td className="px-3 py-2">
                  <PosBadge pos={r.position} />
                </td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-300">
                  {r.deltaRho >= 0 ? "+" : "−"}
                  {Math.abs(r.deltaRho).toFixed(3)}
                </td>
                <td className={`px-3 py-2 ${VERDICT_STYLE[r.verdict] ?? "text-gray-400"}`}>
                  {verdictWord(r.verdict)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

/** The context benchmarks — ECR, ESPN, Sleeper — reported SEPARATELY from the ADP claim.
 *
 *  We trail every one of them today, which is exactly why this table is not optional: a page that
 *  showed only the comparison we lead would be selecting its own evidence. */
function OtherBenchmarksTable({ rows }: { rows: TrackRecordOtherBenchmark[] }) {
  if (rows.length === 0) return null
  return (
    <div className="mb-4 rounded-lg border border-[#262626] bg-[#0f0f0f] p-4">
      <h3 className="mb-1 text-xs font-semibold uppercase tracking-wider text-gray-500">
        The other rankings we are measured against
      </h3>
      <p className="mb-3 text-[11px] leading-relaxed text-gray-600">
        These are reported separately and are not part of the claim above.
      </p>
      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b border-[#262626] text-[10px] uppercase tracking-wider text-gray-500">
              <th className="px-3 py-2">Ranking</th>
              <th className="px-3 py-2 text-right">Seasons</th>
              <th className="px-3 py-2 text-right">Gap</th>
              <th className="px-3 py-2">Reads as</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.key} className="border-b border-[#1a1a1a] last:border-0">
                <td className="px-3 py-2 text-gray-300">{r.label}</td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-400">{r.nSeasons}</td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-300">
                  {r.deltaRho >= 0 ? "+" : "−"}
                  {Math.abs(r.deltaRho).toFixed(3)}
                </td>
                <td className={`px-3 py-2 ${VERDICT_STYLE[r.verdict] ?? "text-gray-400"}`}>
                  {verdictWord(r.verdict)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

/** NF-TR1 §4 — the six required disclosures, visible and in plain words.
 *
 *  Rendered as a plain list with no expander, because a disclosure a reader has to open is a
 *  disclosure most readers never see. The strings arrive pre-written and denylist-screened; ⛔ do
 *  not edit, reorder by meaning, or conditionally hide one. */
function Disclosures({ items }: { items: string[] }) {
  if (items.length === 0) return null
  return (
    <div className="mb-4 rounded-lg border border-[#262626] bg-[#0f0f0f] p-4">
      <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-gray-500">
        What this does and does not mean
      </h3>
      <ul className="space-y-2">
        {items.map((d) => (
          <li key={d} className="flex gap-2 text-[13px] leading-relaxed text-gray-400">
            <span aria-hidden="true" className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-gray-600" />
            <span>{d}</span>
          </li>
        ))}
      </ul>
    </div>
  )
}

/** NF-TR1 §5 — the PRECISE layer. The exact approved analyst sentence plus the named benchmark,
 *  the metric, the player count, the seasons and the interval.
 *
 *  ⭐ RELOCATED, NEVER DELETED. The operator's readability constraint moved this below a plain lead
 *  because analyst register in the headline shrinks the audience — it did not license dropping the
 *  rigor. Everything a reader would need to check the claim is in here, verbatim from the export. */
function HowWeMeasured({ claim }: { claim: TrackRecordClaim }) {
  const facts: [string, string][] = [
    ["Benchmark", claim.benchmark],
    ["Metric", claim.metric],
    ["Seasons", `${claim.seasons} (${claim.nSeasons} seasons)`],
    [
      "Players scored",
      `about ${claim.playersPerSeason} per season (${claim.playersPerSeasonMin}–${claim.playersPerSeasonMax})`,
    ],
    [
      `${claim.ciLevel}% interval on the gap`,
      `${claim.ciLow >= 0 ? "+" : "−"}${Math.abs(claim.ciLow).toFixed(3)} to ${
        claim.ciHigh >= 0 ? "+" : "−"
      }${Math.abs(claim.ciHigh).toFixed(3)}${claim.ciIncludesZero ? " — includes zero" : ""}`,
    ],
  ]
  return (
    <details className="mb-6 rounded-lg border border-[#262626] bg-[#0f0f0f] p-4">
      <summary className="cursor-pointer text-xs font-semibold uppercase tracking-wider text-gray-400">
        {METHOD_DISCLOSURE_LABEL}
      </summary>
      <p className="mt-3 max-w-3xl text-[13px] leading-relaxed text-gray-300">{claim.precise}</p>
      <dl className="mt-4 grid gap-x-6 gap-y-2 sm:grid-cols-[auto_1fr]">
        {facts.map(([label, value]) => (
          <div key={label} className="contents">
            <dt className="text-[11px] uppercase tracking-wider text-gray-500">{label}</dt>
            <dd className="mb-2 text-[13px] leading-relaxed text-gray-400 sm:mb-0">{value}</dd>
          </div>
        ))}
      </dl>
      <p className="mt-4 max-w-3xl text-[13px] leading-relaxed text-gray-400">{claim.method}</p>
      <p className="mt-3 max-w-3xl text-[13px] leading-relaxed text-gray-400">{claim.architecture}</p>
    </details>
  )
}

function LockedCurrentSeasonCard({ lockedSeason }: { lockedSeason: number }) {
  const { groups } = useAuth()
  const entitled = canAccess("fantasy", groups)
  return (
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-[#262626] bg-[#111111] p-4">
      <div>
        <p className="text-sm font-medium text-gray-200">
          {lockedSeason} season projections{entitled ? "" : " — subscriber only"}
        </p>
        <p className="mt-1 max-w-md text-xs leading-relaxed text-gray-500">
          This page is the receipts: past seasons, graded against what actually happened. The current
          season&apos;s live projections are the paid product.
        </p>
      </div>
      {entitled ? (
        <Link
          href="/fantasy/projections"
          className="rounded border border-[#10b981]/40 bg-[#10b981]/10 px-3 py-1.5 text-xs font-semibold text-[#10b981] transition-colors hover:bg-[#10b981]/20"
        >
          See {lockedSeason} projections
        </Link>
      ) : (
        <Link
          href="/subscribe"
          className="flex items-center gap-1.5 rounded border border-[#10b981]/40 bg-[#10b981]/10 px-3 py-1.5 text-xs font-semibold text-[#10b981] transition-colors hover:bg-[#10b981]/20"
        >
          <Lock className="h-3 w-3" /> Unlock {lockedSeason}
        </Link>
      )}
    </div>
  )
}

/** Emerald = fade hit (or an ungraded fade, from an export that predates `fadeResult`), rose = fade
 *  miss, amber = a genuine push (tie), muted gray = not a fade at all — "wins and losses both"
 *  applies to the chart too, not just the table's badge.
 *
 *  ⚠️ Match on the exact string, never a fallthrough `else` — `fadeResult` is `undefined` (not
 *  `"push"`) on a row from a stale/pre-grading export, and an `else` branch there paints every
 *  ungraded fade amber as a fake tie (see `FadeBadge`'s comment for the live incident this caused). */
function fadeDotColor(row: TrackRecordRow): string {
  if (!row.isFade) return "#4b5563"
  if (row.fadeResult === "miss") return "#f43f5e"
  if (row.fadeResult === "push") return "#f59e0b"
  return "#10b981" // "hit", or ungraded (null/undefined)
}

function FadeDot({ cx, cy, payload }: any) {
  const row = payload as TrackRecordRow
  return (
    <g>
      {/* Invisible larger hit-area — a real finger touch point is ~40-48px, and the visible dot
          below (r=2.5-4) is far smaller than that, so a tap on a real phone was landing between
          dots more often than on one. This circle is unstyled/transparent but still receives
          pointer events by default in SVG (no `pointer-events: none` here), so it enlarges the
          effective tap target without changing what's drawn. */}
      <circle cx={cx} cy={cy} r={14} fill="transparent" />
      <circle
        cx={cx}
        cy={cy}
        r={row.isFade ? 4 : 2.5}
        fill={fadeDotColor(row)}
        fillOpacity={row.isFade ? 0.85 : 0.4}
      />
    </g>
  )
}

function RankScatter({ rows }: { rows: TrackRecordRow[] }) {
  const maxRank = Math.max(1, ...rows.map((r) => Math.max(r.ourRank, r.actualRank)))
  return (
    <div className="mb-6 rounded-lg border border-[#262626] bg-[#0f0f0f] p-4">
      <h2 className="mb-1 text-xs font-semibold uppercase tracking-wider text-gray-500">
        Our rank vs. how the season actually finished
      </h2>
      <p className="mb-3 text-[11px] leading-relaxed text-gray-600">
        Every dot is a player; closer to the diagonal is a better call. Highlighted dots are our
        highest-conviction disagreements with ADP that season (the &ldquo;fades&rdquo;) — where the
        airtight independent claim lives.
      </p>
      <div className="mb-3">
        <FadeLegend />
      </div>
      <div className="h-72 w-full">
        <ResponsiveContainer width="100%" height="100%">
          <ScatterChart margin={{ top: 8, right: 12, bottom: 8, left: 0 }}>
            <CartesianGrid stroke="#1a1a1a" />
            <XAxis
              type="number"
              dataKey="ourRank"
              name="Our rank"
              domain={[1, maxRank]}
              stroke="#6b7280"
              fontSize={11}
              label={{ value: "Our rank (within position)", position: "insideBottom", offset: -4, fill: "#6b7280", fontSize: 11 }}
            />
            <YAxis
              type="number"
              dataKey="actualRank"
              name="Actual finish"
              domain={[1, maxRank]}
              stroke="#6b7280"
              fontSize={11}
              label={{ value: "Actual finish", angle: -90, position: "insideLeft", fill: "#6b7280", fontSize: 11 }}
            />
            <ReferenceLine
              segment={[{ x: 1, y: 1 }, { x: maxRank, y: maxRank }]}
              stroke="#374151"
              strokeDasharray="4 4"
            />
            <Tooltip
              cursor={{ strokeDasharray: "3 3" }}
              content={({ active, payload }) => {
                if (!active || !payload?.length) return null
                const row = payload[0].payload as TrackRecordRow
                return (
                  <div className="rounded border border-[#262626] bg-[#0f0f0f] px-2.5 py-1.5 text-xs text-gray-300">
                    <div className="font-medium text-gray-100">
                      {row.playerName} · {row.position}
                    </div>
                    <div>
                      Our rank {posRank(row.position, row.ourRank)} · ADP rank{" "}
                      {posRank(row.position, row.adpRank)} · actual {posRank(row.position, row.actualRank)}
                    </div>
                    {row.isFade && (
                      <div
                        className={
                          row.fadeResult === "miss"
                            ? "text-rose-400"
                            : row.fadeResult === "push"
                              ? "text-amber-500"
                              : "text-[#10b981]"
                        }
                      >
                        high-conviction fade{row.fadeResult ? ` · ${row.fadeResult}` : ""}
                      </div>
                    )}
                  </div>
                )
              }}
            />
            <Scatter data={rows} shape={<FadeDot />} />
          </ScatterChart>
        </ResponsiveContainer>
      </div>
    </div>
  )
}

/** All three ranks in this table are WITHIN-POSITION (the scatter chart's axis already says so —
 *  "Our rank (within position)" — but the table's bare "1"/"2"/"3" reads as an overall rank,
 *  especially on the "All" position tab where several different positions' #1s all show "1"). Prefix
 *  with the position so it reads unambiguously regardless of which tab is active, e.g. "QB1"/"RB12". */
function posRank(pos: string, rank: number | null): string {
  return rank == null ? "—" : `${pos}${rank}`
}

function TrackRecordTable({ rows }: { rows: TrackRecordRow[] }) {
  const [page, setPage] = useState(0)
  const [pageSize, setPageSize] = useState<number>(PAGE_SIZES[0])
  const sorted = useMemo(() => rows.slice().sort((a, b) => a.ourRank - b.ourRank), [rows])
  const paged =
    pageSize === ALL_ROWS ? sorted : sorted.slice(page * pageSize, (page + 1) * pageSize)

  if (rows.length === 0) {
    return (
      <EmptyBlock
        title="No scored players for this position"
        detail="Try a different position tab or season."
      />
    )
  }
  return (
    <div className="rounded-lg border border-[#262626] bg-[#0f0f0f]">
      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs">
          <thead>
            <tr className="border-b border-[#262626] text-[10px] uppercase tracking-wider text-gray-500">
              {/* Sticky so a player's identity stays visible while scrolling right on mobile, where
                  this table is wider than the screen — otherwise a scrolled-right row is anonymous
                  numbers with no name attached. */}
              <th className="sticky left-0 z-10 bg-[#0f0f0f] px-3 py-2">Player</th>
              <th className="px-3 py-2">Pos</th>
              <th className="px-3 py-2 text-right">Our rank (pos)</th>
              <th className="px-3 py-2 text-right">Our pts</th>
              <th className="px-3 py-2 text-right">ADP rank (pos)</th>
              <th className="px-3 py-2 text-right">ADP</th>
              <th className="px-3 py-2 text-right">Actual rank (pos)</th>
              <th className="px-3 py-2 text-right">Actual pts</th>
              <th className="px-3 py-2">
                <InfoTip label="Fade">{GLOSSARY.fade}</InfoTip>
              </th>
            </tr>
          </thead>
          <tbody>
            {paged.map((r) => (
              <tr key={r.playerId} className="border-b border-[#1a1a1a] last:border-0">
                <td className="sticky left-0 bg-[#0f0f0f] px-3 py-2">
                  <Link
                    href={`/fantasy/player/${r.playerId}`}
                    className="text-gray-200 hover:text-[#10b981] transition-colors"
                  >
                    {r.playerName}
                  </Link>
                </td>
                <td className="px-3 py-2">
                  <PosBadge pos={r.position} />
                </td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-300">{posRank(r.position, r.ourRank)}</td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-400">{num(r.ourPoints)}</td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-300">{posRank(r.position, r.adpRank)}</td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-400">{num(r.adp)}</td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-300">{posRank(r.position, r.actualRank)}</td>
                <td className="px-3 py-2 text-right tabular-nums text-gray-400">{num(r.actualPoints)}</td>
                <td className="px-3 py-2">
                  <FadeBadge isFade={r.isFade} fadeResult={r.fadeResult} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="border-t border-[#262626] p-3">
        <Pagination
          page={page}
          pageSize={pageSize}
          total={sorted.length}
          onPage={setPage}
          onPageSize={setPageSize}
        />
      </div>
    </div>
  )
}

export function FantasyTrackRecordPage() {
  const { data: manifest, isLoading: manifestLoading, error: manifestError } = useTrackRecordManifest()
  const seasons = manifest?.seasons ?? []
  const [season, setSeason] = useState<number | null>(null)
  const activeSeason = season ?? seasons[seasons.length - 1] ?? null
  const { data: seasonRows, isLoading: seasonLoading } = useTrackRecordSeason(activeSeason)
  const [position, setPosition] = useState("All")

  const filteredRows = useMemo(() => {
    const rows = seasonRows ?? []
    return position === "All" ? rows : rows.filter((r) => r.position === position)
  }, [seasonRows, position])

  return (
    <div className="mx-auto max-w-5xl px-4 py-8">
      <SurfaceHeader
        title="Track Record"
        blurb="Our past-season fantasy projections, graded against what actually happened — model rank vs. that season's ADP vs. the realized finish. The full picture, wins and losses both."
      />

      {manifestLoading && <LoadingBlock label="Loading the track record…" />}
      {!manifestLoading && (manifestError || !manifest || seasons.length === 0) && (
        <EmptyBlock
          title="Track record not published yet"
          detail="The receipts export hasn't landed yet — check back soon."
        />
      )}

      {/* ⭐ OUTSIDE the manifest guard, and that placement is load-bearing: "calibration appears
          before the benchmark comparison" must hold on the loading, error and empty renders too,
          not only on the happy path. It carries no measured figure, so there is nothing for it to
          be wrong about while the fetch is in flight. */}
      <CalibrationLead />

      {manifest && seasons.length > 0 && (
        <>
          {/* ⛔ NO `?? manifest.headline` FALLBACK HERE, and that omission is the point. A
              pre-NF-TR1 artifact's `headline` is the un-hedged analyst sentence ("we finished
              ahead", no interval beside it); defaulting to it would put exactly the wording this
              story retires back in the lead position during the deploy-skew window. It renders in
              `LegacyClaim`'s fine print instead, and the calibration block above still leads. */}
          {manifest.claim ? (
            <>
              <ClaimLead lead={manifest.claim.lead} />
              <PositionTable rows={manifest.claim.byPosition} />
              <Disclosures items={manifest.claim.disclosures} />
              <OtherBenchmarksTable rows={manifest.claim.otherBenchmarks} />
              <HowWeMeasured claim={manifest.claim} />
            </>
          ) : (
            <LegacyClaim headline={manifest.headline} />
          )}
          <LockedCurrentSeasonCard lockedSeason={manifest.lockedSeason} />

          <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-wrap gap-1.5">
              {seasons.map((s) => (
                <button
                  key={s}
                  onClick={() => setSeason(s)}
                  className={`rounded border px-2.5 py-1 text-xs font-medium transition-colors ${
                    s === activeSeason
                      ? "border-[#10b981]/50 bg-[#10b981]/10 text-[#10b981]"
                      : "border-[#262626] bg-[#0f0f0f] text-gray-400 hover:text-gray-200"
                  }`}
                >
                  {s}
                </button>
              ))}
            </div>
            <PositionTabs value={position} onChange={setPosition} positions={[...SKILL_POSITIONS]} />
          </div>

          {seasonLoading && <LoadingBlock label="Loading the season…" />}
          {!seasonLoading && seasonRows && (
            <>
              {activeSeason != null && manifest.adpSourceBySeason[String(activeSeason)] === "mfl" && (
                <p className="mb-4 rounded border border-[#262626] bg-[#0f0f0f] px-3 py-2 text-[11px] leading-relaxed text-gray-500">
                  Fantasy Football Calculator has no ADP archive for {activeSeason} — the ADP column
                  below is sourced from MyFantasyLeague instead, a second independent real-draft
                  consensus.
                </p>
              )}
              {activeSeason != null && manifest.adpSourceBySeason[String(activeSeason)] === undefined && (
                <p className="mb-4 rounded border border-[#262626] bg-[#0f0f0f] px-3 py-2 text-[11px] leading-relaxed text-gray-500">
                  No ADP archive is available for {activeSeason} from either source — this season shows
                  our projection vs. the realized outcome only, no ADP column or fade highlighting.
                </p>
              )}
              <RankScatter rows={filteredRows} />
              <TrackRecordTable rows={filteredRows} />
            </>
          )}
        </>
      )}
    </div>
  )
}
