from pipeline.sensors.lineup_monitor_sensor import lineup_monitor_sensor
from pipeline.sensors.pregame_snapshot_sensor import pregame_snapshot_sensor
from pipeline.sensors.clv_alert_sensor import clv_alert_sensor

all_sensors = [lineup_monitor_sensor, pregame_snapshot_sensor, clv_alert_sensor]
