import { readFileSync } from "node:fs"
import { join } from "node:path"
import type { Page, Request, Route } from "@playwright/test"

/**
 * E9.63 — hermetic API + third-party interception.
 *
 * The E2E build is compiled with `NEXT_PUBLIC_API_URL=/__e2e-api` (see `e2e/e2e.env` for why the
 * base must be SAME-ORIGIN — the shipped CSP blocks any other host before Playwright can route
 * it). An API call this file fails to intercept therefore cannot reach production; it lands on the
 * local Next server as a 404 and shows up as a visible failure rather than a test that quietly
 * passes against live data.
 */

export const API_PREFIX = "/__e2e-api"

const FIXTURE_DIR = join(process.cwd(), "e2e", "fixtures", "api")

function fixture<T = any>(name: string): T {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, name), "utf8"))
}

export const FIXTURES = {
  // E9.59. Was synthetic while the route was un-deployed; a REAL capture since 2026-08-07,
  // once the API-Gateway `NONE` route went live. ⚠️ Its amount is now the true $10, so the
  // "a price renders" spec no longer discriminates a hardcoded price — the `transform` spec
  // (which changes the SERVER's amount and demands the DOM follow) is what carries that, and
  // it is immune to whatever this fixture holds.
  publicPricing: () => fixture("subscription-public-pricing.json"),
  projectionsLocked: () => fixture("fantasy-nfl-projections-2026-locked.json"),
  projectionsEntitled: () => fixture("fantasy-nfl-projections-2026-entitled.synthetic.json"),
  manifestLocked: () => fixture("fantasy-nfl-manifest-2026-locked.json"),
  boardLocked: () => fixture("fantasy-nfl-board-full_ppr-12-2026-locked.json"),
  trackRecordManifest: () => fixture("fantasy-nfl-track-record-manifest.json"),
  trackRecordSeason: () => fixture("fantasy-nfl-track-record-2025.json"),
  // E9.46 — the home page's live model-vs-market element. A verbatim public capture; ⚠️ its
  // CONTENT changes every day, so `home-positioning.spec.ts` asserts against the payload's OWN
  // values and never a literal.
  //
  // ⚠️ CORRECTED 2026-08-08: this comment used to say "whichever game currently has the widest
  // gap". It is not. `_FEATURED_TODAY_SERVING_SQL` filters on `layer4_h2h_conviction_flag` (two
  // independent Credence estimators agreeing within 0.02, computed without reference to odds) and
  // then orders `game_datetime ASC … LIMIT 1` — so it is the EARLIEST-STARTING qualifying game,
  // and nothing in the selection looks at the size of the gap at all.
  featuredPick: () => fixture("picks-featured.json"),
  // E9.46 — the ONE public current-season fantasy player. ⚠️ NOT a capture: the route is not
  // deployed yet (it 401s until deploy.sh + the API-Gateway NONE change), so this is generated
  // output of the SHIPPING selector run over the real served board — see
  // `e2e/fixtures/build-featured-player.py`. Its content changes whenever the board is
  // re-published, so the specs assert against the payload's OWN values, never a hardcoded name.
  featuredFantasyPlayer: () => fixture("fantasy-nfl-featured-player.json"),
  // ⭐ FREEMIUM BUILD — the FULL board and manifest, which is what EVERY caller now receives on the
  // generic surfaces. Generated by `build-entitled-fixture.mjs` for the same two reasons the
  // entitled projections are (no public unlocked artifact exists to capture; committing the paid
  // product to test a render is the wrong trade). The board deliberately carries three degenerate
  // expected-games rows — see that script's header.
  boardFree: () => fixture("fantasy-nfl-board-full_ppr-12-2026-free.json"),
  manifestFree: () => fixture("fantasy-nfl-manifest-2026-free.json"),
}

/**
 * Which shape the fantasy surfaces get back.
 *
 *   "free"     — the generic board, un-redacted. ⭐ THE DEFAULT, because since the freemium build
 *                this is what an ANONYMOUS visitor receives; it is also byte-identical to what a
 *                subscriber receives, which `test_freemium_tier.py` asserts server-side.
 *   "entitled" — the same thing for the projections surface, kept under its own name so the
 *                pre-freemium specs read unchanged.
 *   "locked"   — 🗄️ THE RETIRED E9.56 REDACTION. No live caller receives this any more. It is kept
 *                because the components still carry their `locked` branches (a row arriving without
 *                `pts` must render a chip, never `NaN`), and `locked-surfaces.spec.ts` is what
 *                proves those branches still work — i.e. that withdrawing the open board would be
 *                a config decision rather than a rebuild. ⛔ Do not read a spec using this mode as
 *                a description of current behaviour.
 */
export type Entitlement = "free" | "locked" | "entitled"

export type MockOptions = {
  entitlement?: Entitlement
  /** Last-chance mutation of a payload before it is served — used to reproduce a server state we
   *  cannot capture (e.g. the deploy-skew `upgrade.ctaHref: "/pricing"` of E9.56c). */
  transform?: (pathname: string, body: any) => any
  /**
   * API paths to answer with a 5xx instead of a fixture — the READ ITSELF failing, which
   * `transform` structurally cannot express (it rewrites a body that was successfully served).
   *
   * ⭐ E9.46 needs it because "the model published nothing today" and "this page could not reach
   * the model" are DIFFERENT FACTS that the home page states differently, and a harness that can
   * only produce the first can only ever test half of that. Registered here rather than as a
   * spec-local `page.route` override so the call still lands in `requested` — an override would
   * make the request invisible to `expectApiFullyMocked`, i.e. a failure path that looks to the
   * harness like a page that never asked for anything.
   */
  fail?: string[]
}

export type ApiMock = {
  /** Every API path the page asked for. */
  requested: string[]
  /** API paths NO fixture matched — a non-empty list means the page reached for something this
   *  harness does not model, and every assertion downstream of it is suspect. */
  unmatched: string[]
}

/** The one free (config, size) preset — mirrors `entitlement.FREE_BOARD_CONFIG`/`FREE_BOARD_SIZE`.
 *  Held here as well as in the fixture so the harness can REFUSE a paid board rather than serving
 *  every preset a 200 and letting a spec assert against a state the API never produces. */
export const FREE_BOARD = { config: "full_ppr", size: 12 } as const

function payloadFor(pathname: string, entitlement: Entitlement): unknown | undefined {
  const locked = entitlement === "locked"
  if (pathname === "/fantasy/nfl/projections") {
    return locked ? FIXTURES.projectionsLocked() : FIXTURES.projectionsEntitled()
  }
  if (pathname === "/subscription/public-pricing") return FIXTURES.publicPricing()
  // ⚠️ THESE TWO USED TO IGNORE `entitlement` ENTIRELY and always serve the locked capture, which
  // was correct while the locked payload was the only anonymous shape. Post-freemium that would
  // make every "free" spec silently assert against the retired redaction — a suite testing a state
  // no user can reach, and passing.
  if (pathname === "/fantasy/nfl/manifest") {
    return locked ? FIXTURES.manifestLocked() : FIXTURES.manifestFree()
  }
  if (pathname === "/fantasy/nfl/board") {
    return locked ? FIXTURES.boardLocked() : FIXTURES.boardFree()
  }
  if (pathname === "/fantasy/nfl/track-record/manifest") return FIXTURES.trackRecordManifest()
  if (/^\/fantasy\/nfl\/track-record\/\d{4}$/.test(pathname)) return FIXTURES.trackRecordSeason()
  if (pathname === "/picks/featured") return FIXTURES.featuredPick()
  if (pathname === "/fantasy/nfl/featured-player") return FIXTURES.featuredFantasyPlayer()
  return undefined
}

/**
 * Install the API mock and the third-party blocks on a page.
 *
 * Returns a live record of what was asked for — assert `unmatched` is empty in any spec whose
 * conclusion depends on the page having got its data.
 */
/**
 * G100-D1 — the CDN read path.
 *
 * An ANONYMOUS caller no longer calls the API Lambda directly: `lib/api.ts::cdnFetch` fetches the
 * same-origin `/api/public/*` route handler, which Vercel serves from the edge (see that handler's
 * module comment). Those requests do NOT carry `API_PREFIX`, so without this map they would slip
 * past the interceptor entirely — and, because they are same-origin, they would land on the local
 * Next server and be answered by the REAL handler, which would then try to reach the real API. A
 * hermetic suite would silently stop being hermetic.
 *
 * Mapping back to the canonical API path (rather than adding a second fixture key space) is what
 * keeps every existing spec working unchanged: `fail: ["/picks/featured"]` and any `transform`
 * keyed on an API path keep meaning exactly what they meant before, regardless of which transport
 * the page happened to use.
 *
 * ⚠️ COVERAGE NOTE: intercepting here means Playwright answers BEFORE the route handler runs, so
 * the handler's own logic is not exercised by the E2E suite. That is deliberate — its contract
 * (never forwards Authorization, allowlist-only, never caches an empty body) is pinned by
 * `betting_ml/tests/test_g100_d1_cost_guardrails.py`, and its actual payoff is CDN behaviour that
 * no browser test can observe anyway.
 */
const CDN_PREFIX = "/api/public"

function cdnPathToApiPath(pathname: string): string | undefined {
  if (!pathname.startsWith(CDN_PREFIX + "/")) return undefined
  const rest = pathname.slice(CDN_PREFIX.length + 1)
  if (rest === "featured") return "/picks/featured"
  if (rest === "featured-player") return "/fantasy/nfl/featured-player"
  if (rest === "manifest") return "/fantasy/nfl/manifest"
  if (rest === "projections") return "/fantasy/nfl/projections"
  if (rest === "board") return "/fantasy/nfl/board"
  if (rest === "track-record/manifest") return "/fantasy/nfl/track-record/manifest"
  if (/^track-record\/\d{4}$/.test(rest)) return `/fantasy/nfl/${rest}`
  return undefined
}

export async function mockApi(page: Page, options: MockOptions = {}): Promise<ApiMock> {
  // ⭐ DEFAULT FLIPPED FROM "locked" TO "free" (freemium build). The default has to be what an
  // anonymous visitor actually gets, or a new spec that forgets to name a mode silently tests a
  // state no user can reach. Every pre-existing spec names its mode explicitly, so nothing else
  // moves. `entitled` is retained as a distinct name and resolves to the same payloads.
  const entitlement = options.entitlement ?? "free"
  const mock: ApiMock = { requested: [], unmatched: [] }

  /** Answer one intercepted call, given the canonical API path it resolves to. */
  const fulfil = async (route: Route, apiPath: string, search: string) => {
    mock.requested.push(apiPath + search)

    if (options.fail?.includes(apiPath)) {
      await route.fulfill({
        status: 503,
        contentType: "application/json",
        body: JSON.stringify({ detail: "e2e: deliberate read failure" }),
      })
      return
    }

    // ⭐ THE HARNESS MODELS THE FORMAT PAYWALL, because a mock that answered 200 for every preset
    // would let a spec "prove" a locked format renders fine — a state no user can reach. One preset
    // is free (`entitlement.FREE_BOARD_CONFIG`/`FREE_BOARD_SIZE`); anything else is a 403.
    // Mirrors `routers/fantasy.py::nfl_board`.
    //
    // ⚠️ "free" ONLY, NOT "not entitled". `"locked"` models the RETIRED E9.56 server, which served
    // every preset with its values removed and had no format tier at all — applying today's paywall
    // there would refuse boards that server answered, and `locked-surfaces.spec.ts` would fail
    // describing a world neither server ever produced. A mock must model ONE server per mode.
    if (apiPath === "/fantasy/nfl/board" && entitlement === "free") {
      const q = new URLSearchParams(search)
      const isFreeBoard = q.get("config") === FREE_BOARD.config && q.get("size") === String(FREE_BOARD.size)
      if (!isFreeBoard) {
        await route.fulfill({
          status: 403,
          contentType: "application/json",
          body: JSON.stringify({ detail: "This league format is part of a Credence membership." }),
        })
        return
      }
    }

    let body = payloadFor(apiPath, entitlement)
    if (body === undefined) {
      mock.unmatched.push(apiPath + search)
      await route.fulfill({
        status: 501,
        contentType: "application/json",
        body: JSON.stringify({ detail: `e2e: no fixture for ${apiPath}` }),
      })
      return
    }
    if (options.transform) body = options.transform(apiPath, body)

    await route.fulfill({
      status: 200,
      contentType: "application/json",
      headers: { "access-control-allow-origin": "*" },
      body: JSON.stringify(body),
    })
  }

  await page.route(`**${API_PREFIX}/**`, async (route: Route, request: Request) => {
    const url = new URL(request.url())
    // Strip the harness prefix so the fixture map is keyed on the API's OWN paths — the same
    // strings that appear in `app/backend/routers/fantasy.py`.
    const apiPath = url.pathname.slice(url.pathname.indexOf(API_PREFIX) + API_PREFIX.length)
    await fulfil(route, apiPath, url.search)
  })

  await page.route(`**${CDN_PREFIX}/**`, async (route: Route, request: Request) => {
    const url = new URL(request.url())
    const apiPath = cdnPathToApiPath(url.pathname)
    if (apiPath === undefined) {
      // An unmapped CDN path is a harness gap, not a pass — surface it the same way an unmatched
      // API path is surfaced rather than letting it reach the real handler.
      mock.unmatched.push(url.pathname + url.search)
      await route.fulfill({
        status: 501,
        contentType: "application/json",
        body: JSON.stringify({ detail: `e2e: unmapped CDN path ${url.pathname}` }),
      })
      return
    }
    await fulfil(route, apiPath, url.search)
  })

  await blockThirdParty(page)
  return mock
}

/**
 * Cut every third-party beacon. Sentry's DSN is hardcoded in `instrumentation-client.ts` and
 * PostHog is proxied through the same-origin `/ingest` rewrite, so without this the suite makes
 * real outbound calls from CI — slow, flaky, and it pollutes production analytics with robot
 * traffic.
 */
export async function blockThirdParty(page: Page) {
  for (const pattern of ["**/ingest/**", "**/*.sentry.io/**", "**/*.i.posthog.com/**"]) {
    await page.route(pattern, (route) => route.abort())
  }
}

/** Collect uncaught page errors so a spec can assert the surface rendered without throwing. */
export function collectPageErrors(page: Page): string[] {
  const errors: string[] = []
  page.on("pageerror", (e) => errors.push(String(e)))
  return errors
}
