import { readFileSync } from "node:fs"
import { join } from "node:path"
import type { Page, Request, Route } from "@playwright/test"
import { buildBoard, matchRosterToBoard } from "@/lib/league-scoring"
import { buildEnv } from "./env"

/**
 * E9.63 — hermetic API + third-party interception.
 *
 * The E2E build is compiled with `NEXT_PUBLIC_API_URL=/__e2e-api` (see `e2e/e2e.env` for why the
 * base must be SAME-ORIGIN — the shipped CSP blocks any other host before Playwright can route
 * it). An API call this file fails to intercept therefore cannot reach production; it lands on the
 * local Next server as a 404 and shows up as a visible failure rather than a test that quietly
 * passes against live data.
 */

export const API_PREFIX = "/__e2e-api"

/** The fake PostHog token the E2E build is compiled with — read from the same file the build
 *  sourced, never hardcoded, so a change to `e2e.env` cannot silently orphan the remote-config
 *  stub keyed on it (`buildEnv` throws rather than returning undefined). */
const POSTHOG_E2E_TOKEN = buildEnv("NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN")

const FIXTURE_DIR = join(process.cwd(), "e2e", "fixtures", "api")

function fixture<T = any>(name: string): T {
  return JSON.parse(readFileSync(join(FIXTURE_DIR, name), "utf8"))
}

export const FIXTURES = {
  // E9.59. Was synthetic while the route was un-deployed; a REAL capture since 2026-08-07,
  // once the API-Gateway `NONE` route went live. ⚠️ Its amount is now the true $10, so the
  // "a price renders" spec no longer discriminates a hardcoded price — the `transform` spec
  // (which changes the SERVER's amount and demands the DOM follow) is what carries that, and
  // it is immune to whatever this fixture holds.
  publicPricing: () => fixture("subscription-public-pricing.json"),
  projectionsLocked: () => fixture("fantasy-nfl-projections-2026-locked.json"),
  projectionsEntitled: () => fixture("fantasy-nfl-projections-2026-entitled.synthetic.json"),
  manifestLocked: () => fixture("fantasy-nfl-manifest-2026-locked.json"),
  boardLocked: () => fixture("fantasy-nfl-board-full_ppr-12-2026-locked.json"),
  trackRecordManifest: () => fixture("fantasy-nfl-track-record-manifest.json"),
  trackRecordSeason: () => fixture("fantasy-nfl-track-record-2025.json"),
  // E9.46 — the home page's live model-vs-market element. A verbatim public capture; ⚠️ its
  // CONTENT changes every day, so `home-positioning.spec.ts` asserts against the payload's OWN
  // values and never a literal.
  //
  // ⚠️ CORRECTED 2026-08-08: this comment used to say "whichever game currently has the widest
  // gap". It is not. `_FEATURED_TODAY_SERVING_SQL` filters on `layer4_h2h_conviction_flag` (two
  // independent Credence estimators agreeing within 0.02, computed without reference to odds) and
  // then orders `game_datetime ASC … LIMIT 1` — so it is the EARLIEST-STARTING qualifying game,
  // and nothing in the selection looks at the size of the gap at all.
  featuredPick: () => fixture("picks-featured.json"),
  // E9.46 — the ONE public current-season fantasy player. ⚠️ NOT a capture: the route is not
  // deployed yet (it 401s until deploy.sh + the API-Gateway NONE change), so this is generated
  // output of the SHIPPING selector run over the real served board — see
  // `e2e/fixtures/build-featured-player.py`. Its content changes whenever the board is
  // re-published, so the specs assert against the payload's OWN values, never a hardcoded name.
  featuredFantasyPlayer: () => fixture("fantasy-nfl-featured-player.json"),
  // ⭐ FREEMIUM BUILD — the FULL board and manifest, which is what EVERY caller now receives on the
  // generic surfaces. Generated by `build-entitled-fixture.mjs` for the same two reasons the
  // entitled projections are (no public unlocked artifact exists to capture; committing the paid
  // product to test a render is the wrong trade). The board deliberately carries three degenerate
  // expected-games rows — see that script's header.
  boardFree: () => fixture("fantasy-nfl-board-full_ppr-12-2026-free.json"),
  manifestFree: () => fixture("fantasy-nfl-manifest-2026-free.json"),
  // ⭐ G100-C1 — a free account's ONE saved league, as `/fantasy/nfl/my-teams` serves it.
  //
  // Deliberately a league that DIFFERS from the free preset in three ways at once (10 teams not 12,
  // half-PPR not full, superflex + two starting TEs with a TE reception premium). A fixture close to
  // `full_ppr`/12 would produce a near-empty delta, and every assertion about the activation screen
  // would pass just as well against a broken delta computation — the "fixture where nothing can go
  // wrong" shape. These settings move QBs and TEs by whole tiers, so the screen has something real
  // to show and a sign error is visible.
  myTeams: () => fixture("fantasy-nfl-my-teams.json"),
  // ⭐ G100-C1 (live fix) — the import platform list and one Sleeper account's leagues.
  //
  // ⚠️ THE LEAGUE LIST DELIBERATELY CONTAINS BOTH CASES: `999999` is the league `myTeams` already
  // holds (so it is an UPDATE, which costs no quota and must stay importable) and `888888` is a
  // second one (a CREATE, which the free quota refuses). A fixture with only the unsaved league
  // would let "everything is locked" pass as correct, which is the defect facing the other way —
  // a returning user could no longer re-sync the roster they already have.
  importPlatforms: () => fixture("fantasy-import-platforms.json"),
  importSleeperLeagues: () => fixture("fantasy-import-sleeper-leagues.json"),
}

/**
 * Which shape the fantasy surfaces get back.
 *
 *   "free"     — the generic board, un-redacted. ⭐ THE DEFAULT, because since the freemium build
 *                this is what an ANONYMOUS visitor receives; it is also byte-identical to what a
 *                subscriber receives, which `test_freemium_tier.py` asserts server-side.
 *   "entitled" — the same thing for the projections surface, kept under its own name so the
 *                pre-freemium specs read unchanged.
 *   "locked"   — 🗄️ THE RETIRED E9.56 REDACTION. No live caller receives this any more. It is kept
 *                because the components still carry their `locked` branches (a row arriving without
 *                `pts` must render a chip, never `NaN`), and `locked-surfaces.spec.ts` is what
 *                proves those branches still work — i.e. that withdrawing the open board would be
 *                a config decision rather than a rebuild. ⛔ Do not read a spec using this mode as
 *                a description of current behaviour.
 */
export type Entitlement = "free" | "locked" | "entitled"

export type MockOptions = {
  entitlement?: Entitlement
  /** Last-chance mutation of a payload before it is served — used to reproduce a server state we
   *  cannot capture (e.g. the deploy-skew `upgrade.ctaHref: "/pricing"` of E9.56c). */
  transform?: (pathname: string, body: any) => any
  /**
   * API paths to answer with a 5xx instead of a fixture — the READ ITSELF failing, which
   * `transform` structurally cannot express (it rewrites a body that was successfully served).
   *
   * ⭐ E9.46 needs it because "the model published nothing today" and "this page could not reach
   * the model" are DIFFERENT FACTS that the home page states differently, and a harness that can
   * only produce the first can only ever test half of that. Registered here rather than as a
   * spec-local `page.route` override so the call still lands in `requested` — an override would
   * make the request invisible to `expectApiFullyMocked`, i.e. a failure path that looks to the
   * harness like a page that never asked for anything.
   */
  fail?: string[]
  /**
   * ⭐ G100-C1 — how many personalized leagues this caller has SAVED.
   *
   *   "none"     — a fresh free account. THE DEFAULT, because it is the state every new user is in
   *                and the state the activation screen's empty branch has to handle. A spec that
   *                forgets to name a mode gets the honest starting point rather than a configured
   *                league it never asked for.
   *   "one"      — the free tier, in use.
   *   "overQuota"— a LAPSED SUBSCRIBER: three saved, one served. `withheld_by_quota` is non-zero,
   *                which is the only way to exercise the "nothing was deleted" notice.
   *   "linked"   — ⭐ E9.64: TWO leagues, both with a linked team and a real roster. The mode My
   *                Teams needs, because the captured league is `source_team_key: null` with a null
   *                roster — an honest state, and the ONLY one the other three modes can produce, so
   *                every roster table on that surface was structurally unreachable. See
   *                `linkedLeaguePair` for why the two differ in exactly one scoring rule.
   */
  leagues?: "none" | "one" | "overQuota" | "linked"
  /**
   * ⭐ G100-D0 — what `/subscription/status` reports for this caller.
   *
   *   "none"     — THE DEFAULT. No access: the state a visitor is in when they click Subscribe,
   *                and the state the post-checkout screen is in while the Stripe webhook has not
   *                landed yet.
   *   "active"   — `has_access: true`. The post-checkout screen's poll succeeds.
   *
   * Both are needed and neither is redundant: `subscription_started` must fire on the second and
   * must NOT fire on the first, and a harness that could only produce "active" would make the
   * negative half of that contract untestable — i.e. it could not tell "fires when access lands"
   * from "fires on page load", which is the defect this event is most likely to have.
   */
  subscription?: "none" | "active"
  /**
   * ⭐ G100-D0-R1 — what `POST /auth/accept-terms` answers, which is now the SIGNUP SIGNAL.
   *
   *   "created"  — this sign-in recorded the account's FIRST acceptance ⇒ a new account, at
   *                whichever door. `user_signup_completed` must fire.
   *   "existing" — THE DEFAULT, because it is the ordinary steady state (every sign-in after the
   *                first). `user_signup_completed` must NOT fire, even when the visitor clicked
   *                Sign Up — that is the false positive R1 removed, and a harness that could not
   *                produce this mode could not test it.
   *   "skew"     — the pre-R1 Lambda: `204`, no body. Neither `created: true` nor `created: false`
   *                but ABSENT, which the client must read as "the server did not tell us" and NOT
   *                as a negative answer. The API ships only via deploy.sh while the frontend
   *                auto-deploys, so this state is guaranteed to happen at least once in prod.
   */
  termsAcceptance?: "created" | "existing" | "skew"
  /**
   * ⭐ E9.64 — hold these API paths back by `ms` before answering, to make a RACE deterministic.
   *
   * ⚠️ THIS IS NOT A LATENCY KNOB, and using it as one would be a mistake. It exists because a
   * red-proof case for a race is worthless unless the race resolves the same way every run.
   * `custom-selection-lost-to-the-load-race` breaks `useFormatSelection`'s `savedLeaguesLoading`
   * deferral — the guard that stops it committing a format before it knows whether the caller has a
   * saved league. Against a local server both reads land within a few ms of each other, so the
   * broken build lost the race SOMETIMES: two consecutive runs of identical code gave RED and then
   * MISMATCH, which is the worst possible verdict from a falsifiability harness (a single green run
   * reads as proof).
   *
   * Delaying `/fantasy/leagues` makes the manifest reliably win. That does not weaken the healthy
   * path — the deferral's whole job is to WAIT for that read, so the fixed build passes at any
   * delay, and the case now separates the two builds every time.
   *
   * ⛔ Do not reach for this to "give the page time to settle". Auto-retrying assertions do that
   * job; a delay bakes a timing assumption into the harness. It is for ORDERING two reads whose
   * relative order is the property under test.
   */
  delay?: { paths: string[]; ms: number }
}

export type ApiMock = {
  /** Every API path the page asked for. */
  requested: string[]
  /** API paths NO fixture matched — a non-empty list means the page reached for something this
   *  harness does not model, and every assertion downstream of it is suspect. */
  unmatched: string[]
}

/** The one free (config, size) preset — mirrors `entitlement.FREE_BOARD_CONFIG`/`FREE_BOARD_SIZE`.
 *  Held here as well as in the fixture so the harness can REFUSE a paid board rather than serving
 *  every preset a 200 and letting a spec assert against a state the API never produces. */
export const FREE_BOARD = { config: "full_ppr", size: 12 } as const

function payloadFor(pathname: string, entitlement: Entitlement): unknown | undefined {
  const locked = entitlement === "locked"
  if (pathname === "/fantasy/nfl/projections") {
    return locked ? FIXTURES.projectionsLocked() : FIXTURES.projectionsEntitled()
  }
  // 🔒 NF-EPIC 1 — the PAID half of the projection (raw stat line + fpStd/fpHalf).
  //
  // ⚠️ ENTITLED ONLY, and modelling the refusal is the point: falling through to `undefined` makes
  // the harness answer 501/unmatched for a free caller, which is what a spec asserting "a free
  // account cannot obtain the stat line" needs. Serving it to everyone would let that spec pass
  // against a server no caller can reach — the shape this harness's own comments warn about.
  if (pathname === "/fantasy/nfl/projections-full") {
    return entitlement === "entitled" ? FIXTURES.projectionsEntitled() : undefined
  }
  if (pathname === "/subscription/public-pricing") return FIXTURES.publicPricing()
  // ⚠️ THESE TWO USED TO IGNORE `entitlement` ENTIRELY and always serve the locked capture, which
  // was correct while the locked payload was the only anonymous shape. Post-freemium that would
  // make every "free" spec silently assert against the retired redaction — a suite testing a state
  // no user can reach, and passing.
  if (pathname === "/fantasy/nfl/manifest") {
    return locked ? FIXTURES.manifestLocked() : FIXTURES.manifestFree()
  }
  if (pathname === "/fantasy/nfl/board") {
    return locked ? FIXTURES.boardLocked() : FIXTURES.boardFree()
  }
  if (pathname === "/fantasy/nfl/track-record/manifest") return FIXTURES.trackRecordManifest()
  if (/^\/fantasy\/nfl\/track-record\/\d{4}$/.test(pathname)) return FIXTURES.trackRecordSeason()
  if (pathname === "/picks/featured") return FIXTURES.featuredPick()
  if (pathname === "/fantasy/nfl/featured-player") return FIXTURES.featuredFantasyPlayer()
  // ── PLATFORM IMPORT (NF-C0), as far as the LEAGUE LIST ────────────────────────────────────────
  // Deliberately NOT the preview endpoint. The list is where G100-C1's quota boundary is drawn —
  // once an account is at its quota, every league here except the one it already saved is
  // unimportable, and that has to be visible BEFORE the work. Mocking `preview` too would model a
  // flow the free tier is not supposed to be able to reach.
  if (pathname === "/fantasy/import/platforms") return FIXTURES.importPlatforms()
  if (pathname === "/fantasy/import/sleeper/leagues") return FIXTURES.importSleeperLeagues()
  return undefined
}

/**
 * G100-D0 — the BILLING reads, which are per-caller and therefore kept out of `payloadFor` for the
 * same reason the saved-league reads are (that function's whole point is a payload that does not
 * depend on who is asking).
 *
 * ⚠️ The checkout-session URL is a host the spec ANSWERS rather than one it aborts. `startCheckout`
 * ends in `window.location.href = res.url`, and an aborted top-level navigation strands the tab on
 * `about:blank` — whose origin is `null`, so reading `localStorage` throws `SecurityError` and the
 * failure has nothing to do with the page under test (the same trap `signup-funnel.spec.ts`
 * documents for the Cognito redirect).
 */
export const E2E_CHECKOUT_URL = "https://checkout.stripe.com/c/pay/e2e-fake-session"

/** The id a CREATE hands back. A spec can assert on it to prove the save round-tripped. */
export const E2E_CREATED_LEAGUE_ID = "e2e-created-league"

/**
 * G100-D0 — the league WRITE path (`POST` creates, `PUT` updates).
 *
 * Returns `undefined` for anything that is not a league write, so the read map is reached unchanged.
 *
 * ⚠️ The `POST`/`PUT` split is not cosmetic — it is the exact distinction `league_config_completed`
 * keys on. The editor treats a `null` league id as a CREATE and fires the activation clause; an
 * update fires nothing, deliberately, so that one user tweaking a scoring weight cannot inflate the
 * denominator paid conversion is measured against. A harness that answered both identically could
 * not tell those two apart, and the "fires on every save" defect would pass.
 *
 * ⛔ It does NOT model the server's quota refusal (`409` on a second create). That is enforced
 * server-side and asserted against the real ASGI app in `test_g100_c1_free_league.py`; reproducing
 * it here would be a browser test appearing to check authorization, which is the most convincing
 * vacuous guard available.
 */
function writeResponseFor(
  pathname: string,
  method: string,
  postData: string | null,
): unknown | undefined {
  const isCreate = method === "POST" && pathname === "/fantasy/leagues"
  const isUpdate = method === "PUT" && /^\/fantasy\/leagues\/[^/]+$/.test(pathname)
  if (!isCreate && !isUpdate) return undefined

  let config: Record<string, unknown> = {}
  try {
    config = postData ? JSON.parse(postData) : {}
  } catch {
    config = {}
  }
  return {
    ...config,
    league_id: isCreate ? E2E_CREATED_LEAGUE_ID : pathname.split("/").pop(),
    created_at: "2026-08-09T12:00:00Z",
    updated_at: "2026-08-09T12:00:00Z",
  }
}

function billingPayloadFor(
  pathname: string,
  subscription: NonNullable<MockOptions["subscription"]>,
): unknown | undefined {
  if (pathname === "/subscription/status") {
    const active = subscription === "active"
    return {
      tier: active ? "subscriber" : "free",
      has_access: active,
      is_beta: false,
      has_billing: active,
      cancel_at_period_end: false,
      current_period_end: null,
    }
  }
  if (pathname === "/subscription/pricing") {
    return {
      tier: "founding",
      unit_amount: 1000,
      currency: "usd",
      founding_slots_used: 3,
      founding_cap: 50,
      founding_available: true,
    }
  }
  if (pathname === "/stripe/create-checkout-session") return { url: E2E_CHECKOUT_URL }
  return undefined
}

/**
 * ⭐ E9.64 — the LINKED pair My Teams is built to show, and the one shape no other mode can produce.
 *
 * ══ WHY A PAIR, AND WHY THEY DIFFER IN EXACTLY ONE RULE ═══════════════════════════════════════
 *
 * NF-C6's whole claim is "each roster scored under ITS OWN league's format". A single league cannot
 * test that at all, and two leagues differing in many ways would let any number of wrong
 * implementations pass — including the one that matters, where the surface scores every roster on
 * ONE board and relabels it. So these two are byte-identical except for what a reception is worth
 * (`per_stat.rec`: the captured 0.5, and 0), carrying the SAME roster of the SAME players.
 *
 * That makes the difference between the two cards ARITHMETIC rather than a vibe: for a non-TE it is
 * exactly `0.5 × receptions`, which `fantasy-my-teams.spec.ts` computes from the projections
 * fixture's own `rec` and checks. A surface that scored both rosters on one board renders identical
 * numbers and fails; one that merely scored them "differently" fails too, because the size of the
 * difference is pinned. ⚠️ The TE bonus (`position_bonuses.TE.rec: 0.5`) makes a TE's effective
 * reception worth 1.0, so the spec must choose a non-TE — the roster below is built to give it one.
 *
 * ⛔ NOTHING HERE IS HAND-WRITTEN. The league is the real capture with two fields changed, and every
 * rostered player is read out of the real projections payload — which is the point: a hand-authored
 * roster would encode this session's assumption about the name/position join
 * (`matchRosterToBoard` keys on a normalized `name|pos`), i.e. the very thing under test.
 */

/** A rostered name that is deliberately NOT on the board — the "we could not resolve this" row. */
export const E2E_UNMATCHED_ROSTER_NAME = "Notta Realplayer"

/** The first player at `pos`, in served order, with a non-zero reception count where asked. */
function boardPlayerAt(pos: string, needsReceptions: boolean): any {
  const players = FIXTURES.projectionsEntitled().players as any[]
  const hit = players.find(
    (p) => p.pos === pos && (!needsReceptions || (p.rec ?? 0) > 0) && !!p.name,
  )
  // A missing position is a FIXTURE change, not a test failure to be shrugged off: every assertion
  // downstream would silently describe a roster that is one player short.
  if (!hit) throw new Error(`e2e: the projections fixture has no ${pos} with the required stat line`)
  return hit
}

/**
 * The rostered player the cross-league arithmetic is checked on.
 *
 * ⚠️ EXPORTED SO THERE IS ONE SPELLING OF THE SELECTOR. `fantasy-my-teams.spec.ts` needs both his
 * NAME (to find his rows) and his projected RECEPTIONS (to predict the gap between the two leagues);
 * re-deriving him there with a copy of this predicate would silently start describing a different
 * player the moment either copy moved, and the spec would then assert a correct gap about the wrong
 * man. ⭐ NON-TE deliberately: `position_bonuses.TE.rec` makes a tight end's reception worth 1.0
 * rather than 0.5, so a TE subject would put the expected gap out by exactly a factor of two — and
 * that reads as a scoring bug in the app rather than in the test.
 */
export function linkedRosterSubject(): { name: string; rec: number } {
  const wr = boardPlayerAt("WR", true)
  return { name: wr.name, rec: wr.rec }
}

/**
 * The ONE saved league's server-scored board, exactly as `/fantasy/nfl/league-board` serves it.
 *
 * ⚠️ EXPORTED FOR THE SAME REASON AS `linkedRosterSubject` — one spelling. `free-league.spec.ts`
 * re-derives the overall-rank move from the two boards' OWN `ovrRank` values, and a second local
 * `buildBoard(...)` call there would be a copy of this that can drift; the spec would then compare
 * the rendered chip against a board the app was never served.
 */
export function leagueBoardPlayers(): { id: string; name: string; ovrRank: number }[] {
  return leagueBoardBuild().players as { id: string; name: string; ovrRank: number }[]
}

function leagueBoardBuild() {
  return buildBoard(FIXTURES.projectionsEntitled().players, FIXTURES.myTeams().leagues[0])
}

function linkedRoster(): unknown[] {
  const entry = (p: any, starter: boolean) => ({
    player_key: `e2e-${p.id}`,
    name: p.name,
    position: p.pos,
    team: p.team,
    starter,
  })
  return [
    // ⭐ The WR is the one the arithmetic check uses — non-TE, so no position bonus is in play.
    entry(boardPlayerAt("WR", true), true),
    entry(boardPlayerAt("RB", true), true),
    entry(boardPlayerAt("QB", false), true),
    // A bench player, so BOTH roster tables render — `RosterTable` returns null on an empty list,
    // and a roster of starters only would leave the bench branch unexercised.
    entry(boardPlayerAt("TE", true), false),
    // Unresolvable, so the "N of M matched" note has something to count. A roster where everything
    // matches cannot tell "the note is correct" from "the note never renders".
    {
      player_key: "e2e-unmatched",
      name: E2E_UNMATCHED_ROSTER_NAME,
      position: "WR",
      team: "FA",
      starter: false,
    },
  ]
}

/** The captured league, linked, plus its reception-free twin. Ids are stable for spec locators. */
export const E2E_LINKED_LEAGUES = {
  half: { id: "e2e-league-1", name: "Sunday Money" },
  standard: { id: "e2e-league-standard", name: "Standard Money" },
} as const

function linkedLeaguePair(): any[] {
  const base = FIXTURES.myTeams().leagues[0]
  const roster = linkedRoster()
  const half = {
    ...base,
    league_id: E2E_LINKED_LEAGUES.half.id,
    name: E2E_LINKED_LEAGUES.half.name,
    source_team_key: "e2e-team-1",
    source_team_name: "Credence FC",
    imported_roster: roster,
    roster_synced_at: "2026-08-10T12:00:00Z",
  }
  return [
    half,
    {
      ...half,
      league_id: E2E_LINKED_LEAGUES.standard.id,
      name: E2E_LINKED_LEAGUES.standard.name,
      ppr: "standard",
      scoring: { ...base.scoring, per_stat: { ...base.scoring.per_stat, rec: 0 } },
    },
  ]
}

/**
 * ⭐ E9.64 — THE IMPORT PREVIEW: step 2 of the importer, "Review what we read".
 *
 * ══ WHY THIS IS SYNTHESISED AND WHY THAT IS THE RIGHT CALL HERE ═══════════════════════════════
 *
 * The README's rule is ⛔ do not hand-write a fixture, because a hand-written one encodes the
 * assumption under test. There is no capture to take: `/fantasy/import/sleeper/preview` requires an
 * authenticated caller AND a real Sleeper league, so nothing anonymous can produce one — the same
 * position `build-entitled-fixture.mjs` and the track-record claim builder were in, and this follows
 * their precedent: derive everything that CAN be real, and say plainly what cannot.
 *
 *   · `config` IS the real captured league (`fantasy-nfl-my-teams.json`) — its scoring, its roster
 *     shape, its team count. That is the part the review screen reads out, so it is the part that
 *     had to be real.
 *   · `teams` are built from the real board, so the roster names resolve through the same
 *     `name|pos` join the app uses.
 *   · `warnings` / `unmapped_scoring_keys` are SYNTHETIC, and unavoidably so: a warning list has to
 *     be NON-EMPTY for "the things we could not read are shown before you save" to mean anything,
 *     and no anonymous capture can supply one. ⚠️ That is not a hole in the assertion, because the
 *     property under test is that whatever the SERVER sends is rendered VERBATIM — the component's
 *     own comment ("an import that quietly loses a rule is the failure this whole surface guards").
 *     The wording being ours is exactly why the spec can check it word for word.
 */
export const E2E_IMPORT_WARNING =
  "Your league scores a bonus for a 40+ yard reception that we record but do not project."

/** A scoring key we carry through under the platform's own name without projecting it. */
export const E2E_IMPORT_UNMAPPED_KEY = "rec_40p_bonus"

/** Two teams off the real board. Neither is flagged `is_owner` — Sleeper cannot tell us which team
 *  is the caller's, which is precisely why the review screen makes the user pick one (NF-C6). */
function previewTeams(): unknown[] {
  const players = FIXTURES.projectionsEntitled().players as any[]
  const take = (from: number, count: number) =>
    players.slice(from, from + count).map((p) => ({
      player_key: `e2e-${p.id}`,
      name: p.name,
      position: p.pos,
      team: p.team,
      starter: true,
    }))
  return [
    { team_key: "e2e-team-1", name: "Credence FC", owner: "e2e-tester", is_owner: false, players: take(0, 4) },
    { team_key: "e2e-team-2", name: "Rivals United", owner: "someone-else", is_owner: false, players: take(4, 4) },
  ]
}

function importPreviewFor(sourceLeagueId: string): unknown {
  const base = FIXTURES.myTeams().leagues[0] as any
  // The league CONFIG only — never the saved-league envelope. A preview describes what the platform
  // says, and carrying `league_id` through here would let a spec pass while the importer treated an
  // un-saved preview as an already-saved league.
  const { name, n_teams, ppr, superflex, scoring, roster, sport, format_version } = base
  return {
    platform: "sleeper",
    source_league_id: sourceLeagueId,
    season: "2026",
    config: {
      name,
      n_teams,
      ppr,
      superflex,
      // ⚠️ A CAPTURED TERM IS AN ORDINARY `per_stat` RULE WITH NO PROJECTION BEHIND IT — that is the
      // whole mechanism, and it took two wrong guesses to land on. `resolveScoring` builds its term
      // list from `per_stat` ALONE and grades each key `applied` or `captured` by whether
      // `STAT_FIELD` knows it; `capturedRules` is carried on the report but never becomes a term,
      // and `unmapped_scoring_keys` only supplies display LABELS. So a mock that set either of
      // those instead (both read as the obvious place) would render the disclosure nowhere while
      // looking entirely reasonable — and a spec asserting on it would be asserting on a screen the
      // user never sees. `captured_rules` is kept alongside because that is where a SAVED league
      // stores the same fact.
      scoring: {
        ...scoring,
        per_stat: { ...scoring.per_stat, [E2E_IMPORT_UNMAPPED_KEY]: 1.5 },
      },
      roster,
      sport,
      format_version,
      captured_rules: { [E2E_IMPORT_UNMAPPED_KEY]: 1.5 },
    },
    teams: previewTeams(),
    draft: null,
    warnings: [E2E_IMPORT_WARNING],
    unmapped_scoring_keys: [E2E_IMPORT_UNMAPPED_KEY],
  }
}

/**
 * G100-C1 — the PER-CALLER saved-league reads.
 *
 * ⚠️ Kept OUT of `payloadFor` on purpose. That function is a pure map from (path, entitlement) to a
 * fixture, which is exactly right for the generic surfaces — their whole invariant is that the
 * payload does NOT depend on the caller. These two do. Threading a saved-league count through
 * `payloadFor` would blur the one distinction the harness exists to model, so the per-caller reads
 * get their own resolver and the shape of the code states which half of the tier each path is in.
 */
function personalPayloadFor(
  pathname: string,
  leagues: NonNullable<MockOptions["leagues"]>,
): unknown | undefined {
  // 🔒 NF-EPIC 1 — the league board is scored SERVER-SIDE now (the raw stat line it is scored from
  // became paid). The harness computes it with the SAME `buildBoard` the browser used to run, off
  // the entitled projections fixture, so the delta this screen exists to show stays REAL. Returning
  // the generic board here instead would make every riser/faller assertion pass against a board
  // that never moved — the vacuous-fixture shape this file already guards against elsewhere.
  if (pathname === "/fantasy/nfl/league-board") {
    const league = FIXTURES.myTeams().leagues[0]
    if (!league || leagues === "none") return undefined
    const built = leagueBoardBuild()
    return {
      season: 2026,
      league,
      board: {
        players: built.players,
        replacement: built.replacement,
        started: built.started,
        coverage: built.coverage,
      },
      roster: matchRosterToBoard(league.imported_roster ?? [], built.players),
    }
  }
  if (pathname !== "/fantasy/nfl/my-teams" && pathname !== "/fantasy/leagues") return undefined

  const base = FIXTURES.myTeams()
  const one = base.leagues[0]
  // NF-EPIC 1 — `/fantasy/nfl/my-teams` now carries each league's roster ALREADY joined to its own
  // server-scored board. Computed here for the same reason as the board above: a hardcoded empty
  // map would make "my roster renders" pass on nothing.
  // `any` is honest here rather than lazy: `fixture()` returns parsed JSON, so the league shape is
  // untyped at this boundary and inventing a local interface would be a second, driftable spelling
  // of `SavedLeague`.
  const rostersFor = (ls: any[]) =>
    Object.fromEntries(
      ls.map((l: any) => [
        l.league_id,
        matchRosterToBoard(
          l.imported_roster ?? [],
          buildBoard(FIXTURES.projectionsEntitled().players, l).players,
        ),
      ]),
    )

  if (leagues === "none") {
    return pathname === "/fantasy/leagues"
      ? []
      : { ...base, leagues: [], saved_total: 0, withheld_by_quota: 0, rosters: {} }
  }

  // ⭐ E9.64 — both leagues are the caller's own and both are served; there is no quota story here,
  // so `saved_total` matches and `withheld_by_quota` stays 0 (a lapsed-member notice on this mode
  // would be a second, unrelated behaviour leaking into every My Teams assertion).
  if (leagues === "linked") {
    const pair = linkedLeaguePair()
    return pathname === "/fantasy/leagues"
      ? pair
      : {
          ...base,
          leagues: pair,
          saved_total: pair.length,
          withheld_by_quota: 0,
          rosters: rostersFor(pair),
        }
  }

  if (leagues === "overQuota") {
    // A lapsed subscriber: three saved, one served. The MANAGEMENT list returns all three (they are
    // the user's own configs and must stay deletable); the PERSONALIZATION serve returns one. That
    // asymmetry is the behaviour, so the harness has to reproduce it rather than smoothing it over.
    const all = [
      one,
      { ...one, league_id: "e2e-league-2", name: "Dynasty B", created_at: "2026-08-02T12:00:00Z" },
      { ...one, league_id: "e2e-league-3", name: "Dynasty C", created_at: "2026-08-03T12:00:00Z" },
    ]
    return pathname === "/fantasy/leagues"
      ? all
      : { ...base, leagues: [one], saved_total: 3, withheld_by_quota: 2, rosters: rostersFor([one]) }
  }

  return pathname === "/fantasy/leagues"
    ? [one]
    : { ...base, rosters: rostersFor(base.leagues) }
}

/**
 * Install the API mock and the third-party blocks on a page.
 *
 * Returns a live record of what was asked for — assert `unmatched` is empty in any spec whose
 * conclusion depends on the page having got its data.
 */
/**
 * G100-D1 — the CDN read path.
 *
 * An ANONYMOUS caller no longer calls the API Lambda directly: `lib/api.ts::cdnFetch` fetches the
 * same-origin `/api/public/*` route handler, which Vercel serves from the edge (see that handler's
 * module comment). Those requests do NOT carry `API_PREFIX`, so without this map they would slip
 * past the interceptor entirely — and, because they are same-origin, they would land on the local
 * Next server and be answered by the REAL handler, which would then try to reach the real API. A
 * hermetic suite would silently stop being hermetic.
 *
 * Mapping back to the canonical API path (rather than adding a second fixture key space) is what
 * keeps every existing spec working unchanged: `fail: ["/picks/featured"]` and any `transform`
 * keyed on an API path keep meaning exactly what they meant before, regardless of which transport
 * the page happened to use.
 *
 * ⚠️ COVERAGE NOTE: intercepting here means Playwright answers BEFORE the route handler runs, so
 * the handler's own logic is not exercised by the E2E suite. That is deliberate — its contract
 * (never forwards Authorization, allowlist-only, never caches an empty body) is pinned by
 * `betting_ml/tests/test_g100_d1_cost_guardrails.py`, and its actual payoff is CDN behaviour that
 * no browser test can observe anyway.
 */
const CDN_PREFIX = "/api/public"

function cdnPathToApiPath(pathname: string): string | undefined {
  if (!pathname.startsWith(CDN_PREFIX + "/")) return undefined
  const rest = pathname.slice(CDN_PREFIX.length + 1)
  if (rest === "featured") return "/picks/featured"
  if (rest === "featured-player") return "/fantasy/nfl/featured-player"
  if (rest === "manifest") return "/fantasy/nfl/manifest"
  if (rest === "projections") return "/fantasy/nfl/projections"
  if (rest === "board") return "/fantasy/nfl/board"
  if (rest === "track-record/manifest") return "/fantasy/nfl/track-record/manifest"
  if (/^track-record\/\d{4}$/.test(rest)) return `/fantasy/nfl/${rest}`
  return undefined
}

export async function mockApi(page: Page, options: MockOptions = {}): Promise<ApiMock> {
  // ⭐ DEFAULT FLIPPED FROM "locked" TO "free" (freemium build). The default has to be what an
  // anonymous visitor actually gets, or a new spec that forgets to name a mode silently tests a
  // state no user can reach. Every pre-existing spec names its mode explicitly, so nothing else
  // moves. `entitled` is retained as a distinct name and resolves to the same payloads.
  const entitlement = options.entitlement ?? "free"
  const mock: ApiMock = { requested: [], unmatched: [] }

  /** Answer one intercepted call, given the canonical API path it resolves to. */
  const fulfil = async (route: Route, apiPath: string, search: string) => {
    mock.requested.push(apiPath + search)

    // Held BEFORE anything is answered, so the delay applies whichever branch below serves this
    // path — including the failure branch. See `MockOptions.delay`.
    if (options.delay?.paths.some((p) => apiPath.startsWith(p))) {
      await new Promise((r) => setTimeout(r, options.delay!.ms))
    }

    // ⭐ G100-D0 — SAVING a league, which is a WRITE and therefore invisible to `payloadFor`'s
    // (path, entitlement) map.
    //
    // This exists for one specific assertion. `league_config_completed` is the second clause of the
    // activation definition and the ONLY one with no production evidence yet — it fires on a CREATE
    // and not on an update, and until this handler existed nothing anywhere could drive that path.
    // A funnel step that has never been observed firing is a step the dashboard may well be
    // charting a permanent zero for.
    //
    // Echoing the posted config back (rather than serving a canned league) is what makes the
    // response a real round trip: the editor writes `result.league_id` into its own state and
    // re-reads the config from the response, so a canned body would silently discard what the user
    // typed and the spec would be asserting against a league nobody configured.
    // ⭐ G100-D0-R1 — the post-sign-in writes. Both are `POST`s with no fixture, so without this
    // they would 501 and land in `unmatched`; `/auth/accept-terms` additionally carries the signal
    // the whole signup funnel now keys on, and its THREE modes are not interchangeable (see
    // `MockOptions.termsAcceptance`).
    if (apiPath === "/auth/verify-email") {
      await route.fulfill({ status: 204, body: "" })
      return
    }
    if (apiPath === "/auth/accept-terms") {
      const mode = options.termsAcceptance ?? "existing"
      if (mode === "skew") {
        // The pre-R1 Lambda, verbatim: 204, no body, no `created` key anywhere.
        await route.fulfill({ status: 204, body: "" })
        return
      }
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ created: mode === "created" }),
      })
      return
    }

    // ⭐ E9.64 — the review queue. A POST whose answer depends on the league the user clicked, so it
    // cannot live in `payloadFor`'s (path, entitlement) map.
    if (apiPath === "/fantasy/import/sleeper/preview") {
      let leagueId = ""
      try {
        leagueId = JSON.parse(route.request().postData() ?? "{}").league_id ?? ""
      } catch {
        leagueId = ""
      }
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(importPreviewFor(leagueId)),
      })
      return
    }

    const written = writeResponseFor(apiPath, route.request().method(), route.request().postData())
    if (written !== undefined) {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(written),
      })
      return
    }

    if (options.fail?.includes(apiPath)) {
      await route.fulfill({
        status: 503,
        contentType: "application/json",
        body: JSON.stringify({ detail: "e2e: deliberate read failure" }),
      })
      return
    }

    // ⭐ THE HARNESS MODELS THE FORMAT PAYWALL, because a mock that answered 200 for every preset
    // would let a spec "prove" a locked format renders fine — a state no user can reach. One preset
    // is free (`entitlement.FREE_BOARD_CONFIG`/`FREE_BOARD_SIZE`); anything else is a 403.
    // Mirrors `routers/fantasy.py::nfl_board`.
    //
    // ⚠️ "free" ONLY, NOT "not entitled". `"locked"` models the RETIRED E9.56 server, which served
    // every preset with its values removed and had no format tier at all — applying today's paywall
    // there would refuse boards that server answered, and `locked-surfaces.spec.ts` would fail
    // describing a world neither server ever produced. A mock must model ONE server per mode.
    if (apiPath === "/fantasy/nfl/board" && entitlement === "free") {
      const q = new URLSearchParams(search)
      const isFreeBoard = q.get("config") === FREE_BOARD.config && q.get("size") === String(FREE_BOARD.size)
      if (!isFreeBoard) {
        await route.fulfill({
          status: 403,
          contentType: "application/json",
          body: JSON.stringify({ detail: "This league format is part of a Credence membership." }),
        })
        return
      }
    }

    let body =
      personalPayloadFor(apiPath, options.leagues ?? "none") ??
      billingPayloadFor(apiPath, options.subscription ?? "none") ??
      payloadFor(apiPath, entitlement)
    if (body === undefined) {
      mock.unmatched.push(apiPath + search)
      await route.fulfill({
        status: 501,
        contentType: "application/json",
        body: JSON.stringify({ detail: `e2e: no fixture for ${apiPath}` }),
      })
      return
    }
    if (options.transform) body = options.transform(apiPath, body)

    await route.fulfill({
      status: 200,
      contentType: "application/json",
      headers: { "access-control-allow-origin": "*" },
      body: JSON.stringify(body),
    })
  }

  await page.route(`**${API_PREFIX}/**`, async (route: Route, request: Request) => {
    const url = new URL(request.url())
    // Strip the harness prefix so the fixture map is keyed on the API's OWN paths — the same
    // strings that appear in `app/backend/routers/fantasy.py`.
    const apiPath = url.pathname.slice(url.pathname.indexOf(API_PREFIX) + API_PREFIX.length)
    await fulfil(route, apiPath, url.search)
  })

  await page.route(`**${CDN_PREFIX}/**`, async (route: Route, request: Request) => {
    const url = new URL(request.url())
    const apiPath = cdnPathToApiPath(url.pathname)
    if (apiPath === undefined) {
      // An unmapped CDN path is a harness gap, not a pass — surface it the same way an unmatched
      // API path is surfaced rather than letting it reach the real handler.
      mock.unmatched.push(url.pathname + url.search)
      await route.fulfill({
        status: 501,
        contentType: "application/json",
        body: JSON.stringify({ detail: `e2e: unmapped CDN path ${url.pathname}` }),
      })
      return
    }
    await fulfil(route, apiPath, url.search)
  })

  await blockThirdParty(page)
  return mock
}

/**
 * Cut every third-party beacon. Sentry's DSN is hardcoded in `instrumentation-client.ts` and
 * PostHog is proxied through the same-origin `/ingest` rewrite, so without this the suite makes
 * real outbound calls from CI — slow, flaky, and it pollutes production analytics with robot
 * traffic.
 */
export async function blockThirdParty(page: Page) {
  for (const pattern of ["**/ingest/**", "**/*.sentry.io/**", "**/*.i.posthog.com/**"]) {
    await page.route(pattern, (route) => route.abort())
  }
}

/** Collect uncaught page errors so a spec can assert the surface rendered without throwing. */
export function collectPageErrors(page: Page): string[] {
  const errors: string[] = []
  page.on("pageerror", (e) => errors.push(String(e)))
  return errors
}

/**
 * G100-C1 — intercept the analytics wire and record what was CAPTURED.
 *
 * ⭐ WHY THE WIRE AND NOT A STUB. The activation event is a CONTRACT with G100-D0's funnel
 * dashboard: the event NAME and its dimensions are what the dashboard reads. A test that stubbed
 * `posthog.capture` and asserted it was called would pass even if PostHog were never initialised —
 * which is exactly the state this suite was in until G100-C1 armed the token, and is the "asserting
 * a NAME rather than the thing the name refers to" shape the red-proof harness exists to catch.
 * Reading the request body proves the event actually left the page under the name the dashboard
 * expects.
 *
 * ⚠️ Install INSTEAD OF `mockApi`'s `blockThirdParty` for the ingest route — this route is
 * registered after it, and Playwright matches the most recently added handler first.
 *
 * PostHog batches, so a captured event may arrive in a `batch` array or as a single `{event, ...}`;
 * both shapes are flattened here. Bodies can also be compressed or form-encoded depending on
 * transport, so a body this cannot parse is IGNORED rather than throwing — an assertion that an
 * event is ABSENT must therefore never rest on this alone (see `expectCaptured`).
 */
export type CapturedEvent = { event: string; properties: Record<string, unknown> }

export async function captureAnalytics(page: Page): Promise<CapturedEvent[]> {
  const events: CapturedEvent[] = []

  // ⭐⭐ WITHOUT THIS, POSTHOG CAPTURES NOTHING IN PLAYWRIGHT AND EVERY ANALYTICS ASSERTION IS
  // VACUOUS — INCLUDING, AND ESPECIALLY, ONE ASSERTING AN EVENT DID *NOT* FIRE.
  //
  // posthog-js runs a bot filter on every `capture()` (`_is_bot` → `xo`, measured against 1.386.6)
  // and TWO of its clauses catch Playwright. BOTH have to be defeated; clearing either one alone
  // changes nothing, which is what makes this so easy to misdiagnose:
  //
  //   1. `!!navigator.webdriver` — Playwright sets it on every page.
  //   2. `navigator.userAgentData.brands` containing "HeadlessChrome". ⚠️ NOT fixed by overriding
  //      the user-agent STRING via `test.use({ userAgent })`: `userAgentData` is a separate
  //      structured field and keeps reporting the real brand. A UA override therefore LOOKS like
  //      the fix and does nothing — measured.
  //
  // The failure is completely silent: the SDK initialises, POSTs `/flags/`, loads its remote
  // config, and then drops every event including `$pageview`. An empty ingest log is
  // indistinguishable from "the app never called capture()". Two other plausible causes were
  // measured and RULED OUT along the way, so nobody re-chases them: the shipped CSP (`connect-src
  // 'self'` already covers the same-origin `/ingest` path — allowing `blob:` workers changed
  // nothing) and the remote-config stub below.
  //
  // Confined to the harness — no application code knows about it — and `addInitScript` runs before
  // any page script, so the SDK never observes the real values.
  await page.addInitScript(() => {
    Object.defineProperty(navigator, "webdriver", { get: () => false, configurable: true })
    Object.defineProperty(navigator, "userAgentData", {
      get: () => ({
        brands: [
          { brand: "Chromium", version: "140" },
          { brand: "Google Chrome", version: "140" },
        ],
        mobile: false,
        platform: "macOS",
      }),
      configurable: true,
    })
  })

  await page.route("**/ingest/**", async (route: Route, request: Request) => {
    const path = new URL(request.url()).pathname

    // posthog-js will not finish initialising until its REMOTE CONFIG resolves, and it reads that
    // from `window._POSTHOG_REMOTE_CONFIG[token].config` set by this script. An empty body leaves
    // the SDK waiting; every feature is switched OFF here so the harness pulls in no further
    // external dependencies (recordings, surveys, experiments) that it would then have to model.
    if (path.endsWith("/config.js")) {
      const token = POSTHOG_E2E_TOKEN
      const config = {
        supportedCompression: [],
        autocapture_opt_out: true,
        hasFeatureFlags: false,
        sessionRecording: null,
        surveys: false,
        captureDeadClicks: false,
        defaultIdentifiedOnly: false,
        errorTracking: { autocaptureExceptions: false },
      }
      await route.fulfill({
        status: 200,
        contentType: "application/javascript",
        body: `window._POSTHOG_REMOTE_CONFIG = ${JSON.stringify({ [token]: { config, siteApps: [] } })};`,
      })
      return
    }

    // ⚠️ ANY OTHER SCRIPT MUST BE ANSWERED AS JAVASCRIPT, NOT JSON. `/ingest/**` also serves
    // posthog-js's own assets, and a JSON body handed to a `<script>` throws
    // `SyntaxError: Unexpected token ':'` — which surfaced as three uncaught page errors and failed
    // four unrelated assertions running `expectNoPageErrors`, i.e. a harness bug wearing an
    // application defect's clothes.
    if (path.endsWith(".js")) {
      await route.fulfill({ status: 200, contentType: "application/javascript", body: "" })
      return
    }

    if (request.method() === "POST" && /\/(e|i\/v0\/e)\/?$/.test(path)) {
      try {
        const raw = request.postData()
        if (raw) {
          const text = raw.startsWith("data=") ? decodeURIComponent(raw.slice(5)) : raw
          const decoded = /^[A-Za-z0-9+/=_-]+$/.test(text.trim())
            ? Buffer.from(text.trim(), "base64").toString("utf8")
            : text
          const parsed = JSON.parse(decoded)
          for (const item of Array.isArray(parsed) ? parsed : (parsed.batch ?? [parsed])) {
            if (item && typeof item.event === "string") {
              events.push({ event: item.event, properties: item.properties ?? {} })
            }
          }
        }
      } catch {
        /* unparseable transport — never throw from a route handler; see the note above */
      }
    }

    // Answered, never aborted: an aborted request makes posthog-js RETRY, which would multiply a
    // single capture across the retry schedule and break any "fired exactly once" assertion.
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ status: 1 }),
    })
  })

  return events
}
