#!/usr/bin/env python3
"""
scripts/ddl/generate_w5b_external_tables.py   (E11.1-W5b archetype mini-wave)

Emit Snowflake EXTERNAL TABLE DDL for the W5b archetype mart by reading the ACTUAL
schema of its S3 parquet (written by run_w1_lakehouse.py --archetype) via DuckDB.

W5b = the single dual-branch mart mart_batter_archetype_vs_pitcher_cluster. Its upstream
mart_player_archetype_posteriors is a BUILDER-OUTPUT parquet read directly by the mart's
duckdb branch (no external table) — produced by
betting_ml/scripts/eb_priors/compute_archetype_posteriors.py (--seed / --s3). Same machinery
+ rationale as generate_w5_external_tables.py.

PREREQUISITES:
  1. The posteriors parquet exists in S3 (compute_archetype_posteriors.py --seed or --s3).
  2. run_w1_lakehouse.py --archetype has been run at least once (the mart parquet exists).
  3. AWS creds reachable via the DuckDB credential chain; the lakehouse_ext schema + stage +
     parquet_snappy file format already exist (W1d).

USAGE:
  uv run python scripts/ddl/generate_w5b_external_tables.py            # → stdout + .sql file
  uv run python scripts/ddl/generate_w5b_external_tables.py --print    # stdout only

OUTPUT: scripts/ddl/w5b_external_tables.generated.sql — REVIEW, then run in Snowflake BEFORE
flipping the mart to a view (before the PR merges). Refresh: refresh_w1_external_tables.py
(ARCHETYPE_TABLES). AUTO_REFRESH=FALSE.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUT_PATH = REPO_ROOT / "scripts" / "ddl" / "w5b_external_tables.generated.sql"

BUCKET = "s3://baseball-betting-ml-artifacts"
LAKEHOUSE = f"{BUCKET}/baseball/lakehouse"
SCHEMA = "baseball_data.lakehouse_ext"
STAGE = f"{SCHEMA}.s3_lakehouse"
FILE_FORMAT = f"{SCHEMA}.parquet_snappy"

W5B_MODELS = ["mart_batter_archetype_vs_pitcher_cluster"]


def duckdb_to_snowflake_type(duck_type: str) -> str:
    t = duck_type.upper().strip()
    if t.startswith("DECIMAL") or t.startswith("NUMERIC"):
        return "FLOAT"
    if t in ("DOUBLE", "FLOAT", "REAL"):
        return "FLOAT"
    if t in ("BIGINT", "INTEGER", "HUGEINT", "UBIGINT", "UINTEGER",
             "SMALLINT", "USMALLINT", "TINYINT", "UTINYINT", "INT", "INT64"):
        return "NUMBER(38,0)"
    if t in ("BOOLEAN", "BOOL"):
        return "BOOLEAN"
    if t == "DATE":
        return "DATE"
    if t.startswith("TIMESTAMP"):
        return "TIMESTAMP_NTZ"
    if t in ("VARCHAR", "TEXT", "STRING", "CHAR", "BLOB", "UUID"):
        return "VARCHAR"
    return "VARCHAR"


def get_duckdb_conn():
    import duckdb
    conn = duckdb.connect()
    conn.execute("INSTALL httpfs; LOAD httpfs")
    conn.execute("CREATE OR REPLACE SECRET baseball_s3 "
                 "(TYPE S3, PROVIDER credential_chain, REGION 'us-east-2')")
    for _p in ("SET http_timeout = 600000", "SET http_retries = 8"):
        try:
            conn.execute(_p)
        except Exception:
            pass
    return conn


def describe_parquet(conn, model: str):
    loc = f"{LAKEHOUSE}/{model}/data.parquet"
    rows = conn.execute(f"DESCRIBE SELECT * FROM read_parquet('{loc}')").fetchall()
    return [(r[0], r[1]) for r in rows]


def emit_external_table(model: str, cols) -> str:
    col_lines = [
        f"    {name.upper():<28} {duckdb_to_snowflake_type(dt):<14} AS (VALUE:{name.lower()}::{duckdb_to_snowflake_type(dt)})"
        for name, dt in cols
    ]
    cols_block = ",\n".join(col_lines)
    return (
        f"-- ── {model}  ({len(cols)} columns) ──\n"
        f"CREATE OR REPLACE EXTERNAL TABLE {SCHEMA}.{model} (\n"
        f"{cols_block}\n)\n"
        f"WITH LOCATION = @{STAGE}/{model}/\n"
        f"FILE_FORMAT = {FILE_FORMAT}\n"
        f"AUTO_REFRESH = FALSE\n"
        f"COMMENT = 'E11.1-W5b: {model} from S3 lakehouse parquet (tolerance-parity mart)';\n"
    )


def main() -> None:
    print_only = "--print" in sys.argv
    conn = get_duckdb_conn()
    header = (
        "-- =============================================================================\n"
        "-- w5b_external_tables.generated.sql — GENERATED by generate_w5b_external_tables.py\n"
        "-- E11.1-W5b: external table over S3 parquet for the archetype mart. Reuses the\n"
        "-- lakehouse_ext schema + s3_lakehouse stage + parquet_snappy format (W1d). Run AFTER\n"
        "-- run_w1_lakehouse.py --archetype, and BEFORE merging the mart (which becomes a view).\n"
        "-- Refresh: refresh_w1_external_tables.py (ARCHETYPE_TABLES).\n"
        "-- =============================================================================\n"
    )
    blocks = [header]
    for model in W5B_MODELS:
        try:
            cols = describe_parquet(conn, model)
            blocks.append(emit_external_table(model, cols))
            print(f"  {model}: {len(cols)} columns", file=sys.stderr)
        except Exception as e:
            print(f"  SKIP {model}: {e}  (has run_w1_lakehouse.py --archetype written it yet?)",
                  file=sys.stderr)
    conn.close()
    verify = "\n-- Verification:\n" + "".join(f"-- SELECT count(*) FROM {SCHEMA}.{m};\n" for m in W5B_MODELS)
    ddl = "\n".join(blocks) + verify
    if print_only:
        print(ddl)
    else:
        OUT_PATH.write_text(ddl)
        print(f"\nWrote {OUT_PATH}", file=sys.stderr)
        print("Review it, then run it in Snowflake before flipping the mart to a view.", file=sys.stderr)


if __name__ == "__main__":
    main()
