#!/usr/bin/env python3
"""
scripts/ddl/generate_w7_external_tables.py   (E11.1-W7a — the FINISH wave)

Emit Snowflake EXTERNAL TABLE DDL for the builder-output cluster parquet so the dbt
FEATURE models can read the cluster assignments from S3 (lakehouse_ext) instead of the
native baseball_data.statsapi.{batter,pitcher}_clusters tables — which lets the operator
DROP the native Snowflake cluster_batters / cluster_pitchers builds (the W7a credit drop).

The cluster parquet is written by the EXISTING --s3 build of:
  betting_ml/scripts/batter_clustering/cluster_batters.py   --s3   → batter_clusters/data.parquet
  betting_ml/scripts/pitcher_clustering/cluster_pitchers.py --s3   → pitcher_clusters/data.parquet
(both seeded once from Snowflake via --seed; see those scripts' E11.1-W5b header). W5b
already migrated the archetype MART chain that reads these via read_parquet(); W7a closes
the loop by giving the cluster tables a Snowflake-visible external table so the feature
layer (still built on Snowflake until W7b) no longer needs the native cluster tables.

PREREQUISITES:
  1. The cluster parquet exists in S3 (cluster_batters.py / cluster_pitchers.py --seed or --s3).
  2. AWS creds reachable via the DuckDB credential chain; the lakehouse_ext schema + stage +
     parquet_snappy file format already exist (W1d).

USAGE:
  uv run python scripts/ddl/generate_w7_external_tables.py            # → stdout + .sql file
  uv run python scripts/ddl/generate_w7_external_tables.py --print    # stdout only

OUTPUT: scripts/ddl/w7_external_tables.generated.sql — REVIEW, then run in Snowflake BEFORE
repointing the feature models' source('statsapi', ...) → source('lakehouse_clusters', ...)
(before the PR merges). Refresh: refresh_w1_external_tables.py (W7_TABLES). AUTO_REFRESH=FALSE.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUT_PATH = REPO_ROOT / "scripts" / "ddl" / "w7_external_tables.generated.sql"

BUCKET = "s3://baseball-betting-ml-artifacts"
LAKEHOUSE = f"{BUCKET}/baseball/lakehouse"
SCHEMA = "baseball_data.lakehouse_ext"
STAGE = f"{SCHEMA}.s3_lakehouse"
FILE_FORMAT = f"{SCHEMA}.parquet_snappy"

# Builder-output cluster tables (single-file data.parquet, unique on (<id>, season)).
W7_MODELS = ["batter_clusters", "pitcher_clusters"]


def duckdb_to_snowflake_type(duck_type: str) -> str:
    t = duck_type.upper().strip()
    if t.startswith("DECIMAL") or t.startswith("NUMERIC"):
        return "FLOAT"
    if t in ("DOUBLE", "FLOAT", "REAL"):
        return "FLOAT"
    if t in ("BIGINT", "INTEGER", "HUGEINT", "UBIGINT", "UINTEGER",
             "SMALLINT", "USMALLINT", "TINYINT", "UTINYINT", "INT", "INT64"):
        return "NUMBER(38,0)"
    if t in ("BOOLEAN", "BOOL"):
        return "BOOLEAN"
    if t == "DATE":
        return "DATE"
    if t.startswith("TIMESTAMP"):
        return "TIMESTAMP_NTZ"
    if t in ("VARCHAR", "TEXT", "STRING", "CHAR", "BLOB", "UUID"):
        return "VARCHAR"
    return "VARCHAR"


def get_duckdb_conn():
    import duckdb
    conn = duckdb.connect()
    conn.execute("INSTALL httpfs; LOAD httpfs")
    conn.execute("CREATE OR REPLACE SECRET baseball_s3 "
                 "(TYPE S3, PROVIDER credential_chain, REGION 'us-east-2')")
    for _p in ("SET http_timeout = 600000", "SET http_retries = 8"):
        try:
            conn.execute(_p)
        except Exception:
            pass
    return conn


def describe_parquet(conn, model: str):
    loc = f"{LAKEHOUSE}/{model}/data.parquet"
    rows = conn.execute(f"DESCRIBE SELECT * FROM read_parquet('{loc}')").fetchall()
    return [(r[0], r[1]) for r in rows]


def emit_external_table(model: str, cols) -> str:
    col_lines = [
        f"    {name.upper():<28} {duckdb_to_snowflake_type(dt):<14} AS (VALUE:{name.lower()}::{duckdb_to_snowflake_type(dt)})"
        for name, dt in cols
    ]
    cols_block = ",\n".join(col_lines)
    return (
        f"-- ── {model}  ({len(cols)} columns) ──\n"
        f"CREATE OR REPLACE EXTERNAL TABLE {SCHEMA}.{model} (\n"
        f"{cols_block}\n)\n"
        f"WITH LOCATION = @{STAGE}/{model}/\n"
        f"FILE_FORMAT = {FILE_FORMAT}\n"
        f"AUTO_REFRESH = FALSE\n"
        f"COMMENT = 'E11.1-W7a: {model} from S3 lakehouse parquet — frees the native cluster build to be dropped';\n"
        f"-- Preserve the request/feature reader grant on (re)create (INC-18 band-aid class):\n"
        f"GRANT SELECT ON EXTERNAL TABLE {SCHEMA}.{model} TO ROLE CREDENCE_API_RO;\n"
    )


def main() -> None:
    print_only = "--print" in sys.argv
    conn = get_duckdb_conn()
    header = (
        "-- =============================================================================\n"
        "-- w7_external_tables.generated.sql — GENERATED by generate_w7_external_tables.py\n"
        "-- E11.1-W7a: external tables over the S3 cluster parquet so the feature layer can\n"
        "-- read clusters from lakehouse_ext (source 'lakehouse_clusters') instead of the\n"
        "-- native statsapi.{batter,pitcher}_clusters — frees the native cluster builds to drop.\n"
        "-- Run AFTER cluster_batters/cluster_pitchers --seed (or --s3), and BEFORE merging the\n"
        "-- feature-model source repoint. Refresh: refresh_w1_external_tables.py (W7_TABLES).\n"
        "-- =============================================================================\n"
    )
    blocks = [header]
    for model in W7_MODELS:
        try:
            cols = describe_parquet(conn, model)
            blocks.append(emit_external_table(model, cols))
            print(f"  {model}: {len(cols)} columns", file=sys.stderr)
        except Exception as e:
            print(f"  SKIP {model}: {e}  (have you run cluster_*.py --seed / --s3 yet?)",
                  file=sys.stderr)
    conn.close()
    verify = "\n-- Verification:\n" + "".join(f"-- SELECT count(*) FROM {SCHEMA}.{m};\n" for m in W7_MODELS)
    ddl = "\n".join(blocks) + verify
    if print_only:
        print(ddl)
    else:
        OUT_PATH.write_text(ddl)
        print(f"\nWrote {OUT_PATH}", file=sys.stderr)
        print("Review it, then run it in Snowflake before repointing the feature models.", file=sys.stderr)


if __name__ == "__main__":
    main()
