#!/usr/bin/env python3
"""
scripts/ddl/generate_w3pre_external_tables.py   (E11.1-W3pre lakehouse decommission)

Emit Snowflake EXTERNAL TABLE DDL for the W3pre STAGING models by reading the ACTUAL
schema of each flattened S3 parquet (written by run_w1_lakehouse.py W3PRE_STG_MODELS) via
DuckDB. Identical mechanism to generate_w2_external_tables.py — UPPERCASE unquoted columns
via `<COL_UPPER> <TYPE> AS (VALUE:<col_lower>::<TYPE>)` so downstream unquoted refs resolve
(no INFER_SCHEMA quoted-lowercase case-trap), types from the real parquet.

PREREQUISITES:
  1. The raw tier is in S3 (scripts/export_odds_raw_to_s3.py + migrated writers).
  2. run_w1_lakehouse.py --w3pre-only has written lakehouse/stg_*/data.parquet.
  3. The lakehouse_ext schema + stage + parquet_snappy file format exist (W1d).

USAGE:
  uv run python scripts/ddl/generate_w3pre_external_tables.py          # → stdout + .sql file
  uv run python scripts/ddl/generate_w3pre_external_tables.py --print  # stdout only

OUTPUT: scripts/ddl/w3pre_external_tables.generated.sql
  Operator REVIEWS, runs it in Snowflake BEFORE flipping the W3pre stg models to views.
  AUTO_REFRESH=FALSE — refreshed each run by scripts/refresh_w1_external_tables.py (W3PRE_TABLES).
  Rollback: the original Snowflake-built staging tables are not dropped; re-enable their
  dbt build (revert the model) to roll back.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUT_PATH = REPO_ROOT / "scripts" / "ddl" / "w3pre_external_tables.generated.sql"

BUCKET = "s3://baseball-betting-ml-artifacts"
LAKEHOUSE = f"{BUCKET}/baseball/lakehouse"
SCHEMA = "baseball_data.lakehouse_ext"
STAGE = f"{SCHEMA}.s3_lakehouse"
FILE_FORMAT = f"{SCHEMA}.parquet_snappy"

# Mirror run_w1_lakehouse.W3PRE_STG_MODELS.
W3PRE_STG_MODELS = [
    "stg_oddsapi_odds",
    "stg_oddsapi_events",
    "stg_derivative_odds",
    "stg_statsapi_games",
]


def duckdb_to_snowflake_type(duck_type: str) -> str:
    t = duck_type.upper().strip()
    if t.startswith("DECIMAL") or t.startswith("NUMERIC"):
        return "FLOAT"
    if t in ("DOUBLE", "FLOAT", "REAL"):
        return "FLOAT"
    if t in ("BIGINT", "INTEGER", "HUGEINT", "UBIGINT", "UINTEGER",
             "SMALLINT", "USMALLINT", "TINYINT", "UTINYINT", "INT", "INT64"):
        return "NUMBER(38,0)"
    if t in ("BOOLEAN", "BOOL"):
        return "BOOLEAN"
    if t == "DATE":
        return "DATE"
    if t.startswith("TIMESTAMP"):  # TIMESTAMP / TIMESTAMP WITH TIME ZONE → NTZ instant
        return "TIMESTAMP_NTZ"
    if t in ("VARCHAR", "TEXT", "STRING", "CHAR", "BLOB", "UUID"):
        return "VARCHAR"
    return "VARCHAR"


def get_duckdb_conn():
    import duckdb
    conn = duckdb.connect()
    conn.execute("INSTALL httpfs; LOAD httpfs")
    conn.execute("""
        CREATE OR REPLACE SECRET baseball_s3 (
          TYPE S3, PROVIDER credential_chain, REGION 'us-east-2'
        )
    """)
    return conn


def describe_parquet(conn, model: str) -> list[tuple[str, str]]:
    loc = f"{LAKEHOUSE}/{model}/data.parquet"
    rows = conn.execute(f"DESCRIBE SELECT * FROM read_parquet('{loc}')").fetchall()
    return [(r[0], r[1]) for r in rows]


def emit_external_table(model: str, cols: list[tuple[str, str]]) -> str:
    col_lines = []
    for name, duck_type in cols:
        sf_type = duckdb_to_snowflake_type(duck_type)
        col_lines.append(
            f"    {name.upper():<26} {sf_type:<14} AS (VALUE:{name.lower()}::{sf_type})"
        )
    cols_block = ",\n".join(col_lines)
    return (
        f"-- ── {model}  ({len(cols)} columns) ──\n"
        f"CREATE OR REPLACE EXTERNAL TABLE {SCHEMA}.{model} (\n"
        f"{cols_block}\n"
        f")\n"
        f"WITH LOCATION = @{STAGE}/{model}/\n"
        f"FILE_FORMAT = {FILE_FORMAT}\n"
        f"AUTO_REFRESH = FALSE\n"
        f"COMMENT = 'E11.1-W3pre: {model} from S3 lakehouse parquet';\n"
    )


def main() -> None:
    print_only = "--print" in sys.argv
    conn = get_duckdb_conn()

    header = (
        "-- =============================================================================\n"
        "-- w3pre_external_tables.generated.sql — GENERATED by generate_w3pre_external_tables.py\n"
        "-- E11.1-W3pre: Snowflake external tables over the flattened S3 parquet for the\n"
        "-- odds/staging tier. Reuses the lakehouse_ext schema + s3_lakehouse stage +\n"
        "-- parquet_snappy file format (W1d). Run AFTER run_w1_lakehouse.py --w3pre-only has\n"
        "-- written lakehouse/stg_*/data.parquet, and BEFORE merging the W3pre stg models\n"
        "-- (which become views over these). Refresh: scripts/refresh_w1_external_tables.py.\n"
        "-- DO NOT hand-edit — regenerate from the parquet if a model's schema changes.\n"
        "-- =============================================================================\n"
    )
    blocks = [header]
    for model in W3PRE_STG_MODELS:
        try:
            cols = describe_parquet(conn, model)
            blocks.append(emit_external_table(model, cols))
            print(f"  {model}: {len(cols)} columns", file=sys.stderr)
        except Exception as e:
            print(f"  SKIP {model}: {e}  (has run_w1_lakehouse.py --w3pre-only written it?)",
                  file=sys.stderr)
    conn.close()

    verify = "\n-- Verification (run after CREATE):\n" + "".join(
        f"-- SELECT count(*) FROM {SCHEMA}.{m};\n" for m in W3PRE_STG_MODELS
    )
    ddl = "\n".join(blocks) + verify

    if print_only:
        print(ddl)
    else:
        OUT_PATH.write_text(ddl)
        print(f"\nWrote {OUT_PATH}", file=sys.stderr)
        print("Review it, then run it in Snowflake before flipping the W3pre stg models to views.",
              file=sys.stderr)


if __name__ == "__main__":
    main()
