-- =============================================================================
-- w11c_external_tables.generated.sql — GENERATED by generate_w11c_external_tables.py
-- E11.1-W11 Tier-C: external tables over the S3 parquet for the weather stg + feature
-- layer. Run AFTER run_w1_lakehouse.py --w11c (parquet must exist) and BEFORE the PR
-- merges (the models' Snowflake else branch reads these). Refresh:
-- refresh_w1_external_tables.py --w11c (W11C_TABLES).
-- =============================================================================

-- ── stg_weather_raw  (13 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_weather_raw (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    VENUE_ID                         NUMBER(38,0)   AS (VALUE:venue_id::NUMBER(38,0)),
    GAME_DATETIME_UTC                TIMESTAMP_NTZ  AS (VALUE:game_datetime_utc::TIMESTAMP_NTZ),
    FETCH_OFFSET_HOURS               FLOAT          AS (VALUE:fetch_offset_hours::FLOAT),
    TEMP_F                           FLOAT          AS (VALUE:temp_f::FLOAT),
    WIND_SPEED_MPH                   FLOAT          AS (VALUE:wind_speed_mph::FLOAT),
    WIND_DIRECTION_DEG               NUMBER(38,0)   AS (VALUE:wind_direction_deg::NUMBER(38,0)),
    HUMIDITY_PCT                     NUMBER(38,0)   AS (VALUE:humidity_pct::NUMBER(38,0)),
    CONDITION_TEXT                   VARCHAR        AS (VALUE:condition_text::VARCHAR),
    API_SOURCE                       VARCHAR        AS (VALUE:api_source::VARCHAR),
    WEATHER_OBSERVATION_TYPE         VARCHAR        AS (VALUE:weather_observation_type::VARCHAR),
    HOURS_TO_FIRST_PITCH             NUMBER(38,0)   AS (VALUE:hours_to_first_pitch::NUMBER(38,0)),
    LOADED_AT                        TIMESTAMP_NTZ  AS (VALUE:loaded_at::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_weather_raw/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W11 Tier-C: stg_weather_raw from S3 lakehouse parquet (weather feed)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.stg_weather_raw TO ROLE CREDENCE_API_RO;

-- ── stg_weather_raw_snapshots  (11 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_weather_raw_snapshots (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    VENUE_ID                         NUMBER(38,0)   AS (VALUE:venue_id::NUMBER(38,0)),
    TEMP_F                           FLOAT          AS (VALUE:temp_f::FLOAT),
    WIND_SPEED_MPH                   FLOAT          AS (VALUE:wind_speed_mph::FLOAT),
    WIND_DIRECTION_DEG               NUMBER(38,0)   AS (VALUE:wind_direction_deg::NUMBER(38,0)),
    HUMIDITY_PCT                     NUMBER(38,0)   AS (VALUE:humidity_pct::NUMBER(38,0)),
    CONDITION_TEXT                   VARCHAR        AS (VALUE:condition_text::VARCHAR),
    WIND_COMPONENT_MPH               FLOAT          AS (VALUE:wind_component_mph::FLOAT),
    IS_DOME                          BOOLEAN        AS (VALUE:is_dome::BOOLEAN),
    RECORD_HASH                      VARCHAR        AS (VALUE:record_hash::VARCHAR),
    LOADED_AT                        TIMESTAMP_NTZ  AS (VALUE:loaded_at::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_weather_raw_snapshots/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W11 Tier-C: stg_weather_raw_snapshots from S3 lakehouse parquet (weather feed)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.stg_weather_raw_snapshots TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_weather_status  (14 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_weather_status (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    VENUE_ID                         NUMBER(38,0)   AS (VALUE:venue_id::NUMBER(38,0)),
    TEMP_F                           FLOAT          AS (VALUE:temp_f::FLOAT),
    WIND_SPEED_MPH                   FLOAT          AS (VALUE:wind_speed_mph::FLOAT),
    WIND_DIRECTION_DEG               NUMBER(38,0)   AS (VALUE:wind_direction_deg::NUMBER(38,0)),
    HUMIDITY_PCT                     NUMBER(38,0)   AS (VALUE:humidity_pct::NUMBER(38,0)),
    CONDITION_TEXT                   VARCHAR        AS (VALUE:condition_text::VARCHAR),
    WIND_COMPONENT_MPH               FLOAT          AS (VALUE:wind_component_mph::FLOAT),
    IS_DOME                          BOOLEAN        AS (VALUE:is_dome::BOOLEAN),
    VALID_FROM                       TIMESTAMP_NTZ  AS (VALUE:valid_from::TIMESTAMP_NTZ),
    VALID_TO                         TIMESTAMP_NTZ  AS (VALUE:valid_to::TIMESTAMP_NTZ),
    IS_CURRENT                       BOOLEAN        AS (VALUE:is_current::BOOLEAN),
    RECORD_HASH                      VARCHAR        AS (VALUE:record_hash::VARCHAR),
    COMPUTED_AT                      TIMESTAMP_NTZ  AS (VALUE:computed_at::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_weather_status/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W11 Tier-C: feature_pregame_weather_status from S3 lakehouse parquet (weather feed)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_weather_status TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_weather_features  (9 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_weather_features (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    VENUE_ID                         NUMBER(38,0)   AS (VALUE:venue_id::NUMBER(38,0)),
    WEATHER_OBSERVATION_TYPE         VARCHAR        AS (VALUE:weather_observation_type::VARCHAR),
    TEMP_F                           FLOAT          AS (VALUE:temp_f::FLOAT),
    WIND_SPEED_MPH                   FLOAT          AS (VALUE:wind_speed_mph::FLOAT),
    WIND_DIRECTION_DEG               NUMBER(38,0)   AS (VALUE:wind_direction_deg::NUMBER(38,0)),
    HUMIDITY_PCT                     NUMBER(38,0)   AS (VALUE:humidity_pct::NUMBER(38,0)),
    WIND_COMPONENT_MPH               FLOAT          AS (VALUE:wind_component_mph::FLOAT),
    IS_DOME                          BOOLEAN        AS (VALUE:is_dome::BOOLEAN)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_weather_features/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W11 Tier-C: feature_pregame_weather_features from S3 lakehouse parquet (weather feed)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_weather_features TO ROLE CREDENCE_API_RO;

-- Verification:
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_weather_raw;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_weather_raw_snapshots;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_weather_status;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_weather_features;
