-- =============================================================================
-- w11d_external_tables.generated.sql — GENERATED by generate_w11d_external_tables.py
-- E11.1-W11 Tier-D: external tables over the S3 parquet for the public-betting stg + feature
-- layer. Run AFTER run_w1_lakehouse.py --w11d (parquet must exist) and BEFORE the PR
-- merges (the models' Snowflake else branch reads these). Refresh:
-- refresh_w1_external_tables.py --w11d (W11D_TABLES).
-- =============================================================================

-- ── stg_actionnetwork_public_betting  (15 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_actionnetwork_public_betting (
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    AN_GAME_ID                       VARCHAR        AS (VALUE:an_game_id::VARCHAR),
    HOME_TEAM_ID                     VARCHAR        AS (VALUE:home_team_id::VARCHAR),
    AWAY_TEAM_ID                     VARCHAR        AS (VALUE:away_team_id::VARCHAR),
    HOME_ML_MONEY_PCT                FLOAT          AS (VALUE:home_ml_money_pct::FLOAT),
    AWAY_ML_MONEY_PCT                FLOAT          AS (VALUE:away_ml_money_pct::FLOAT),
    HOME_ML_TICKET_PCT               FLOAT          AS (VALUE:home_ml_ticket_pct::FLOAT),
    AWAY_ML_TICKET_PCT               FLOAT          AS (VALUE:away_ml_ticket_pct::FLOAT),
    OVER_MONEY_PCT                   FLOAT          AS (VALUE:over_money_pct::FLOAT),
    UNDER_MONEY_PCT                  FLOAT          AS (VALUE:under_money_pct::FLOAT),
    OVER_TICKET_PCT                  FLOAT          AS (VALUE:over_ticket_pct::FLOAT),
    UNDER_TICKET_PCT                 FLOAT          AS (VALUE:under_ticket_pct::FLOAT),
    ML_SHARP_SIGNAL                  FLOAT          AS (VALUE:ml_sharp_signal::FLOAT),
    TOTAL_SHARP_SIGNAL               FLOAT          AS (VALUE:total_sharp_signal::FLOAT),
    INGESTION_TIMESTAMP              TIMESTAMP_NTZ  AS (VALUE:ingestion_timestamp::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_actionnetwork_public_betting/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W11 Tier-D: stg_actionnetwork_public_betting from S3 lakehouse parquet (public-betting feed)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.stg_actionnetwork_public_betting TO ROLE CREDENCE_API_RO;

-- ── stg_actionnetwork_public_betting_snapshots  (14 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_actionnetwork_public_betting_snapshots (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    AN_GAME_ID                       VARCHAR        AS (VALUE:an_game_id::VARCHAR),
    HOME_ML_MONEY_PCT                FLOAT          AS (VALUE:home_ml_money_pct::FLOAT),
    AWAY_ML_MONEY_PCT                FLOAT          AS (VALUE:away_ml_money_pct::FLOAT),
    HOME_ML_TICKET_PCT               FLOAT          AS (VALUE:home_ml_ticket_pct::FLOAT),
    AWAY_ML_TICKET_PCT               FLOAT          AS (VALUE:away_ml_ticket_pct::FLOAT),
    OVER_MONEY_PCT                   FLOAT          AS (VALUE:over_money_pct::FLOAT),
    UNDER_MONEY_PCT                  FLOAT          AS (VALUE:under_money_pct::FLOAT),
    OVER_TICKET_PCT                  FLOAT          AS (VALUE:over_ticket_pct::FLOAT),
    UNDER_TICKET_PCT                 FLOAT          AS (VALUE:under_ticket_pct::FLOAT),
    ML_SHARP_SIGNAL                  FLOAT          AS (VALUE:ml_sharp_signal::FLOAT),
    TOTAL_SHARP_SIGNAL               FLOAT          AS (VALUE:total_sharp_signal::FLOAT),
    RECORD_HASH                      VARCHAR        AS (VALUE:record_hash::VARCHAR),
    LOADED_AT                        TIMESTAMP_NTZ  AS (VALUE:loaded_at::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_actionnetwork_public_betting_snapshots/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W11 Tier-D: stg_actionnetwork_public_betting_snapshots from S3 lakehouse parquet (public-betting feed)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.stg_actionnetwork_public_betting_snapshots TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_public_betting_status  (17 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_public_betting_status (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    AN_GAME_ID                       VARCHAR        AS (VALUE:an_game_id::VARCHAR),
    HOME_ML_MONEY_PCT                FLOAT          AS (VALUE:home_ml_money_pct::FLOAT),
    AWAY_ML_MONEY_PCT                FLOAT          AS (VALUE:away_ml_money_pct::FLOAT),
    HOME_ML_TICKET_PCT               FLOAT          AS (VALUE:home_ml_ticket_pct::FLOAT),
    AWAY_ML_TICKET_PCT               FLOAT          AS (VALUE:away_ml_ticket_pct::FLOAT),
    OVER_MONEY_PCT                   FLOAT          AS (VALUE:over_money_pct::FLOAT),
    UNDER_MONEY_PCT                  FLOAT          AS (VALUE:under_money_pct::FLOAT),
    OVER_TICKET_PCT                  FLOAT          AS (VALUE:over_ticket_pct::FLOAT),
    UNDER_TICKET_PCT                 FLOAT          AS (VALUE:under_ticket_pct::FLOAT),
    ML_SHARP_SIGNAL                  FLOAT          AS (VALUE:ml_sharp_signal::FLOAT),
    TOTAL_SHARP_SIGNAL               FLOAT          AS (VALUE:total_sharp_signal::FLOAT),
    VALID_FROM                       TIMESTAMP_NTZ  AS (VALUE:valid_from::TIMESTAMP_NTZ),
    VALID_TO                         TIMESTAMP_NTZ  AS (VALUE:valid_to::TIMESTAMP_NTZ),
    IS_CURRENT                       BOOLEAN        AS (VALUE:is_current::BOOLEAN),
    RECORD_HASH                      VARCHAR        AS (VALUE:record_hash::VARCHAR),
    COMPUTED_AT                      TIMESTAMP_NTZ  AS (VALUE:computed_at::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_public_betting_status/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W11 Tier-D: feature_pregame_public_betting_status from S3 lakehouse parquet (public-betting feed)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_public_betting_status TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_public_betting_features  (13 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_public_betting_features (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    AN_GAME_ID                       VARCHAR        AS (VALUE:an_game_id::VARCHAR),
    HOME_ML_MONEY_PCT                FLOAT          AS (VALUE:home_ml_money_pct::FLOAT),
    AWAY_ML_MONEY_PCT                FLOAT          AS (VALUE:away_ml_money_pct::FLOAT),
    HOME_ML_TICKET_PCT               FLOAT          AS (VALUE:home_ml_ticket_pct::FLOAT),
    AWAY_ML_TICKET_PCT               FLOAT          AS (VALUE:away_ml_ticket_pct::FLOAT),
    OVER_MONEY_PCT                   FLOAT          AS (VALUE:over_money_pct::FLOAT),
    UNDER_MONEY_PCT                  FLOAT          AS (VALUE:under_money_pct::FLOAT),
    OVER_TICKET_PCT                  FLOAT          AS (VALUE:over_ticket_pct::FLOAT),
    UNDER_TICKET_PCT                 FLOAT          AS (VALUE:under_ticket_pct::FLOAT),
    ML_SHARP_SIGNAL                  FLOAT          AS (VALUE:ml_sharp_signal::FLOAT),
    TOTAL_SHARP_SIGNAL               FLOAT          AS (VALUE:total_sharp_signal::FLOAT),
    PUBLIC_BETTING_SNAPSHOT_TS       TIMESTAMP_NTZ  AS (VALUE:public_betting_snapshot_ts::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_public_betting_features/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W11 Tier-D: feature_pregame_public_betting_features from S3 lakehouse parquet (public-betting feed)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_public_betting_features TO ROLE CREDENCE_API_RO;

-- Verification:
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_actionnetwork_public_betting;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_actionnetwork_public_betting_snapshots;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_public_betting_status;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_public_betting_features;
