-- =============================================================================
-- w11tx_external_tables.generated.sql — GENERATED by generate_w11tx_external_table.py
-- E11.22: external table over the S3 parquet for stg_statsapi_transactions. Run AFTER
-- run_w1_lakehouse.py --w11tx (parquet must exist) and BEFORE the model repoint merges
-- (the else branch reads this). Refresh: refresh_w1_external_tables.py --w11tx (W11TX_TABLES).
-- =============================================================================

-- ── stg_statsapi_transactions  (12 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_statsapi_transactions (
    TRANSACTION_ID           VARCHAR        AS (VALUE:transaction_id::VARCHAR),
    PLAYER_ID                NUMBER(38,0)   AS (VALUE:player_id::NUMBER(38,0)),
    PLAYER_NAME              VARCHAR        AS (VALUE:player_name::VARCHAR),
    TEAM_ID                  NUMBER(38,0)   AS (VALUE:team_id::NUMBER(38,0)),
    TEAM_NAME                VARCHAR        AS (VALUE:team_name::VARCHAR),
    TRANSACTION_DATE         VARCHAR        AS (VALUE:transaction_date::VARCHAR),
    EFFECTIVE_DATE           VARCHAR        AS (VALUE:effective_date::VARCHAR),
    RESOLUTION_DATE          VARCHAR        AS (VALUE:resolution_date::VARCHAR),
    TYPE_CODE                VARCHAR        AS (VALUE:type_code::VARCHAR),
    TYPE_DESCRIPTION         VARCHAR        AS (VALUE:type_description::VARCHAR),
    DESCRIPTION              VARCHAR        AS (VALUE:description::VARCHAR),
    INGESTION_TS             TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_statsapi_transactions/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.22: stg_statsapi_transactions from S3 lakehouse parquet (player_transactions read-cutover)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.stg_statsapi_transactions TO ROLE CREDENCE_API_RO;

-- Verification:
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_statsapi_transactions;
