-- =============================================================================
-- w2_external_tables.generated.sql  —  GENERATED by generate_w2_external_tables.py
-- E11.1-W2: Snowflake external tables over S3 parquet for the W2 marts.
-- Reuses the lakehouse_ext schema + s3_lakehouse stage + parquet_snappy file
-- format created by w1_external_tables.sql (W1d). Run AFTER run_w1_lakehouse.py
-- has written the W2 parquet, and BEFORE merging the W2 models (which become
-- views over these tables). Refresh: scripts/refresh_w1_external_tables.py.
-- DO NOT hand-edit — regenerate from the parquet if a mart's schema changes.
-- =============================================================================

-- ── mart_pitcher_batted_ball_profile  (12 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_pitcher_batted_ball_profile (
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    BF_COUNT                       NUMBER(38,0)   AS (VALUE:bf_count::NUMBER(38,0)),
    TOTAL_BATTED_BALLS             NUMBER(38,0)   AS (VALUE:total_batted_balls::NUMBER(38,0)),
    GB_COUNT                       NUMBER(38,0)   AS (VALUE:gb_count::NUMBER(38,0)),
    FB_COUNT                       NUMBER(38,0)   AS (VALUE:fb_count::NUMBER(38,0)),
    LD_COUNT                       NUMBER(38,0)   AS (VALUE:ld_count::NUMBER(38,0)),
    POPUP_COUNT                    NUMBER(38,0)   AS (VALUE:popup_count::NUMBER(38,0)),
    GB_PCT                         FLOAT          AS (VALUE:gb_pct::FLOAT),
    FB_PCT                         FLOAT          AS (VALUE:fb_pct::FLOAT),
    LD_PCT                         FLOAT          AS (VALUE:ld_pct::FLOAT),
    POPUP_PCT                      FLOAT          AS (VALUE:popup_pct::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_pitcher_batted_ball_profile/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W2: mart_pitcher_batted_ball_profile from S3 lakehouse parquet';

-- ── mart_batter_bat_tracking_profile  (5 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_batter_bat_tracking_profile (
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    BATTER_ID                      NUMBER(38,0)   AS (VALUE:batter_id::NUMBER(38,0)),
    BAT_SPEED_30D                  FLOAT          AS (VALUE:bat_speed_30d::FLOAT),
    SWING_LENGTH_30D               FLOAT          AS (VALUE:swing_length_30d::FLOAT),
    ATTACK_ANGLE_30D               FLOAT          AS (VALUE:attack_angle_30d::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_batter_bat_tracking_profile/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W2: mart_batter_bat_tracking_profile from S3 lakehouse parquet';

-- ── mart_batter_rolling_stats  (102 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_batter_rolling_stats (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    BATTER_ID                      NUMBER(38,0)   AS (VALUE:batter_id::NUMBER(38,0)),
    BATTER_HAND                    VARCHAR        AS (VALUE:batter_hand::VARCHAR),
    BATTING_TEAM                   VARCHAR        AS (VALUE:batting_team::VARCHAR),
    OPPOSING_TEAM                  VARCHAR        AS (VALUE:opposing_team::VARCHAR),
    PA_COUNT                       NUMBER(38,0)   AS (VALUE:pa_count::NUMBER(38,0)),
    PITCHES_SEEN                   NUMBER(38,0)   AS (VALUE:pitches_seen::NUMBER(38,0)),
    HITS                           FLOAT          AS (VALUE:hits::FLOAT),
    HOME_RUNS                      FLOAT          AS (VALUE:home_runs::FLOAT),
    STRIKEOUTS                     FLOAT          AS (VALUE:strikeouts::FLOAT),
    WALKS                          FLOAT          AS (VALUE:walks::FLOAT),
    AVG                            FLOAT          AS (VALUE:avg::FLOAT),
    OBP                            FLOAT          AS (VALUE:obp::FLOAT),
    SLG                            FLOAT          AS (VALUE:slg::FLOAT),
    OPS                            FLOAT          AS (VALUE:ops::FLOAT),
    WOBA                           FLOAT          AS (VALUE:woba::FLOAT),
    XWOBA                          FLOAT          AS (VALUE:xwoba::FLOAT),
    XBA                            FLOAT          AS (VALUE:xba::FLOAT),
    XSLG                           FLOAT          AS (VALUE:xslg::FLOAT),
    K_PCT                          FLOAT          AS (VALUE:k_pct::FLOAT),
    BB_PCT                         FLOAT          AS (VALUE:bb_pct::FLOAT),
    HARD_HIT_PCT                   FLOAT          AS (VALUE:hard_hit_pct::FLOAT),
    BARREL_PCT                     FLOAT          AS (VALUE:barrel_pct::FLOAT),
    WHIFF_RATE                     FLOAT          AS (VALUE:whiff_rate::FLOAT),
    SWINGING_STRIKE_RATE           FLOAT          AS (VALUE:swinging_strike_rate::FLOAT),
    CHASE_RATE                     FLOAT          AS (VALUE:chase_rate::FLOAT),
    ZONE_SWING_RATE                FLOAT          AS (VALUE:zone_swing_rate::FLOAT),
    GAMES_7D                       NUMBER(38,0)   AS (VALUE:games_7d::NUMBER(38,0)),
    PA_COUNT_7D                    FLOAT          AS (VALUE:pa_count_7d::FLOAT),
    AVG_7D                         FLOAT          AS (VALUE:avg_7d::FLOAT),
    OBP_7D                         FLOAT          AS (VALUE:obp_7d::FLOAT),
    SLG_7D                         FLOAT          AS (VALUE:slg_7d::FLOAT),
    OPS_7D                         FLOAT          AS (VALUE:ops_7d::FLOAT),
    WOBA_7D                        FLOAT          AS (VALUE:woba_7d::FLOAT),
    XWOBA_7D                       FLOAT          AS (VALUE:xwoba_7d::FLOAT),
    XBA_7D                         FLOAT          AS (VALUE:xba_7d::FLOAT),
    XSLG_7D                        FLOAT          AS (VALUE:xslg_7d::FLOAT),
    K_PCT_7D                       FLOAT          AS (VALUE:k_pct_7d::FLOAT),
    BB_PCT_7D                      FLOAT          AS (VALUE:bb_pct_7d::FLOAT),
    HARD_HIT_PCT_7D                FLOAT          AS (VALUE:hard_hit_pct_7d::FLOAT),
    BARREL_PCT_7D                  FLOAT          AS (VALUE:barrel_pct_7d::FLOAT),
    WHIFF_RATE_7D                  FLOAT          AS (VALUE:whiff_rate_7d::FLOAT),
    SWINGING_STRIKE_RATE_7D        FLOAT          AS (VALUE:swinging_strike_rate_7d::FLOAT),
    CHASE_RATE_7D                  FLOAT          AS (VALUE:chase_rate_7d::FLOAT),
    ZONE_SWING_RATE_7D             FLOAT          AS (VALUE:zone_swing_rate_7d::FLOAT),
    GAMES_14D                      NUMBER(38,0)   AS (VALUE:games_14d::NUMBER(38,0)),
    PA_COUNT_14D                   FLOAT          AS (VALUE:pa_count_14d::FLOAT),
    AVG_14D                        FLOAT          AS (VALUE:avg_14d::FLOAT),
    OBP_14D                        FLOAT          AS (VALUE:obp_14d::FLOAT),
    SLG_14D                        FLOAT          AS (VALUE:slg_14d::FLOAT),
    OPS_14D                        FLOAT          AS (VALUE:ops_14d::FLOAT),
    WOBA_14D                       FLOAT          AS (VALUE:woba_14d::FLOAT),
    XWOBA_14D                      FLOAT          AS (VALUE:xwoba_14d::FLOAT),
    XBA_14D                        FLOAT          AS (VALUE:xba_14d::FLOAT),
    XSLG_14D                       FLOAT          AS (VALUE:xslg_14d::FLOAT),
    K_PCT_14D                      FLOAT          AS (VALUE:k_pct_14d::FLOAT),
    BB_PCT_14D                     FLOAT          AS (VALUE:bb_pct_14d::FLOAT),
    HARD_HIT_PCT_14D               FLOAT          AS (VALUE:hard_hit_pct_14d::FLOAT),
    BARREL_PCT_14D                 FLOAT          AS (VALUE:barrel_pct_14d::FLOAT),
    WHIFF_RATE_14D                 FLOAT          AS (VALUE:whiff_rate_14d::FLOAT),
    SWINGING_STRIKE_RATE_14D       FLOAT          AS (VALUE:swinging_strike_rate_14d::FLOAT),
    CHASE_RATE_14D                 FLOAT          AS (VALUE:chase_rate_14d::FLOAT),
    ZONE_SWING_RATE_14D            FLOAT          AS (VALUE:zone_swing_rate_14d::FLOAT),
    GAMES_30D                      NUMBER(38,0)   AS (VALUE:games_30d::NUMBER(38,0)),
    PA_COUNT_30D                   FLOAT          AS (VALUE:pa_count_30d::FLOAT),
    AVG_30D                        FLOAT          AS (VALUE:avg_30d::FLOAT),
    OBP_30D                        FLOAT          AS (VALUE:obp_30d::FLOAT),
    SLG_30D                        FLOAT          AS (VALUE:slg_30d::FLOAT),
    OPS_30D                        FLOAT          AS (VALUE:ops_30d::FLOAT),
    WOBA_30D                       FLOAT          AS (VALUE:woba_30d::FLOAT),
    XWOBA_30D                      FLOAT          AS (VALUE:xwoba_30d::FLOAT),
    XBA_30D                        FLOAT          AS (VALUE:xba_30d::FLOAT),
    XSLG_30D                       FLOAT          AS (VALUE:xslg_30d::FLOAT),
    K_PCT_30D                      FLOAT          AS (VALUE:k_pct_30d::FLOAT),
    BB_PCT_30D                     FLOAT          AS (VALUE:bb_pct_30d::FLOAT),
    HARD_HIT_PCT_30D               FLOAT          AS (VALUE:hard_hit_pct_30d::FLOAT),
    BARREL_PCT_30D                 FLOAT          AS (VALUE:barrel_pct_30d::FLOAT),
    WHIFF_RATE_30D                 FLOAT          AS (VALUE:whiff_rate_30d::FLOAT),
    SWINGING_STRIKE_RATE_30D       FLOAT          AS (VALUE:swinging_strike_rate_30d::FLOAT),
    CHASE_RATE_30D                 FLOAT          AS (VALUE:chase_rate_30d::FLOAT),
    ZONE_SWING_RATE_30D            FLOAT          AS (VALUE:zone_swing_rate_30d::FLOAT),
    GAMES_STD                      NUMBER(38,0)   AS (VALUE:games_std::NUMBER(38,0)),
    PA_COUNT_STD                   FLOAT          AS (VALUE:pa_count_std::FLOAT),
    AVG_STD                        FLOAT          AS (VALUE:avg_std::FLOAT),
    OBP_STD                        FLOAT          AS (VALUE:obp_std::FLOAT),
    SLG_STD                        FLOAT          AS (VALUE:slg_std::FLOAT),
    OPS_STD                        FLOAT          AS (VALUE:ops_std::FLOAT),
    WOBA_STD                       FLOAT          AS (VALUE:woba_std::FLOAT),
    XWOBA_STD                      FLOAT          AS (VALUE:xwoba_std::FLOAT),
    XBA_STD                        FLOAT          AS (VALUE:xba_std::FLOAT),
    XSLG_STD                       FLOAT          AS (VALUE:xslg_std::FLOAT),
    K_PCT_STD                      FLOAT          AS (VALUE:k_pct_std::FLOAT),
    BB_PCT_STD                     FLOAT          AS (VALUE:bb_pct_std::FLOAT),
    ISO_STD                        FLOAT          AS (VALUE:iso_std::FLOAT),
    HARD_HIT_PCT_STD               FLOAT          AS (VALUE:hard_hit_pct_std::FLOAT),
    BARREL_PCT_STD                 FLOAT          AS (VALUE:barrel_pct_std::FLOAT),
    WHIFF_RATE_STD                 FLOAT          AS (VALUE:whiff_rate_std::FLOAT),
    SWINGING_STRIKE_RATE_STD       FLOAT          AS (VALUE:swinging_strike_rate_std::FLOAT),
    CHASE_RATE_STD                 FLOAT          AS (VALUE:chase_rate_std::FLOAT),
    ZONE_SWING_RATE_STD            FLOAT          AS (VALUE:zone_swing_rate_std::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_batter_rolling_stats/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W2: mart_batter_rolling_stats from S3 lakehouse parquet';

-- ── mart_pitcher_rolling_stats  (81 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_pitcher_rolling_stats (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    PITCHER_HAND                   VARCHAR        AS (VALUE:pitcher_hand::VARCHAR),
    PITCHING_TEAM                  VARCHAR        AS (VALUE:pitching_team::VARCHAR),
    FACING_TEAM                    VARCHAR        AS (VALUE:facing_team::VARCHAR),
    IS_STARTER                     BOOLEAN        AS (VALUE:is_starter::BOOLEAN),
    BATTERS_FACED                  NUMBER(38,0)   AS (VALUE:batters_faced::NUMBER(38,0)),
    PITCH_COUNT                    NUMBER(38,0)   AS (VALUE:pitch_count::NUMBER(38,0)),
    STRIKEOUTS                     FLOAT          AS (VALUE:strikeouts::FLOAT),
    WALKS                          FLOAT          AS (VALUE:walks::FLOAT),
    HITS_ALLOWED                   FLOAT          AS (VALUE:hits_allowed::FLOAT),
    HOME_RUNS_ALLOWED              FLOAT          AS (VALUE:home_runs_allowed::FLOAT),
    WOBA_AGAINST                   FLOAT          AS (VALUE:woba_against::FLOAT),
    XWOBA_AGAINST                  FLOAT          AS (VALUE:xwoba_against::FLOAT),
    K_PCT                          FLOAT          AS (VALUE:k_pct::FLOAT),
    BB_PCT                         FLOAT          AS (VALUE:bb_pct::FLOAT),
    WHIFF_RATE                     FLOAT          AS (VALUE:whiff_rate::FLOAT),
    SWINGING_STRIKE_RATE           FLOAT          AS (VALUE:swinging_strike_rate::FLOAT),
    BATTER_CHASE_RATE              FLOAT          AS (VALUE:batter_chase_rate::FLOAT),
    HARD_HIT_PCT_ALLOWED           FLOAT          AS (VALUE:hard_hit_pct_allowed::FLOAT),
    BARREL_PCT_ALLOWED             FLOAT          AS (VALUE:barrel_pct_allowed::FLOAT),
    AVG_FASTBALL_VELO              FLOAT          AS (VALUE:avg_fastball_velo::FLOAT),
    AVG_RELEASE_EXTENSION          FLOAT          AS (VALUE:avg_release_extension::FLOAT),
    GAMES_7D                       NUMBER(38,0)   AS (VALUE:games_7d::NUMBER(38,0)),
    BATTERS_FACED_7D               FLOAT          AS (VALUE:batters_faced_7d::FLOAT),
    PITCHES_7D                     FLOAT          AS (VALUE:pitches_7d::FLOAT),
    WOBA_AGAINST_7D                FLOAT          AS (VALUE:woba_against_7d::FLOAT),
    XWOBA_AGAINST_7D               FLOAT          AS (VALUE:xwoba_against_7d::FLOAT),
    K_PCT_7D                       FLOAT          AS (VALUE:k_pct_7d::FLOAT),
    BB_PCT_7D                      FLOAT          AS (VALUE:bb_pct_7d::FLOAT),
    WHIFF_RATE_7D                  FLOAT          AS (VALUE:whiff_rate_7d::FLOAT),
    SWINGING_STRIKE_RATE_7D        FLOAT          AS (VALUE:swinging_strike_rate_7d::FLOAT),
    BATTER_CHASE_RATE_7D           FLOAT          AS (VALUE:batter_chase_rate_7d::FLOAT),
    HARD_HIT_PCT_7D                FLOAT          AS (VALUE:hard_hit_pct_7d::FLOAT),
    BARREL_PCT_7D                  FLOAT          AS (VALUE:barrel_pct_7d::FLOAT),
    AVG_FASTBALL_VELO_7D           FLOAT          AS (VALUE:avg_fastball_velo_7d::FLOAT),
    AVG_RELEASE_EXTENSION_7D       FLOAT          AS (VALUE:avg_release_extension_7d::FLOAT),
    GAMES_14D                      NUMBER(38,0)   AS (VALUE:games_14d::NUMBER(38,0)),
    BATTERS_FACED_14D              FLOAT          AS (VALUE:batters_faced_14d::FLOAT),
    PITCHES_14D                    FLOAT          AS (VALUE:pitches_14d::FLOAT),
    WOBA_AGAINST_14D               FLOAT          AS (VALUE:woba_against_14d::FLOAT),
    XWOBA_AGAINST_14D              FLOAT          AS (VALUE:xwoba_against_14d::FLOAT),
    K_PCT_14D                      FLOAT          AS (VALUE:k_pct_14d::FLOAT),
    BB_PCT_14D                     FLOAT          AS (VALUE:bb_pct_14d::FLOAT),
    WHIFF_RATE_14D                 FLOAT          AS (VALUE:whiff_rate_14d::FLOAT),
    SWINGING_STRIKE_RATE_14D       FLOAT          AS (VALUE:swinging_strike_rate_14d::FLOAT),
    BATTER_CHASE_RATE_14D          FLOAT          AS (VALUE:batter_chase_rate_14d::FLOAT),
    HARD_HIT_PCT_14D               FLOAT          AS (VALUE:hard_hit_pct_14d::FLOAT),
    BARREL_PCT_14D                 FLOAT          AS (VALUE:barrel_pct_14d::FLOAT),
    AVG_FASTBALL_VELO_14D          FLOAT          AS (VALUE:avg_fastball_velo_14d::FLOAT),
    AVG_RELEASE_EXTENSION_14D      FLOAT          AS (VALUE:avg_release_extension_14d::FLOAT),
    GAMES_30D                      NUMBER(38,0)   AS (VALUE:games_30d::NUMBER(38,0)),
    BATTERS_FACED_30D              FLOAT          AS (VALUE:batters_faced_30d::FLOAT),
    PITCHES_30D                    FLOAT          AS (VALUE:pitches_30d::FLOAT),
    WOBA_AGAINST_30D               FLOAT          AS (VALUE:woba_against_30d::FLOAT),
    XWOBA_AGAINST_30D              FLOAT          AS (VALUE:xwoba_against_30d::FLOAT),
    K_PCT_30D                      FLOAT          AS (VALUE:k_pct_30d::FLOAT),
    BB_PCT_30D                     FLOAT          AS (VALUE:bb_pct_30d::FLOAT),
    WHIFF_RATE_30D                 FLOAT          AS (VALUE:whiff_rate_30d::FLOAT),
    SWINGING_STRIKE_RATE_30D       FLOAT          AS (VALUE:swinging_strike_rate_30d::FLOAT),
    BATTER_CHASE_RATE_30D          FLOAT          AS (VALUE:batter_chase_rate_30d::FLOAT),
    HARD_HIT_PCT_30D               FLOAT          AS (VALUE:hard_hit_pct_30d::FLOAT),
    BARREL_PCT_30D                 FLOAT          AS (VALUE:barrel_pct_30d::FLOAT),
    AVG_FASTBALL_VELO_30D          FLOAT          AS (VALUE:avg_fastball_velo_30d::FLOAT),
    AVG_RELEASE_EXTENSION_30D      FLOAT          AS (VALUE:avg_release_extension_30d::FLOAT),
    GAMES_STD                      NUMBER(38,0)   AS (VALUE:games_std::NUMBER(38,0)),
    BATTERS_FACED_STD              FLOAT          AS (VALUE:batters_faced_std::FLOAT),
    PITCHES_STD                    FLOAT          AS (VALUE:pitches_std::FLOAT),
    WOBA_AGAINST_STD               FLOAT          AS (VALUE:woba_against_std::FLOAT),
    XWOBA_AGAINST_STD              FLOAT          AS (VALUE:xwoba_against_std::FLOAT),
    K_PCT_STD                      FLOAT          AS (VALUE:k_pct_std::FLOAT),
    BB_PCT_STD                     FLOAT          AS (VALUE:bb_pct_std::FLOAT),
    WHIFF_RATE_STD                 FLOAT          AS (VALUE:whiff_rate_std::FLOAT),
    SWINGING_STRIKE_RATE_STD       FLOAT          AS (VALUE:swinging_strike_rate_std::FLOAT),
    BATTER_CHASE_RATE_STD          FLOAT          AS (VALUE:batter_chase_rate_std::FLOAT),
    HARD_HIT_PCT_STD               FLOAT          AS (VALUE:hard_hit_pct_std::FLOAT),
    BARREL_PCT_STD                 FLOAT          AS (VALUE:barrel_pct_std::FLOAT),
    AVG_FASTBALL_VELO_STD          FLOAT          AS (VALUE:avg_fastball_velo_std::FLOAT),
    AVG_RELEASE_EXTENSION_STD      FLOAT          AS (VALUE:avg_release_extension_std::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_pitcher_rolling_stats/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W2: mart_pitcher_rolling_stats from S3 lakehouse parquet';

-- ── mart_starting_pitcher_game_log  (23 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_starting_pitcher_game_log (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    PITCHING_TEAM                  VARCHAR        AS (VALUE:pitching_team::VARCHAR),
    BATTING_TEAM                   VARCHAR        AS (VALUE:batting_team::VARCHAR),
    HOME_TEAM                      VARCHAR        AS (VALUE:home_team::VARCHAR),
    AWAY_TEAM                      VARCHAR        AS (VALUE:away_team::VARCHAR),
    IS_HOME_TEAM                   BOOLEAN        AS (VALUE:is_home_team::BOOLEAN),
    TOTAL_PITCHES                  NUMBER(38,0)   AS (VALUE:total_pitches::NUMBER(38,0)),
    BATTERS_FACED                  NUMBER(38,0)   AS (VALUE:batters_faced::NUMBER(38,0)),
    OUTS_RECORDED                  FLOAT          AS (VALUE:outs_recorded::FLOAT),
    INNINGS_PITCHED                FLOAT          AS (VALUE:innings_pitched::FLOAT),
    STRIKEOUTS                     FLOAT          AS (VALUE:strikeouts::FLOAT),
    WALKS                          FLOAT          AS (VALUE:walks::FLOAT),
    HIT_BY_PITCH                   FLOAT          AS (VALUE:hit_by_pitch::FLOAT),
    HOME_RUNS_ALLOWED              FLOAT          AS (VALUE:home_runs_allowed::FLOAT),
    HITS_ALLOWED                   FLOAT          AS (VALUE:hits_allowed::FLOAT),
    RUNS_ALLOWED                   FLOAT          AS (VALUE:runs_allowed::FLOAT),
    XWOBA_AGAINST                  FLOAT          AS (VALUE:xwoba_against::FLOAT),
    AVG_FASTBALL_VELO              FLOAT          AS (VALUE:avg_fastball_velo::FLOAT),
    CUMULATIVE_SEASON_IP           FLOAT          AS (VALUE:cumulative_season_ip::FLOAT),
    CUMULATIVE_SEASON_PITCHES      FLOAT          AS (VALUE:cumulative_season_pitches::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_starting_pitcher_game_log/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W2: mart_starting_pitcher_game_log from S3 lakehouse parquet';

-- ── mart_pitcher_batter_history  (8 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_pitcher_batter_history (
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    BATTER_ID                      NUMBER(38,0)   AS (VALUE:batter_id::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    PA_COUNT                       NUMBER(38,0)   AS (VALUE:pa_count::NUMBER(38,0)),
    WOBA_VALUE_SUM                 FLOAT          AS (VALUE:woba_value_sum::FLOAT),
    WOBA_DENOM_SUM                 FLOAT          AS (VALUE:woba_denom_sum::FLOAT),
    XWOBA_SUM                      FLOAT          AS (VALUE:xwoba_sum::FLOAT),
    XWOBA_OBS                      FLOAT          AS (VALUE:xwoba_obs::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_pitcher_batter_history/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W2: mart_pitcher_batter_history from S3 lakehouse parquet';

-- ── mart_starter_csw_rolling  (7 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_starter_csw_rolling (
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    CSW_PCT_3START                 FLOAT          AS (VALUE:csw_pct_3start::FLOAT),
    CSW_PCT_SEASON                 FLOAT          AS (VALUE:csw_pct_season::FLOAT),
    PITCHES_3START                 FLOAT          AS (VALUE:pitches_3start::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_starter_csw_rolling/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W2: mart_starter_csw_rolling from S3 lakehouse parquet';

-- ── mart_starter_pitch_mix_rolling  (12 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_starter_pitch_mix_rolling (
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    TOTAL_PITCHES_5START           FLOAT          AS (VALUE:total_pitches_5start::FLOAT),
    CAREER_STARTS_BEFORE_GAME      NUMBER(38,0)   AS (VALUE:career_starts_before_game::NUMBER(38,0)),
    FASTBALL_PCT_5START            FLOAT          AS (VALUE:fastball_pct_5start::FLOAT),
    BREAKING_PCT_5START            FLOAT          AS (VALUE:breaking_pct_5start::FLOAT),
    OFFSPEED_PCT_5START            FLOAT          AS (VALUE:offspeed_pct_5start::FLOAT),
    FASTBALL_PCT_SEASON            FLOAT          AS (VALUE:fastball_pct_season::FLOAT),
    BREAKING_PCT_SEASON            FLOAT          AS (VALUE:breaking_pct_season::FLOAT),
    OFFSPEED_PCT_SEASON            FLOAT          AS (VALUE:offspeed_pct_season::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_starter_pitch_mix_rolling/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W2: mart_starter_pitch_mix_rolling from S3 lakehouse parquet';

-- Verification (run after CREATE):
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_pitcher_batted_ball_profile;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_batter_bat_tracking_profile;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_batter_rolling_stats;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_pitcher_rolling_stats;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_starting_pitcher_game_log;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_pitcher_batter_history;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_starter_csw_rolling;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_starter_pitch_mix_rolling;
