-- =============================================================================
-- w3_external_tables.generated.sql  —  GENERATED by generate_w3_external_tables.py
-- E11.1-W3: Snowflake external tables over S3 parquet for the W3 marts.
-- Reuses the lakehouse_ext schema + s3_lakehouse stage + parquet_snappy file
-- format created by w1_external_tables.sql (W1d). Run AFTER run_w1_lakehouse.py
-- has written the W3 parquet, and BEFORE merging the W3 models (which become
-- views over these tables). Refresh: scripts/refresh_w1_external_tables.py.
-- DO NOT hand-edit — regenerate from the parquet if a mart's schema changes.
-- =============================================================================

-- ── mart_pitcher_pitch_archetype  (8 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_pitcher_pitch_archetype (
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    TOTAL_PITCHES                  NUMBER(38,0)   AS (VALUE:total_pitches::NUMBER(38,0)),
    CLASSIFIED_PITCHES             FLOAT          AS (VALUE:classified_pitches::FLOAT),
    FASTBALL_PCT                   FLOAT          AS (VALUE:fastball_pct::FLOAT),
    BREAKING_PCT                   FLOAT          AS (VALUE:breaking_pct::FLOAT),
    OFFSPEED_PCT                   FLOAT          AS (VALUE:offspeed_pct::FLOAT),
    PITCH_ARCHETYPE                VARCHAR        AS (VALUE:pitch_archetype::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_pitcher_pitch_archetype/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_pitcher_pitch_archetype from S3 lakehouse parquet';

-- ── mart_batter_vs_pitch_archetype  (13 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_batter_vs_pitch_archetype (
    BATTER_ID                      NUMBER(38,0)   AS (VALUE:batter_id::NUMBER(38,0)),
    PITCH_ARCHETYPE                VARCHAR        AS (VALUE:pitch_archetype::VARCHAR),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    PA_COUNT                       NUMBER(38,0)   AS (VALUE:pa_count::NUMBER(38,0)),
    RAW_WOBA                       FLOAT          AS (VALUE:raw_woba::FLOAT),
    RAW_XWOBA                      FLOAT          AS (VALUE:raw_xwoba::FLOAT),
    RAW_K_PCT                      FLOAT          AS (VALUE:raw_k_pct::FLOAT),
    RAW_ISO                        FLOAT          AS (VALUE:raw_iso::FLOAT),
    SHRINK_WEIGHT                  FLOAT          AS (VALUE:shrink_weight::FLOAT),
    ADJ_WOBA                       FLOAT          AS (VALUE:adj_woba::FLOAT),
    ADJ_XWOBA                      FLOAT          AS (VALUE:adj_xwoba::FLOAT),
    ADJ_K_PCT                      FLOAT          AS (VALUE:adj_k_pct::FLOAT),
    ADJ_ISO                        FLOAT          AS (VALUE:adj_iso::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_batter_vs_pitch_archetype/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_batter_vs_pitch_archetype from S3 lakehouse parquet';

-- ── mart_batter_vs_handedness_splits  (35 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_batter_vs_handedness_splits (
    BATTER_ID                      NUMBER(38,0)   AS (VALUE:batter_id::NUMBER(38,0)),
    PITCHER_HAND                   VARCHAR        AS (VALUE:pitcher_hand::VARCHAR),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    PLATE_APPEARANCES              NUMBER(38,0)   AS (VALUE:plate_appearances::NUMBER(38,0)),
    AT_BATS                        FLOAT          AS (VALUE:at_bats::FLOAT),
    PITCHES_SEEN                   NUMBER(38,0)   AS (VALUE:pitches_seen::NUMBER(38,0)),
    STRIKEOUTS                     FLOAT          AS (VALUE:strikeouts::FLOAT),
    WALKS                          FLOAT          AS (VALUE:walks::FLOAT),
    HIT_BY_PITCH                   FLOAT          AS (VALUE:hit_by_pitch::FLOAT),
    SINGLES                        FLOAT          AS (VALUE:singles::FLOAT),
    DOUBLES                        FLOAT          AS (VALUE:doubles::FLOAT),
    TRIPLES                        FLOAT          AS (VALUE:triples::FLOAT),
    HOME_RUNS                      FLOAT          AS (VALUE:home_runs::FLOAT),
    HITS                           FLOAT          AS (VALUE:hits::FLOAT),
    TOTAL_BASES                    FLOAT          AS (VALUE:total_bases::FLOAT),
    BATTED_BALLS                   FLOAT          AS (VALUE:batted_balls::FLOAT),
    HARD_HITS                      FLOAT          AS (VALUE:hard_hits::FLOAT),
    BARRELS                        FLOAT          AS (VALUE:barrels::FLOAT),
    SWINGS                         FLOAT          AS (VALUE:swings::FLOAT),
    WHIFFS                         FLOAT          AS (VALUE:whiffs::FLOAT),
    K_PCT                          FLOAT          AS (VALUE:k_pct::FLOAT),
    BB_PCT                         FLOAT          AS (VALUE:bb_pct::FLOAT),
    OBP_DENOM                      FLOAT          AS (VALUE:obp_denom::FLOAT),
    OBP                            FLOAT          AS (VALUE:obp::FLOAT),
    SLG                            FLOAT          AS (VALUE:slg::FLOAT),
    OPS                            FLOAT          AS (VALUE:ops::FLOAT),
    WOBA                           FLOAT          AS (VALUE:woba::FLOAT),
    XWOBA                          FLOAT          AS (VALUE:xwoba::FLOAT),
    HARD_HIT_PCT                   FLOAT          AS (VALUE:hard_hit_pct::FLOAT),
    BARREL_PCT                     FLOAT          AS (VALUE:barrel_pct::FLOAT),
    SWING_RATE                     FLOAT          AS (VALUE:swing_rate::FLOAT),
    WHIFF_RATE                     FLOAT          AS (VALUE:whiff_rate::FLOAT),
    SWINGING_STRIKE_RATE           FLOAT          AS (VALUE:swinging_strike_rate::FLOAT),
    CHASE_RATE                     FLOAT          AS (VALUE:chase_rate::FLOAT),
    ZONE_CONTACT_RATE              FLOAT          AS (VALUE:zone_contact_rate::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_batter_vs_handedness_splits/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_batter_vs_handedness_splits from S3 lakehouse parquet';

-- ── mart_pitcher_vs_handedness_splits  (34 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_pitcher_vs_handedness_splits (
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    BATTER_HAND                    VARCHAR        AS (VALUE:batter_hand::VARCHAR),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    PLATE_APPEARANCES              NUMBER(38,0)   AS (VALUE:plate_appearances::NUMBER(38,0)),
    TOTAL_PITCHES                  NUMBER(38,0)   AS (VALUE:total_pitches::NUMBER(38,0)),
    STRIKEOUTS                     FLOAT          AS (VALUE:strikeouts::FLOAT),
    WALKS                          FLOAT          AS (VALUE:walks::FLOAT),
    HIT_BY_PITCH                   FLOAT          AS (VALUE:hit_by_pitch::FLOAT),
    HITS                           FLOAT          AS (VALUE:hits::FLOAT),
    HOME_RUNS                      FLOAT          AS (VALUE:home_runs::FLOAT),
    SWINGS                         FLOAT          AS (VALUE:swings::FLOAT),
    WHIFFS                         FLOAT          AS (VALUE:whiffs::FLOAT),
    K_PCT                          FLOAT          AS (VALUE:k_pct::FLOAT),
    BB_PCT                         FLOAT          AS (VALUE:bb_pct::FLOAT),
    HR_PCT                         FLOAT          AS (VALUE:hr_pct::FLOAT),
    XWOBA_AGAINST                  FLOAT          AS (VALUE:xwoba_against::FLOAT),
    WHIFF_RATE                     FLOAT          AS (VALUE:whiff_rate::FLOAT),
    SWINGING_STRIKE_RATE           FLOAT          AS (VALUE:swinging_strike_rate::FLOAT),
    FASTBALL_PCT                   FLOAT          AS (VALUE:fastball_pct::FLOAT),
    BREAKING_PCT                   FLOAT          AS (VALUE:breaking_pct::FLOAT),
    OFFSPEED_PCT                   FLOAT          AS (VALUE:offspeed_pct::FLOAT),
    PITCHES_PITCHER_AHEAD          FLOAT          AS (VALUE:pitches_pitcher_ahead::FLOAT),
    FASTBALL_PCT_PITCHER_AHEAD     FLOAT          AS (VALUE:fastball_pct_pitcher_ahead::FLOAT),
    BREAKING_PCT_PITCHER_AHEAD     FLOAT          AS (VALUE:breaking_pct_pitcher_ahead::FLOAT),
    OFFSPEED_PCT_PITCHER_AHEAD     FLOAT          AS (VALUE:offspeed_pct_pitcher_ahead::FLOAT),
    PITCHES_HITTER_AHEAD           FLOAT          AS (VALUE:pitches_hitter_ahead::FLOAT),
    FASTBALL_PCT_HITTER_AHEAD      FLOAT          AS (VALUE:fastball_pct_hitter_ahead::FLOAT),
    BREAKING_PCT_HITTER_AHEAD      FLOAT          AS (VALUE:breaking_pct_hitter_ahead::FLOAT),
    OFFSPEED_PCT_HITTER_AHEAD      FLOAT          AS (VALUE:offspeed_pct_hitter_ahead::FLOAT),
    PITCHES_TWO_STRIKE             FLOAT          AS (VALUE:pitches_two_strike::FLOAT),
    WHIFF_RATE_TWO_STRIKE          FLOAT          AS (VALUE:whiff_rate_two_strike::FLOAT),
    FASTBALL_PCT_TWO_STRIKE        FLOAT          AS (VALUE:fastball_pct_two_strike::FLOAT),
    BREAKING_PCT_TWO_STRIKE        FLOAT          AS (VALUE:breaking_pct_two_strike::FLOAT),
    OFFSPEED_PCT_TWO_STRIKE        FLOAT          AS (VALUE:offspeed_pct_two_strike::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_pitcher_vs_handedness_splits/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_pitcher_vs_handedness_splits from S3 lakehouse parquet';

-- ── mart_starter_tto_splits  (8 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_starter_tto_splits (
    PITCHER_ID                     NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    SEASON                         NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    TTO1_BF                        NUMBER(38,0)   AS (VALUE:tto1_bf::NUMBER(38,0)),
    TTO3_BF                        NUMBER(38,0)   AS (VALUE:tto3_bf::NUMBER(38,0)),
    TTO_MIN_BF                     NUMBER(38,0)   AS (VALUE:tto_min_bf::NUMBER(38,0)),
    TTO1_XWOBA_AGAINST             FLOAT          AS (VALUE:tto1_xwoba_against::FLOAT),
    TTO3_XWOBA_AGAINST             FLOAT          AS (VALUE:tto3_xwoba_against::FLOAT),
    TTO3_XWOBA_PENALTY             FLOAT          AS (VALUE:tto3_xwoba_penalty::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_starter_tto_splits/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_starter_tto_splits from S3 lakehouse parquet';

-- ── mart_team_base_state_splits  (12 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_team_base_state_splits (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    TEAM_ABBREV                    VARCHAR        AS (VALUE:team_abbrev::VARCHAR),
    PA_WITH_RUNNERS_ON_30D         FLOAT          AS (VALUE:pa_with_runners_on_30d::FLOAT),
    WOBA_WITH_RUNNERS_ON_30D       FLOAT          AS (VALUE:woba_with_runners_on_30d::FLOAT),
    XWOBA_WITH_RUNNERS_ON_30D      FLOAT          AS (VALUE:xwoba_with_runners_on_30d::FLOAT),
    WOBA_WITH_RISP_30D             FLOAT          AS (VALUE:woba_with_risp_30d::FLOAT),
    XWOBA_WITH_RISP_30D            FLOAT          AS (VALUE:xwoba_with_risp_30d::FLOAT),
    RUNS_PER_BASERUNNER_30D        FLOAT          AS (VALUE:runs_per_baserunner_30d::FLOAT),
    WOBA_AGAINST_WITH_RUNNERS_ON_30D FLOAT          AS (VALUE:woba_against_with_runners_on_30d::FLOAT),
    WOBA_AGAINST_WITH_RISP_30D     FLOAT          AS (VALUE:woba_against_with_risp_30d::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_team_base_state_splits/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_team_base_state_splits from S3 lakehouse parquet';

-- ── mart_team_vs_pitcher_hand  (57 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_team_vs_pitcher_hand (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    TEAM                           VARCHAR        AS (VALUE:team::VARCHAR),
    OPP_STARTER_HAND               VARCHAR        AS (VALUE:opp_starter_hand::VARCHAR),
    RUNS_SCORED                    NUMBER(38,0)   AS (VALUE:runs_scored::NUMBER(38,0)),
    PA_COUNT                       NUMBER(38,0)   AS (VALUE:pa_count::NUMBER(38,0)),
    STRIKEOUTS                     FLOAT          AS (VALUE:strikeouts::FLOAT),
    WALKS                          FLOAT          AS (VALUE:walks::FLOAT),
    TOTAL_BASES                    FLOAT          AS (VALUE:total_bases::FLOAT),
    AT_BATS                        FLOAT          AS (VALUE:at_bats::FLOAT),
    HARD_HIT_BALLS                 FLOAT          AS (VALUE:hard_hit_balls::FLOAT),
    BARRELS                        FLOAT          AS (VALUE:barrels::FLOAT),
    BATTED_BALLS                   NUMBER(38,0)   AS (VALUE:batted_balls::NUMBER(38,0)),
    WOBA                           FLOAT          AS (VALUE:woba::FLOAT),
    XWOBA                          FLOAT          AS (VALUE:xwoba::FLOAT),
    K_PCT                          FLOAT          AS (VALUE:k_pct::FLOAT),
    BB_PCT                         FLOAT          AS (VALUE:bb_pct::FLOAT),
    SLUGGING                       FLOAT          AS (VALUE:slugging::FLOAT),
    HARD_HIT_PCT                   FLOAT          AS (VALUE:hard_hit_pct::FLOAT),
    BARREL_PCT                     FLOAT          AS (VALUE:barrel_pct::FLOAT),
    GAMES_7D                       NUMBER(38,0)   AS (VALUE:games_7d::NUMBER(38,0)),
    RUNS_PER_GAME_7D               FLOAT          AS (VALUE:runs_per_game_7d::FLOAT),
    WOBA_7D                        FLOAT          AS (VALUE:woba_7d::FLOAT),
    XWOBA_7D                       FLOAT          AS (VALUE:xwoba_7d::FLOAT),
    K_PCT_7D                       FLOAT          AS (VALUE:k_pct_7d::FLOAT),
    BB_PCT_7D                      FLOAT          AS (VALUE:bb_pct_7d::FLOAT),
    SLUGGING_7D                    FLOAT          AS (VALUE:slugging_7d::FLOAT),
    HARD_HIT_PCT_7D                FLOAT          AS (VALUE:hard_hit_pct_7d::FLOAT),
    BARREL_PCT_7D                  FLOAT          AS (VALUE:barrel_pct_7d::FLOAT),
    GAMES_14D                      NUMBER(38,0)   AS (VALUE:games_14d::NUMBER(38,0)),
    RUNS_PER_GAME_14D              FLOAT          AS (VALUE:runs_per_game_14d::FLOAT),
    WOBA_14D                       FLOAT          AS (VALUE:woba_14d::FLOAT),
    XWOBA_14D                      FLOAT          AS (VALUE:xwoba_14d::FLOAT),
    K_PCT_14D                      FLOAT          AS (VALUE:k_pct_14d::FLOAT),
    BB_PCT_14D                     FLOAT          AS (VALUE:bb_pct_14d::FLOAT),
    SLUGGING_14D                   FLOAT          AS (VALUE:slugging_14d::FLOAT),
    HARD_HIT_PCT_14D               FLOAT          AS (VALUE:hard_hit_pct_14d::FLOAT),
    BARREL_PCT_14D                 FLOAT          AS (VALUE:barrel_pct_14d::FLOAT),
    GAMES_30D                      NUMBER(38,0)   AS (VALUE:games_30d::NUMBER(38,0)),
    RUNS_PER_GAME_30D              FLOAT          AS (VALUE:runs_per_game_30d::FLOAT),
    WOBA_30D                       FLOAT          AS (VALUE:woba_30d::FLOAT),
    XWOBA_30D                      FLOAT          AS (VALUE:xwoba_30d::FLOAT),
    K_PCT_30D                      FLOAT          AS (VALUE:k_pct_30d::FLOAT),
    BB_PCT_30D                     FLOAT          AS (VALUE:bb_pct_30d::FLOAT),
    SLUGGING_30D                   FLOAT          AS (VALUE:slugging_30d::FLOAT),
    HARD_HIT_PCT_30D               FLOAT          AS (VALUE:hard_hit_pct_30d::FLOAT),
    BARREL_PCT_30D                 FLOAT          AS (VALUE:barrel_pct_30d::FLOAT),
    GAMES_STD                      NUMBER(38,0)   AS (VALUE:games_std::NUMBER(38,0)),
    RUNS_PER_GAME_STD              FLOAT          AS (VALUE:runs_per_game_std::FLOAT),
    WOBA_STD                       FLOAT          AS (VALUE:woba_std::FLOAT),
    XWOBA_STD                      FLOAT          AS (VALUE:xwoba_std::FLOAT),
    K_PCT_STD                      FLOAT          AS (VALUE:k_pct_std::FLOAT),
    BB_PCT_STD                     FLOAT          AS (VALUE:bb_pct_std::FLOAT),
    SLUGGING_STD                   FLOAT          AS (VALUE:slugging_std::FLOAT),
    HARD_HIT_PCT_STD               FLOAT          AS (VALUE:hard_hit_pct_std::FLOAT),
    BARREL_PCT_STD                 FLOAT          AS (VALUE:barrel_pct_std::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_team_vs_pitcher_hand/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_team_vs_pitcher_hand from S3 lakehouse parquet';

-- ── mart_bullpen_handedness_splits  (8 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_bullpen_handedness_splits (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    TEAM_ABBREV                    VARCHAR        AS (VALUE:team_abbrev::VARCHAR),
    BP_XWOBA_VS_RHB_30D            FLOAT          AS (VALUE:bp_xwoba_vs_rhb_30d::FLOAT),
    BP_XWOBA_VS_LHB_30D            FLOAT          AS (VALUE:bp_xwoba_vs_lhb_30d::FLOAT),
    BP_PA_VS_RHB_30D               FLOAT          AS (VALUE:bp_pa_vs_rhb_30d::FLOAT),
    BP_PA_VS_LHB_30D               FLOAT          AS (VALUE:bp_pa_vs_lhb_30d::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_bullpen_handedness_splits/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_bullpen_handedness_splits from S3 lakehouse parquet';

-- ── mart_bullpen_leverage  (7 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_bullpen_leverage (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    TEAM_ABBREV                    VARCHAR        AS (VALUE:team_abbrev::VARCHAR),
    BP_LEVERAGE_SUM_3D             FLOAT          AS (VALUE:bp_leverage_sum_3d::FLOAT),
    BP_HIGH_LEV_APPEARANCES_3D     FLOAT          AS (VALUE:bp_high_lev_appearances_3d::FLOAT),
    BP_LEVERAGE_SUM_1D             FLOAT          AS (VALUE:bp_leverage_sum_1d::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_bullpen_leverage/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_bullpen_leverage from S3 lakehouse parquet';

-- ── mart_bullpen_workload  (25 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_bullpen_workload (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                      NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    PITCHING_TEAM                  VARCHAR        AS (VALUE:pitching_team::VARCHAR),
    HOME_TEAM                      VARCHAR        AS (VALUE:home_team::VARCHAR),
    AWAY_TEAM                      VARCHAR        AS (VALUE:away_team::VARCHAR),
    BULLPEN_PITCHES_TODAY          FLOAT          AS (VALUE:bullpen_pitches_today::FLOAT),
    PITCHERS_USED_TODAY            NUMBER(38,0)   AS (VALUE:pitchers_used_today::NUMBER(38,0)),
    RELIEVER_APPEARANCES_TODAY     NUMBER(38,0)   AS (VALUE:reliever_appearances_today::NUMBER(38,0)),
    HAD_HIGH_LEVERAGE_APPEARANCE   NUMBER(38,0)   AS (VALUE:had_high_leverage_appearance::NUMBER(38,0)),
    HAD_CLOSER_APPEARANCE          NUMBER(38,0)   AS (VALUE:had_closer_appearance::NUMBER(38,0)),
    BULLPEN_PITCHES_PREV_1D        FLOAT          AS (VALUE:bullpen_pitches_prev_1d::FLOAT),
    BULLPEN_PITCHES_PREV_3D        FLOAT          AS (VALUE:bullpen_pitches_prev_3d::FLOAT),
    BULLPEN_PITCHES_PREV_7D        FLOAT          AS (VALUE:bullpen_pitches_prev_7d::FLOAT),
    PITCHERS_USED_PREV_3D          FLOAT          AS (VALUE:pitchers_used_prev_3d::FLOAT),
    PITCHERS_USED_PREV_7D          FLOAT          AS (VALUE:pitchers_used_prev_7d::FLOAT),
    RELIEVER_APPEARANCES_PREV_3D   FLOAT          AS (VALUE:reliever_appearances_prev_3d::FLOAT),
    RELIEVER_APPEARANCES_PREV_7D   FLOAT          AS (VALUE:reliever_appearances_prev_7d::FLOAT),
    HIGH_LEVERAGE_USED_PREV_2D     NUMBER(38,0)   AS (VALUE:high_leverage_used_prev_2d::NUMBER(38,0)),
    CLOSER_USED_PREV_1D            NUMBER(38,0)   AS (VALUE:closer_used_prev_1d::NUMBER(38,0)),
    CLOSER_USED_PREV_2D            NUMBER(38,0)   AS (VALUE:closer_used_prev_2d::NUMBER(38,0)),
    BULLPEN_IP_PREV_1D             FLOAT          AS (VALUE:bullpen_ip_prev_1d::FLOAT),
    BULLPEN_IP_PREV_2D             FLOAT          AS (VALUE:bullpen_ip_prev_2d::FLOAT),
    BULLPEN_IP_PREV_3D             FLOAT          AS (VALUE:bullpen_ip_prev_3d::FLOAT),
    PITCHERS_USED_PREV_2D          FLOAT          AS (VALUE:pitchers_used_prev_2d::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_bullpen_workload/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_bullpen_workload from S3 lakehouse parquet';

-- ── mart_reliever_top3_availability  (9 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_reliever_top3_availability (
    GAME_PK                        NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                      DATE           AS (VALUE:game_date::DATE),
    TEAM_ABBREV                    VARCHAR        AS (VALUE:team_abbrev::VARCHAR),
    CLOSER_AVAILABLE               NUMBER(38,0)   AS (VALUE:closer_available::NUMBER(38,0)),
    CLOSER_REST_DAYS               NUMBER(38,0)   AS (VALUE:closer_rest_days::NUMBER(38,0)),
    SETUP1_AVAILABLE               NUMBER(38,0)   AS (VALUE:setup1_available::NUMBER(38,0)),
    SETUP1_REST_DAYS               NUMBER(38,0)   AS (VALUE:setup1_rest_days::NUMBER(38,0)),
    SETUP2_AVAILABLE               NUMBER(38,0)   AS (VALUE:setup2_available::NUMBER(38,0)),
    SETUP2_REST_DAYS               NUMBER(38,0)   AS (VALUE:setup2_rest_days::NUMBER(38,0))
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_reliever_top3_availability/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3: mart_reliever_top3_availability from S3 lakehouse parquet';

-- Verification (run after CREATE):
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_pitcher_pitch_archetype;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_batter_vs_pitch_archetype;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_batter_vs_handedness_splits;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_pitcher_vs_handedness_splits;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_starter_tto_splits;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_team_base_state_splits;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_team_vs_pitcher_hand;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_bullpen_handedness_splits;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_bullpen_leverage;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_bullpen_workload;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_reliever_top3_availability;
