-- =============================================================================
-- w3pre_external_tables.generated.sql — GENERATED by generate_w3pre_external_tables.py
-- E11.1-W3pre: Snowflake external tables over the flattened S3 parquet for the
-- odds/staging tier. Reuses the lakehouse_ext schema + s3_lakehouse stage +
-- parquet_snappy file format (W1d). Run AFTER run_w1_lakehouse.py --w3pre-only has
-- written lakehouse/stg_*/data.parquet, and BEFORE merging the W3pre stg models
-- (which become views over these). Refresh: scripts/refresh_w1_external_tables.py.
-- DO NOT hand-edit — regenerate from the parquet if a model's schema changes.
-- =============================================================================

-- ── stg_oddsapi_odds  (21 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_oddsapi_odds (
    INGESTION_TS               VARCHAR        AS (VALUE:ingestion_ts::VARCHAR),
    LOAD_ID                    VARCHAR        AS (VALUE:load_id::VARCHAR),
    MARKET_REQUESTED           VARCHAR        AS (VALUE:market_requested::VARCHAR),
    REGION_REQUESTED           VARCHAR        AS (VALUE:region_requested::VARCHAR),
    X_REQUESTS_USED            NUMBER(38,0)   AS (VALUE:x_requests_used::NUMBER(38,0)),
    X_REQUESTS_REMAINING       NUMBER(38,0)   AS (VALUE:x_requests_remaining::NUMBER(38,0)),
    EVENT_ID                   VARCHAR        AS (VALUE:event_id::VARCHAR),
    SPORT_KEY                  VARCHAR        AS (VALUE:sport_key::VARCHAR),
    SPORT_TITLE                VARCHAR        AS (VALUE:sport_title::VARCHAR),
    COMMENCE_TIME              TIMESTAMP_NTZ  AS (VALUE:commence_time::TIMESTAMP_NTZ),
    HOME_TEAM                  VARCHAR        AS (VALUE:home_team::VARCHAR),
    AWAY_TEAM                  VARCHAR        AS (VALUE:away_team::VARCHAR),
    BOOKMAKER_KEY              VARCHAR        AS (VALUE:bookmaker_key::VARCHAR),
    BOOKMAKER_TITLE            VARCHAR        AS (VALUE:bookmaker_title::VARCHAR),
    BOOKMAKER_LAST_UPDATE      TIMESTAMP_NTZ  AS (VALUE:bookmaker_last_update::TIMESTAMP_NTZ),
    MARKET_KEY                 VARCHAR        AS (VALUE:market_key::VARCHAR),
    MARKET_LAST_UPDATE         TIMESTAMP_NTZ  AS (VALUE:market_last_update::TIMESTAMP_NTZ),
    OUTCOME_NAME               VARCHAR        AS (VALUE:outcome_name::VARCHAR),
    OUTCOME_PRICE_AMERICAN     NUMBER(38,0)   AS (VALUE:outcome_price_american::NUMBER(38,0)),
    OUTCOME_PRICE_DECIMAL      FLOAT          AS (VALUE:outcome_price_decimal::FLOAT),
    OUTCOME_POINT              FLOAT          AS (VALUE:outcome_point::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_oddsapi_odds/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3pre: stg_oddsapi_odds from S3 lakehouse parquet';

-- ── stg_oddsapi_events  (10 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_oddsapi_events (
    INGESTION_TS               VARCHAR        AS (VALUE:ingestion_ts::VARCHAR),
    LOAD_ID                    VARCHAR        AS (VALUE:load_id::VARCHAR),
    X_REQUESTS_USED            NUMBER(38,0)   AS (VALUE:x_requests_used::NUMBER(38,0)),
    X_REQUESTS_REMAINING       NUMBER(38,0)   AS (VALUE:x_requests_remaining::NUMBER(38,0)),
    EVENT_ID                   VARCHAR        AS (VALUE:event_id::VARCHAR),
    SPORT_KEY                  VARCHAR        AS (VALUE:sport_key::VARCHAR),
    SPORT_TITLE                VARCHAR        AS (VALUE:sport_title::VARCHAR),
    COMMENCE_TIME              TIMESTAMP_NTZ  AS (VALUE:commence_time::TIMESTAMP_NTZ),
    HOME_TEAM                  VARCHAR        AS (VALUE:home_team::VARCHAR),
    AWAY_TEAM                  VARCHAR        AS (VALUE:away_team::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_oddsapi_events/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3pre: stg_oddsapi_events from S3 lakehouse parquet';

-- ── stg_derivative_odds  (25 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_derivative_odds (
    INGESTION_TS               TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ),
    LOAD_ID                    VARCHAR        AS (VALUE:load_id::VARCHAR),
    REQUESTED_SNAPSHOT_TS      TIMESTAMP_NTZ  AS (VALUE:requested_snapshot_ts::TIMESTAMP_NTZ),
    ACTUAL_SNAPSHOT_TS         TIMESTAMP_NTZ  AS (VALUE:actual_snapshot_ts::TIMESTAMP_NTZ),
    PREVIOUS_SNAPSHOT_TS       TIMESTAMP_NTZ  AS (VALUE:previous_snapshot_ts::TIMESTAMP_NTZ),
    NEXT_SNAPSHOT_TS           TIMESTAMP_NTZ  AS (VALUE:next_snapshot_ts::TIMESTAMP_NTZ),
    MARKETS_REQUESTED          VARCHAR        AS (VALUE:markets_requested::VARCHAR),
    REGIONS_REQUESTED          VARCHAR        AS (VALUE:regions_requested::VARCHAR),
    X_REQUESTS_REMAINING       NUMBER(38,0)   AS (VALUE:x_requests_remaining::NUMBER(38,0)),
    X_REQUESTS_LAST            NUMBER(38,0)   AS (VALUE:x_requests_last::NUMBER(38,0)),
    EVENT_ID                   VARCHAR        AS (VALUE:event_id::VARCHAR),
    SPORT_KEY                  VARCHAR        AS (VALUE:sport_key::VARCHAR),
    COMMENCE_TIME              TIMESTAMP_NTZ  AS (VALUE:commence_time::TIMESTAMP_NTZ),
    HOME_TEAM                  VARCHAR        AS (VALUE:home_team::VARCHAR),
    AWAY_TEAM                  VARCHAR        AS (VALUE:away_team::VARCHAR),
    BOOKMAKER_KEY              VARCHAR        AS (VALUE:bookmaker_key::VARCHAR),
    BOOKMAKER_TITLE            VARCHAR        AS (VALUE:bookmaker_title::VARCHAR),
    BOOKMAKER_LAST_UPDATE      TIMESTAMP_NTZ  AS (VALUE:bookmaker_last_update::TIMESTAMP_NTZ),
    MARKET_KEY                 VARCHAR        AS (VALUE:market_key::VARCHAR),
    MARKET_LAST_UPDATE         TIMESTAMP_NTZ  AS (VALUE:market_last_update::TIMESTAMP_NTZ),
    OUTCOME_NAME               VARCHAR        AS (VALUE:outcome_name::VARCHAR),
    OUTCOME_DESCRIPTION        VARCHAR        AS (VALUE:outcome_description::VARCHAR),
    OUTCOME_PRICE_AMERICAN     NUMBER(38,0)   AS (VALUE:outcome_price_american::NUMBER(38,0)),
    OUTCOME_PRICE_DECIMAL      FLOAT          AS (VALUE:outcome_price_decimal::FLOAT),
    OUTCOME_POINT              FLOAT          AS (VALUE:outcome_point::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_derivative_odds/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3pre: stg_derivative_odds from S3 lakehouse parquet';

-- ── stg_statsapi_games  (32 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_statsapi_games (
    GAME_PK                    NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_GUID                  VARCHAR        AS (VALUE:game_guid::VARCHAR),
    GAME_TYPE                  VARCHAR        AS (VALUE:game_type::VARCHAR),
    SEASON                     NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    GAME_DATE                  TIMESTAMP_NTZ  AS (VALUE:game_date::TIMESTAMP_NTZ),
    OFFICIAL_DATE              DATE           AS (VALUE:official_date::DATE),
    DAY_NIGHT                  VARCHAR        AS (VALUE:day_night::VARCHAR),
    DOUBLE_HEADER              VARCHAR        AS (VALUE:double_header::VARCHAR),
    GAME_NUMBER                NUMBER(38,0)   AS (VALUE:game_number::NUMBER(38,0)),
    GAMES_IN_SERIES            NUMBER(38,0)   AS (VALUE:games_in_series::NUMBER(38,0)),
    SERIES_GAME_NUMBER         NUMBER(38,0)   AS (VALUE:series_game_number::NUMBER(38,0)),
    SERIES_DESCRIPTION         VARCHAR        AS (VALUE:series_description::VARCHAR),
    SCHEDULED_INNINGS          NUMBER(38,0)   AS (VALUE:scheduled_innings::NUMBER(38,0)),
    IS_TIE                     BOOLEAN        AS (VALUE:is_tie::BOOLEAN),
    ABSTRACT_GAME_STATE        VARCHAR        AS (VALUE:abstract_game_state::VARCHAR),
    DETAILED_STATE             VARCHAR        AS (VALUE:detailed_state::VARCHAR),
    STATUS_CODE                VARCHAR        AS (VALUE:status_code::VARCHAR),
    HOME_TEAM_ID               NUMBER(38,0)   AS (VALUE:home_team_id::NUMBER(38,0)),
    HOME_TEAM_NAME             VARCHAR        AS (VALUE:home_team_name::VARCHAR),
    HOME_SCORE                 NUMBER(38,0)   AS (VALUE:home_score::NUMBER(38,0)),
    HOME_IS_WINNER             BOOLEAN        AS (VALUE:home_is_winner::BOOLEAN),
    HOME_WINS                  NUMBER(38,0)   AS (VALUE:home_wins::NUMBER(38,0)),
    HOME_LOSSES                NUMBER(38,0)   AS (VALUE:home_losses::NUMBER(38,0)),
    AWAY_TEAM_ID               NUMBER(38,0)   AS (VALUE:away_team_id::NUMBER(38,0)),
    AWAY_TEAM_NAME             VARCHAR        AS (VALUE:away_team_name::VARCHAR),
    AWAY_SCORE                 NUMBER(38,0)   AS (VALUE:away_score::NUMBER(38,0)),
    AWAY_IS_WINNER             BOOLEAN        AS (VALUE:away_is_winner::BOOLEAN),
    AWAY_WINS                  NUMBER(38,0)   AS (VALUE:away_wins::NUMBER(38,0)),
    AWAY_LOSSES                NUMBER(38,0)   AS (VALUE:away_losses::NUMBER(38,0)),
    VENUE_ID                   NUMBER(38,0)   AS (VALUE:venue_id::NUMBER(38,0)),
    VENUE_NAME                 VARCHAR        AS (VALUE:venue_name::VARCHAR),
    INGESTION_TS               TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_statsapi_games/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W3pre: stg_statsapi_games from S3 lakehouse parquet';

-- Verification (run after CREATE):
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_oddsapi_odds;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_oddsapi_events;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_derivative_odds;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_statsapi_games;
