-- =============================================================================
-- w4_external_tables.generated.sql  —  GENERATED by generate_w4_external_tables.py
-- E11.1-W4: Snowflake external tables over S3 parquet for the W4 marts + their
-- FanGraphs precursor subtree. Reuses the lakehouse_ext schema + s3_lakehouse
-- stage + parquet_snappy file format created by w1_external_tables.sql (W1d).
-- Run AFTER run_w1_lakehouse.py --w4 has written the W4 parquet, and BEFORE
-- merging the W4 models (which become views over these tables). Refresh:
-- scripts/refresh_w1_external_tables.py (W4_TABLES). DO NOT hand-edit —
-- regenerate from the parquet if a model's schema changes.
-- =============================================================================

-- ── stg_fangraphs__stuff_plus  (14 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_fangraphs__stuff_plus (
    FG_PITCHER_ID                      VARCHAR        AS (VALUE:fg_pitcher_id::VARCHAR),
    PITCHER_NAME                       VARCHAR        AS (VALUE:pitcher_name::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    IP                                 FLOAT          AS (VALUE:ip::FLOAT),
    STUFF_PLUS                         FLOAT          AS (VALUE:stuff_plus::FLOAT),
    LOCATION_PLUS                      FLOAT          AS (VALUE:location_plus::FLOAT),
    PITCHING_PLUS                      FLOAT          AS (VALUE:pitching_plus::FLOAT),
    FASTBALL_PCT                       FLOAT          AS (VALUE:fastball_pct::FLOAT),
    BREAKING_PCT                       FLOAT          AS (VALUE:breaking_pct::FLOAT),
    OFFSPEED_PCT                       FLOAT          AS (VALUE:offspeed_pct::FLOAT),
    PRIMARY_PITCH_TYPE                 VARCHAR        AS (VALUE:primary_pitch_type::VARCHAR),
    MLBAM_PITCHER_ID                   VARCHAR        AS (VALUE:mlbam_pitcher_id::VARCHAR),
    INGESTION_TS                       TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ),
    LOAD_ID                            VARCHAR        AS (VALUE:load_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_fangraphs__stuff_plus/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: stg_fangraphs__stuff_plus from S3 lakehouse parquet';

-- ── stg_fangraphs__zips_pitching  (17 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_fangraphs__zips_pitching (
    FG_PITCHER_ID                      VARCHAR        AS (VALUE:fg_pitcher_id::VARCHAR),
    PITCHER_NAME                       VARCHAR        AS (VALUE:pitcher_name::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    PROJECTION_TYPE                    VARCHAR        AS (VALUE:projection_type::VARCHAR),
    PROJ_ERA                           FLOAT          AS (VALUE:proj_era::FLOAT),
    PROJ_FIP                           FLOAT          AS (VALUE:proj_fip::FLOAT),
    PROJ_XFIP                          FLOAT          AS (VALUE:proj_xfip::FLOAT),
    PROJ_K_PCT                         FLOAT          AS (VALUE:proj_k_pct::FLOAT),
    PROJ_BB_PCT                        FLOAT          AS (VALUE:proj_bb_pct::FLOAT),
    PROJ_K_PER_9                       FLOAT          AS (VALUE:proj_k_per_9::FLOAT),
    PROJ_BB_PER_9                      FLOAT          AS (VALUE:proj_bb_per_9::FLOAT),
    PROJ_IP                            FLOAT          AS (VALUE:proj_ip::FLOAT),
    PROJ_WAR                           FLOAT          AS (VALUE:proj_war::FLOAT),
    PROJ_WHIP                          FLOAT          AS (VALUE:proj_whip::FLOAT),
    MLBAM_PITCHER_ID                   VARCHAR        AS (VALUE:mlbam_pitcher_id::VARCHAR),
    INGESTION_TS                       TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ),
    LOAD_ID                            VARCHAR        AS (VALUE:load_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_fangraphs__zips_pitching/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: stg_fangraphs__zips_pitching from S3 lakehouse parquet';

-- ── stg_fangraphs__pitcher_arsenal  (13 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_fangraphs__pitcher_arsenal (
    FG_PITCHER_ID                      VARCHAR        AS (VALUE:fg_pitcher_id::VARCHAR),
    PITCHER_NAME                       VARCHAR        AS (VALUE:pitcher_name::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    PITCH_TYPE                         VARCHAR        AS (VALUE:pitch_type::VARCHAR),
    PITCH_USAGE_PCT                    FLOAT          AS (VALUE:pitch_usage_pct::FLOAT),
    STUFF_PLUS                         FLOAT          AS (VALUE:stuff_plus::FLOAT),
    LOCATION_PLUS                      FLOAT          AS (VALUE:location_plus::FLOAT),
    PITCHING_PLUS                      FLOAT          AS (VALUE:pitching_plus::FLOAT),
    AVG_VELOCITY_MPH                   FLOAT          AS (VALUE:avg_velocity_mph::FLOAT),
    AVG_H_BREAK_IN                     FLOAT          AS (VALUE:avg_h_break_in::FLOAT),
    AVG_V_BREAK_IN                     FLOAT          AS (VALUE:avg_v_break_in::FLOAT),
    INGESTION_TS                       TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ),
    LOAD_ID                            VARCHAR        AS (VALUE:load_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_fangraphs__pitcher_arsenal/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: stg_fangraphs__pitcher_arsenal from S3 lakehouse parquet';

-- ── stg_fangraphs__zips_hitting  (18 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_fangraphs__zips_hitting (
    FG_BATTER_ID                       VARCHAR        AS (VALUE:fg_batter_id::VARCHAR),
    BATTER_NAME                        VARCHAR        AS (VALUE:batter_name::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    PROJECTION_TYPE                    VARCHAR        AS (VALUE:projection_type::VARCHAR),
    PROJ_WRC_PLUS                      FLOAT          AS (VALUE:proj_wrc_plus::FLOAT),
    PROJ_OBP                           FLOAT          AS (VALUE:proj_obp::FLOAT),
    PROJ_SLG                           FLOAT          AS (VALUE:proj_slg::FLOAT),
    PROJ_AVG                           FLOAT          AS (VALUE:proj_avg::FLOAT),
    PROJ_K_PCT                         FLOAT          AS (VALUE:proj_k_pct::FLOAT),
    PROJ_BB_PCT                        FLOAT          AS (VALUE:proj_bb_pct::FLOAT),
    PROJ_PA                            FLOAT          AS (VALUE:proj_pa::FLOAT),
    PROJ_HR                            FLOAT          AS (VALUE:proj_hr::FLOAT),
    PROJ_WAR                           FLOAT          AS (VALUE:proj_war::FLOAT),
    PROJ_ISO                           FLOAT          AS (VALUE:proj_iso::FLOAT),
    PROJ_WOBA                          FLOAT          AS (VALUE:proj_woba::FLOAT),
    MLBAM_BATTER_ID                    VARCHAR        AS (VALUE:mlbam_batter_id::VARCHAR),
    INGESTION_TS                       TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ),
    LOAD_ID                            VARCHAR        AS (VALUE:load_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_fangraphs__zips_hitting/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: stg_fangraphs__zips_hitting from S3 lakehouse parquet';

-- ── stg_fangraphs__hitting_leaderboard  (70 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_fangraphs__hitting_leaderboard (
    FG_BATTER_ID                       VARCHAR        AS (VALUE:fg_batter_id::VARCHAR),
    BATTER_NAME                        VARCHAR        AS (VALUE:batter_name::VARCHAR),
    MLBAM_BATTER_ID                    VARCHAR        AS (VALUE:mlbam_batter_id::VARCHAR),
    TEAM_ABBREV                        VARCHAR        AS (VALUE:team_abbrev::VARCHAR),
    AGE                                NUMBER(38,0)   AS (VALUE:age::NUMBER(38,0)),
    POSITION                           VARCHAR        AS (VALUE:position::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    WINDOW_TYPE                        VARCHAR        AS (VALUE:window_type::VARCHAR),
    WINDOW_START                       VARCHAR        AS (VALUE:window_start::VARCHAR),
    WINDOW_END                         VARCHAR        AS (VALUE:window_end::VARCHAR),
    PA                                 FLOAT          AS (VALUE:pa::FLOAT),
    AB                                 FLOAT          AS (VALUE:ab::FLOAT),
    G                                  FLOAT          AS (VALUE:g::FLOAT),
    HR                                 FLOAT          AS (VALUE:hr::FLOAT),
    R                                  FLOAT          AS (VALUE:r::FLOAT),
    RBI                                FLOAT          AS (VALUE:rbi::FLOAT),
    SB                                 FLOAT          AS (VALUE:sb::FLOAT),
    AVG                                FLOAT          AS (VALUE:avg::FLOAT),
    OBP                                FLOAT          AS (VALUE:obp::FLOAT),
    SLG                                FLOAT          AS (VALUE:slg::FLOAT),
    OPS                                FLOAT          AS (VALUE:ops::FLOAT),
    ISO                                FLOAT          AS (VALUE:iso::FLOAT),
    BABIP                              FLOAT          AS (VALUE:babip::FLOAT),
    K_PCT                              FLOAT          AS (VALUE:k_pct::FLOAT),
    BB_PCT                             FLOAT          AS (VALUE:bb_pct::FLOAT),
    BB_PER_K                           FLOAT          AS (VALUE:bb_per_k::FLOAT),
    TTO_PCT                            FLOAT          AS (VALUE:tto_pct::FLOAT),
    WRC_PLUS                           FLOAT          AS (VALUE:wrc_plus::FLOAT),
    WOBA                               FLOAT          AS (VALUE:woba::FLOAT),
    WRAA                               FLOAT          AS (VALUE:wraa::FLOAT),
    WAR                                FLOAT          AS (VALUE:war::FLOAT),
    O_SWING_PCT                        FLOAT          AS (VALUE:o_swing_pct::FLOAT),
    Z_SWING_PCT                        FLOAT          AS (VALUE:z_swing_pct::FLOAT),
    SWING_PCT                          FLOAT          AS (VALUE:swing_pct::FLOAT),
    O_CONTACT_PCT                      FLOAT          AS (VALUE:o_contact_pct::FLOAT),
    Z_CONTACT_PCT                      FLOAT          AS (VALUE:z_contact_pct::FLOAT),
    CONTACT_PCT                        FLOAT          AS (VALUE:contact_pct::FLOAT),
    ZONE_PCT                           FLOAT          AS (VALUE:zone_pct::FLOAT),
    SWSTR_PCT                          FLOAT          AS (VALUE:swstr_pct::FLOAT),
    F_STRIKE_PCT                       FLOAT          AS (VALUE:f_strike_pct::FLOAT),
    EV_AVG                             FLOAT          AS (VALUE:ev_avg::FLOAT),
    EV_90TH                            FLOAT          AS (VALUE:ev_90th::FLOAT),
    EV_MAX                             FLOAT          AS (VALUE:ev_max::FLOAT),
    BARREL_PCT                         FLOAT          AS (VALUE:barrel_pct::FLOAT),
    HARD_HIT_PCT                       FLOAT          AS (VALUE:hard_hit_pct::FLOAT),
    GB_PCT                             FLOAT          AS (VALUE:gb_pct::FLOAT),
    LD_PCT                             FLOAT          AS (VALUE:ld_pct::FLOAT),
    FB_PCT                             FLOAT          AS (VALUE:fb_pct::FLOAT),
    IFFB_PCT                           FLOAT          AS (VALUE:iffb_pct::FLOAT),
    HR_PER_FB                          FLOAT          AS (VALUE:hr_per_fb::FLOAT),
    LAUNCH_ANGLE_AVG                   FLOAT          AS (VALUE:launch_angle_avg::FLOAT),
    PULL_PCT                           FLOAT          AS (VALUE:pull_pct::FLOAT),
    CENT_PCT                           FLOAT          AS (VALUE:cent_pct::FLOAT),
    OPPO_PCT                           FLOAT          AS (VALUE:oppo_pct::FLOAT),
    XWOBA                              FLOAT          AS (VALUE:xwoba::FLOAT),
    XAVG                               FLOAT          AS (VALUE:xavg::FLOAT),
    XSLG                               FLOAT          AS (VALUE:xslg::FLOAT),
    AVG_BAT_SPEED                      FLOAT          AS (VALUE:avg_bat_speed::FLOAT),
    ATTACK_ANGLE                       FLOAT          AS (VALUE:attack_angle::FLOAT),
    SWING_LENGTH                       FLOAT          AS (VALUE:swing_length::FLOAT),
    BLAST_CONTACT_PCT                  FLOAT          AS (VALUE:blast_contact_pct::FLOAT),
    BLAST_SWING_PCT                    FLOAT          AS (VALUE:blast_swing_pct::FLOAT),
    FAST_SWING_PCT                     FLOAT          AS (VALUE:fast_swing_pct::FLOAT),
    SQUARED_UP_CONTACT_PCT             FLOAT          AS (VALUE:squared_up_contact_pct::FLOAT),
    SQUARED_UP_SWING_PCT               FLOAT          AS (VALUE:squared_up_swing_pct::FLOAT),
    WBSR                               FLOAT          AS (VALUE:wbsr::FLOAT),
    UBR                                FLOAT          AS (VALUE:ubr::FLOAT),
    SPD_SCORE                          FLOAT          AS (VALUE:spd_score::FLOAT),
    INGESTION_TS                       TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ),
    LOAD_ID                            VARCHAR        AS (VALUE:load_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_fangraphs__hitting_leaderboard/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: stg_fangraphs__hitting_leaderboard from S3 lakehouse parquet';

-- ── fct_fangraphs_pitcher_arsenal_wide  (14 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.fct_fangraphs_pitcher_arsenal_wide (
    FG_PITCHER_ID                      VARCHAR        AS (VALUE:fg_pitcher_id::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    OVERALL_STUFF_PLUS                 FLOAT          AS (VALUE:overall_stuff_plus::FLOAT),
    MLBAM_PITCHER_ID                   NUMBER(38,0)   AS (VALUE:mlbam_pitcher_id::NUMBER(38,0)),
    PRIMARY_PITCH_TYPE                 VARCHAR        AS (VALUE:primary_pitch_type::VARCHAR),
    FASTBALL_PCT                       FLOAT          AS (VALUE:fastball_pct::FLOAT),
    BREAKING_PCT                       FLOAT          AS (VALUE:breaking_pct::FLOAT),
    OFFSPEED_PCT                       FLOAT          AS (VALUE:offspeed_pct::FLOAT),
    FASTBALL_STUFF_PLUS                FLOAT          AS (VALUE:fastball_stuff_plus::FLOAT),
    SLIDER_STUFF_PLUS                  FLOAT          AS (VALUE:slider_stuff_plus::FLOAT),
    CURVEBALL_STUFF_PLUS               FLOAT          AS (VALUE:curveball_stuff_plus::FLOAT),
    CHANGEUP_STUFF_PLUS                FLOAT          AS (VALUE:changeup_stuff_plus::FLOAT),
    AVG_FASTBALL_VELO_MPH              FLOAT          AS (VALUE:avg_fastball_velo_mph::FLOAT),
    MAX_PITCH_BREAK_IN                 FLOAT          AS (VALUE:max_pitch_break_in::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/fct_fangraphs_pitcher_arsenal_wide/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: fct_fangraphs_pitcher_arsenal_wide from S3 lakehouse parquet';

-- ── fct_fangraphs_hitting_analytics  (24 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.fct_fangraphs_hitting_analytics (
    FG_BATTER_ID                       VARCHAR        AS (VALUE:fg_batter_id::VARCHAR),
    BATTER_NAME                        VARCHAR        AS (VALUE:batter_name::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    PROJ_WRC_PLUS                      FLOAT          AS (VALUE:proj_wrc_plus::FLOAT),
    PROJ_OBP                           FLOAT          AS (VALUE:proj_obp::FLOAT),
    PROJ_SLG                           FLOAT          AS (VALUE:proj_slg::FLOAT),
    PROJ_K_PCT                         FLOAT          AS (VALUE:proj_k_pct::FLOAT),
    PROJ_BB_PCT                        FLOAT          AS (VALUE:proj_bb_pct::FLOAT),
    PROJ_PA                            FLOAT          AS (VALUE:proj_pa::FLOAT),
    PROJ_HR                            FLOAT          AS (VALUE:proj_hr::FLOAT),
    PROJ_WAR                           FLOAT          AS (VALUE:proj_war::FLOAT),
    MLBAM_BATTER_ID                    VARCHAR        AS (VALUE:mlbam_batter_id::VARCHAR),
    ROLLING_WRC_PLUS_7D                FLOAT          AS (VALUE:rolling_wrc_plus_7d::FLOAT),
    ROLLING_WRC_PLUS_14D               FLOAT          AS (VALUE:rolling_wrc_plus_14d::FLOAT),
    ROLLING_WRC_PLUS_30D               FLOAT          AS (VALUE:rolling_wrc_plus_30d::FLOAT),
    SEASON_WRC_PLUS                    FLOAT          AS (VALUE:season_wrc_plus::FLOAT),
    ROLLING_OBP_7D                     FLOAT          AS (VALUE:rolling_obp_7d::FLOAT),
    ROLLING_OBP_14D                    FLOAT          AS (VALUE:rolling_obp_14d::FLOAT),
    ROLLING_OBP_30D                    FLOAT          AS (VALUE:rolling_obp_30d::FLOAT),
    SEASON_OBP                         FLOAT          AS (VALUE:season_obp::FLOAT),
    ROLLING_PA_7D                      FLOAT          AS (VALUE:rolling_pa_7d::FLOAT),
    ROLLING_PA_14D                     FLOAT          AS (VALUE:rolling_pa_14d::FLOAT),
    ROLLING_PA_30D                     FLOAT          AS (VALUE:rolling_pa_30d::FLOAT),
    SEASON_PA                          FLOAT          AS (VALUE:season_pa::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/fct_fangraphs_hitting_analytics/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: fct_fangraphs_hitting_analytics from S3 lakehouse parquet';

-- ── fct_fangraphs_pitching_analytics  (22 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.fct_fangraphs_pitching_analytics (
    FG_PITCHER_ID                      VARCHAR        AS (VALUE:fg_pitcher_id::VARCHAR),
    PITCHER_NAME                       VARCHAR        AS (VALUE:pitcher_name::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    STUFF_PLUS                         FLOAT          AS (VALUE:stuff_plus::FLOAT),
    LOCATION_PLUS                      FLOAT          AS (VALUE:location_plus::FLOAT),
    PITCHING_PLUS                      FLOAT          AS (VALUE:pitching_plus::FLOAT),
    PRIMARY_PITCH_TYPE                 VARCHAR        AS (VALUE:primary_pitch_type::VARCHAR),
    FASTBALL_PCT                       FLOAT          AS (VALUE:fastball_pct::FLOAT),
    BREAKING_PCT                       FLOAT          AS (VALUE:breaking_pct::FLOAT),
    OFFSPEED_PCT                       FLOAT          AS (VALUE:offspeed_pct::FLOAT),
    STUFF_IP                           FLOAT          AS (VALUE:stuff_ip::FLOAT),
    PROJ_ERA                           FLOAT          AS (VALUE:proj_era::FLOAT),
    PROJ_FIP                           FLOAT          AS (VALUE:proj_fip::FLOAT),
    PROJ_XFIP                          FLOAT          AS (VALUE:proj_xfip::FLOAT),
    PROJ_K_PCT                         FLOAT          AS (VALUE:proj_k_pct::FLOAT),
    PROJ_BB_PCT                        FLOAT          AS (VALUE:proj_bb_pct::FLOAT),
    PROJ_K_PER_9                       FLOAT          AS (VALUE:proj_k_per_9::FLOAT),
    PROJ_BB_PER_9                      FLOAT          AS (VALUE:proj_bb_per_9::FLOAT),
    PROJ_IP                            FLOAT          AS (VALUE:proj_ip::FLOAT),
    PROJ_WAR                           FLOAT          AS (VALUE:proj_war::FLOAT),
    PROJ_WHIP                          FLOAT          AS (VALUE:proj_whip::FLOAT),
    MLBAM_PITCHER_ID                   VARCHAR        AS (VALUE:mlbam_pitcher_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/fct_fangraphs_pitching_analytics/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: fct_fangraphs_pitching_analytics from S3 lakehouse parquet';

-- ── stg_statsapi_player_profiles  (8 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_statsapi_player_profiles (
    PLAYER_ID                          NUMBER(38,0)   AS (VALUE:player_id::NUMBER(38,0)),
    FULL_NAME                          VARCHAR        AS (VALUE:full_name::VARCHAR),
    BIRTH_DATE                         DATE           AS (VALUE:birth_date::DATE),
    HEIGHT_INCHES                      FLOAT          AS (VALUE:height_inches::FLOAT),
    WEIGHT_LBS                         FLOAT          AS (VALUE:weight_lbs::FLOAT),
    PRIMARY_POSITION_CODE              VARCHAR        AS (VALUE:primary_position_code::VARCHAR),
    ACTIVE                             BOOLEAN        AS (VALUE:active::BOOLEAN),
    LAST_FETCHED_AT                    VARCHAR        AS (VALUE:last_fetched_at::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_statsapi_player_profiles/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: stg_statsapi_player_profiles from S3 lakehouse parquet';

-- ── mart_pitcher_arsenal_summary  (27 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_pitcher_arsenal_summary (
    PITCHER_ID                         NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    GAME_YEAR                          NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    TOTAL_PITCHES                      FLOAT          AS (VALUE:total_pitches::FLOAT),
    FASTBALL_PCT_STATCAST              FLOAT          AS (VALUE:fastball_pct_statcast::FLOAT),
    BREAKING_PCT_STATCAST              FLOAT          AS (VALUE:breaking_pct_statcast::FLOAT),
    OFFSPEED_PCT_STATCAST              FLOAT          AS (VALUE:offspeed_pct_statcast::FLOAT),
    FB_AVG_VELOCITY                    FLOAT          AS (VALUE:fb_avg_velocity::FLOAT),
    BRK_AVG_VELOCITY                   FLOAT          AS (VALUE:brk_avg_velocity::FLOAT),
    OS_AVG_VELOCITY                    FLOAT          AS (VALUE:os_avg_velocity::FLOAT),
    FB_AVG_HMOV                        FLOAT          AS (VALUE:fb_avg_hmov::FLOAT),
    BRK_AVG_HMOV                       FLOAT          AS (VALUE:brk_avg_hmov::FLOAT),
    FB_AVG_VMOV                        FLOAT          AS (VALUE:fb_avg_vmov::FLOAT),
    BRK_AVG_VMOV                       FLOAT          AS (VALUE:brk_avg_vmov::FLOAT),
    FB_AVG_SPIN                        FLOAT          AS (VALUE:fb_avg_spin::FLOAT),
    BRK_AVG_SPIN                       FLOAT          AS (VALUE:brk_avg_spin::FLOAT),
    FB_RELEASE_HEIGHT                  FLOAT          AS (VALUE:fb_release_height::FLOAT),
    FB_RELEASE_SIDE                    FLOAT          AS (VALUE:fb_release_side::FLOAT),
    FB_EXTENSION                       FLOAT          AS (VALUE:fb_extension::FLOAT),
    FB_ARM_ANGLE                       FLOAT          AS (VALUE:fb_arm_angle::FLOAT),
    OVERALL_STUFF_PLUS                 FLOAT          AS (VALUE:overall_stuff_plus::FLOAT),
    FASTBALL_STUFF_PLUS                FLOAT          AS (VALUE:fastball_stuff_plus::FLOAT),
    SLIDER_STUFF_PLUS                  FLOAT          AS (VALUE:slider_stuff_plus::FLOAT),
    CURVEBALL_STUFF_PLUS               FLOAT          AS (VALUE:curveball_stuff_plus::FLOAT),
    CHANGEUP_STUFF_PLUS                FLOAT          AS (VALUE:changeup_stuff_plus::FLOAT),
    FASTBALL_PCT                       FLOAT          AS (VALUE:fastball_pct::FLOAT),
    BREAKING_PCT                       FLOAT          AS (VALUE:breaking_pct::FLOAT),
    OFFSPEED_PCT                       FLOAT          AS (VALUE:offspeed_pct::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_pitcher_arsenal_summary/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: mart_pitcher_arsenal_summary from S3 lakehouse parquet';

-- ── mart_pitcher_profile_summary  (19 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_pitcher_profile_summary (
    PITCHER_ID                         NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    GAME_YEAR                          NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    BF_COUNT                           NUMBER(38,0)   AS (VALUE:bf_count::NUMBER(38,0)),
    TOTAL_PITCHES                      FLOAT          AS (VALUE:total_pitches::FLOAT),
    FASTBALL_PCT                       FLOAT          AS (VALUE:fastball_pct::FLOAT),
    BREAKING_PCT                       FLOAT          AS (VALUE:breaking_pct::FLOAT),
    OFFSPEED_PCT                       FLOAT          AS (VALUE:offspeed_pct::FLOAT),
    FB_AVG_VELOCITY                    FLOAT          AS (VALUE:fb_avg_velocity::FLOAT),
    FB_ARM_ANGLE                       FLOAT          AS (VALUE:fb_arm_angle::FLOAT),
    FB_AVG_HMOV                        FLOAT          AS (VALUE:fb_avg_hmov::FLOAT),
    FB_AVG_VMOV                        FLOAT          AS (VALUE:fb_avg_vmov::FLOAT),
    BRK_AVG_HMOV                       FLOAT          AS (VALUE:brk_avg_hmov::FLOAT),
    BRK_AVG_VMOV                       FLOAT          AS (VALUE:brk_avg_vmov::FLOAT),
    OVERALL_STUFF_PLUS                 FLOAT          AS (VALUE:overall_stuff_plus::FLOAT),
    K_PCT                              FLOAT          AS (VALUE:k_pct::FLOAT),
    BB_PCT                             FLOAT          AS (VALUE:bb_pct::FLOAT),
    WHIFF_PCT                          FLOAT          AS (VALUE:whiff_pct::FLOAT),
    GB_PCT                             FLOAT          AS (VALUE:gb_pct::FLOAT),
    BIRTH_DATE                         DATE           AS (VALUE:birth_date::DATE)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_pitcher_profile_summary/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: mart_pitcher_profile_summary from S3 lakehouse parquet';

-- ── mart_batter_profile_summary  (16 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_batter_profile_summary (
    BATTER_ID                          NUMBER(38,0)   AS (VALUE:batter_id::NUMBER(38,0)),
    GAME_YEAR                          NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    PA_COUNT                           NUMBER(38,0)   AS (VALUE:pa_count::NUMBER(38,0)),
    AVG_EXIT_VELOCITY                  FLOAT          AS (VALUE:avg_exit_velocity::FLOAT),
    GB_PCT                             FLOAT          AS (VALUE:gb_pct::FLOAT),
    FB_PCT                             FLOAT          AS (VALUE:fb_pct::FLOAT),
    LD_PCT                             FLOAT          AS (VALUE:ld_pct::FLOAT),
    PULL_PCT                           FLOAT          AS (VALUE:pull_pct::FLOAT),
    HARD_HIT_PCT                       FLOAT          AS (VALUE:hard_hit_pct::FLOAT),
    BARREL_PCT                         FLOAT          AS (VALUE:barrel_pct::FLOAT),
    AVG_XWOBA                          FLOAT          AS (VALUE:avg_xwoba::FLOAT),
    K_PCT                              FLOAT          AS (VALUE:k_pct::FLOAT),
    BB_PCT                             FLOAT          AS (VALUE:bb_pct::FLOAT),
    ISO                                FLOAT          AS (VALUE:iso::FLOAT),
    PROJ_K_PCT                         FLOAT          AS (VALUE:proj_k_pct::FLOAT),
    PROJ_BB_PCT                        FLOAT          AS (VALUE:proj_bb_pct::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_batter_profile_summary/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: mart_batter_profile_summary from S3 lakehouse parquet';

-- ── mart_park_factors_granular  (26 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_park_factors_granular (
    VENUE_ID                           NUMBER(38,0)   AS (VALUE:venue_id::NUMBER(38,0)),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    N_PA                               NUMBER(38,0)   AS (VALUE:n_pa::NUMBER(38,0)),
    RAW_HR_FACTOR                      FLOAT          AS (VALUE:raw_hr_factor::FLOAT),
    RAW_DOUBLES_TRIPLES_FACTOR         FLOAT          AS (VALUE:raw_doubles_triples_factor::FLOAT),
    RAW_SINGLES_FACTOR                 FLOAT          AS (VALUE:raw_singles_factor::FLOAT),
    RAW_BB_FACTOR                      FLOAT          AS (VALUE:raw_bb_factor::FLOAT),
    RAW_SO_FACTOR                      FLOAT          AS (VALUE:raw_so_factor::FLOAT),
    RAW_WOBA_FACTOR                    FLOAT          AS (VALUE:raw_woba_factor::FLOAT),
    EB_HR_FACTOR                       FLOAT          AS (VALUE:eb_hr_factor::FLOAT),
    EB_DOUBLES_TRIPLES_FACTOR          FLOAT          AS (VALUE:eb_doubles_triples_factor::FLOAT),
    EB_SINGLES_FACTOR                  FLOAT          AS (VALUE:eb_singles_factor::FLOAT),
    EB_BB_FACTOR                       FLOAT          AS (VALUE:eb_bb_factor::FLOAT),
    EB_SO_FACTOR                       FLOAT          AS (VALUE:eb_so_factor::FLOAT),
    EB_WOBA_FACTOR                     FLOAT          AS (VALUE:eb_woba_factor::FLOAT),
    SHRINKAGE_HR                       FLOAT          AS (VALUE:shrinkage_hr::FLOAT),
    SHRINKAGE_DOUBLES_TRIPLES          FLOAT          AS (VALUE:shrinkage_doubles_triples::FLOAT),
    SHRINKAGE_SINGLES                  FLOAT          AS (VALUE:shrinkage_singles::FLOAT),
    SHRINKAGE_BB                       FLOAT          AS (VALUE:shrinkage_bb::FLOAT),
    SHRINKAGE_SO                       FLOAT          AS (VALUE:shrinkage_so::FLOAT),
    PRIOR_MEAN_HR                      FLOAT          AS (VALUE:prior_mean_hr::FLOAT),
    PRIOR_VARIANCE_HR                  FLOAT          AS (VALUE:prior_variance_hr::FLOAT),
    PRIOR_MEAN_DOUBLES_TRIPLES         FLOAT          AS (VALUE:prior_mean_doubles_triples::FLOAT),
    PRIOR_VARIANCE_DOUBLES_TRIPLES     FLOAT          AS (VALUE:prior_variance_doubles_triples::FLOAT),
    FIT_DATE                           VARCHAR        AS (VALUE:fit_date::VARCHAR),
    RUN_ID                             VARCHAR        AS (VALUE:run_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_park_factors_granular/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: mart_park_factors_granular from S3 lakehouse parquet';

-- ── mart_batter_woba_vs_cluster  (9 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_batter_woba_vs_cluster (
    BATTER_ID                          NUMBER(38,0)   AS (VALUE:batter_id::NUMBER(38,0)),
    CLUSTER_ID                         NUMBER(38,0)   AS (VALUE:cluster_id::NUMBER(38,0)),
    GAME_DATE                          DATE           AS (VALUE:game_date::DATE),
    PA_COUNT                           FLOAT          AS (VALUE:pa_count::FLOAT),
    RAW_WOBA                           FLOAT          AS (VALUE:raw_woba::FLOAT),
    RAW_XWOBA                          FLOAT          AS (VALUE:raw_xwoba::FLOAT),
    SHRINK_WEIGHT                      FLOAT          AS (VALUE:shrink_weight::FLOAT),
    ADJ_WOBA                           FLOAT          AS (VALUE:adj_woba::FLOAT),
    ADJ_XWOBA                          FLOAT          AS (VALUE:adj_xwoba::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_batter_woba_vs_cluster/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: mart_batter_woba_vs_cluster from S3 lakehouse parquet';

-- ── mart_catcher_framing  (7 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_catcher_framing (
    PLAYER_ID                          VARCHAR        AS (VALUE:player_id::VARCHAR),
    SEASON                             NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    INNINGS_CAUGHT                     FLOAT          AS (VALUE:innings_caught::FLOAT),
    IS_RELIABLE                        BOOLEAN        AS (VALUE:is_reliable::BOOLEAN),
    FRAMING_RUNS_ABOVE_AVERAGE         FLOAT          AS (VALUE:framing_runs_above_average::FLOAT),
    DEFENSIVE_RUNS_ABOVE_AVERAGE       FLOAT          AS (VALUE:defensive_runs_above_average::FLOAT),
    STOLEN_BASE_RUNS_ABOVE_AVERAGE     FLOAT          AS (VALUE:stolen_base_runs_above_average::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_catcher_framing/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W4: mart_catcher_framing from S3 lakehouse parquet';

-- Verification (run after CREATE):
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_fangraphs__stuff_plus;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_fangraphs__zips_pitching;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_fangraphs__pitcher_arsenal;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_fangraphs__zips_hitting;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_fangraphs__hitting_leaderboard;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.fct_fangraphs_pitcher_arsenal_wide;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.fct_fangraphs_hitting_analytics;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.fct_fangraphs_pitching_analytics;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_statsapi_player_profiles;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_pitcher_arsenal_summary;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_pitcher_profile_summary;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_batter_profile_summary;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_park_factors_granular;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_batter_woba_vs_cluster;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_catcher_framing;
