-- =============================================================================
-- w5b_external_tables.generated.sql — GENERATED by generate_w5b_external_tables.py
-- E11.1-W5b: external table over S3 parquet for the archetype mart. Reuses the
-- lakehouse_ext schema + s3_lakehouse stage + parquet_snappy format (W1d). Run AFTER
-- run_w1_lakehouse.py --archetype, and BEFORE merging the mart (which becomes a view).
-- Refresh: refresh_w1_external_tables.py (ARCHETYPE_TABLES).
-- =============================================================================

-- ── mart_batter_archetype_vs_pitcher_cluster  (9 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.mart_batter_archetype_vs_pitcher_cluster (
    BATTER_CLUSTER_LABEL         VARCHAR        AS (VALUE:batter_cluster_label::VARCHAR),
    PITCHER_CLUSTER_LABEL        VARCHAR        AS (VALUE:pitcher_cluster_label::VARCHAR),
    GAME_DATE                    DATE           AS (VALUE:game_date::DATE),
    PA_WEIGHT                    FLOAT          AS (VALUE:pa_weight::FLOAT),
    RAW_WOBA                     FLOAT          AS (VALUE:raw_woba::FLOAT),
    RAW_XWOBA                    FLOAT          AS (VALUE:raw_xwoba::FLOAT),
    SHRINK_WEIGHT                FLOAT          AS (VALUE:shrink_weight::FLOAT),
    ADJ_WOBA                     FLOAT          AS (VALUE:adj_woba::FLOAT),
    ADJ_XWOBA                    FLOAT          AS (VALUE:adj_xwoba::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/mart_batter_archetype_vs_pitcher_cluster/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W5b: mart_batter_archetype_vs_pitcher_cluster from S3 lakehouse parquet (tolerance-parity mart)';

-- Verification:
-- SELECT count(*) FROM baseball_data.lakehouse_ext.mart_batter_archetype_vs_pitcher_cluster;
