-- =============================================================================
-- w7_external_tables.generated.sql — GENERATED by generate_w7_external_tables.py
-- E11.1-W7a: external tables over the S3 cluster parquet so the feature layer can
-- read clusters from lakehouse_ext (source 'lakehouse_clusters') instead of the
-- native statsapi.{batter,pitcher}_clusters — frees the native cluster builds to drop.
-- Run AFTER cluster_batters/cluster_pitchers --seed (or --s3), and BEFORE merging the
-- feature-model source repoint. Refresh: refresh_w1_external_tables.py (W7_TABLES).
-- =============================================================================

-- ── batter_clusters  (6 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.batter_clusters (
    BATTER_ID                    NUMBER(38,0)   AS (VALUE:batter_id::NUMBER(38,0)),
    SEASON                       NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    CLUSTER_ID                   NUMBER(38,0)   AS (VALUE:cluster_id::NUMBER(38,0)),
    CLUSTER_LABEL                VARCHAR        AS (VALUE:cluster_label::VARCHAR),
    SILHOUETTE_SCORE             FLOAT          AS (VALUE:silhouette_score::FLOAT),
    RUN_TIMESTAMP                TIMESTAMP_NTZ  AS (VALUE:run_timestamp::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/batter_clusters/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W7a: batter_clusters from S3 lakehouse parquet — frees the native cluster build to be dropped';
-- Preserve the request/feature reader grant on (re)create (INC-18 band-aid class):
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.batter_clusters TO ROLE CREDENCE_API_RO;

-- ── pitcher_clusters  (7 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.pitcher_clusters (
    PITCHER_ID                   NUMBER(38,0)   AS (VALUE:pitcher_id::NUMBER(38,0)),
    SEASON                       NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    CLUSTER_ID                   NUMBER(38,0)   AS (VALUE:cluster_id::NUMBER(38,0)),
    CLUSTER_LABEL                VARCHAR        AS (VALUE:cluster_label::VARCHAR),
    SILHOUETTE_SCORE             FLOAT          AS (VALUE:silhouette_score::FLOAT),
    FIT_DATE                     DATE           AS (VALUE:fit_date::DATE),
    RUN_TIMESTAMP                TIMESTAMP_NTZ  AS (VALUE:run_timestamp::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/pitcher_clusters/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W7a: pitcher_clusters from S3 lakehouse parquet — frees the native cluster build to be dropped';
-- Preserve the request/feature reader grant on (re)create (INC-18 band-aid class):
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.pitcher_clusters TO ROLE CREDENCE_API_RO;

-- Verification:
-- SELECT count(*) FROM baseball_data.lakehouse_ext.batter_clusters;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.pitcher_clusters;
