-- =============================================================================
-- w8a_external_tables.generated.sql — GENERATED by generate_w8a_external_tables.py
-- E11.1-W8a: external tables over the S3 parquet for the upstream feature layer +
-- EB posteriors. Run AFTER run_w1_lakehouse.py --w8a (parquet must exist) and BEFORE
-- the PR merges (the models' Snowflake else branch reads these). Refresh:
-- refresh_w1_external_tables.py (W8A_TABLES).
-- =============================================================================

-- ── stg_statsapi_starter_snapshots  (6 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.stg_statsapi_starter_snapshots (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    SIDE                             VARCHAR        AS (VALUE:side::VARCHAR),
    PROBABLE_PITCHER_ID              NUMBER(38,0)   AS (VALUE:probable_pitcher_id::NUMBER(38,0)),
    PROBABLE_PITCHER_NAME            VARCHAR        AS (VALUE:probable_pitcher_name::VARCHAR),
    INGESTION_TS                     TIMESTAMP_NTZ  AS (VALUE:ingestion_ts::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/stg_statsapi_starter_snapshots/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: stg_statsapi_starter_snapshots from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.stg_statsapi_starter_snapshots TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_starter_status  (10 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_starter_status (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    SIDE                             VARCHAR        AS (VALUE:side::VARCHAR),
    STARTER_PLAYER_ID                NUMBER(38,0)   AS (VALUE:starter_player_id::NUMBER(38,0)),
    STARTER_PLAYER_NAME              VARCHAR        AS (VALUE:starter_player_name::VARCHAR),
    VALID_FROM                       TIMESTAMP_NTZ  AS (VALUE:valid_from::TIMESTAMP_NTZ),
    VALID_TO                         TIMESTAMP_NTZ  AS (VALUE:valid_to::TIMESTAMP_NTZ),
    IS_CURRENT                       BOOLEAN        AS (VALUE:is_current::BOOLEAN),
    RECORD_HASH                      VARCHAR        AS (VALUE:record_hash::VARCHAR),
    COMPUTED_AT                      TIMESTAMP_NTZ  AS (VALUE:computed_at::TIMESTAMP_NTZ)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_starter_status/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: feature_pregame_starter_status from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_starter_status TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_park_status  (12 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_park_status (
    VENUE_ID                         NUMBER(38,0)   AS (VALUE:venue_id::NUMBER(38,0)),
    SEASON                           NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    EB_PARK_RUN_FACTOR               FLOAT          AS (VALUE:eb_park_run_factor::FLOAT),
    SHRINKAGE_FACTOR                 FLOAT          AS (VALUE:shrinkage_factor::FLOAT),
    ELEVATION_FT                     NUMBER(38,0)   AS (VALUE:elevation_ft::NUMBER(38,0)),
    CENTER_FT                        NUMBER(38,0)   AS (VALUE:center_ft::NUMBER(38,0)),
    ROOF_TYPE                        VARCHAR        AS (VALUE:roof_type::VARCHAR),
    VALID_FROM                       DATE           AS (VALUE:valid_from::DATE),
    VALID_TO                         DATE           AS (VALUE:valid_to::DATE),
    RECORD_HASH                      VARCHAR        AS (VALUE:record_hash::VARCHAR),
    COMPUTED_AT                      TIMESTAMP_NTZ  AS (VALUE:computed_at::TIMESTAMP_NTZ),
    IS_CURRENT                       BOOLEAN        AS (VALUE:is_current::BOOLEAN)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_park_status/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: feature_pregame_park_status from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_park_status TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_park_features  (25 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_park_features (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                        NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    VENUE_ID                         NUMBER(38,0)   AS (VALUE:venue_id::NUMBER(38,0)),
    VENUE_NAME                       VARCHAR        AS (VALUE:venue_name::VARCHAR),
    ELEVATION_FT                     NUMBER(38,0)   AS (VALUE:elevation_ft::NUMBER(38,0)),
    TURF_TYPE                        VARCHAR        AS (VALUE:turf_type::VARCHAR),
    ROOF_TYPE                        VARCHAR        AS (VALUE:roof_type::VARCHAR),
    LEFT_LINE_FT                     NUMBER(38,0)   AS (VALUE:left_line_ft::NUMBER(38,0)),
    LEFT_FT                          NUMBER(38,0)   AS (VALUE:left_ft::NUMBER(38,0)),
    LEFT_CENTER_FT                   NUMBER(38,0)   AS (VALUE:left_center_ft::NUMBER(38,0)),
    CENTER_FT                        NUMBER(38,0)   AS (VALUE:center_ft::NUMBER(38,0)),
    RIGHT_CENTER_FT                  NUMBER(38,0)   AS (VALUE:right_center_ft::NUMBER(38,0)),
    RIGHT_LINE_FT                    NUMBER(38,0)   AS (VALUE:right_line_ft::NUMBER(38,0)),
    RUNS_PER_GAME_AT_PARK            FLOAT          AS (VALUE:runs_per_game_at_park::FLOAT),
    PARK_RUN_FACTOR_3YR              FLOAT          AS (VALUE:park_run_factor_3yr::FLOAT),
    EB_PARK_RUN_FACTOR               FLOAT          AS (VALUE:eb_park_run_factor::FLOAT),
    SHRINKAGE_FACTOR                 FLOAT          AS (VALUE:shrinkage_factor::FLOAT),
    EB_HR_FACTOR                     FLOAT          AS (VALUE:eb_hr_factor::FLOAT),
    EB_DOUBLES_TRIPLES_FACTOR        FLOAT          AS (VALUE:eb_doubles_triples_factor::FLOAT),
    EB_SINGLES_FACTOR                FLOAT          AS (VALUE:eb_singles_factor::FLOAT),
    EB_BB_FACTOR                     FLOAT          AS (VALUE:eb_bb_factor::FLOAT),
    EB_SO_FACTOR                     FLOAT          AS (VALUE:eb_so_factor::FLOAT),
    EB_WOBA_FACTOR                   FLOAT          AS (VALUE:eb_woba_factor::FLOAT),
    PARK_GRANULAR_N_PA               NUMBER(38,0)   AS (VALUE:park_granular_n_pa::NUMBER(38,0))
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_park_features/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: feature_pregame_park_features from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_park_features TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_team_features  (119 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_team_features (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                        NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    TEAM_ABBREV                      VARCHAR        AS (VALUE:team_abbrev::VARCHAR),
    SIDE                             VARCHAR        AS (VALUE:side::VARCHAR),
    WINS                             FLOAT          AS (VALUE:wins::FLOAT),
    LOSSES                           FLOAT          AS (VALUE:losses::FLOAT),
    GAMES_PLAYED                     FLOAT          AS (VALUE:games_played::FLOAT),
    WIN_PCT                          FLOAT          AS (VALUE:win_pct::FLOAT),
    PYTHAGOREAN_WIN_EXP              FLOAT          AS (VALUE:pythagorean_win_exp::FLOAT),
    PYTHAGOREAN_RESIDUAL_SEASON      FLOAT          AS (VALUE:pythagorean_residual_season::FLOAT),
    PYTHAGOREAN_RESIDUAL_30D         FLOAT          AS (VALUE:pythagorean_residual_30d::FLOAT),
    GAMES_BACK                       FLOAT          AS (VALUE:games_back::FLOAT),
    STREAK_DIRECTION                 VARCHAR        AS (VALUE:streak_direction::VARCHAR),
    STREAK_LENGTH                    NUMBER(38,0)   AS (VALUE:streak_length::NUMBER(38,0)),
    OFF_RUNS_PER_GAME_7D             FLOAT          AS (VALUE:off_runs_per_game_7d::FLOAT),
    OFF_RUNS_PER_GAME_14D            FLOAT          AS (VALUE:off_runs_per_game_14d::FLOAT),
    OFF_RUNS_PER_GAME_30D            FLOAT          AS (VALUE:off_runs_per_game_30d::FLOAT),
    OFF_RUNS_PER_GAME_STD            FLOAT          AS (VALUE:off_runs_per_game_std::FLOAT),
    OFF_WOBA_7D                      FLOAT          AS (VALUE:off_woba_7d::FLOAT),
    OFF_WOBA_14D                     FLOAT          AS (VALUE:off_woba_14d::FLOAT),
    OFF_WOBA_30D                     FLOAT          AS (VALUE:off_woba_30d::FLOAT),
    OFF_WOBA_STD                     FLOAT          AS (VALUE:off_woba_std::FLOAT),
    OFF_XWOBA_7D                     FLOAT          AS (VALUE:off_xwoba_7d::FLOAT),
    OFF_XWOBA_14D                    FLOAT          AS (VALUE:off_xwoba_14d::FLOAT),
    OFF_XWOBA_30D                    FLOAT          AS (VALUE:off_xwoba_30d::FLOAT),
    OFF_XWOBA_STD                    FLOAT          AS (VALUE:off_xwoba_std::FLOAT),
    OFF_K_PCT_7D                     FLOAT          AS (VALUE:off_k_pct_7d::FLOAT),
    OFF_K_PCT_30D                    FLOAT          AS (VALUE:off_k_pct_30d::FLOAT),
    OFF_K_PCT_STD                    FLOAT          AS (VALUE:off_k_pct_std::FLOAT),
    OFF_BB_PCT_7D                    FLOAT          AS (VALUE:off_bb_pct_7d::FLOAT),
    OFF_BB_PCT_30D                   FLOAT          AS (VALUE:off_bb_pct_30d::FLOAT),
    OFF_BB_PCT_STD                   FLOAT          AS (VALUE:off_bb_pct_std::FLOAT),
    OFF_HARD_HIT_PCT_7D              FLOAT          AS (VALUE:off_hard_hit_pct_7d::FLOAT),
    OFF_HARD_HIT_PCT_30D             FLOAT          AS (VALUE:off_hard_hit_pct_30d::FLOAT),
    OFF_HARD_HIT_PCT_STD             FLOAT          AS (VALUE:off_hard_hit_pct_std::FLOAT),
    OFF_BARREL_PCT_30D               FLOAT          AS (VALUE:off_barrel_pct_30d::FLOAT),
    OFF_SLUGGING_30D                 FLOAT          AS (VALUE:off_slugging_30d::FLOAT),
    PIT_RUNS_ALLOWED_7D              FLOAT          AS (VALUE:pit_runs_allowed_7d::FLOAT),
    PIT_RUNS_ALLOWED_14D             FLOAT          AS (VALUE:pit_runs_allowed_14d::FLOAT),
    PIT_RUNS_ALLOWED_30D             FLOAT          AS (VALUE:pit_runs_allowed_30d::FLOAT),
    PIT_RUNS_ALLOWED_STD             FLOAT          AS (VALUE:pit_runs_allowed_std::FLOAT),
    PIT_WOBA_AGAINST_7D              FLOAT          AS (VALUE:pit_woba_against_7d::FLOAT),
    PIT_WOBA_AGAINST_14D             FLOAT          AS (VALUE:pit_woba_against_14d::FLOAT),
    PIT_WOBA_AGAINST_30D             FLOAT          AS (VALUE:pit_woba_against_30d::FLOAT),
    PIT_WOBA_AGAINST_STD             FLOAT          AS (VALUE:pit_woba_against_std::FLOAT),
    PIT_XWOBA_AGAINST_7D             FLOAT          AS (VALUE:pit_xwoba_against_7d::FLOAT),
    PIT_XWOBA_AGAINST_14D            FLOAT          AS (VALUE:pit_xwoba_against_14d::FLOAT),
    PIT_XWOBA_AGAINST_30D            FLOAT          AS (VALUE:pit_xwoba_against_30d::FLOAT),
    PIT_XWOBA_AGAINST_STD            FLOAT          AS (VALUE:pit_xwoba_against_std::FLOAT),
    PIT_K_PCT_7D                     FLOAT          AS (VALUE:pit_k_pct_7d::FLOAT),
    PIT_K_PCT_30D                    FLOAT          AS (VALUE:pit_k_pct_30d::FLOAT),
    PIT_K_PCT_STD                    FLOAT          AS (VALUE:pit_k_pct_std::FLOAT),
    PIT_BB_PCT_7D                    FLOAT          AS (VALUE:pit_bb_pct_7d::FLOAT),
    PIT_BB_PCT_30D                   FLOAT          AS (VALUE:pit_bb_pct_30d::FLOAT),
    PIT_BB_PCT_STD                   FLOAT          AS (VALUE:pit_bb_pct_std::FLOAT),
    PIT_HARD_HIT_PCT_7D              FLOAT          AS (VALUE:pit_hard_hit_pct_7d::FLOAT),
    PIT_HARD_HIT_PCT_30D             FLOAT          AS (VALUE:pit_hard_hit_pct_30d::FLOAT),
    PIT_HARD_HIT_PCT_STD             FLOAT          AS (VALUE:pit_hard_hit_pct_std::FLOAT),
    PIT_BARREL_PCT_30D               FLOAT          AS (VALUE:pit_barrel_pct_30d::FLOAT),
    VS_LHP_WOBA_30D                  FLOAT          AS (VALUE:vs_lhp_woba_30d::FLOAT),
    VS_LHP_XWOBA_30D                 FLOAT          AS (VALUE:vs_lhp_xwoba_30d::FLOAT),
    VS_LHP_K_PCT_30D                 FLOAT          AS (VALUE:vs_lhp_k_pct_30d::FLOAT),
    VS_LHP_BB_PCT_30D                FLOAT          AS (VALUE:vs_lhp_bb_pct_30d::FLOAT),
    VS_LHP_HARD_HIT_PCT_30D          FLOAT          AS (VALUE:vs_lhp_hard_hit_pct_30d::FLOAT),
    VS_LHP_SLUGGING_30D              FLOAT          AS (VALUE:vs_lhp_slugging_30d::FLOAT),
    VS_LHP_WOBA_STD                  FLOAT          AS (VALUE:vs_lhp_woba_std::FLOAT),
    VS_LHP_XWOBA_STD                 FLOAT          AS (VALUE:vs_lhp_xwoba_std::FLOAT),
    VS_RHP_WOBA_30D                  FLOAT          AS (VALUE:vs_rhp_woba_30d::FLOAT),
    VS_RHP_XWOBA_30D                 FLOAT          AS (VALUE:vs_rhp_xwoba_30d::FLOAT),
    VS_RHP_K_PCT_30D                 FLOAT          AS (VALUE:vs_rhp_k_pct_30d::FLOAT),
    VS_RHP_BB_PCT_30D                FLOAT          AS (VALUE:vs_rhp_bb_pct_30d::FLOAT),
    VS_RHP_HARD_HIT_PCT_30D          FLOAT          AS (VALUE:vs_rhp_hard_hit_pct_30d::FLOAT),
    VS_RHP_SLUGGING_30D              FLOAT          AS (VALUE:vs_rhp_slugging_30d::FLOAT),
    VS_RHP_WOBA_STD                  FLOAT          AS (VALUE:vs_rhp_woba_std::FLOAT),
    VS_RHP_XWOBA_STD                 FLOAT          AS (VALUE:vs_rhp_xwoba_std::FLOAT),
    BULLPEN_PITCHES_PREV_1D          FLOAT          AS (VALUE:bullpen_pitches_prev_1d::FLOAT),
    BULLPEN_PITCHES_PREV_3D          FLOAT          AS (VALUE:bullpen_pitches_prev_3d::FLOAT),
    BULLPEN_PITCHES_PREV_7D          FLOAT          AS (VALUE:bullpen_pitches_prev_7d::FLOAT),
    PITCHERS_USED_PREV_3D            FLOAT          AS (VALUE:pitchers_used_prev_3d::FLOAT),
    PITCHERS_USED_PREV_7D            FLOAT          AS (VALUE:pitchers_used_prev_7d::FLOAT),
    RELIEVER_APPEARANCES_PREV_3D     FLOAT          AS (VALUE:reliever_appearances_prev_3d::FLOAT),
    RELIEVER_APPEARANCES_PREV_7D     FLOAT          AS (VALUE:reliever_appearances_prev_7d::FLOAT),
    HIGH_LEVERAGE_USED_PREV_2D       NUMBER(38,0)   AS (VALUE:high_leverage_used_prev_2d::NUMBER(38,0)),
    CLOSER_USED_PREV_1D              NUMBER(38,0)   AS (VALUE:closer_used_prev_1d::NUMBER(38,0)),
    CLOSER_USED_PREV_2D              NUMBER(38,0)   AS (VALUE:closer_used_prev_2d::NUMBER(38,0)),
    BULLPEN_IP_PREV_1D               FLOAT          AS (VALUE:bullpen_ip_prev_1d::FLOAT),
    BULLPEN_IP_PREV_2D               FLOAT          AS (VALUE:bullpen_ip_prev_2d::FLOAT),
    PITCHERS_USED_PREV_2D            FLOAT          AS (VALUE:pitchers_used_prev_2d::FLOAT),
    DAYS_REST                        NUMBER(38,0)   AS (VALUE:days_rest::NUMBER(38,0)),
    GAMES_LAST_7D                    NUMBER(38,0)   AS (VALUE:games_last_7d::NUMBER(38,0)),
    GAMES_LAST_14D                   NUMBER(38,0)   AS (VALUE:games_last_14d::NUMBER(38,0)),
    CONSECUTIVE_HOME_GAMES           NUMBER(38,0)   AS (VALUE:consecutive_home_games::NUMBER(38,0)),
    CONSECUTIVE_AWAY_GAMES           NUMBER(38,0)   AS (VALUE:consecutive_away_games::NUMBER(38,0)),
    TZ_CHANGED_FROM_LAST_GAME        BOOLEAN        AS (VALUE:tz_changed_from_last_game::BOOLEAN),
    BP_K_PCT_14D                     FLOAT          AS (VALUE:bp_k_pct_14d::FLOAT),
    BP_BB_PCT_14D                    FLOAT          AS (VALUE:bp_bb_pct_14d::FLOAT),
    BP_XWOBA_AGAINST_14D             FLOAT          AS (VALUE:bp_xwoba_against_14d::FLOAT),
    BP_HARD_HIT_PCT_14D              FLOAT          AS (VALUE:bp_hard_hit_pct_14d::FLOAT),
    BP_WHIFF_RATE_14D                FLOAT          AS (VALUE:bp_whiff_rate_14d::FLOAT),
    BP_INNINGS_PITCHED_14D           FLOAT          AS (VALUE:bp_innings_pitched_14d::FLOAT),
    BP_K_PCT_30D                     FLOAT          AS (VALUE:bp_k_pct_30d::FLOAT),
    BP_BB_PCT_30D                    FLOAT          AS (VALUE:bp_bb_pct_30d::FLOAT),
    BP_XWOBA_AGAINST_30D             FLOAT          AS (VALUE:bp_xwoba_against_30d::FLOAT),
    BP_HARD_HIT_PCT_30D              FLOAT          AS (VALUE:bp_hard_hit_pct_30d::FLOAT),
    BP_WHIFF_RATE_30D                FLOAT          AS (VALUE:bp_whiff_rate_30d::FLOAT),
    BP_INNINGS_PITCHED_30D           FLOAT          AS (VALUE:bp_innings_pitched_30d::FLOAT),
    BP_EB_XWOBA                      FLOAT          AS (VALUE:bp_eb_xwoba::FLOAT),
    BP_EB_UNCERTAINTY                FLOAT          AS (VALUE:bp_eb_uncertainty::FLOAT),
    BP_EB_COVERAGE_PCT               FLOAT          AS (VALUE:bp_eb_coverage_pct::FLOAT),
    OFF_WOBA_7D_MINUS_30D            FLOAT          AS (VALUE:off_woba_7d_minus_30d::FLOAT),
    PIT_XWOBA_7D_MINUS_30D           FLOAT          AS (VALUE:pit_xwoba_7d_minus_30d::FLOAT),
    OFF_GAMES_PLAYED_7D              NUMBER(38,0)   AS (VALUE:off_games_played_7d::NUMBER(38,0)),
    OFF_GAMES_PLAYED_14D             NUMBER(38,0)   AS (VALUE:off_games_played_14d::NUMBER(38,0)),
    OFF_GAMES_PLAYED_30D             NUMBER(38,0)   AS (VALUE:off_games_played_30d::NUMBER(38,0)),
    OFF_GAMES_PLAYED_STD             NUMBER(38,0)   AS (VALUE:off_games_played_std::NUMBER(38,0)),
    ELO_RATING                       FLOAT          AS (VALUE:elo_rating::FLOAT),
    TEAM_OAA_PRIOR_SEASON            FLOAT          AS (VALUE:team_oaa_prior_season::FLOAT),
    TEAM_OAA_BLENDED                 FLOAT          AS (VALUE:team_oaa_blended::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_team_features/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: feature_pregame_team_features from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_team_features TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_expected_lineup  (30 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_expected_lineup (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:GAME_PK::NUMBER(38,0)),
    HOME_AWAY                        VARCHAR        AS (VALUE:home_away::VARCHAR),
    EXPECTED_LINEUP_MASS             FLOAT          AS (VALUE:expected_lineup_mass::FLOAT),
    N_CANDIDATES                     NUMBER(38,0)   AS (VALUE:n_candidates::NUMBER(38,0)),
    EXP_LHB_COUNT                    FLOAT          AS (VALUE:exp_lhb_count::FLOAT),
    EXP_RHB_COUNT                    FLOAT          AS (VALUE:exp_rhb_count::FLOAT),
    EXP_WOBA_30D                     FLOAT          AS (VALUE:exp_woba_30d::FLOAT),
    EXP_XWOBA_30D                    FLOAT          AS (VALUE:exp_xwoba_30d::FLOAT),
    EXP_K_PCT_30D                    FLOAT          AS (VALUE:exp_k_pct_30d::FLOAT),
    EXP_BB_PCT_30D                   FLOAT          AS (VALUE:exp_bb_pct_30d::FLOAT),
    EXP_HARD_HIT_PCT_30D             FLOAT          AS (VALUE:exp_hard_hit_pct_30d::FLOAT),
    EXP_BARREL_PCT_30D               FLOAT          AS (VALUE:exp_barrel_pct_30d::FLOAT),
    EXP_WHIFF_RATE_30D               FLOAT          AS (VALUE:exp_whiff_rate_30d::FLOAT),
    EXP_CHASE_RATE_30D               FLOAT          AS (VALUE:exp_chase_rate_30d::FLOAT),
    EXP_WOBA_STD                     FLOAT          AS (VALUE:exp_woba_std::FLOAT),
    EXP_XWOBA_STD                    FLOAT          AS (VALUE:exp_xwoba_std::FLOAT),
    EXP_K_PCT_STD                    FLOAT          AS (VALUE:exp_k_pct_std::FLOAT),
    EXP_BB_PCT_STD                   FLOAT          AS (VALUE:exp_bb_pct_std::FLOAT),
    EXP_HARD_HIT_PCT_STD             FLOAT          AS (VALUE:exp_hard_hit_pct_std::FLOAT),
    EXP_BARREL_PCT_STD               FLOAT          AS (VALUE:exp_barrel_pct_std::FLOAT),
    EXP_WOBA_VS_LHP                  FLOAT          AS (VALUE:exp_woba_vs_lhp::FLOAT),
    EXP_XWOBA_VS_LHP                 FLOAT          AS (VALUE:exp_xwoba_vs_lhp::FLOAT),
    EXP_K_PCT_VS_LHP                 FLOAT          AS (VALUE:exp_k_pct_vs_lhp::FLOAT),
    EXP_BB_PCT_VS_LHP                FLOAT          AS (VALUE:exp_bb_pct_vs_lhp::FLOAT),
    EXP_HARD_HIT_PCT_VS_LHP          FLOAT          AS (VALUE:exp_hard_hit_pct_vs_lhp::FLOAT),
    EXP_WOBA_VS_RHP                  FLOAT          AS (VALUE:exp_woba_vs_rhp::FLOAT),
    EXP_XWOBA_VS_RHP                 FLOAT          AS (VALUE:exp_xwoba_vs_rhp::FLOAT),
    EXP_K_PCT_VS_RHP                 FLOAT          AS (VALUE:exp_k_pct_vs_rhp::FLOAT),
    EXP_BB_PCT_VS_RHP                FLOAT          AS (VALUE:exp_bb_pct_vs_rhp::FLOAT),
    EXP_HARD_HIT_PCT_VS_RHP          FLOAT          AS (VALUE:exp_hard_hit_pct_vs_rhp::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_expected_lineup/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: feature_pregame_expected_lineup from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_expected_lineup TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_odds_features  (31 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_odds_features (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    GAME_YEAR                        NUMBER(38,0)   AS (VALUE:game_year::NUMBER(38,0)),
    HOME_TEAM                        VARCHAR        AS (VALUE:home_team::VARCHAR),
    AWAY_TEAM                        VARCHAR        AS (VALUE:away_team::VARCHAR),
    HAS_ODDS                         BOOLEAN        AS (VALUE:has_odds::BOOLEAN),
    ODDS_BOOKMAKER_KEY               VARCHAR        AS (VALUE:odds_bookmaker_key::VARCHAR),
    ODDS_INGESTION_TS                TIMESTAMP_NTZ  AS (VALUE:odds_ingestion_ts::TIMESTAMP_NTZ),
    ODDS_HOURS_BEFORE_GAME           NUMBER(38,0)   AS (VALUE:odds_hours_before_game::NUMBER(38,0)),
    HOME_MONEYLINE_AMERICAN          FLOAT          AS (VALUE:HOME_MONEYLINE_AMERICAN::FLOAT),
    AWAY_MONEYLINE_AMERICAN          FLOAT          AS (VALUE:AWAY_MONEYLINE_AMERICAN::FLOAT),
    HOME_MONEYLINE_DECIMAL           FLOAT          AS (VALUE:HOME_MONEYLINE_DECIMAL::FLOAT),
    AWAY_MONEYLINE_DECIMAL           FLOAT          AS (VALUE:AWAY_MONEYLINE_DECIMAL::FLOAT),
    HOME_IMPLIED_PROB                FLOAT          AS (VALUE:HOME_IMPLIED_PROB::FLOAT),
    AWAY_IMPLIED_PROB                FLOAT          AS (VALUE:AWAY_IMPLIED_PROB::FLOAT),
    TOTAL_MARKET_VIG                 FLOAT          AS (VALUE:TOTAL_MARKET_VIG::FLOAT),
    TOTAL_LINE                       FLOAT          AS (VALUE:TOTAL_LINE::FLOAT),
    OVER_AMERICAN                    FLOAT          AS (VALUE:OVER_AMERICAN::FLOAT),
    UNDER_AMERICAN                   FLOAT          AS (VALUE:UNDER_AMERICAN::FLOAT),
    OVER_IMPLIED_PROB                FLOAT          AS (VALUE:OVER_IMPLIED_PROB::FLOAT),
    UNDER_IMPLIED_PROB               FLOAT          AS (VALUE:UNDER_IMPLIED_PROB::FLOAT),
    TOTALS_MARKET_VIG                FLOAT          AS (VALUE:TOTALS_MARKET_VIG::FLOAT),
    HOME_WIN_PROB_CONSENSUS          FLOAT          AS (VALUE:home_win_prob_consensus::FLOAT),
    HOME_WIN_PROB_SHARP              FLOAT          AS (VALUE:home_win_prob_sharp::FLOAT),
    HOME_WIN_PROB_SOFT               FLOAT          AS (VALUE:home_win_prob_soft::FLOAT),
    SHARP_SOFT_ML_DELTA              FLOAT          AS (VALUE:sharp_soft_ml_delta::FLOAT),
    ML_CONSENSUS_STD                 FLOAT          AS (VALUE:ml_consensus_std::FLOAT),
    MARKET_BOOKMAKER_COUNT           NUMBER(38,0)   AS (VALUE:market_bookmaker_count::NUMBER(38,0)),
    TOTAL_LINE_CONSENSUS             FLOAT          AS (VALUE:total_line_consensus::FLOAT),
    TOTAL_LINE_STD                   FLOAT          AS (VALUE:total_line_std::FLOAT),
    OVER_PROB_CONSENSUS              FLOAT          AS (VALUE:over_prob_consensus::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_odds_features/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: feature_pregame_odds_features from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_odds_features TO ROLE CREDENCE_API_RO;

-- ── feature_pregame_sub_model_signals  (94 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_sub_model_signals (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:GAME_PK::NUMBER(38,0)),
    SIDE                             VARCHAR        AS (VALUE:SIDE::VARCHAR),
    RUN_ENV_MU_V4                    FLOAT          AS (VALUE:run_env_mu_v4::FLOAT),
    RUN_ENV_MU_V4_UNCERTAINTY        FLOAT          AS (VALUE:run_env_mu_v4_uncertainty::FLOAT),
    RUN_ENV_MU_V4_AVAILABLE          BOOLEAN        AS (VALUE:run_env_mu_v4_available::BOOLEAN),
    RUN_ENV_DISPERSION_V4            FLOAT          AS (VALUE:run_env_dispersion_v4::FLOAT),
    RUN_ENV_DISPERSION_V4_AVAILABLE  BOOLEAN        AS (VALUE:run_env_dispersion_v4_available::BOOLEAN),
    RUN_ENV_SIGNAL_V4                FLOAT          AS (VALUE:run_env_signal_v4::FLOAT),
    RUN_ENV_SIGNAL_V4_UNCERTAINTY    FLOAT          AS (VALUE:run_env_signal_v4_uncertainty::FLOAT),
    RUN_ENV_SIGNAL_V4_AVAILABLE      BOOLEAN        AS (VALUE:run_env_signal_v4_available::BOOLEAN),
    RUN_ENV_SIGNAL_V3                FLOAT          AS (VALUE:run_env_signal_v3::FLOAT),
    RUN_ENV_SIGNAL_V3_UNCERTAINTY    FLOAT          AS (VALUE:run_env_signal_v3_uncertainty::FLOAT),
    RUN_ENV_SIGNAL_V3_AVAILABLE      BOOLEAN        AS (VALUE:run_env_signal_v3_available::BOOLEAN),
    ENVIRONMENT_VOLATILITY_V3        FLOAT          AS (VALUE:environment_volatility_v3::FLOAT),
    ENVIRONMENT_VOLATILITY_V3_AVAILABLE BOOLEAN        AS (VALUE:environment_volatility_v3_available::BOOLEAN),
    PRED_RUNS_RAW_V1                 FLOAT          AS (VALUE:pred_runs_raw_v1::FLOAT),
    RUNS_INDEX_V1                    FLOAT          AS (VALUE:runs_index_v1::FLOAT),
    PRED_RUNS_RAW_V1_AVAILABLE       BOOLEAN        AS (VALUE:pred_runs_raw_v1_available::BOOLEAN),
    PRED_RUNS_MU_V2                  FLOAT          AS (VALUE:pred_runs_mu_v2::FLOAT),
    PRED_RUNS_DISPERSION_V2          FLOAT          AS (VALUE:pred_runs_dispersion_v2::FLOAT),
    PRED_RUNS_RAW_V2                 FLOAT          AS (VALUE:pred_runs_raw_v2::FLOAT),
    PRED_RUNS_UNCERTAINTY_V2         FLOAT          AS (VALUE:pred_runs_uncertainty_v2::FLOAT),
    PRED_RUNS_MU_V2_AVAILABLE        BOOLEAN        AS (VALUE:pred_runs_mu_v2_available::BOOLEAN),
    STARTER_SUPPRESSION_MU_V1        FLOAT          AS (VALUE:starter_suppression_mu_v1::FLOAT),
    STARTER_SUPPRESSION_SIGMA_V1     FLOAT          AS (VALUE:starter_suppression_sigma_v1::FLOAT),
    STARTER_SUPPRESSION_SIGNAL_V1    FLOAT          AS (VALUE:starter_suppression_signal_v1::FLOAT),
    STARTER_UNCERTAINTY_V1           FLOAT          AS (VALUE:starter_uncertainty_v1::FLOAT),
    STARTER_SUPPRESSION_MU_V1_AVAILABLE BOOLEAN        AS (VALUE:starter_suppression_mu_v1_available::BOOLEAN),
    BULLPEN_AVAILABILITY_INDEX_V1    FLOAT          AS (VALUE:bullpen_availability_index_v1::FLOAT),
    BULLPEN_AVAILABILITY_INDEX_V1_AVAILABLE BOOLEAN        AS (VALUE:bullpen_availability_index_v1_available::BOOLEAN),
    BULLPEN_FATIGUE_SIGNAL_V1        FLOAT          AS (VALUE:bullpen_fatigue_signal_v1::FLOAT),
    BULLPEN_FATIGUE_SIGNAL_V1_AVAILABLE BOOLEAN        AS (VALUE:bullpen_fatigue_signal_v1_available::BOOLEAN),
    BULLPEN_QUALITY_MU_V1            FLOAT          AS (VALUE:bullpen_quality_mu_v1::FLOAT),
    BULLPEN_QUALITY_MU_V1_UNCERTAINTY FLOAT          AS (VALUE:bullpen_quality_mu_v1_uncertainty::FLOAT),
    BULLPEN_QUALITY_MU_V1_AVAILABLE  BOOLEAN        AS (VALUE:bullpen_quality_mu_v1_available::BOOLEAN),
    BULLPEN_QUALITY_SIGMA_V1         FLOAT          AS (VALUE:bullpen_quality_sigma_v1::FLOAT),
    BULLPEN_QUALITY_SIGMA_V1_AVAILABLE BOOLEAN        AS (VALUE:bullpen_quality_sigma_v1_available::BOOLEAN),
    BULLPEN_QUALITY_SIGNAL_V1        FLOAT          AS (VALUE:bullpen_quality_signal_v1::FLOAT),
    BULLPEN_QUALITY_SIGNAL_V1_UNCERTAINTY FLOAT          AS (VALUE:bullpen_quality_signal_v1_uncertainty::FLOAT),
    BULLPEN_QUALITY_SIGNAL_V1_AVAILABLE BOOLEAN        AS (VALUE:bullpen_quality_signal_v1_available::BOOLEAN),
    HIGH_LEVERAGE_AVAILABILITY_PROXY_V1 FLOAT          AS (VALUE:high_leverage_availability_proxy_v1::FLOAT),
    HIGH_LEVERAGE_AVAILABILITY_PROXY_V1_AVAILABLE BOOLEAN        AS (VALUE:high_leverage_availability_proxy_v1_available::BOOLEAN),
    LATE_GAME_VOLATILITY_SIGNAL_V1   FLOAT          AS (VALUE:late_game_volatility_signal_v1::FLOAT),
    LATE_GAME_VOLATILITY_SIGNAL_V1_AVAILABLE BOOLEAN        AS (VALUE:late_game_volatility_signal_v1_available::BOOLEAN),
    BULLPEN_MU_V2                    FLOAT          AS (VALUE:bullpen_mu_v2::FLOAT),
    BULLPEN_MU_V2_UNCERTAINTY        FLOAT          AS (VALUE:bullpen_mu_v2_uncertainty::FLOAT),
    BULLPEN_MU_V2_AVAILABLE          BOOLEAN        AS (VALUE:bullpen_mu_v2_available::BOOLEAN),
    BULLPEN_DISPERSION_V2            FLOAT          AS (VALUE:bullpen_dispersion_v2::FLOAT),
    BULLPEN_DISPERSION_V2_AVAILABLE  BOOLEAN        AS (VALUE:bullpen_dispersion_v2_available::BOOLEAN),
    BULLPEN_FATIGUE_ADJUSTED_MU_V2   FLOAT          AS (VALUE:bullpen_fatigue_adjusted_mu_v2::FLOAT),
    BULLPEN_FATIGUE_ADJUSTED_MU_V2_UNCERTAINTY FLOAT          AS (VALUE:bullpen_fatigue_adjusted_mu_v2_uncertainty::FLOAT),
    BULLPEN_FATIGUE_ADJUSTED_MU_V2_AVAILABLE BOOLEAN        AS (VALUE:bullpen_fatigue_adjusted_mu_v2_available::BOOLEAN),
    BULLPEN_UNCERTAINTY_V2           FLOAT          AS (VALUE:bullpen_uncertainty_v2::FLOAT),
    BULLPEN_UNCERTAINTY_V2_AVAILABLE BOOLEAN        AS (VALUE:bullpen_uncertainty_v2_available::BOOLEAN),
    MATCHUP_ADVANTAGE_MU_V1          FLOAT          AS (VALUE:matchup_advantage_mu_v1::FLOAT),
    MATCHUP_ADVANTAGE_MU_V1_UNCERTAINTY FLOAT          AS (VALUE:matchup_advantage_mu_v1_uncertainty::FLOAT),
    MATCHUP_ADVANTAGE_MU_V1_AVAILABLE BOOLEAN        AS (VALUE:matchup_advantage_mu_v1_available::BOOLEAN),
    MATCHUP_ADVANTAGE_SIGMA_V1       FLOAT          AS (VALUE:matchup_advantage_sigma_v1::FLOAT),
    MATCHUP_ADVANTAGE_SIGMA_V1_AVAILABLE BOOLEAN        AS (VALUE:matchup_advantage_sigma_v1_available::BOOLEAN),
    MATCHUP_VOLATILITY_SIGNAL_V1     FLOAT          AS (VALUE:matchup_volatility_signal_v1::FLOAT),
    MATCHUP_VOLATILITY_SIGNAL_V1_AVAILABLE BOOLEAN        AS (VALUE:matchup_volatility_signal_v1_available::BOOLEAN),
    MATCHUP_SOFT_VS_HARD_DELTA_V1    FLOAT          AS (VALUE:matchup_soft_vs_hard_delta_v1::FLOAT),
    MATCHUP_SOFT_VS_HARD_DELTA_V1_AVAILABLE BOOLEAN        AS (VALUE:matchup_soft_vs_hard_delta_v1_available::BOOLEAN),
    MATCHUP_K_PRESSURE_SIGNAL_V1     FLOAT          AS (VALUE:matchup_k_pressure_signal_v1::FLOAT),
    MATCHUP_K_PRESSURE_SIGNAL_V1_AVAILABLE BOOLEAN        AS (VALUE:matchup_k_pressure_signal_v1_available::BOOLEAN),
    MATCHUP_POWER_SIGNAL_V1          FLOAT          AS (VALUE:matchup_power_signal_v1::FLOAT),
    MATCHUP_POWER_SIGNAL_V1_AVAILABLE BOOLEAN        AS (VALUE:matchup_power_signal_v1_available::BOOLEAN),
    MATCHUP_CELL_POSTERIOR_SOURCE_V1 FLOAT          AS (VALUE:matchup_cell_posterior_source_v1::FLOAT),
    MATCHUP_CELL_POSTERIOR_SOURCE_V1_AVAILABLE BOOLEAN        AS (VALUE:matchup_cell_posterior_source_v1_available::BOOLEAN),
    STARTER_IP_MU_V1                 FLOAT          AS (VALUE:starter_ip_mu_v1::FLOAT),
    STARTER_IP_DISPERSION_V1         FLOAT          AS (VALUE:starter_ip_dispersion_v1::FLOAT),
    STARTER_IP_SIGNAL_V1             FLOAT          AS (VALUE:starter_ip_signal_v1::FLOAT),
    STARTER_IP_P80_OUTS_V1           FLOAT          AS (VALUE:starter_ip_p80_outs_v1::FLOAT),
    STARTER_IP_P20_OUTS_V1           FLOAT          AS (VALUE:starter_ip_p20_outs_v1::FLOAT),
    STARTER_IP_UNCERTAINTY_V1        FLOAT          AS (VALUE:starter_ip_uncertainty_v1::FLOAT),
    STARTER_IP_IS_BULK_USAGE_V1      BOOLEAN        AS (VALUE:starter_ip_is_bulk_usage_v1::BOOLEAN),
    STARTER_IP_MU_V1_AVAILABLE       BOOLEAN        AS (VALUE:starter_ip_mu_v1_available::BOOLEAN),
    ENV_LEAGUE_STATE_MU_V1           FLOAT          AS (VALUE:env_league_state_mu_v1::FLOAT),
    ENV_LEAGUE_STATE_MU_V1_UNCERTAINTY FLOAT          AS (VALUE:env_league_state_mu_v1_uncertainty::FLOAT),
    ENV_LEAGUE_STATE_MU_V1_AVAILABLE BOOLEAN        AS (VALUE:env_league_state_mu_v1_available::BOOLEAN),
    ENV_LEAGUE_STATE_SIGMA_V1        FLOAT          AS (VALUE:env_league_state_sigma_v1::FLOAT),
    ENV_LEAGUE_STATE_SIGMA_V1_AVAILABLE BOOLEAN        AS (VALUE:env_league_state_sigma_v1_available::BOOLEAN),
    ENV_TEAM_OFF_STATE_V1            FLOAT          AS (VALUE:env_team_off_state_v1::FLOAT),
    ENV_TEAM_OFF_STATE_V1_AVAILABLE  BOOLEAN        AS (VALUE:env_team_off_state_v1_available::BOOLEAN),
    ENV_TEAM_PITCH_STATE_V1          FLOAT          AS (VALUE:env_team_pitch_state_v1::FLOAT),
    ENV_TEAM_PITCH_STATE_V1_AVAILABLE BOOLEAN        AS (VALUE:env_team_pitch_state_v1_available::BOOLEAN),
    DEFENSE_QUALITY_MU_V1            FLOAT          AS (VALUE:defense_quality_mu_v1::FLOAT),
    DEFENSE_QUALITY_MU_V1_AVAILABLE  BOOLEAN        AS (VALUE:defense_quality_mu_v1_available::BOOLEAN),
    DEFENSE_QUALITY_OAA_Z_V1         FLOAT          AS (VALUE:defense_quality_oaa_z_v1::FLOAT),
    DEFENSE_QUALITY_OAA_Z_V1_AVAILABLE BOOLEAN        AS (VALUE:defense_quality_oaa_z_v1_available::BOOLEAN),
    DEFENSE_QUALITY_SPRINT_Z_V1      FLOAT          AS (VALUE:defense_quality_sprint_z_v1::FLOAT),
    DEFENSE_QUALITY_SPRINT_Z_V1_AVAILABLE BOOLEAN        AS (VALUE:defense_quality_sprint_z_v1_available::BOOLEAN),
    TEST_SIGNAL_V1                   FLOAT          AS (VALUE:test_signal_v1::FLOAT),
    TEST_SIGNAL_V1_AVAILABLE         BOOLEAN        AS (VALUE:test_signal_v1_available::BOOLEAN)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/feature_pregame_sub_model_signals/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: feature_pregame_sub_model_signals from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.feature_pregame_sub_model_signals TO ROLE CREDENCE_API_RO;

-- ── int_bullpen_ali_by_season  (4 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.int_bullpen_ali_by_season (
    SEASON                           NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    PITCHER_ID                       VARCHAR        AS (VALUE:pitcher_id::VARCHAR),
    APPEARANCES                      NUMBER(38,0)   AS (VALUE:appearances::NUMBER(38,0)),
    NORMALIZED_ALI                   FLOAT          AS (VALUE:normalized_ali::FLOAT)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/int_bullpen_ali_by_season/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: int_bullpen_ali_by_season from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.int_bullpen_ali_by_season TO ROLE CREDENCE_API_RO;

-- ── eb_bullpen_posteriors  (17 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.eb_bullpen_posteriors (
    GAME_PK                          VARCHAR        AS (VALUE:game_pk::VARCHAR),
    PITCHER_ID                       VARCHAR        AS (VALUE:pitcher_id::VARCHAR),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    SEASON                           NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    PITCHING_TEAM                    VARCHAR        AS (VALUE:pitching_team::VARCHAR),
    LEVERAGE_ROLE                    VARCHAR        AS (VALUE:leverage_role::VARCHAR),
    AGE_BAND                         VARCHAR        AS (VALUE:age_band::VARCHAR),
    OUTS_IN_GAME                     FLOAT          AS (VALUE:outs_in_game::FLOAT),
    CURRENT_SEASON_BF                NUMBER(38,0)   AS (VALUE:current_season_bf::NUMBER(38,0)),
    EB_DATA_SOURCE                   VARCHAR        AS (VALUE:eb_data_source::VARCHAR),
    ROLE_CHANGED                     BOOLEAN        AS (VALUE:role_changed::BOOLEAN),
    EB_XWOBA_AGAINST                 FLOAT          AS (VALUE:eb_xwoba_against::FLOAT),
    EB_K_PCT                         FLOAT          AS (VALUE:eb_k_pct::FLOAT),
    EB_BB_PCT                        FLOAT          AS (VALUE:eb_bb_pct::FLOAT),
    EB_XWOBA_UNCERTAINTY             FLOAT          AS (VALUE:eb_xwoba_uncertainty::FLOAT),
    FIT_DATE                         DATE           AS (VALUE:fit_date::DATE),
    RUN_ID                           VARCHAR        AS (VALUE:run_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/eb_bullpen_posteriors/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: eb_bullpen_posteriors from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.eb_bullpen_posteriors TO ROLE CREDENCE_API_RO;

-- ── eb_bullpen_team_posteriors  (10 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.eb_bullpen_team_posteriors (
    GAME_PK                          NUMBER(38,0)   AS (VALUE:game_pk::NUMBER(38,0)),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    SEASON                           NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    TEAM                             VARCHAR        AS (VALUE:team::VARCHAR),
    TEAM_EB_BULLPEN_XWOBA            FLOAT          AS (VALUE:team_eb_bullpen_xwoba::FLOAT),
    TEAM_EB_BULLPEN_UNCERTAINTY      FLOAT          AS (VALUE:team_eb_bullpen_uncertainty::FLOAT),
    N_RELIEVERS                      NUMBER(38,0)   AS (VALUE:n_relievers::NUMBER(38,0)),
    N_PRIOR_ONLY                     FLOAT          AS (VALUE:n_prior_only::FLOAT),
    FIT_DATE                         DATE           AS (VALUE:fit_date::DATE),
    RUN_ID                           VARCHAR        AS (VALUE:run_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/eb_bullpen_team_posteriors/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: eb_bullpen_team_posteriors from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.eb_bullpen_team_posteriors TO ROLE CREDENCE_API_RO;

-- ── eb_starter_posteriors  (18 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.eb_starter_posteriors (
    GAME_PK                          VARCHAR        AS (VALUE:game_pk::VARCHAR),
    SIDE                             VARCHAR        AS (VALUE:side::VARCHAR),
    PITCHER_ID                       VARCHAR        AS (VALUE:pitcher_id::VARCHAR),
    SEASON                           NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    AGE_BAND                         VARCHAR        AS (VALUE:age_band::VARCHAR),
    CURRENT_SEASON_BF                NUMBER(38,0)   AS (VALUE:current_season_bf::NUMBER(38,0)),
    CURRENT_SEASON_STARTS            NUMBER(38,0)   AS (VALUE:current_season_starts::NUMBER(38,0)),
    EB_DATA_SOURCE                   VARCHAR        AS (VALUE:eb_data_source::VARCHAR),
    EB_XWOBA_AGAINST                 FLOAT          AS (VALUE:eb_xwoba_against::FLOAT),
    EB_K_PCT                         FLOAT          AS (VALUE:eb_k_pct::FLOAT),
    EB_BB_PCT                        FLOAT          AS (VALUE:eb_bb_pct::FLOAT),
    EB_XWOBA_UNCERTAINTY             FLOAT          AS (VALUE:eb_xwoba_uncertainty::FLOAT),
    EB_XWOBA_AGAINST_SEQUENTIAL      FLOAT          AS (VALUE:eb_xwoba_against_sequential::FLOAT),
    POSTERIOR_SOURCE                 VARCHAR        AS (VALUE:posterior_source::VARCHAR),
    PRIOR_AGE_DAYS                   NUMBER(38,0)   AS (VALUE:prior_age_days::NUMBER(38,0)),
    FIT_DATE                         DATE           AS (VALUE:fit_date::DATE),
    RUN_ID                           VARCHAR        AS (VALUE:run_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/eb_starter_posteriors/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: eb_starter_posteriors from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.eb_starter_posteriors TO ROLE CREDENCE_API_RO;

-- ── eb_batter_posteriors_raw  (17 columns) ──
CREATE OR REPLACE EXTERNAL TABLE baseball_data.lakehouse_ext.eb_batter_posteriors_raw (
    GAME_PK                          VARCHAR        AS (VALUE:game_pk::VARCHAR),
    BATTING_SLOT                     NUMBER(38,0)   AS (VALUE:batting_slot::NUMBER(38,0)),
    BATTER_ID                        VARCHAR        AS (VALUE:batter_id::VARCHAR),
    SEASON                           NUMBER(38,0)   AS (VALUE:season::NUMBER(38,0)),
    GAME_DATE                        DATE           AS (VALUE:game_date::DATE),
    EB_DATA_SOURCE                   VARCHAR        AS (VALUE:eb_data_source::VARCHAR),
    EB_WOBA                          FLOAT          AS (VALUE:eb_woba::FLOAT),
    EB_K_PCT                         FLOAT          AS (VALUE:eb_k_pct::FLOAT),
    EB_BB_PCT                        FLOAT          AS (VALUE:eb_bb_pct::FLOAT),
    EB_ISO                           FLOAT          AS (VALUE:eb_iso::FLOAT),
    EB_WOBA_UNCERTAINTY              FLOAT          AS (VALUE:eb_woba_uncertainty::FLOAT),
    PA_WEIGHT                        FLOAT          AS (VALUE:pa_weight::FLOAT),
    EB_WOBA_SEQUENTIAL               FLOAT          AS (VALUE:eb_woba_sequential::FLOAT),
    POSTERIOR_SOURCE                 VARCHAR        AS (VALUE:posterior_source::VARCHAR),
    PRIOR_AGE_DAYS                   NUMBER(38,0)   AS (VALUE:prior_age_days::NUMBER(38,0)),
    FIT_DATE                         DATE           AS (VALUE:fit_date::DATE),
    RUN_ID                           VARCHAR        AS (VALUE:run_id::VARCHAR)
)
WITH LOCATION = @baseball_data.lakehouse_ext.s3_lakehouse/eb_batter_posteriors_raw/
FILE_FORMAT = baseball_data.lakehouse_ext.parquet_snappy
AUTO_REFRESH = FALSE
COMMENT = 'E11.1-W8a: eb_batter_posteriors_raw from S3 lakehouse parquet (upstream feature layer + EB posteriors)';
GRANT SELECT ON EXTERNAL TABLE baseball_data.lakehouse_ext.eb_batter_posteriors_raw TO ROLE CREDENCE_API_RO;

-- =============================================================================
-- ⚠️ INC-19 DROP+rebuild — run ONCE at cutover for the 5 EB INCREMENTALS so the
-- native Snowflake tables adopt the FLOAT column types from the external table.
-- (dbt --full-refresh MERGEs, it does NOT DROP — so DROP explicitly here, then let
-- the next `dbtf build --select <model>` recreate from lakehouse_ext.<model>.)
-- =============================================================================
DROP TABLE IF EXISTS baseball_data.betting.int_bullpen_ali_by_season;
DROP TABLE IF EXISTS baseball_data.betting.eb_bullpen_posteriors;
DROP TABLE IF EXISTS baseball_data.betting.eb_bullpen_team_posteriors;
DROP TABLE IF EXISTS baseball_data.betting.eb_starter_posteriors;
DROP TABLE IF EXISTS baseball_data.betting.eb_batter_posteriors_raw;

-- Verification:
-- SELECT count(*) FROM baseball_data.lakehouse_ext.stg_statsapi_starter_snapshots;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_starter_status;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_park_status;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_park_features;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_team_features;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_expected_lineup;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_odds_features;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.feature_pregame_sub_model_signals;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.int_bullpen_ali_by_season;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.eb_bullpen_posteriors;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.eb_bullpen_team_posteriors;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.eb_starter_posteriors;
-- SELECT count(*) FROM baseball_data.lakehouse_ext.eb_batter_posteriors_raw;
