"""Guards the K-projection serving self-heal (2026-07-03).

The daily sub-model signal ops only score `_recent_completed_dates()` (T-2/T-1); TODAY's
`starter_ip_v1` signal is never generated by the pipeline, yet `write_pitcher_k_projections.py`
hard-depends on it (it joins `starter_ip_signals` and skips starters with a null `starter_ip_mu`).
`_ensure_starter_ip_signal` closes that gap: it generates today's signal on demand when absent,
so both the daily op and the hourly host cron (which both invoke this script) self-heal.

Pure/mocked — no Snowflake, no subprocess. Asserts the generate-only-when-missing contract, the
env→schema resolution, and fail-soft behaviour (a bad presence check or a failed generation must
never raise out of this WARN-tier writer).
"""
import scripts.write_pitcher_k_projections as wk

_DAY = "2026-07-03"


class _Cur:
    def __init__(self, count):
        self._count = count
        self.executed = None

    def execute(self, sql, params=None):
        self.executed = (sql, params)

    def fetchone(self):
        return (self._count,)


class _Conn:
    def __init__(self, count):
        self._cur = _Cur(count)

    def cursor(self):
        return self._cur

    def close(self):
        pass


def _patch_conn(monkeypatch, count=0, raises=False):
    import betting_ml.utils.data_loader as dl

    def _factory(*a, **k):
        if raises:
            raise RuntimeError("snowflake down")
        return _Conn(count)

    monkeypatch.setattr(dl, "get_snowflake_connection", _factory)


def _patch_run(monkeypatch, returncode=0):
    calls = []

    class _Result:
        def __init__(self):
            self.returncode = returncode
            self.stderr = "boom" if returncode else ""
            self.stdout = ""

    def _fake_run(cmd, **kw):
        calls.append(cmd)
        return _Result()

    monkeypatch.setattr(wk.subprocess, "run", _fake_run)
    return calls


def test_generates_when_signal_missing(monkeypatch):
    """Zero rows for the date → the generator is invoked with the right --date/--env."""
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, count=0)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)

    assert len(calls) == 1, "missing signal must trigger exactly one generation"
    cmd = calls[0]
    assert str(wk._STARTER_IP_GEN) in cmd
    assert "--date" in cmd and cmd[cmd.index("--date") + 1] == _DAY
    assert "--env" in cmd and cmd[cmd.index("--env") + 1] == "prod"


def test_skips_generation_when_signal_present(monkeypatch):
    """Rows already exist → no generation (idempotent, cheap hourly re-runs)."""
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, count=25)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)

    assert calls == [], "present signal must NOT be regenerated"


def test_env_defaults_to_dev_without_target_env(monkeypatch):
    """Dev isolation: without TARGET_ENV=prod the generation targets the dev schema."""
    monkeypatch.delenv("TARGET_ENV", raising=False)
    _patch_conn(monkeypatch, count=0)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)

    assert calls and calls[0][calls[0].index("--env") + 1] == "dev"


def test_presence_check_failure_falls_through_to_generation(monkeypatch):
    """A flaky Snowflake presence check must not abort — treat as missing and generate."""
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, raises=True)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)  # must not raise

    assert len(calls) == 1


def test_generation_failure_is_fail_soft(monkeypatch):
    """A non-zero generator exit is logged, not raised (WARN-tier writer never blocks serving)."""
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, count=0)
    _patch_run(monkeypatch, returncode=1)

    wk._ensure_starter_ip_signal(_DAY)  # must not raise
