"""Guards the K-projection serving self-heal (2026-07-03).

The daily sub-model signal ops only score `_recent_completed_dates()` (T-2/T-1); TODAY's
`starter_ip_v1` signal is never generated by the pipeline, yet `write_pitcher_k_projections.py`
hard-depends on it (it joins `starter_ip_signals` and skips starters with a null `starter_ip_mu`).
`_ensure_starter_ip_signal` closes that gap: it generates today's signal on demand when absent,
so both the daily op and the hourly host cron (which both invoke this script) self-heal.

E11.20 phase-2a (2026-07-20): the PRESENCE CHECK moved from Snowflake to the S3 lakehouse mirror
(so the steady state opens no warehouse session), and a successful generation is now followed by a
RE-MIRROR back to S3 — without it the signal would exist only in Snowflake and the writer's own
read would still see nothing (the INC-25 ordering rule). These tests patch the DuckDB helper
instead of the Snowflake connector, and assert the mirror step.

Pure/mocked — no S3, no subprocess. Asserts the generate-only-when-missing contract, the
env→schema resolution, and fail-soft behaviour (a bad presence check or a failed generation must
never raise out of this WARN-tier writer).
"""
import scripts.write_pitcher_k_projections as wk

_DAY = "2026-07-03"


class _Conn:
    """Minimal stand-in for the DuckDB connection the presence check now uses.

    The self-heal issues TWO counts: `present` (starter_ip_signals rows for today) and
    `expected` (starters WITH pregame features today = the generator's own input universe).
    Return the right one per query so the regen-on-incomplete branch is exercised.
    """

    def __init__(self, present, expected):
        self._present = present
        self._expected = expected
        self._last_sql = ""

    def execute(self, sql, params=None):
        self._last_sql = sql
        return self

    def fetchone(self):
        if "feature_pregame_starter_features" in self._last_sql:
            return (self._expected,)
        return (self._present,)

    def close(self):
        pass


def _patch_conn(monkeypatch, present=0, expected=30, raises=False):
    def _factory(*a, **k):
        if raises:
            raise RuntimeError("lakehouse read failed")
        return _Conn(present, expected)

    monkeypatch.setattr(wk, "_duck_lakehouse", _factory)


def _patch_run(monkeypatch, returncode=0):
    calls = []

    class _Result:
        def __init__(self):
            self.returncode = returncode
            self.stderr = "boom" if returncode else ""
            self.stdout = ""

    def _fake_run(cmd, **kw):
        calls.append(cmd)
        return _Result()

    monkeypatch.setattr(wk.subprocess, "run", _fake_run)
    return calls


def test_generates_when_signal_missing(monkeypatch):
    """Zero rows but features ready → the generator is invoked with the right --date/--env."""
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, present=0, expected=30)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)

    assert len(calls) == 2, "missing signal must trigger one generation + one S3 re-mirror"
    cmd = calls[0]
    assert str(wk._STARTER_IP_GEN) in cmd
    assert "--date" in cmd and cmd[cmd.index("--date") + 1] == _DAY
    assert "--env" in cmd and cmd[cmd.index("--env") + 1] == "prod"
    # The generator reads its feature sources from S3 too — only its MERGE write is Snowflake.
    assert "--s3" in cmd
    # INC-25: without the re-mirror the signal lands in Snowflake only and the writer's own
    # lakehouse read would still find nothing, so scoring would keep skipping.
    mirror = calls[1]
    assert str(wk._STARTER_IP_MIRROR) in mirror
    assert "--table" in mirror and mirror[mirror.index("--table") + 1] == wk._STARTER_IP_TABLE


def test_regenerates_when_coverage_incomplete(monkeypatch):
    """⭐ The 2026-07-24 cost-race fix: a PARTIAL early generation must NOT freeze coverage.

    present=1 (only the afternoon starter scored) but expected=30 (all of today's starters now
    have pregame features) → the self-heal must regenerate to fill the gap, not skip because a
    single stale row exists (the old `if present:` bug that left /props showing one pitcher).
    """
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, present=1, expected=30)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)

    assert len(calls) == 2, "incomplete coverage (present<expected) must regenerate, not skip"


def test_skips_generation_when_signal_complete(monkeypatch):
    """Coverage complete (present >= expected) → no generation (idempotent, cheap re-runs)."""
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, present=30, expected=30)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)

    assert calls == [], "complete signal must NOT be regenerated"


def test_skips_when_no_features_yet(monkeypatch):
    """No starters have pregame features yet (expected==0) → nothing to generate; no SF touch.

    Guards against a wasted Snowflake self-heal (and a per-run loop) when there is genuinely no
    input universe — e.g. a very early-morning run before any features are built.
    """
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, present=0, expected=0)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)

    assert calls == [], "no input universe → must not touch Snowflake"


def test_env_defaults_to_dev_without_target_env(monkeypatch):
    """Dev isolation: without TARGET_ENV=prod the generation targets the dev schema."""
    monkeypatch.delenv("TARGET_ENV", raising=False)
    _patch_conn(monkeypatch, present=0, expected=30)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)

    assert calls and calls[0][calls[0].index("--env") + 1] == "dev"


def test_presence_check_failure_falls_through_to_generation(monkeypatch):
    """A flaky lakehouse presence check must not abort — treat as incomplete and generate."""
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, raises=True)
    calls = _patch_run(monkeypatch, returncode=0)

    wk._ensure_starter_ip_signal(_DAY)  # must not raise

    assert len(calls) == 2


def test_generation_failure_is_fail_soft(monkeypatch):
    """A non-zero generator exit is logged, not raised (WARN-tier writer never blocks serving)."""
    monkeypatch.setenv("TARGET_ENV", "prod")
    _patch_conn(monkeypatch, present=0, expected=30)
    calls = _patch_run(monkeypatch, returncode=1)

    wk._ensure_starter_ip_signal(_DAY)  # must not raise

    # A failed generation must NOT go on to mirror — that would overwrite the S3 parquet from a
    # Snowflake table the generator just failed to update.
    assert len(calls) == 1
