"""test_nf_inc_0917b_wire_shape.py — the weekly contract must reach the WIRE, not just validate.

⛔⛔ THE DEFECT THESE GUARD, IN ONE SENTENCE: `NflWeeklyManifest.model_validate(manifest)` ran on
every weekly build, passed every time, and `framing` still reached nobody — because the validated
object was DISCARDED and the raw input dict was written. `/fantasy/weekly` then died on
`framing.interval_note` for 758 minutes (NF-INC-0917).

⭐ A DEFAULTED FIELD IS THE DANGEROUS SHAPE, and that is the generalisation worth keeping: a field
declared REQUIRED WITH A DEFAULT can NEVER fail validation by being absent. So "it validates" says
nothing at all about whether it is on the wire, and the two questions need two instruments —
`model_validate` for the first, `missing_declared_fields` for the second.

⭐⭐ WHY THESE ASSERT ON SERVED BYTES RATHER THAN ON MODELS. NF-INC-0917's own finding was that the
E2E assertions ALREADY EXISTED — test 8 already read both framing notes — and the suite was green
through the entire outage, because every weekly fixture is generated by the SHIPPING WRITER and the
shipping writer always emits `framing`. A guard is only as good as the states its fixtures can
reach. So every case here is driven by one of two writer-independent payloads:

  * `_HISTORICAL_MANIFEST` — the REAL published week-2 blob, the one that actually took the page
    down. Nothing synthetic can be this authoritative, and it cannot drift toward the happy path
    because it is a recording rather than a construction.
  * `_degenerate(...)` — a key DELETED from a real payload (PR #1143's method), never a second
    hand-written fixture that would drift from the writer.

⚠️ NON-VACUITY FIRST in both directions: `test_the_historical_manifest_really_is_defective` fails
if the recording ever stops carrying the defect, so the refusal cases below cannot pass for the
wrong reason (NF1.7(a)).
"""
from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace

import pytest

from app.backend.models import nfl_weekly as C
from app.backend.services import entitlement
from betting_ml.tests.test_nf_c6_ph2_weekly_contract import _call

_REPO = Path(__file__).resolve().parents[2]
_ABL = _REPO / "quant_sports_intel_models/football/nfl/fantasy/ablation_results"

#: The manifest that WAS published for 2026 week 2 — the payload of the outage, recorded.
_HISTORICAL_MANIFEST = json.loads((_ABL / "nf_wk_td1_before_week2_manifest.json").read_text())
#: Its players payload — the PRE-TD generation (four component fields null on every projected row).
_HISTORICAL_PLAYERS = json.loads((_ABL / "nf_wk_td1_before_week2_players.json").read_text())

#: The nine defaulted manifest fields the live wire was missing on 2026-09-16, and the four inside
#: `lineage`. Written down so a change to the contract shows up here as a diff to argue about
#: rather than as a silently shrinking assertion.
_ABSENT_ON_THE_WIRE = (
    "manifest.season_type", "manifest.scoring_system_id",
    "manifest.interval_lo_level", "manifest.interval_hi_level",
    "manifest.ros_basis", "manifest.ros_sigma_lo_level", "manifest.ros_sigma_hi_level",
    "manifest.positions", "manifest.framing",
    "manifest.lineage.model_family", "manifest.lineage.target",
    "manifest.lineage.component_head_status", "manifest.lineage.scoring_contract_version",
)


def _degenerate(blob: dict, *keys: str) -> dict:
    """A real payload with keys REMOVED — the only fixture shape that can reach the broken branch.

    ⛔ Deliberately not a second hand-written fixture: one written beside the shipping writer drifts
    from it silently, and then the guard tests a payload nothing produces (NF-C0e).
    """
    out = json.loads(json.dumps(blob))
    for k in keys:
        out.pop(k, None)
    return out


def _built(manifest: dict, payload: dict | None = None, current: dict | None = None) -> dict:
    """A `built` dict shaped exactly as `run_weekly_serving.build` returns one."""
    return {
        "target": SimpleNamespace(season=manifest.get("season", 2026), week=manifest.get("week", 2)),
        "manifest": manifest,
        "payload": payload if payload is not None else _HISTORICAL_PLAYERS,
        "current": current if current is not None else {
            "season": 2026, "week": 2, "generated_at": "2026-09-15T15:32:59+00:00",
            "manifest_key": C.weekly_manifest_key(2026, 2),
            "players_key": C.weekly_players_key(2026, 2),
        },
        "diagnostics": {},
    }


@pytest.fixture()
def runner():
    from quant_sports_intel_models.football.nfl.fantasy import run_weekly_serving
    return run_weekly_serving


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 1. NON-VACUITY — the recording still carries the defect it is here to represent
# ══════════════════════════════════════════════════════════════════════════════════════════════

def test_the_historical_manifest_really_is_defective():
    """⛔ IF THIS GOES GREEN-WITH-ZERO, EVERY REFUSAL BELOW IS VACUOUS.

    The whole method here is "drive the guards with the blob that actually broke production". That
    only means something while the recording is still the broken one — a fixture quietly repaired
    (or regenerated by the shipping writer) would turn every case below into a test of the happy
    path, which is precisely the failure NF-INC-0917 diagnosed in the E2E suite.
    """
    missing = C.missing_declared_fields(_HISTORICAL_MANIFEST, C.NflWeeklyManifest, where="manifest")
    assert set(missing) == set(_ABSENT_ON_THE_WIRE), (
        "the recorded week-2 manifest no longer carries the exact defect this file is built on: "
        f"unexpected={sorted(set(missing) - set(_ABSENT_ON_THE_WIRE))} "
        f"no-longer-missing={sorted(set(_ABSENT_ON_THE_WIRE) - set(missing))}"
    )


def test_the_defect_is_invisible_to_the_check_the_builder_was_running():
    """⭐ THE MECHANISM, ASSERTED RATHER THAN NARRATED — and the reason this story exists.

    `model_validate` PASSES on the blob that took the page down. That is not a bug in pydantic: a
    defaulted field cannot fail validation by being absent, because the default lands on the object
    being built. The builder's guard was answering a question nobody needed answered.
    """
    C.NflWeeklyManifest.model_validate(_HISTORICAL_MANIFEST)  # passes — that IS the finding
    assert C.missing_declared_fields(_HISTORICAL_MANIFEST, C.NflWeeklyManifest), (
        "the two instruments now agree, which means one of them has stopped discriminating"
    )


def test_an_absent_object_throws_where_an_absent_scalar_only_renders_undefined():
    """⭐ WHY THIS WAS ONE CRASH AND NOT A CASCADE — a property of TYPE, not of care.

    Nine declared fields were missing and exactly one took the route down. The discriminator is not
    which field anyone happened to read: it is that `framing` is the ONLY object-valued defaulted
    field on this contract, and an absent object throws on its first property read while an absent
    scalar renders `undefined`. Pinned because it ranks the remaining risk on any contract like this
    one — and because `scoring_system_id` is missing from the players payload today under exactly
    the same shape, with a REQUIRED mirror in `frontend/lib/nfl-weekly.ts`.
    """
    object_valued = {
        name for name, f in C.NflWeeklyManifest.model_fields.items()
        if not f.is_required() and C._nested_model(f.annotation) is not None
    }
    assert object_valued == {"framing"}, (
        "the set of object-valued DEFAULTED manifest fields has changed. Each new member is a "
        f"latent hard crash on any client that dereferences it unguarded: {sorted(object_valued)}"
    )


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 2. THE BUILDER HALF — the write path refuses what validation waved through
# ══════════════════════════════════════════════════════════════════════════════════════════════

def test_the_write_path_refuses_the_manifest_that_actually_shipped(runner, tmp_path):
    from quant_sports_intel_models.football.nfl.fantasy import weekly_serving as WS

    with pytest.raises(WS.WeeklyServingError) as e:
        runner.stage(_built(_HISTORICAL_MANIFEST), tmp_path)
    assert "framing" in str(e.value)


def test_the_dry_run_refuses_too_not_only_a_real_publish(runner):
    """⚠️ A `--dry-run` that skips the gate rehearses a different program — and the dry run is the
    one an operator uses to convince themselves a publish is safe (the NF-INJ3B reading)."""
    from quant_sports_intel_models.football.nfl.fantasy import weekly_serving as WS

    with pytest.raises(WS.WeeklyServingError):
        runner.publish(_built(_HISTORICAL_MANIFEST), "no-such-bucket", do_publish=False)


def test_the_validated_dump_is_what_makes_the_same_blob_publishable(runner, tmp_path):
    """The fix, end to end: the SAME recorded blob, through the coercion `build` now applies."""
    fixed = C.NflWeeklyManifest.model_validate(_HISTORICAL_MANIFEST).model_dump()
    fixed_players = C.NflWeeklyPayload.model_validate(_HISTORICAL_PLAYERS).model_dump()
    written = runner.stage(_built(fixed, payload=fixed_players), tmp_path)
    staged = json.loads(next(p for p in written if p.name == "manifest.json").read_text())
    assert C.missing_declared_fields(staged, C.NflWeeklyManifest) == []
    assert staged["framing"]["interval_note"].strip(), "the block is present but says nothing"


def test_the_gate_cannot_pass_on_nothing(runner):
    """A gate that examined no field has not passed (NF1.7(a))."""
    from quant_sports_intel_models.football.nfl.fantasy import weekly_serving as WS

    with pytest.raises(WS.WeeklyServingError):
        runner.assert_contract_shaped({"manifest": {}, "payload": {}, "current": {}})
    checked = runner.assert_contract_shaped(_built(
        C.NflWeeklyManifest.model_validate(_HISTORICAL_MANIFEST).model_dump(),
        payload=C.NflWeeklyPayload.model_validate(_HISTORICAL_PLAYERS).model_dump(),
    ))
    assert all(v > 0 for v in checked.values()), checked


def test_a_missing_field_on_one_player_row_is_caught_too(runner, tmp_path):
    """The per-row contract is inside the payload, so the gate has to recurse into it. Driven by
    deleting a key from ONE real row — a writer that dropped a field on a subset is the shape a
    whole-payload spot check would miss."""
    from quant_sports_intel_models.football.nfl.fantasy import weekly_serving as WS

    players = C.NflWeeklyPayload.model_validate(_HISTORICAL_PLAYERS).model_dump()
    players["players"][17].pop("fpP90")
    with pytest.raises(WS.WeeklyServingError) as e:
        runner.stage(_built(C.NflWeeklyManifest.model_validate(_HISTORICAL_MANIFEST).model_dump(),
                            payload=players), tmp_path)
    assert "players[17].fpP90" in str(e.value)


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 3. BOTH PUBLISHED GENERATIONS STAY READABLE — coercion ADDS, it never rejects or rewrites
# ══════════════════════════════════════════════════════════════════════════════════════════════

def _diff_against_superset(original, dumped, where: str = "") -> tuple[list[str], list[str]]:
    """(keys LOST, keys whose VALUE moved) walking `original` against `dumped`, at every depth.

    ⚠️ A FLAT `dumped[k] == v` IS THE WRONG TEST and asserted a false failure on the first run:
    `lineage` legitimately gains four nested defaults, so the nested OBJECT differs while nothing
    inside it moved. The claim being made is "dumped is a SUPERSET of original with identical
    values", which is a recursive statement — anything flatter either misses a nested removal or
    reports a nested addition as a change.
    """
    lost: list[str] = []
    changed: list[str] = []
    pre = f"{where}." if where else ""
    for k, v in original.items():
        if k not in dumped:
            lost.append(f"{pre}{k}")
            continue
        d = dumped[k]
        if isinstance(v, dict) and isinstance(d, dict):
            sub_lost, sub_changed = _diff_against_superset(v, d, where=f"{pre}{k}")
            lost += sub_lost
            changed += sub_changed
        elif isinstance(v, list) and isinstance(d, list):
            if len(v) != len(d):
                changed.append(f"{pre}{k} (length {len(v)} -> {len(d)})")
                continue
            for i, (a, b) in enumerate(zip(v, d)):
                if isinstance(a, dict) and isinstance(b, dict):
                    sub_lost, sub_changed = _diff_against_superset(a, b, where=f"{pre}{k}[{i}]")
                    lost += sub_lost
                    changed += sub_changed
                elif a != b:
                    changed.append(f"{pre}{k}[{i}]")
        elif d != v:
            changed.append(f"{pre}{k}")
    return lost, changed


def _post_td(players: dict) -> dict:
    """The POST-TD generation, which has not published yet: the same real rows with the four
    component fields NF-WK-TD1 added carrying values instead of nulls."""
    out = json.loads(json.dumps(players))
    for r in out["players"]:
        if r["status"] == "projected":
            for f in ("passTd", "passInt", "rushTd", "recTd"):
                r[f] = 0.25
    return out


@pytest.mark.parametrize("label,blob,model", [
    ("pre-TD manifest", _HISTORICAL_MANIFEST, C.NflWeeklyManifest),
    ("pre-TD players", _HISTORICAL_PLAYERS, C.NflWeeklyPayload),
    ("post-TD players", _post_td(_HISTORICAL_PLAYERS), C.NflWeeklyPayload),
])
def test_coercion_is_additive_on_every_published_generation(label, blob, model):
    """⭐ NF-C0, BOTH DIRECTIONS. The fix may only ADD defaults: it must never reject an
    already-published blob (which would 500 a live route) and never change a value (which would
    make a serving change look like a model change). Asserted on the real recordings, per
    generation, rather than on a synthetic sample of one."""
    dumped = model.model_validate(blob).model_dump()
    lost, changed = _diff_against_superset(blob, dumped)
    assert lost == [], f"{label}: coercion REMOVED {lost}"
    assert changed == [], f"{label}: coercion CHANGED {changed} — a serving fix must not move a value"
    assert C.missing_declared_fields(dumped, model) == [], f"{label}: still short of the contract"


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 4. THE ROUTE HALF — enforced at serving, whatever the builder wrote
# ══════════════════════════════════════════════════════════════════════════════════════════════

@pytest.fixture()
def defective_store(monkeypatch):
    """Serve the EXACT blob production was serving on 2026-09-16 — the route half has to be
    provable against it, because every manifest already sitting in S3 is that shape."""
    from app.backend.routers import fantasy
    from app.backend.services import cost_guardrails, jwt_verify

    cost_guardrails.get_limiter().reset()
    cur = {"season": 2026, "week": 2, "generated_at": "2026-09-15T15:32:59+00:00",
           "manifest_key": C.weekly_manifest_key(2026, 2),
           "players_key": C.weekly_players_key(2026, 2)}

    def fake_load(rel_key: str, sport: str = "nfl"):
        if rel_key.endswith("current.json"):
            return cur
        if rel_key.endswith("manifest.json"):
            return _HISTORICAL_MANIFEST
        if rel_key.endswith("players.json"):
            return _HISTORICAL_PLAYERS
        return None

    monkeypatch.setattr(fantasy, "_load_json", fake_load)
    monkeypatch.setattr(jwt_verify, "_fetch_jwks", lambda: None)
    jwt_verify.reset_jwks_cache()
    return True


def test_the_route_serves_the_whole_contract_from_the_defective_blob(defective_store):
    """⭐ THE HALF THAT DOES NOT NEED A BOX DEPLOY. The stored blob is still the broken one here —
    exactly as every blob in S3 is until the next build republishes — and the wire is complete
    anyway. That is the point of putting the coercion at the route: the two halves ship down
    different pipes (box CD vs `deploy.sh`), so each has to stand alone."""
    status, body = _call("/fantasy/nfl/weekly/manifest", "season=2026")
    assert status == 200, body
    served = json.loads(body)
    assert C.missing_declared_fields(served, C.NflWeeklyManifest, where="manifest") == []
    assert served["framing"]["interval_note"].strip()
    assert served["framing"]["best_alpha"] == 0.0


def test_every_defaulted_field_on_this_contract_reaches_the_wire(defective_store):
    """THE AUDIT, ASSERTED ON SERVED BYTES — the incident's whole lesson.

    Not "the model declares a default" (it always did) and not "the object has the attribute" (it
    always did). The question is whether the bytes a browser receives carry it, so this reads the
    response body and nothing else.
    """
    served = json.loads(_call("/fantasy/nfl/weekly/manifest", "season=2026")[1])
    defaulted = [n for n, f in C.NflWeeklyManifest.model_fields.items() if not f.is_required()]
    assert len(defaulted) >= 9, "the defaulted set shrank — is this still auditing anything?"
    assert [n for n in defaulted if n not in served] == []
    nested = [n for n, f in C.NflWeeklyLineage.model_fields.items() if not f.is_required()]
    assert [n for n in nested if n not in served["lineage"]] == []


def test_the_route_preserves_the_entitlement_envelope(defective_store):
    """⛔ E9.41, THE DIRECTION THIS FIX COULD HAVE INTRODUCED. A bare
    `response_model=NflWeeklyManifest` drops `entitled`/`freeBoard`/`locked`/`lockedSeason` —
    measured, not hypothesised — because pydantic silently discards what it has no field for. That
    is `FeaturedYesterday` losing `status` all over again: fixing a missing-field defect by
    introducing a dropped-field defect is the same bug facing the other way."""
    served = json.loads(_call("/fantasy/nfl/weekly/manifest", "season=2026")[1])
    bare = C.NflWeeklyManifest.model_validate(
        entitlement.open_manifest_payload(_HISTORICAL_MANIFEST)).model_dump()
    would_have_been_dropped = sorted(
        k for k in entitlement.open_manifest_payload(_HISTORICAL_MANIFEST) if k not in bare)
    assert would_have_been_dropped, (
        "the envelope no longer adds an undeclared key, so this guard has nothing to defend — "
        "check whether the response model still needs to declare it"
    )
    assert [k for k in would_have_been_dropped if k not in served] == [], (
        f"the response model dropped {would_have_been_dropped} from the wire"
    )


def test_the_response_model_declares_every_key_the_envelope_actually_adds():
    """⭐ DERIVED FROM THE ENVELOPE, NEVER A HAND LIST — because the residual risk of declaring the
    envelope is that the envelope GROWS and the new key is silently stripped. Calling
    `open_manifest_payload` for the answer means that becomes a red build instead."""
    enveloped = entitlement.open_manifest_payload(
        C.NflWeeklyManifest.model_validate(_HISTORICAL_MANIFEST).model_dump())
    declared = set(C.NflWeeklyManifestResponse.model_fields)
    assert set(enveloped) - declared == set(), (
        f"`open_manifest_payload` adds {sorted(set(enveloped) - declared)}, which "
        "`NflWeeklyManifestResponse` does not declare — it would be stripped on serialize (E9.41)"
    )


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 5. THE CSP — session replay was OFF in production and nothing said so
# ══════════════════════════════════════════════════════════════════════════════════════════════

_NEXT_CONFIG = _REPO / "frontend/next.config.mjs"


def _csp_directives() -> dict[str, list[str]]:
    """Every CSP directive in the real config, parsed from COMMENT-STRIPPED source.

    ⚠️ STRIPPING IS LOAD-BEARING, not hygiene. The change this guards ships with an explanatory
    comment that says the words `worker-src` and `blob:` several times, so a bare substring scan
    over the raw file would be satisfied by the PROSE with the directive deleted — the INC-38
    "a comment cannot satisfy a guard" shape, which this repo has shipped more than once.
    """
    import re

    src = "\n".join(
        line for line in _NEXT_CONFIG.read_text().splitlines()
        if not line.lstrip().startswith("//")
    )
    out: dict[str, list[str]] = {}
    for m in re.finditer(r'"([a-z-]+-src|frame-ancestors) ([^"]+)"', src):
        out[m.group(1)] = m.group(2).split()
    return out


def test_the_csp_parser_is_not_vacuous():
    """NF1.7(a): a parser returning nothing would make the assertion below vacuously true."""
    d = _csp_directives()
    assert "img-src" in d and "connect-src" in d, f"the CSP parse looks wrong: {sorted(d)}"


def test_the_replay_worker_is_not_blocked_by_our_own_policy():
    """⛔ `blob:` IS THE ASSERTION, not `worker-src`.

    Sentry builds its replay worker from a `blob:` URL, so a directive naming only `'self'` reads
    as a fix and changes nothing — the browser still refuses the worker, the console still warns,
    and no replay attaches. With no `worker-src` at all it falls back to `default-src 'self'`,
    which is the state the whole 758-minute outage was recorded in.
    """
    d = _csp_directives()
    assert "worker-src" in d, (
        "no worker-src directive — it falls back to default-src 'self' and Sentry's replay worker "
        "is refused, so session replay is silently OFF in production"
    )
    assert "blob:" in d["worker-src"], (
        f"worker-src is {d['worker-src']} — without `blob:` the replay worker is still blocked"
    )


def test_the_worker_source_stays_narrow():
    """Loosening a CSP is a security change and should be argued, not drifted into. `'self'` +
    `blob:` grants nothing an attacker could not already reach through the existing
    `script-src 'unsafe-inline'`; a third-party host here would be a different claim."""
    assert set(_csp_directives()["worker-src"]) <= {"'self'", "blob:"}, (
        "worker-src has grown beyond our own origin and our own blobs — that is a posture change"
    )


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 6. THE PATTERN ITSELF — `model_validate` as a bare statement is the defect, mechanised
# ══════════════════════════════════════════════════════════════════════════════════════════════

_RUNNER = _REPO / "quant_sports_intel_models/football/nfl/fantasy/run_weekly_serving.py"
_ROUTER = _REPO / "app/backend/routers/fantasy.py"


def _bare_model_validate_lines(path: Path) -> list[int]:
    """Line numbers where `…model_validate(…)` is an EXPRESSION STATEMENT — validated, discarded.

    ⭐ AST, NOT GREP, and the difference is not pedantry here: this file's own comments quote the
    defective form several times to explain it, and a substring scan would fire on the explanation
    while a deleted assignment went unnoticed. The parser only sees code.
    """
    import ast

    tree = ast.parse(path.read_text())
    out = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Expr) or not isinstance(node.value, ast.Call):
            continue
        fn = node.value.func
        if isinstance(fn, ast.Attribute) and fn.attr == "model_validate":
            out.append(node.lineno)
    return out


def test_the_ast_scan_can_actually_see_a_discarded_validation():
    """NF1.7(a) — if the scanner cannot find the pattern in a sample that certainly contains it,
    the assertion below passes on everything."""
    import ast
    import tempfile

    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as fh:
        fh.write("import m\ndef f(x):\n    m.Model.model_validate(x)\n    return x\n")
        probe = Path(fh.name)
    try:
        assert _bare_model_validate_lines(probe) == [3], "the scanner is blind to its own subject"
    finally:
        probe.unlink()
    assert ast.parse(_RUNNER.read_text()), "the runner no longer parses"


def test_the_weekly_builder_never_validates_and_discards():
    """⛔⛔ THE DEFECT CLASS, BANNED IN THE FILE IT SHIPPED FROM.

    A bare `Model.model_validate(blob)` statement asserts something about a value nobody keeps. On
    a contract with DEFAULTED fields that is not merely useless — it is actively misleading, because
    it reads like a gate and cannot fail on the one thing that actually went wrong. Every
    validation in this runner must bind its result and that result must be what gets written.
    """
    bare = _bare_model_validate_lines(_RUNNER)
    assert bare == [], (
        f"{_RUNNER.name} validates and discards at line(s) {bare} — the NF-INC-0917 shape. "
        "Bind the result and write THAT, or the default lands on an object nobody ships."
    )


def test_the_manifest_route_carries_both_halves_of_the_fix():
    """⭐ TWO SEPARABLE PROPERTIES, AND THE FIRST DRAFT OF THIS GUARD GOT THEIR RELATIONSHIP WRONG.

    It claimed the `response_model` and the in-handler coercion were redundant halves that each
    completed the payload. Measured: they are not. `NflWeeklyManifestResponse` inherits the
    contract, so it fills every defaulted field BY ITSELF — deleting the in-handler coercion leaves
    the wire complete. The two things that are genuinely separable, and that this asserts, are:

      1. the route DECLARES its shape (`response_model`) rather than passing the S3 blob through;
      2. a contract failure is CAUGHT (`ValidationError`) and degrades, instead of 500ing a route
         the page cannot render without.

    Neither is visible in the other's behaviour, which is why the claim is structural. ⚠️ Each
    clause has its own isolating RED case in `nf_inc_0917b_red_proof.py` — a conjunction whose
    clauses are only proven together proves neither (NF-D17).
    """
    import ast

    tree = ast.parse(_ROUTER.read_text())
    fn = next((n for n in ast.walk(tree)
               if isinstance(n, ast.FunctionDef) and n.name == "nfl_weekly_manifest"), None)
    assert fn is not None, "the weekly manifest handler has been renamed — this guard is vacuous"

    declared = {
        kw.arg
        for dec in fn.decorator_list if isinstance(dec, ast.Call)
        for kw in dec.keywords
    }
    assert "response_model" in declared, (
        "the weekly manifest route lost its response_model — it is a pass-through of the S3 blob "
        "again, which is the state the outage was served in"
    )
    degrades = any(
        isinstance(h.type, ast.Name) and h.type.id == "ValidationError"
        for n in ast.walk(fn) if isinstance(n, ast.Try)
        for h in n.handlers
    )
    assert degrades, (
        "the handler has no ValidationError path — a published blob missing a field the contract "
        "REQUIRES would 500 this route, and adding a required field is an ordinary change that "
        "ships no new artifact, so every already-published week would go down with it"
    )


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 7. THE COERCION MUST NOT BECOME A NEW WAY FOR THE ROUTE TO GO DOWN
# ══════════════════════════════════════════════════════════════════════════════════════════════

@pytest.fixture()
def store_missing_a_required_field(monkeypatch):
    """A published manifest short of a field the contract REQUIRES — not a hypothetical.

    Adding a required field to `nfl_weekly.py` is an ordinary change, and `app/**` deliberately does
    not trigger the box deploy, so for one build cycle every manifest already in S3 is short of it.
    """
    from app.backend.routers import fantasy
    from app.backend.services import cost_guardrails, jwt_verify

    cost_guardrails.get_limiter().reset()
    broken = _degenerate(_HISTORICAL_MANIFEST, "n_players")

    def fake_load(rel_key: str, sport: str = "nfl"):
        if rel_key.endswith("current.json"):
            return {"season": 2026, "week": 2, "generated_at": "x",
                    "manifest_key": C.weekly_manifest_key(2026, 2),
                    "players_key": C.weekly_players_key(2026, 2)}
        if rel_key.endswith("manifest.json"):
            return broken
        return None

    monkeypatch.setattr(fantasy, "_load_json", fake_load)
    monkeypatch.setattr(jwt_verify, "_fetch_jwks", lambda: None)
    jwt_verify.reset_jwks_cache()
    return broken


def test_the_degenerate_really_fails_validation(store_missing_a_required_field):
    """NF1.7(a): if the blob still validated, the clause below would be testing the happy path."""
    import pydantic

    with pytest.raises(pydantic.ValidationError):
        C.NflWeeklyManifest.model_validate(store_missing_a_required_field)


def test_an_uncoercible_blob_degrades_rather_than_500ing(store_missing_a_required_field, caplog):
    """⛔ THE ONE DIRECTION THIS FIX COULD HAVE BEEN WORSE THAN THE PASS-THROUGH IT REPLACES.

    Coercion exists to ADD defaults. A blob missing a REQUIRED field is a different failure, and
    hard-failing on it would take every published week's page down for a contract edit that shipped
    no new artifact — a silent incompleteness traded for a loud outage, which is the same mistake
    with better manners. The page has rendered a missing block honestly since PR #1143, so degrading
    is the state that keeps the product up AND truthful.

    ⭐ AND IT MUST SAY SO. A degrade nobody is told about is the swallow-and-continue class; the
    handler logs at ERROR with the season and week, which is the strongest signal available on a
    Lambda that has no `send_alert` path at all (E9.8-P2).
    """
    import logging

    with caplog.at_level(logging.ERROR):
        status, body = _call("/fantasy/nfl/weekly/manifest", "season=2026")
    assert status == 200, f"a published blob became a 500: {body[:400]}"
    served = json.loads(body)
    assert served["season"] == 2026 and served["week"] == 2
    assert "locked" in served, "the entitlement envelope was lost on the degraded path"
    # ⚠️ PINNED ON WHAT AN OPERATOR CAN ACT ON, NOT ON THE PROSE. The first cut of this clause
    # matched a sentence fragment and went red the moment the message was reworded — a guard
    # testing the author's typing rather than the behaviour. What has to be true is that the degrade
    # is logged at ERROR and NAMES THE SLATE, because "a manifest somewhere is incomplete" is not
    # something anyone can act on.
    errs = [r for r in caplog.records if r.levelno >= logging.ERROR]
    assert errs, (
        "the route degraded SILENTLY — the swallow-and-continue class this repo keeps getting "
        f"bitten by; records were {[(r.levelname, r.getMessage()[:50]) for r in caplog.records]}"
    )
    named = [r.getMessage() for r in errs if "2026" in r.getMessage() and "wk2" in r.getMessage()]
    assert named, f"the degrade was logged but does not name the slate: {[r.getMessage()[:80] for r in errs]}"


def test_the_envelope_and_the_response_model_agree_in_both_directions():
    """⭐ THE OTHER DIRECTION, which the keys-subset clause above does not cover.

    That clause stops the envelope GROWING a key the model would strip. This one stops the envelope
    LOSING a key the model REQUIRES — `lockedSeason` and `freeBoard` have no defaults, so an
    envelope that stopped emitting one would make every response un-buildable. Both directions are
    derived by calling `open_manifest_payload`, so neither can be satisfied by a stale hand list.
    """
    enveloped = entitlement.open_manifest_payload(
        C.NflWeeklyManifest.model_validate(_HISTORICAL_MANIFEST).model_dump())
    required = {
        n for n, f in C.NflWeeklyManifestResponse.model_fields.items()
        if f.is_required() and n not in C.NflWeeklyManifest.model_fields
    }
    assert required, "no required envelope fields — this guard is asserting on nothing"
    assert required - set(enveloped) == set(), (
        f"`NflWeeklyManifestResponse` REQUIRES {sorted(required - set(enveloped))}, which "
        "`open_manifest_payload` no longer supplies — every response would fail to build"
    )


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 8. THE ABSENCE COPY MAY NOT ASSERT THE STATE OF CONTENT THAT CAN BE WITHHELD
# ══════════════════════════════════════════════════════════════════════════════════════════════

_CLAIM_COPY = _REPO / "frontend/lib/fantasy-claim-copy.ts"


def _framing_absent_copy() -> str:
    """The `WEEKLY_FRAMING_ABSENT` string, read from the module that owns it."""
    import re

    m = re.search(r'export const WEEKLY_FRAMING_ABSENT\s*=\s*\n?\s*"((?:[^"\\]|\\.)*)"',
                  _CLAIM_COPY.read_text())
    assert m, "could not find WEEKLY_FRAMING_ABSENT — this guard would be vacuous"
    return m.group(1)


def test_the_absence_copy_parses():
    """NF1.7(a) — a parser returning an empty string satisfies every substring clause below."""
    assert len(_framing_absent_copy()) > 80


def test_the_absence_copy_makes_no_claim_about_the_projections_status():
    """⛔ MEASURED ON THE LIVE PAGE 2026-09-16, not reasoned about.

    The two notices had never rendered together. With the INC-0916 suppression live, the weekly page
    shows the withholding notice AND this absence panel, and this copy ended with "…and the
    projections above are unaffected" — while the projections above were WITHHELD. A caveat panel
    that reassures a reader about content the same page is declining to show is not a tone problem;
    it is a false statement, and it is false precisely when someone is most likely to be reading it.

    ⭐ THE CLASS, because the specific sentence will be reworded and this must outlive it: a panel
    that explains ONE absence must not assert the STATE of anything another mechanism can withhold.
    It can describe itself and it can point at something structural — the "80% range" column heading
    is still rendered under suppression (checked on the live page; the columns render with their
    cells withheld), so pointing at it stays true — but "the projections are fine" is a claim about
    a neighbour, and neighbours change.
    """
    copy = _framing_absent_copy().lower()
    forbidden = [
        "projections above are unaffected",
        "projections are unaffected",
        "numbers above are unaffected",
    ]
    hit = [f for f in forbidden if f in copy]
    assert hit == [], (
        f"the framing-absence copy asserts the state of the projections ({hit}) — which is FALSE "
        "whenever WEEKLY_NUMBERS_WITHHELD is on, i.e. exactly when a reader meets both notices"
    )


def test_the_absence_copy_still_says_what_it_is_for():
    """The other side of the clause above: removing the false reassurance must not hollow the panel
    out. It still has to say that the notes did not arrive and that we are not inventing them —
    otherwise a future edit could satisfy the guard by deleting the copy (INC-38)."""
    copy = _framing_absent_copy().lower()
    for phrase in ("did not come through", "not showing them", "80% range"):
        assert phrase in copy, f"the absence copy no longer says {phrase!r}"


def test_the_gate_only_returns_a_count_when_every_declared_field_is_present(runner):
    """⭐ THE INVARIANT THAT MAKES THE `[METRIC]` NUMBER HONEST, asserted instead of assumed.

    `assert_contract_shaped` returns the contract's own field count. That is only a true report of
    what was verified because the function CANNOT return on a blob that is short — it raises. So the
    claim to pin is not the arithmetic of the count (which no reachable state can falsify) but the
    refusal that stands behind it.

    ⚠️ Recorded because I got this wrong first: I made the count blob-derived to defend against
    "reports healthy for a blob it never read", and then could not write a test that distinguished
    the two implementations — there is no input on which they differ. A distinction no test can
    observe is not a safeguard, it is a comment, and the honest guard is this one.
    """
    from quant_sports_intel_models.football.nfl.fantasy import weekly_serving as WS

    full = _built(C.NflWeeklyManifest.model_validate(_HISTORICAL_MANIFEST).model_dump(),
                  payload=C.NflWeeklyPayload.model_validate(_HISTORICAL_PLAYERS).model_dump())
    counts = runner.assert_contract_shaped(full)
    assert counts["manifest"] == len(C.declared_field_names(C.NflWeeklyManifest))

    # Remove ONE declared field from each blob in turn: every one of them must refuse, which is what
    # makes "returned a count" equivalent to "verified all of them".
    for blob_name, model, field in (("manifest", C.NflWeeklyManifest, "framing"),
                                    ("payload", C.NflWeeklyPayload, "scoring_system_id"),
                                    ("current", C.NflWeeklyCurrent, "manifest_key")):
        assert field in C.declared_field_names(model), f"{field} is no longer declared"
        thin = dict(full, **{blob_name: _degenerate(full[blob_name], field)})
        with pytest.raises(WS.WeeklyServingError, match=field):
            runner.assert_contract_shaped(thin)
