"""NF-WK-MT1 — the league-scored WEEKLY line, and the three boundaries that keep it honest.

The paid question the weekly stack exists to answer is "what does MY roster do this week, in MY
league's scoring". Answering it needs no new scoring code and no new distribution: the champion's
component head is already served under the field names `league_scoring` reads, so the ONE server
scorer runs over a weekly row verbatim. What this file pins is the set of things that are TRUE only
because someone chose them, and which nothing else would notice going wrong:

  1. NO FOURTH SCORER. Proven by SUBSTITUTION — `league_scoring.score_row` is replaced with a
     sentinel and the sentinel must come out the other end. A docstring claiming reuse cannot
     satisfy that (INC-38), and neither can an import nothing invokes (NF-C0e's wired-≠-invoked).
     Backed by an AST scan: the adapter carries no numeric literal at all, so it cannot be holding
     a scoring weight of its own.

  2. THE POINT IS EXACT AND THE RANGE IS NOT RE-EXPRESSED. `score_row` returns an interval by
     rescaling the payload's bounds by the ratio the point moved; that value is DISCARDED, and the
     band on the wire is the payload's own, byte-identical. Proven with a league whose scoring
     moves the point hard — if the rescale were leaking through, the band would move with it.

  3. THE TWO PARITY QUESTIONS ARE DIFFERENT QUESTIONS, and each clause says which it asks:
       (a) GATED — our scorer, under the shipped full-PPR preset, against an INDEPENDENT full-PPR
           implementation over the SAME component line. Must agree to float tolerance.
       (b) DIAGNOSTIC, NEVER GATED — the component line against the POINTS HEAD. Those are two
           independent heads of one model, and NF-C6-PH2 measured the gap (mean SIGNED -0.7709,
           median |d| 0.6016, p95 3.7101, max 7.9200, n=503 staged rows, 2026-09-05). Asserting
           they agree would be asserting something known to be false; this file pins that nothing
           does, and that the two numbers stay DISTINCT declared fields on the wire.

⭐ THE ORACLE IN (3a) IS NOT A RESTATEMENT OF THE CODE. It is
`run_nf_c6_ph2_promotion_review.component_coherence`, written by NF-C6-PH2 for a different purpose
before this story existed, and it is USED rather than copied: we overwrite `fpPpr` with our own
output and require the coherence it measures to be exactly zero. A test that recomputed the formula
beside the implementation would be the NF-C0e "reads the value back under the key the code wrote"
shape and would stay green through a wrong stat key — the defect it most needs to catch.

RED-PROVEN: `uv run python betting_ml/tests/nf_wk_mt1_red_proof.py`. Every clause naming a specific
rule has its OWN fixture in which every other clause is satisfied (NF-D17 §7): a fixture that trips
two clauses tests neither, because the first refusal hides the second.

🗓️ FIXTURE TRIPWIRE (inherited, NF-WK-FE1 finding 6 / E9.64b). The weekly fixtures are GENERATED by
the shipping writer because nothing weekly has published yet, so they can only confirm the shape we
already assumed. On the first real publish they are retired and re-captured RAW, and every clause
here re-runs against the captured ones. The clauses are written to survive that: none hardcodes a
player, a point or a row count that a real payload would change — the one count that IS pinned
(`test_the_parity_clause_is_not_vacuous`) is pinned as a FLOOR, so more real rows strengthen it.

Pure/offline (fast gate): committed fixtures, source files and pure functions only. No DuckDB/S3/
network and no `pipeline` import (E11.23). The two heavy imports — the oracle and the league presets
— are LAZY, inside the clauses that use them, so per-worker collection pays nothing for them.
"""
from __future__ import annotations

import ast
import copy
import json
from pathlib import Path

import pytest

from app.backend.models import nfl_weekly as C
from app.backend.services import cost_guardrails as CG
from app.backend.services import league_scoring as ls
from app.backend.services import projection_fields as PF
from app.backend.services import weekly_league_board as WLB

REPO = Path(__file__).resolve().parents[2]
ADAPTER = REPO / "app/backend/services/weekly_league_board.py"
ROUTER = REPO / "app/backend/routers/fantasy.py"
CDN_ROUTE = REPO / "frontend/app/api/public/[...path]/route.ts"
PARITY_MERGE_GATE = REPO / "betting_ml/tests/test_nf_epic1_parity.py"

WEEKLY_ENTITLED = REPO / "frontend/e2e/fixtures/api/fantasy-nfl-weekly-players-entitled.synthetic.json"
WEEKLY_FREE = REPO / "frontend/e2e/fixtures/api/fantasy-nfl-weekly-players-free.synthetic.json"

#: The served path. A SIBLING of `…/weekly/projections`, never a child of it — see
#: `test_the_route_path_is_a_sibling_of_the_free_reads_and_not_a_child`.
ROUTE_PATH = "/fantasy/nfl/weekly/league-board"


@pytest.fixture(scope="module")
def weekly_players() -> list[dict]:
    return json.loads(WEEKLY_ENTITLED.read_text())["players"]


@pytest.fixture(scope="module")
def full_ppr_cfg() -> dict:
    """The SHIPPED full-PPR preset, not a test author's idea of one.

    ⚠️ Load-bearing for the RED proof: the parity clause's deliberate break mutates a weight in
    `league_presets._BASE_SCORING`, and a hardcoded config here would absorb that mutation and
    report a FALSE green — the "the break landed but did not move the asserted predicate" shape
    (E11.24 #815)."""
    from quant_sports_intel_models.football.nfl.fantasy import league_presets as LP

    return LP.full_ppr(12).to_dict()


def _roster_of(players: list[dict]) -> list[dict]:
    return [
        {"name": p["name"], "position": p["pos"], "team": p.get("team"), "starter": True}
        for p in players
    ]


def _score(players, roster, cfg) -> dict:
    return WLB.score_weekly_roster(
        weekly_players=players, roster=roster, cfg=cfg, stat_field=PF.STAT_FIELD
    )


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 1. BOUNDARY (a) — there is no fourth scorer
# ══════════════════════════════════════════════════════════════════════════════════════════════

def test_every_weekly_point_comes_out_of_the_one_server_scorer(
    monkeypatch, weekly_players, full_ppr_cfg
):
    """⭐ SUBSTITUTION, NOT INSPECTION. Replace `league_scoring.score_row` with a sentinel; if the
    adapter scores anything itself, the sentinel cannot appear in its output.

    This is the clause that actually defends the no-fourth-implementation rule. A grep for
    `score_row(` is satisfied by an import, a dead call or a comment; only invoking the real path
    with the real function removed can tell reuse from re-implementation (NF-C0e)."""
    sentinel = -98765.25
    calls: list[str] = []

    def fake_score_row(row, pos, resolved, stat_field):
        calls.append(str(row.get("id")))
        return {"pts": sentinel, "p10": 1.0, "p90": 2.0}

    monkeypatch.setattr(ls, "score_row", fake_score_row)
    out = _score(weekly_players, _roster_of(weekly_players), full_ppr_cfg)

    scored_rows = [r for r in out["rows"] if r.get("absence") is None]
    assert scored_rows, "fixture scored nothing — the clause would pass on an empty roster"
    assert calls, "the one scorer was never called"
    assert {r["leaguePts"] for r in scored_rows} == {sentinel}, (
        "a weekly point reached the wire without coming from league_scoring.score_row — that is a "
        "fourth scoring implementation, and it carries the NF-EPIC 1 parity tax forever"
    )


def test_the_adapter_holds_no_numeric_literal_and_so_cannot_hold_a_scoring_weight():
    """A scorer needs weights; an adapter needs none. An AST scan rather than a regex, so a number
    inside a docstring or a comment cannot satisfy it and a number in real code cannot hide from it.

    ⚠️ If a literal is ever legitimately needed here, add it to an explicit allowlist WITH ITS
    REASON rather than deleting this clause — the allowlist is the record of a decision, the
    deletion would be the loss of one."""
    allowed: set[float] = set()
    tree = ast.parse(ADAPTER.read_text())
    found = [
        n.value
        for n in ast.walk(tree)
        if isinstance(n, ast.Constant)
        and isinstance(n.value, (int, float))
        and not isinstance(n.value, bool)
        and n.value not in allowed
    ]
    assert not found, (
        f"{ADAPTER.name} carries numeric literals {found}. Scoring arithmetic belongs in "
        "league_scoring.py, which is the module the three-implementation parity gate watches."
    )


def test_the_adapter_never_iterates_a_scoring_rule_table():
    """The shape of a scorer is a loop over `per_stat`. The adapter hands that table to
    `score_row` and never walks it — so a re-implementation that dodged the literal check by
    reading weights from the config still goes red here."""
    tree = ast.parse(ADAPTER.read_text())
    for node in ast.walk(tree):
        if isinstance(node, (ast.For, ast.comprehension)):
            target = ast.dump(node.iter if isinstance(node, ast.For) else node.iter)
            assert "per_stat" not in target and "position_bonuses" not in target, (
                "the adapter iterates a scoring rule table; that is the scorer's job"
            )


def test_the_three_implementation_parity_merge_gate_is_still_present():
    """⛔ THE HOLE THIS CLOSES IS "SMUGGLE BY DELETING THE GATE". This story must not edit a scorer,
    and `test_nf_epic1_parity.py` is what would catch it if one did — so the gate's continued
    existence is part of this story's own guarantee.

    ⚠️ DELIBERATELY DOES NOT ASSERT THE SCORERS' CONTENT. A digest pin would make THIS story's
    suite go red on ANOTHER story's legitimate scorer change, which is the NF-D17 coupling
    antipattern: a guard should fail only for the story it defends."""
    assert PARITY_MERGE_GATE.is_file(), "the NF-EPIC 1 three-implementation parity gate is gone"
    src = PARITY_MERGE_GATE.read_text()
    assert "fantasy_engine" in src and "league_scoring" in src, (
        "the parity gate no longer compares the engine against the Lambda scorer"
    )


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 2. BOUNDARY (b) — the point is exact; the range is CARRIED, never re-expressed
# ══════════════════════════════════════════════════════════════════════════════════════════════

def test_the_served_band_is_the_payloads_own_band_byte_identical(weekly_players, full_ppr_cfg):
    """⭐ MEASURED AGAINST A LEAGUE THAT MOVES THE POINT HARD. Under six points per reception the
    league point diverges from PPR by a wide margin; if `score_row`'s rescaled interval were
    leaking onto the wire, the band would move with the point. It must not move at all.

    This is the difference between an honest range and a pseudo-band: re-expressing an 80% interval
    under arbitrary scoring needs the per-stat DISTRIBUTIONS (NF-W6c/W6d — staged, no consumer),
    not the per-stat means, and a rescale labelled as this league's would assert a precision the
    substrate does not have."""
    hot = copy.deepcopy(full_ppr_cfg)
    hot["scoring"]["per_stat"]["rec"] = 6.0
    out = _score(weekly_players, _roster_of(weekly_players), hot)
    by_name = {p["name"]: p for p in weekly_players}

    moved = 0
    for row in out["rows"]:
        if row.get("absence") is not None:
            continue
        src = by_name[row["rosterName"]]
        assert row["bandP10"] == src["fpP10"], "the p10 bound was re-expressed, not carried"
        assert row["bandP90"] == src["fpP90"], "the p90 bound was re-expressed, not carried"
        assert row["pprPts"] == src["fpPpr"], "the PPR point the band belongs to was altered"
        if row["leaguePts"] != src["fpPpr"]:
            moved += 1

    assert moved, (
        "no player's league point differed from PPR under 6-point receptions, so this clause "
        "proved nothing — the band could have been rescaled and still matched"
    )


def test_the_rescaled_interval_score_row_returns_is_discarded(
    monkeypatch, weekly_players, full_ppr_cfg
):
    """The scorer's own `p10`/`p90` must reach no field of the response under ANY name.

    Driven by making them unmistakable: if either value appears anywhere in the output, it was
    carried rather than dropped."""
    poison_lo, poison_hi = -12345.5, -54321.5

    real = ls.score_row

    def tagged(row, pos, resolved, stat_field):
        out = dict(real(row, pos, resolved, stat_field))
        out["p10"], out["p90"] = poison_lo, poison_hi
        return out

    monkeypatch.setattr(ls, "score_row", tagged)
    out = _score(weekly_players, _roster_of(weekly_players), full_ppr_cfg)
    blob = json.dumps(out, default=str)
    assert str(poison_lo) not in blob and str(poison_hi) not in blob, (
        "score_row's rescaled interval reached the response; boundary (b) forbids a band that "
        "claims to be in the caller's scoring when nothing re-expressed it"
    )


def test_the_contract_serves_the_ppr_point_the_band_belongs_to():
    """⚠️ A RANGE RENDERED BESIDE A LEAGUE-SCORED POINT WITH NO PPR POINT IN SIGHT IS A FALSE CLAIM
    — it reads as that point's range, and it is not. So `pprPts` is not an optional extra: it is
    what makes the carried band honest, and the contract must declare it beside the band."""
    fields = set(C.NflWeeklyLeagueRow.model_fields)
    assert {"leaguePts", "pprPts", "bandP10", "bandP90"} <= fields
    note = C.SCORING_BASIS_NOTE.lower()
    assert "ppr" in note and "range" in note, "the scope note does not state what the range is in"


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 3. THE PARITY CLAUSE — and the OTHER comparison, which is a diagnostic and not a gate
# ══════════════════════════════════════════════════════════════════════════════════════════════

def _oracle_diff(players: list[dict], rows: list[dict]) -> dict:
    """Overwrite `fpPpr` with OUR scorer's output and ask NF-C6-PH2's independent implementation
    how far apart they are. Zero means our wiring reproduces full-PPR exactly."""
    from quant_sports_intel_models.football.nfl.fantasy.run_nf_c6_ph2_promotion_review import (
        component_coherence,
    )

    probe = copy.deepcopy({"players": players})
    by_name = {r["rosterName"]: r for r in rows}
    for p in probe["players"]:
        hit = by_name.get(p.get("name"))
        if hit and hit.get("leaguePts") is not None:
            p["fpPpr"] = hit["leaguePts"]
    return component_coherence(probe)


def test_the_server_scorer_reproduces_full_ppr_over_the_weekly_line(
    weekly_players, full_ppr_cfg
):
    """⭐ THE GATED COMPARISON: OUR SCORER vs AN INDEPENDENT FULL-PPR IMPLEMENTATION, over the SAME
    component line. NOT the component sum against the points head — that is a different question
    with a known non-zero answer, and it is the clause below.

    What it catches is the whole wrong-key family (NF-C0e): a component mapped to the wrong stat
    key, a term silently dropped, a weight misapplied. All of those leave every other test green,
    because an unrecognized key passes through as `captured` with no error."""
    out = _score(weekly_players, _roster_of(weekly_players), full_ppr_cfg)
    res = _oracle_diff(weekly_players, out["rows"])

    assert res["evaluable"] is True, f"the oracle could not score anything: {res}"
    assert res["max_abs_diff"] == 0.0, (
        f"our full-PPR scoring of the weekly component line disagrees with an independent "
        f"implementation of the same formula over the same line: {res}"
    )
    assert res["mean_signed_diff"] == 0.0


def test_the_parity_clause_is_not_vacuous(weekly_players, full_ppr_cfg):
    """A comparison that scored NO rows would pass the clause above while proving nothing
    (NF1.7 (a)). The oracle skips byes and rows with no component line, so the count it actually
    reached is asserted as a FLOOR — a real captured payload will raise it, never lower it."""
    out = _score(weekly_players, _roster_of(weekly_players), full_ppr_cfg)
    res = _oracle_diff(weekly_players, out["rows"])
    assert res.get("n", 0) >= 5, (
        f"only {res.get('n')} rows reached the parity comparison; below that it is not measuring "
        "the field map it exists to police"
    )


def test_the_component_line_is_never_asserted_to_equal_the_points_head():
    """⭐ THE DIAGNOSTIC, AND WHY IT MUST NOT BECOME A GATE. The weekly point and the weekly
    component line come from two INDEPENDENT heads of one model; NF-C6-PH2 measured the gap at mean
    SIGNED -0.7709 (the components score BELOW the head), median |d| 0.6016, p95 3.7101, max
    7.9200, over n=503 staged rows on 2026-09-05. Asserting equality would be asserting something
    already measured false, and a surface that presented one as a correction of the other would be
    making a claim the model does not support.

    ⛔ AND THE DIRECTION IS RECORDED BECAUSE IT IS COUNTER-INTUITIVE: a disclosure phrased as "the
    components may exceed the total" is BACKWARDS. The PM adopted that warning verbatim
    (2026-09-14, the NF-WK-FE1 disposition) after the same figures were mislabelled once and
    propagated by copy.

    So the two stay DISTINCT declared fields, and nothing here folds one into the other."""
    fields = C.NflWeeklyLeagueRow.model_fields
    assert "leaguePts" in fields and "pprPts" in fields
    src = ADAPTER.read_text()
    assert "leaguePts" in src and "pprPts" in src
    # The adapter must not reconcile them — no assignment of one from the other.
    assert 'row["pprPts"] = row["leaguePts"]' not in src
    assert 'row["leaguePts"] = row["pprPts"]' not in src


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 4. THE SUBSTRATE REFUSAL — a roster of honest-looking zeroes is the worst available failure
# ══════════════════════════════════════════════════════════════════════════════════════════════

def test_the_public_payload_is_refused_rather_than_scored_to_zero(full_ppr_cfg):
    """⛔ THE FAILURE THIS EXISTS TO PREVENT. Handed the PUBLIC weekly payload, every component is
    absent, every term resolves CAPTURED, and every player scores exactly 0.0 — with no exception,
    no empty list and no error. That is indistinguishable from a bye week and it would be believed.

    Two-sided on purpose: the reduced payload RAISES, and the full one does not."""
    public_players = json.loads(WEEKLY_FREE.read_text())["players"]
    assert public_players, "the free fixture is empty; this clause would pass on nothing"

    with pytest.raises(WLB.WeeklySubstrateError) as exc:
        _score(public_players, _roster_of(public_players), full_ppr_cfg)
    assert "component" in str(exc.value).lower()


def test_an_empty_week_is_refused_with_a_different_cause_than_a_reduced_one(full_ppr_cfg):
    """Two refusals, two messages. "this week published nothing" and "we were handed the public
    blob" point at different fixes, and one message for both would cost an investigation."""
    with pytest.raises(WLB.WeeklySubstrateError) as exc:
        _score([], [], full_ppr_cfg)
    assert "no players" in str(exc.value).lower()


def test_a_full_payload_scores_without_raising(weekly_players, full_ppr_cfg):
    """The other side of the refusal — without it the clause above is satisfied by a function that
    raises unconditionally."""
    out = _score(weekly_players, _roster_of(weekly_players), full_ppr_cfg)
    assert any(r.get("leaguePts") for r in out["rows"])


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 5. COVERAGE — "contributed nothing" and "is not in this number" are different facts
# ══════════════════════════════════════════════════════════════════════════════════════════════

def test_a_league_term_the_weekly_line_cannot_express_is_reported_captured(
    weekly_players, full_ppr_cfg
):
    """⭐ AN ORDINARY FULL-PPR LEAGUE HAS REAL WEIGHTS THIS WEEK'S LINE CANNOT EXPRESS. The champion
    emits eleven components; the preset scores `fumbles_lost` and `two_pt` too, plus every kicker
    and defence term. Those must resolve CAPTURED — named in the report — rather than silently
    zeroed behind an "applied" label.

    ⚠️ The APPLIED set is asserted EXACTLY, not as a subset: a term drifting from captured to
    applied is precisely how a number starts quietly including something it cannot compute."""
    out = _score(weekly_players, _roster_of(weekly_players), full_ppr_cfg)
    terms = out["coverage"]["terms"]
    applied = {t["key"] for t in terms if t["verdict"] == "applied"}
    captured = {t["key"] for t in terms if t["verdict"] == "captured"}

    assert applied == {
        "pass_yds", "pass_td", "pass_int", "rush_yds", "rush_td", "rec", "rec_yds", "rec_td",
    }
    assert {"fumbles_lost", "two_pt"} <= captured, (
        "a full-PPR league's fumble and two-point scoring is absent from the weekly component "
        "line; reporting it as applied would claim a number we did not compute"
    )
    assert any(k.startswith("fg_made") or k.startswith("def_") for k in captured)


def test_the_coverage_report_reaches_the_wire():
    """A report computed and dropped on serialize is the E9.41 class — the store had it right and
    the surface never saw it. `coverage` is declared on the response model, so it cannot be."""
    assert "coverage" in C.NflWeeklyLeagueBoard.model_fields


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 6. ABSENCES — five causes, each reachable, none imputed
# ══════════════════════════════════════════════════════════════════════════════════════════════

def test_the_reasons_reuse_the_contract_where_they_mean_the_same_thing():
    """`position_not_projected` means exactly what it means in `ABSENCE_REASONS`, so it is reused
    verbatim rather than re-spelled — two spellings of one fact is how a consumer's switch
    statement silently stops matching."""
    assert "position_not_projected" in C.ABSENCE_REASONS
    assert "position_not_projected" in C.ROSTER_ABSENCE_REASONS


def test_no_row_is_ever_given_a_manifest_level_reason_it_cannot_know():
    """⛔ `no_gameday_roster_row` and `pit_gate_dropped` are REAL reasons, counted per SLATE on the
    manifest. Per player this route cannot tell which applies — so naming one would be a confident
    wrong explanation, which is worse than an honest "not in this week's projection" (NF1.7 (a);
    the NF-K1 symptom that sent two investigations at a join that was fine)."""
    unknowable = {"no_gameday_roster_row", "pit_gate_dropped"}
    assert unknowable & set(C.ABSENCE_REASONS) == unknowable, "the contract's reasons moved"
    assert not (unknowable & set(C.ROSTER_ABSENCE_REASONS))
    assert not (unknowable & set(WLB._ABSENCE_DETAIL))


@pytest.mark.parametrize(
    "roster_row, served, expected",
    [
        ({"name": "A Kicker", "position": "K"}, {"QB", "RB", "WR", "TE"}, "position_not_projected"),
        ({"name": "A Defence", "position": "DST"}, {"QB", "RB", "WR", "TE"}, "position_not_projected"),
        ({"name": "A Tight End", "position": "TE"}, {"QB", "RB", "WR"}, "position_absent_this_week"),
        ({"name": "A Receiver", "position": "WR"}, {"QB", "RB", "WR", "TE"}, "not_in_weekly_payload"),
        ({"name": "No Position", "position": ""}, {"QB", "RB", "WR", "TE"}, "roster_position_unknown"),
        ({"name": "", "position": "WR"}, {"QB", "RB", "WR", "TE"}, "roster_row_unnamed"),
    ],
)
def test_each_absence_cause_is_reachable_and_distinct(roster_row, served, expected):
    """⭐ EVERY REASON IS DRIVEN, not merely declared. A reason nothing can produce is decoration,
    and a reason two inputs produce is not a distinction (NF-C6b: an empty state meaning several
    things costs an investigation every time it recurs).

    ⚠️ Each case is isolating — a nameless row would ALSO have an unknown position, so the name is
    checked first and the fixtures differ in exactly one respect (NF-D17 §7)."""
    got = WLB.classify_absence(roster_row, served)
    assert got["reason"] == expected
    assert got["reason"] in C.ROSTER_ABSENCE_REASONS
    assert got["detail"], "an absence with no sentence is an empty state again"


def test_the_five_reasons_are_exactly_the_five_the_classifier_can_emit():
    """The declared tuple and the detail table must not drift apart — a reason with no sentence
    would render blank, and a sentence with no reason is unreachable."""
    assert set(C.ROSTER_ABSENCE_REASONS) == set(WLB._ABSENCE_DETAIL)


def test_a_bye_is_a_scored_zero_and_not_an_absence(weekly_players, full_ppr_cfg):
    """⚖️ A BYE IS NOT A MISSING PROJECTION. It is a DETERMINISTIC zero knowable at schedule
    release, so the player is PRESENT with `status="bye"` and scores 0.0 in any scoring — which is
    a different fact from "we have no row for him", and the contract keeps them apart."""
    byes = [p for p in weekly_players if p.get("status") == "bye"]
    assert byes, "the fixture carries no bye row; this clause would pass on nothing"
    out = _score(weekly_players, _roster_of(weekly_players), full_ppr_cfg)
    rows = {r["rosterName"]: r for r in out["rows"]}
    for p in byes:
        row = rows[p["name"]]
        assert row["absence"] is None, "a bye was reported as an absence"
        assert row["status"] == "bye"
        assert row["leaguePts"] == 0.0


def test_weekly_positions_is_read_off_the_rows_not_restated_from_the_constant(full_ppr_cfg):
    """🔴 NF-K1 — DERIVED, NEVER DECLARED. Returning `PROJECTED_POSITIONS` would report a position
    as served right through an outage in which it was not: the 2026-08-16 board published ZERO K
    and D/ST rows and every rostered kicker read "not matched", which points a reader at the join
    rather than at the gap. A position counts as served only if a row exists for it."""
    qbs_only = [{"id": "x", "name": "Only QB", "pos": "QB", "team": "BAL",
                 "status": "projected", "fpPpr": 1.0, "fpP10": 0.0, "fpP90": 2.0, "passYds": 25.0}]
    out = _score(qbs_only, [{"name": "Only QB", "position": "QB"}], full_ppr_cfg)
    assert out["weekly_positions"] == ["QB"]
    assert set(out["weekly_positions"]) < set(C.PROJECTED_POSITIONS)


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 7. THE ROUTE — entitlement, and the cache side decided before the handler was written
# ══════════════════════════════════════════════════════════════════════════════════════════════

def _route():
    """The route object, found by its ENDPOINT FUNCTION rather than by its path.

    ⚠️ LOAD-BEARING, and it was wrong in the first cut: looking it up by `ROUTE_PATH` — a constant
    in THIS file — meant renaming the real route to a CHILD of the free reads left every cache
    clause below reading the old string and passing. The clause would have tested its own constant
    rather than the served surface (the NF-C0e "reads the value back under the key the code wrote"
    shape). Found by the RED proof, not by review."""
    from app.backend.routers import fantasy

    hits = [
        r for r in fantasy.router.routes
        if getattr(r, "endpoint", None) is fantasy.nfl_weekly_league_board
    ]
    assert len(hits) == 1, f"expected exactly one weekly league-board route, found {len(hits)}"
    return hits[0]


def _served_path() -> str:
    """The path the route ACTUALLY serves — what every cache clause must be asked about."""
    return _route().path


def _dependency_calls(dependant) -> set:
    out = set()
    for d in dependant.dependencies:
        out.add(d.call)
        out |= _dependency_calls(d)
    return out


def test_the_route_is_gated_on_fantasy_access_and_not_on_the_free_league_quota():
    """🔒 THE ENTITLEMENT DECISION, PINNED BECAUSE IT IS A PRICING FACT.

    The SEASON twin `/nfl/league-board` sits on `personal_router`, so G100-C1's one free
    personalized league reaches it. This route must not: the free league is a quota grant against
    `PERSONALIZATION`, while the weekly component line is `DECISION_SUPPORT` — the capability whose
    own definition names "the weekly surfaces as they land", and which NF-C6-PH2 placed behind
    `require_fantasy_access` on `/nfl/weekly/projections-full`.

    Widening a sold capability by choosing a different router object would be a pricing change
    wearing a refactor's clothes. Read off the resolved dependency chain rather than the source, so
    a decorator moved to another router goes red here."""
    from app.backend.dependencies import (
        require_fantasy_access,
        require_personalized_league_access,
    )

    calls = _dependency_calls(_route().dependant)
    assert require_fantasy_access in calls, "the paid weekly line is not behind fantasy access"
    assert require_personalized_league_access not in calls, (
        "this route reaches the free personalized-league quota; that widens DECISION_SUPPORT to "
        "the free tier, which is a pricing decision and not a routing one"
    )


def test_the_route_reads_its_caller():
    """Per-caller by construction — it must take the `Request` the quota check needs. The free
    weekly reads deliberately take none; this one deliberately does."""
    import inspect
    from app.backend.routers import fantasy

    params = inspect.signature(fantasy.nfl_weekly_league_board).parameters
    assert "request" in params and "league_id" in params


def test_the_route_path_is_a_sibling_of_the_free_reads_and_not_a_child():
    """⛔ THE BREACH THIS AVOIDS, DEMONSTRATED RATHER THAN REASONED ABOUT. Both allowlists match a
    prefix followed by "/", so a route named `…/weekly/projections/league-board` would have
    INHERITED the FREE route's public cache rule and been served shared-cacheable — one
    subscriber's roster handed to the next caller (NF-EPIC 1: a gated route under a public prefix
    silently inherits that prefix's CDN rule).

    The sibling name collides with nothing, and the child form is scored here so the choice is
    visibly load-bearing instead of looking like a naming preference."""
    served = _served_path()
    assert served == ROUTE_PATH, (
        f"the route now serves {served!r}; this file's documented path is stale"
    )
    assert CG.public_cache_control(served) is None, (
        f"the paid weekly league board at {served!r} matched a PUBLIC cache rule"
    )
    hazard = "/fantasy/nfl/weekly/projections/league-board"
    assert CG.public_cache_control(hazard) is not None, (
        "the prefix hazard no longer exists, so this clause no longer demonstrates anything — "
        "re-derive the naming rule rather than deleting the check"
    )


def test_the_route_is_absent_from_the_cdn_allowlist_and_the_public_cache_rules():
    """Two lists, both of which would break the same way, so both are read."""
    served = _served_path()
    assert served not in CDN_ROUTE.read_text()
    assert not any(served.startswith(p) for p, _s, _w in CG._PUBLIC_CACHE_RULES)


def test_an_authorized_request_is_never_shared_cacheable():
    """Safe STRUCTURALLY rather than by memory: every request here carries `Authorization`, and
    `cache_control_for` answers `private, no-store` unconditionally when it sees one."""
    assert CG.cache_control_for(_served_path(), has_authorization=True, status_code=200) == (
        CG.PRIVATE_CACHE_CONTROL
    )


def test_the_paid_route_is_not_on_the_degrade_floor():
    """Degrade mode is the one-flip cost floor and it is an ALLOWLIST: what stays up is what we
    promise an anonymous visitor. A paid personalized roster is not that, so it sheds — which is
    the intended behaviour, pinned so nobody "fixes" it into the floor later."""
    assert CG.is_allowed_in_degrade(_served_path()) is False


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 8. COPY — projections and ranges, never an instruction
# ══════════════════════════════════════════════════════════════════════════════════════════════

def test_the_served_contract_makes_no_start_sit_or_opponent_claim():
    """Boundary (c): this surface renders projections and ranges. The optimizer that turns them
    into a CHOICE is NF-OPT1, and NF-W1 measured the matchup foil LOSING at all four positions, so
    an opponent claim would be contradicted by our own evidence.

    Scanned over the served NAMES, DESCRIPTIONS and string DEFAULTS — the only routes by which a
    claim reaches a reader — never over source files, which would fire on the champion's own
    `opponent_matchup__*` feature family (the NF-W7 over-eager-guard shape)."""
    texts = [
        (f"{m.__name__}.{n}", t)
        for m in (C.NflWeeklyLeagueRow, C.NflWeeklyLeagueBoard, C.NflWeeklyRosterAbsence)
        for n, f in m.model_fields.items()
        for t in (n, f.description or "", f.default if isinstance(f.default, str) else "")
    ]
    C.assert_no_matchup_claim(texts, where="the NF-WK-MT1 served contract")

    imperatives = ("start ", "sit ", "bench him", "must start", "you should", "we recommend")
    offending = [
        (where, phrase)
        for where, text in texts + [("SCORING_BASIS_NOTE", C.SCORING_BASIS_NOTE)]
        for phrase in imperatives
        if phrase in str(text).lower()
    ]
    assert not offending, f"the weekly lens contract issues a start/sit instruction: {offending}"


def test_the_scope_note_quotes_no_measured_figure():
    """⛔ A TYPED MAGNITUDE DRIFTS SILENTLY ON THE NEXT RE-SCORE. The coherence gap is real and
    measured, and the honest route to rendering it is a coherence block written by the box beside
    the figures `component_coherence` already computes — which the PM declined for now
    (2026-09-14). So the note states the MECHANISM in words and carries no number."""
    import re

    assert not re.search(r"\d+\.\d{2,}", C.SCORING_BASIS_NOTE), (
        "the scope note carries a measured figure; it would drift on the next re-score"
    )


# ══════════════════════════════════════════════════════════════════════════════════════════════
# 9. THE ROUTE, ACTUALLY INVOKED — because "wired" is not "invoked" (NF-C0e)
# ══════════════════════════════════════════════════════════════════════════════════════════════
# Everything above reasons about the route from its signature, its dependency chain and its path.
# None of that proves a request reaches the adapter and comes back shaped. These clauses drive the
# REAL ASGI app.
#
# Raw ASGI rather than starlette's `TestClient`, for the reason E9.56's suite documents: TestClient
# needs `httpx` (absent here) and cannot set the `aws.event` scope key Mangum uses to carry the API
# Gateway authorizer context — the one thing separating a real account from a forged token.

_LEAGUE_ID = "lg-mt1"


def _call(path: str, query: str = "", *, aws_event: dict | None = None):
    """Drive the real app. Returns `(status, parsed_body_or_raw_bytes)`."""
    import anyio

    from app.backend.main import app

    out: dict = {}
    parts: list[bytes] = []

    async def run():
        scope = {
            "type": "http",
            "asgi": {"version": "3.0", "spec_version": "2.1"},
            "http_version": "1.1",
            "method": "GET",
            "scheme": "https",
            "path": path,
            "raw_path": path.encode(),
            "query_string": query.encode(),
            "root_path": "",
            "headers": [(b"host", b"testserver"), (b"content-type", b"application/json")],
            "client": ("test", 1),
            "server": ("testserver", 443),
        }
        if aws_event is not None:
            scope["aws.event"] = aws_event

        async def receive():
            return {"type": "http.request", "body": b"", "more_body": False}

        async def send(message):
            if message["type"] == "http.response.start":
                out["status"] = message["status"]
            elif message["type"] == "http.response.body":
                parts.append(message.get("body", b""))

        await app(scope, receive, send)

    anyio.run(run)
    payload = b"".join(parts)
    try:
        return out["status"], json.loads(payload)
    except Exception:  # noqa: BLE001 — a 401 body may not be JSON, which is a valid outcome
        return out["status"], payload


def _event(groups: str = "[]", sub: str = "user-1"):
    """The authorizer context as Mangum delivers it. ⚠️ `cognito:groups` is BRACKETED and
    SPACE-separated even for one group — NOT comma-separated (G100-C0-MFA measured it); a fixture
    written in the comma form would restate the parser's own assumption and pass on nothing."""
    return {
        "requestContext": {
            "authorizer": {"jwt": {"claims": {"sub": sub, "cognito:groups": groups}}}
        }
    }


@pytest.fixture
def served(monkeypatch, weekly_players, full_ppr_cfg):
    """A subscriber with ONE saved league whose roster mixes every outcome this route can produce:
    a scored starter, a bye, a kicker we never project, and a name that matches nothing."""
    from app.backend.routers import fantasy
    from app.backend.services import cost_guardrails, dynamo, jwt_verify

    # The limiter is PROCESS-GLOBAL and stateful, so an earlier file's requests can deplete the
    # bucket and surface here as payload-shape failures rather than as throttling (G100-C1).
    cost_guardrails.get_limiter().reset()

    bye = next(p["name"] for p in weekly_players if p.get("status") == "bye")
    scored = next(p["name"] for p in weekly_players if p.get("status") == "projected")
    record = {
        **full_ppr_cfg,
        "league_id": _LEAGUE_ID,
        "sport": "nfl",
        "name": "Sunday Money",
        "created_at": "2026-09-01T00:00:00Z",
        "imported_roster": [
            {"name": scored, "position": "QB", "team": "BAL", "starter": True},
            {"name": bye, "position": "RB", "team": "SF", "starter": True},
            {"name": "A Kicker", "position": "K", "team": "BAL", "starter": True},
            {"name": "Never Drafted", "position": "WR", "team": "FA", "starter": False},
        ],
    }
    monkeypatch.setattr(dynamo, "list_fantasy_leagues", lambda uid: [record])

    manifest = {
        "absences": [{"reason": "position_not_projected", "n": 3, "detail": "K/DST not projected"}],
        "projection_day": "2026-09-14T17:00:00Z",
    }

    def load(rel_key, sport="nfl"):
        if rel_key.endswith("current.json"):
            return {"season": 2026, "week": 2}
        if rel_key.endswith("manifest.json"):
            return manifest
        if rel_key.endswith("players.json"):
            return {"season": 2026, "week": 2, "generated_at": "2026-09-14T12:00:00Z",
                    "players": weekly_players}
        return None

    monkeypatch.setattr(fantasy, "_load_json", load)
    # No network: an unreachable JWKS makes every presented token unverifiable, which is both the
    # anonymous path below and a proof the verifier fails CLOSED when it is unavailable.
    monkeypatch.setattr(jwt_verify, "_fetch_jwks", lambda: None)
    jwt_verify.reset_jwks_cache()
    return {"scored": scored, "bye": bye}


def test_an_anonymous_read_is_refused(served):
    """The entitlement-refused read. 401 — "sign in" — because identity resolves before
    entitlement; there is no account to check a membership against."""
    status, _ = _call(ROUTE_PATH, f"league_id={_LEAGUE_ID}&season=2026&week=2")
    assert status == 401


def test_a_signed_in_account_without_a_membership_is_refused(served):
    """403, not 401: a real gateway-validated account with no fantasy entitlement. This is the
    clause that proves the free personalized-league tier does NOT reach the weekly lens — the
    pricing boundary, driven rather than asserted."""
    status, body = _call(
        ROUTE_PATH, f"league_id={_LEAGUE_ID}&season=2026&week=2", aws_event=_event("[]")
    )
    assert status == 403, body


def test_a_league_the_caller_does_not_own_is_indistinguishable_from_one_that_does_not_exist(served):
    """404 rather than 403 — an id they do not own must not be confirmable by its error code."""
    status, _ = _call(
        ROUTE_PATH, "league_id=someone-elses&season=2026&week=2",
        aws_event=_event("[subscriber]"),
    )
    assert status == 404


def test_a_subscriber_gets_a_scored_roster_with_every_absence_cause_distinguishable(served):
    """⭐ THE END-TO-END READ, BOTH WAYS AT ONCE: a scored starter, a bye, a position we do not
    project, and a name that matched nothing — in one response, each rendering as a different,
    named state rather than as four identical blanks (NF-C6b)."""
    status, body = _call(
        ROUTE_PATH, f"league_id={_LEAGUE_ID}&season=2026&week=2",
        aws_event=_event("[subscriber]"),
    )
    assert status == 200, body
    rows = {r["rosterName"]: r for r in body["rows"]}
    assert len(rows) == 4

    hit = rows[served["scored"]]
    assert hit["absence"] is None
    assert hit["leaguePts"] is not None and hit["pprPts"] is not None
    assert hit["bandP10"] is not None and hit["bandP90"] is not None

    assert rows[served["bye"]]["status"] == "bye"
    assert rows[served["bye"]]["absence"] is None
    assert rows["A Kicker"]["absence"]["reason"] == "position_not_projected"
    assert rows["Never Drafted"]["absence"]["reason"] == "not_in_weekly_payload"

    # the honest framing travels with the numbers
    assert body["band_scoring_system_id"] == "ppr"
    assert body["scoring_source"] == "league_settings"
    assert body["scoring_basis_note"]
    assert body["weekly_positions"]
    assert body["absences"], "the manifest's slate-level counts did not reach the wire"
    assert {t["verdict"] for t in body["coverage"]["terms"]} & {"applied", "captured"}


def test_the_response_carries_no_component_line(served):
    """⛔ The caller is entitled to the stat line and can fetch it from
    `/nfl/weekly/projections-full`; shipping it again per rostered player would multiply the
    response for no question this surface asks.

    ⚠️ SCOPED TO `rows`, AND THE SCOPING IS LOAD-BEARING RATHER THAN LAZY — the first cut scanned
    the whole serialized body and went red on `"rec"`, which is the COVERAGE REPORT naming the
    league's reception scoring RULE. `STAT_FIELD["rec"] == "rec"`, so the scoring key and the
    payload field are the same string, and a whole-body scan cannot tell a rule NAME from a
    player's stat VALUE (the NF-W7 `'temp' ⊂ 'attempt'` over-eager-guard shape). What must not
    reach the wire is a per-player component, and that lives in `rows`."""
    _status, body = _call(
        ROUTE_PATH, f"league_id={_LEAGUE_ID}&season=2026&week=2",
        aws_event=_event("[subscriber]"),
    )
    paid = set(C.WEEKLY_COMPONENT_FIELD.values()) | {C.QUANTILE_VECTOR_FIELD}

    # ⭐ THE CONTRACT IS THE ENFORCEMENT, and the RED proof is what established that: an undeclared
    # field cannot reach the wire at all, because Pydantic drops it on serialize (E9.41, working in
    # our favour for once). So a component could only ever arrive by being DECLARED here — which is
    # the mutation this clause must catch, and a rows-only scan would not have.
    assert not (paid & set(C.NflWeeklyLeagueRow.model_fields)), (
        "the lens contract declares a per-player component field; the stat line belongs on "
        "/nfl/weekly/projections-full, which this caller is already entitled to"
    )

    assert body["rows"], "no rows came back; this clause would pass on an empty response"
    leaked = {field for row in body["rows"] for field in paid if field in row}
    assert not leaked, f"per-player component fields reached the lens response: {sorted(leaked)}"

    # …and the coverage report is still there, so the scoping did not gut the clause's context.
    assert body["coverage"]["terms"]


def test_an_unpublished_week_is_a_404_and_not_an_empty_roster(monkeypatch, served):
    """The honest pre-publish state. An empty roster would read as "you have nobody", which is a
    different and false statement — and it is the state the whole product is in until the first
    weekly publish lands.

    ⚠️ ASKS FOR AN EXPLICIT `week`, and that is load-bearing rather than incidental: omitting it
    resolves through `current.json` and 404s on the POINTER, several lines before the payload read
    this clause is actually about. The RED proof caught that — a break in the payload read left the
    clause green because the request never got that far. The pointer path has its own clause below."""
    from app.backend.routers import fantasy

    monkeypatch.setattr(
        fantasy, "_load_json",
        lambda rel_key, sport="nfl": {"season": 2026, "week": 2} if rel_key.endswith("current.json") else None,
    )
    status, _ = _call(
        ROUTE_PATH, f"league_id={_LEAGUE_ID}&season=2026&week=2", aws_event=_event("[subscriber]")
    )
    assert status == 404


def test_a_missing_week_pointer_is_a_404_too(monkeypatch, served):
    """The other unpublished path: no `current.json` to resolve `week` through. A 404 rather than a
    guess at "the highest week directory that exists", which would silently serve a stale week
    whenever a publish half-landed (the reasoning `/nfl/weekly/manifest` already carries)."""
    from app.backend.routers import fantasy

    monkeypatch.setattr(fantasy, "_load_json", lambda rel_key, sport="nfl": None)
    status, _ = _call(
        ROUTE_PATH, f"league_id={_LEAGUE_ID}&season=2026", aws_event=_event("[subscriber]")
    )
    assert status == 404
