#!/usr/bin/env python3
"""NF-WK-FE1 — the WEEKLY fixtures, generated by the SHIPPING writer and reducer.

    uv run python frontend/e2e/fixtures/build-nfl-weekly.py

⭐ WHY GENERATED RATHER THAN CAPTURED, AND WHAT RETIRES IT. Nothing weekly has ever been published:
measured 2026-09-13, `GET /fantasy/nfl/weekly/{manifest,projections}` both answer **404
`{"detail":"Weekly projection not found"}`** from the Lambda (not a 401 from the gateway — the
authorizer is already `NONE`, so the route is anonymously reachable and simply has nothing behind
it). There is therefore no payload to capture. ⚠️ RETIRE THESE ON THE FIRST PUBLISH and re-capture
raw from the live API (E9.64b): a fixture derived from the writer can only ever confirm the shape we
already assumed, and the whole point of a capture is that it can disconfirm it.

⭐ NOTHING BELOW IS AUTHORED BY HAND. Every player row leaves through `weekly_serving.build_players`
— the function the box calls — and both blobs are validated against `app/backend/models/nfl_weekly.py`
on the way out. The FREE blob is then produced by the SHIPPING reducer
`nfl_weekly.public_weekly_payload`, never by deleting keys here: an entitlement spec whose "free"
fixture was hand-reduced would be asserting against my idea of the paywall rather than against the
paywall, and `paid_weekly_fields_present` is run over the result as the audit (the contract's own
instrument) rather than trusted.

⚠️ THE SYNTHETIC INPUT IS THE `qmap`/`comps`/`ros` TRIPLE, NOT THE PAYLOAD. Fitting the champion
needs the lakehouse and is an operator-scale job; what this script stands in for is the MODEL
OUTPUT, and the assembly from model output to contract-shaped payload — which is the part the page
consumes and therefore the part a fixture has to be honest about — is the real code.

WHAT EACH ROW IS HERE TO MAKE REACHABLE (a single "everything present" week would let a component
that renders one em-dash for the whole page pass):

  * a QB / RB / WR / TE  — all four projected positions, so a per-position render cannot be tested
                           on one and assumed for the rest.
  * a BYE                — `status="bye"`, the identity zero at every level. NOT a missing
                           projection: it must render as a stated zero, and its band must be 0–0
                           rather than an em-dash.
  * a FINAL-WEEK player  — `ros*` NULL with `rosWeeks` 0. A different fact from a ROS of zero, and
                           the contract declares it null rather than omitting it.
  * a WEEK-1 ROOKIE      — `histWeeks = 0`. The evidence base the spec requires visible: a
                           projection built on position and a rookie flag alone.
  * a COMPONENT-LESS row — every paid component `None` while the points head is present, which is
                           what the independent-heads design permits and what proves the stat
                           substrate renders its own absence rather than zeros.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[3]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from app.backend.models import nfl_weekly as C  # noqa: E402
from quant_sports_intel_models.football.nfl.fantasy import weekly_projection as WP  # noqa: E402
from quant_sports_intel_models.football.nfl.fantasy import weekly_serving as WS  # noqa: E402

API = REPO / "frontend/e2e/fixtures/api"
OUT_FULL = API / "fantasy-nfl-weekly-players-entitled.synthetic.json"
OUT_FREE = API / "fantasy-nfl-weekly-players-free.synthetic.json"
OUT_MANIFEST = API / "fantasy-nfl-weekly-manifest.synthetic.json"
#: ⭐ NOT an API payload — contract METADATA, which is why it sits beside this script rather
#: than in `api/`. See `_contract_defaults` for what it is for.
OUT_DEFAULTS = Path(__file__).resolve().parent / "nfl-weekly-contract-defaults.json"

SEASON, WEEK = 2026, 2
GENERATED_AT = "2026-09-16T11:30:00+00:00"


def _q(mean: float, spread: float) -> np.ndarray:
    """A plausible 39-level predictive: a right-skewed ladder, which is what a fantasy week is.

    Built from `WP.Q_LEVELS` itself rather than a literal list, so a ladder change moves the fixture
    with the model instead of leaving it silently describing a retired grid.
    """
    z = np.asarray(WP.Q_LEVELS, dtype=float)
    # lognormal-ish: floored at zero (a week cannot score negative in PPR terms here) and fatter on
    # the right, so p90 - point is wider than point - p10, as a real weekly predictive is.
    vec = np.maximum(0.0, mean + spread * (np.log(z / (1 - z))) * 0.42)
    return np.sort(vec)


def _rows() -> tuple[pd.DataFrame, dict[str, np.ndarray], pd.DataFrame, pd.DataFrame, dict, dict]:
    """The synthetic model output, in the exact shapes `build_players` consumes."""
    # ⚠️ `ros_mean` IS ITS OWN COLUMN, NOT `mean * weeks`. Deriving it would give the BYE row a
    # rest-of-season of ZERO — which is wrong in a way a broken render would pass: a bye is one
    # week off, and the player's remaining fifteen are unaffected. The whole point of showing ROS
    # beside a bye is that the two numbers disagree, so the fixture has to make them disagree.
    spec = [
        # gsis, name,               pos,  team, opp,   home,  bye,   mean, spread, hist, wks, ros
        ("00-0034796", "Lamar Jackson",    "QB", "BAL", "CLE", True,  False, 21.4, 7.9, 21, 15, 301.7),
        ("00-0036389", "Justin Jefferson", "WR", "MIN", "GB",  False, False, 17.8, 8.6, 19, 15, 251.0),
        ("00-0037746", "Breece Hall",      "RB", "NYJ", "NE",  True,  False, 14.2, 7.1, 17, 15, 200.2),
        ("00-0036973", "Trey McBride",     "TE", "ARI", "SF",  False, False, 11.6, 5.4, 16, 15, 163.6),
        # THE BYE — identity zero at every level this week, `opp`/`home` null: a stated zero, not a
        # gap. Its ROS is LARGE and unaffected, which is exactly the disagreement above describes.
        ("00-0033873", "Christian McCaffrey", "RB", "SF", None, None, True, 0.0, 0.0, 18, 15, 214.5),
        # THE WEEK-1 ROOKIE — no prior modeled weeks at all. `histWeeks = 0` is the evidence base.
        ("00-0039918", "Caleb Downs",      "WR", "HOU", "JAX", True,  False, 6.9, 5.2, 0, 15, 97.3),
        # THE FINAL-WEEK SHAPE — no remaining horizon, so `ros*` is NULL and `rosWeeks` is 0.
        ("00-0035676", "A.J. Brown",       "WR", "PHI", "DAL", False, False, 16.1, 8.2, 20, 0, 0.0),
        # COMPONENT-LESS — the points head with no advisory line behind it.
        ("00-0038542", "Jaxon Smith-Njigba", "WR", "SEA", "LAR", True, False, 13.4, 6.8, 14, 15, 188.9),
    ]

    universe = pd.DataFrame(
        [{"gsis_id": g, "position": p, "team": t, "is_bye": b, "opponent": o,
          "is_home": (np.nan if h is None else float(h))}
         for g, _n, p, t, o, h, b, _m, _s, _hw, _rw, _r in spec]
    )
    names = {g: n for g, n, *_ in spec}
    hist = {g: hw for g, _n, _p, _t, _o, _h, _b, _m, _s, hw, _rw, _r in spec}

    qmap = {
        g: _q(m, s)
        for g, _n, _p, _t, _o, _h, b, m, s, _hw, _rw, _r in spec
        if not b
    }

    # ROS — indexed by gsis_id, the shape `build_players` looks up. A player ABSENT from this index
    # is exactly how the writer emits the final-week null, so A.J. Brown is simply left out rather
    # than given a null row: the absence IS the mechanism.
    # ⚠️ THE ROS BAND IS WIDER THAN sqrt(weeks) x the WEEKLY spread would give a bye row, whose
    # weekly spread is 0. Using a fixed per-week dispersion keeps every band honest-looking without
    # letting the bye's zero weekly spread collapse its rest-of-season interval to a point.
    ros = pd.DataFrame(
        [{"gsis_id": g, "ros_mean": r,
          "ros_q10": round(r - 6.4 * (rw ** 0.5) * 1.28, 4),
          "ros_q90": round(r + 6.4 * (rw ** 0.5) * 1.28, 4),
          "n_weeks": rw}
         for g, _n, _p, _t, _o, _h, _b, _m, _s, _hw, rw, r in spec if rw > 0]
    ).set_index("gsis_id")

    # The advisory component head. Deliberately missing Smith-Njigba entirely.
    comp_spec = {
        "00-0034796": dict(attempts=32.1, passing_yards=239.4, passing_tds=1.6,
                           passing_interceptions=0.7, carries=8.4, rushing_yards=51.2,
                           rushing_tds=0.4, targets=0.0, receptions=0.0, receiving_yards=0.0,
                           receiving_tds=0.0),
        "00-0036389": dict(attempts=0.0, passing_yards=0.0, passing_tds=0.0,
                           passing_interceptions=0.0, carries=0.3, rushing_yards=1.9,
                           rushing_tds=0.0, targets=9.7, receptions=6.4, receiving_yards=88.3,
                           receiving_tds=0.6),
        "00-0037746": dict(attempts=0.0, passing_yards=0.0, passing_tds=0.0,
                           passing_interceptions=0.0, carries=16.8, rushing_yards=72.1,
                           rushing_tds=0.5, targets=4.1, receptions=3.2, receiving_yards=25.6,
                           receiving_tds=0.1),
        "00-0036973": dict(attempts=0.0, passing_yards=0.0, passing_tds=0.0,
                           passing_interceptions=0.0, carries=0.1, rushing_yards=0.4,
                           rushing_tds=0.0, targets=7.2, receptions=5.3, receiving_yards=57.8,
                           receiving_tds=0.4),
        "00-0033873": dict.fromkeys(C.WEEKLY_COMPONENT_STAT_KEY, 0.0),
        "00-0039918": dict(attempts=0.0, passing_yards=0.0, passing_tds=0.0,
                           passing_interceptions=0.0, carries=0.2, rushing_yards=1.1,
                           rushing_tds=0.0, targets=4.6, receptions=2.9, receiving_yards=34.7,
                           receiving_tds=0.2),
        "00-0035676": dict(attempts=0.0, passing_yards=0.0, passing_tds=0.0,
                           passing_interceptions=0.0, carries=0.4, rushing_yards=2.8,
                           rushing_tds=0.0, targets=8.9, receptions=5.7, receiving_yards=81.4,
                           receiving_tds=0.5),
    }
    comps = pd.DataFrame(
        [{"gsis_id": g, **{f"proj_{k}": v for k, v in d.items()}} for g, d in comp_spec.items()]
    )
    return universe, qmap, comps, ros, names, hist


def build() -> tuple[dict, dict, dict]:
    universe, qmap, comps, ros, names, hist = _rows()

    # ⭐ THE SHIPPING ASSEMBLER. Every field below this line is the writer's, not this script's.
    players = WS.build_players(universe, qmap, comps, ros, names=names, hist_weeks=hist)

    by_pos = {p: sum(1 for r in players if r["pos"] == p) for p in C.PROJECTED_POSITIONS}
    manifest = {
        "season": SEASON,
        "week": WEEK,
        "generated_at": GENERATED_AT,
        "projection_day": "2026-09-17T00:15:00+00:00",
        "n_players": len(players),
        "n_by_position": by_pos,
        "n_bye": sum(1 for p in players if p["status"] == "bye"),
        "n_rookies": sum(1 for p in players if hist.get(p["id"], 0) == 0),
        # ⚠️ THE REASON STRINGS ARE THE RUNNER'S OWN, copied deliberately rather than paraphrased:
        # the page renders `detail` VERBATIM, so a fixture that invented its own wording would be
        # testing the render against prose no reader will ever meet. All THREE reasons are present
        # and non-zero, because a page that distinguishes three causes must be driven by three.
        "absences": [
            {"reason": "position_not_projected", "n": 64,
             "detail": ("NF-W1's champion covers QB/RB/WR/TE only — it was never fitted on K or "
                        "D/ST, so no weekly projection exists for them. Excluded by design, not "
                        "missing.")},
            {"reason": "no_gameday_roster_row", "n": 311,
             "detail": ("on the roster feed but not game-day active/inactive for this week "
                        "(statuses served: ['ACT', 'INA'])")},
            {"reason": "pit_gate_dropped", "n": 2,
             "detail": ("game-day rostered but carrying no predictive after the point-in-time "
                        "gate; dropped rather than fabricated")},
        ],
        "pit_weeks_checked": 19,
        "pit_records_checked": 41822,
        "pit_rows_dropped": 2,
        "input_vintage": {
            "rosters_as_of": "2026-09-16T09:02:11+00:00",
            "schedule_as_of": "2026-09-16T09:02:14+00:00",
            "stats_as_of": "2026-09-16T09:01:58+00:00",
            "snaps_as_of": "2026-09-16T09:02:03+00:00",
            "train_through_season": SEASON,
            "train_through_week": WEEK - 1,
        },
        "lineage": {
            "served_version": WS.SERVED_VERSION,
            "base_model_version": WS.BASE_MODEL_VERSION,
            "point_model_version": WS.POINT_MODEL_VERSION,
            "interval_model_version": WS.INTERVAL_MODEL_VERSION,
        },
    }
    payload = {"season": SEASON, "week": WEEK, "generated_at": GENERATED_AT, "players": players}

    # ── the contract, as the box enforces it ──────────────────────────────────────────────────
    # ⚠️ BOTH BLOBS ARE THE VALIDATED DUMP (NF-INC-0917B). This block said "the contract, as the box
    # enforces it" and mirrored the box on the manifest while DISCARDING the payload's validation —
    # so these fixtures carried `scoring_system_id` on the manifest and not on the players blob,
    # which is the split production is in today. A fixture generator is the closest thing this repo
    # has to a second implementation of the writer, and the two had drifted in exactly the place
    # that mattered: the E2E suite could not reproduce the served shape because it was a third
    # shape, neither the contract nor the wire.
    manifest = C.NflWeeklyManifest.model_validate(manifest).model_dump()
    payload = C.NflWeeklyPayload.model_validate(payload).model_dump()
    C.assert_best_alpha_is_zero(manifest)

    # ── the FREE blob, produced by the SHIPPING reducer ────────────────────────────────────────
    free = C.public_weekly_payload(payload)
    leaked = C.paid_weekly_fields_present(free)
    if leaked:
        raise SystemExit(f"the reducer left paid fields on the free blob: {sorted(leaked)}")
    # And the other direction: a free fixture that carries NOTHING paid because the PAID one was
    # empty too would satisfy the check above vacuously (NF1.7(a)).
    if not C.paid_weekly_fields_present(payload):
        raise SystemExit("the entitled blob carries no paid field at all — the gate spec would "
                         "pass on nothing")
    return manifest, payload, free


def _contract_defaults() -> dict[str, list[str]]:
    """Which fields each weekly model DEFAULTS — derived from the models, for the E2E to strip.

    ⛔⛔ THIS EXISTS SO THE DEGENERATE FIXTURE IS NOT A HAND LIST (NF-INC-0917B).

    PR #1143 gave `weekly-projections.spec.ts` a payload with `framing` deleted, because that was
    the key production omitted. But the mechanism omits EVERY defaulted field — the live manifest
    was short of nine — and `framing` was merely the only one the page dereferenced. A degenerate
    naming one key by hand therefore covers today's page rather than the defect: the first time a
    component reads `interval_lo_level`, the fixture that could reproduce the failure would have to
    be remembered and extended, which is exactly the remembering that fails.

    Deriving the set from `model_fields` means a field added with a default joins the degenerate on
    the next fixture build, with nobody in the loop. The TypeScript spec cannot introspect pydantic,
    so the authority has to travel as data — the same reason `PAID_WEEKLY_PLAYER_FIELDS` is derived
    from the scorer's own map rather than typed out.
    """
    return {
        model.__name__: sorted(n for n, f in model.model_fields.items() if not f.is_required())
        for model in (C.NflWeeklyManifest, C.NflWeeklyLineage, C.NflWeeklyPlayer)
    }


def main() -> None:
    manifest, payload, free = build()
    defaults = _contract_defaults()
    if "framing" not in defaults["NflWeeklyManifest"]:
        raise SystemExit("`framing` is no longer a DEFAULTED manifest field — the degenerate "
                         "fixture this file feeds would stop reproducing the outage")
    OUT_DEFAULTS.write_text(json.dumps(defaults, indent=2, sort_keys=True) + "\n")
    print(f"wrote {OUT_DEFAULTS.relative_to(REPO)} "
          f"({sum(len(v) for v in defaults.values())} defaulted field(s))")
    for path, blob in ((OUT_MANIFEST, manifest), (OUT_FULL, payload), (OUT_FREE, free)):
        path.write_text(json.dumps(blob, indent=2, sort_keys=False) + "\n")
        print(f"wrote {path.relative_to(REPO)} ({path.stat().st_size:,} bytes)")
    paid = sorted(C.paid_weekly_fields_present(payload))
    print(f"paid fields on the entitled blob: {len(paid)} — {paid}")
    print(f"players: {len(payload['players'])}  "
          f"bye: {sum(1 for p in payload['players'] if p['status'] == 'bye')}  "
          f"ros-null: {sum(1 for p in payload['players'] if p['rosPpr'] is None)}  "
          f"histWeeks=0: {sum(1 for p in payload['players'] if p['histWeeks'] == 0)}")


if __name__ == "__main__":
    main()
