#!/usr/bin/env python3
"""NCAAF-P3.2 — the NCAAF fixture that CANNOT be captured, generated by the shipping builder.

    uv run python frontend/e2e/fixtures/build-ncaaf-degraded.py

⭐ THE HAPPY PATH IS CAPTURED, NOT GENERATED. `ncaaf-manifest.json` and
`ncaaf-slate-2026-08-29.json` are verbatim production bytes (`capture-fixtures.mjs`). This script
exists only for the two shapes the live wire cannot produce today, and each is the output of the
SHIPPING builder rather than an authored payload — E9.63's rule is that a hand-written fixture
encodes the assumption under test, and NF-C0e's is that a fixture derived from the code's own
output cannot disconfirm it. So nothing below writes a field by hand: every blob leaves through
`payloads._market()` / `payloads.build_game_payload()`, which validate against the Pydantic
contract in `app/backend/models/ncaaf.py` on the way out.

⚠️ IT USED TO BUILD TWO. NCAAF-P3.3 RETIRED THE MARKET ONE, and the reason is the rule this
script's own header states. `ncaaf-slate-2026-08-29-market.synthetic.json` attached three real 2025
closes to the captured slate because at capture time every game on the wire was `unavailable` and
the market-AVAILABLE branch had nothing to capture. NCAAF-ODDS-LIVE's ahead-of-kickoff feed changed
that: the SAME URL now returns seven priced games and one without a line, captured verbatim as
`ncaaf-slate-2026-08-29-mixed.json`. A generated fixture is a stand-in for a payload nobody can
capture — once the payload exists, keeping the stand-in means testing the render against a shape
derived from the transform under test, which can only ever confirm what we already assumed (E9.64b).

ncaaf-slate-degraded.synthetic.json — THE OPTIONAL-FIELD FLOOR.
     Built by feeding DELIBERATELY SPARSE snapshot rows to `build_game_payload`, so the payload is
     exactly what the writer would emit for a row missing those columns rather than a guess about
     it. Four games, each missing something different, because a single "everything is null" game
     would let a component that renders one em-dash for the whole card pass:
       * no distribution at all (mu/sigma/quantiles all absent) — can a curve be drawn? no. say so.
       * no win probability
       * no quantile ladder but mu+sigma present — the curve's PARAMETRIC fallback
       * no team names / no kickoff time, `start_time_tbd` true
     ⚠️ `market_read_failed` (the OTHER null-market cause) is on the fourth game, because
     "nobody has priced this yet" and "we could not read the market" are different facts and the
     contract's `reason` exists precisely so a surface can say which (NF-C6b).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from app.backend.models import ncaaf as contract  # noqa: E402
from quant_sports_intel_models.football.ncaaf.serving import payloads  # noqa: E402

FIXTURES = REPO / "frontend/e2e/fixtures"
API = FIXTURES / "api"
CAPTURED_SLATE = API / "ncaaf-slate-2026-08-29.json"
OUT_DEGRADED = API / "ncaaf-slate-degraded.synthetic.json"

def _ladder(target: str, values: dict[float, float]) -> dict:
    return {payloads._q_col(target, lvl): v for lvl, v in values.items()}


def build_degraded_slate() -> dict:
    """Four sparse snapshot ROWS → the payload the writer would emit for them."""
    day = "2026-09-05"
    base = {
        "season": 2026, "game_day": day, "season_type": "regular", "cfbd_week": 2,
        "is_neutral_site": False, "is_conference_game": True,
        "home_team_id": 1, "away_team_id": 2,
    }

    # 1 — no distribution at all. The card must say a curve cannot be drawn, not draw a flat line.
    no_dist = {
        **base, "game_id": 900000001, "commence_time": "2026-09-05T16:00:00.000Z",
        "start_time_tbd": False,
        "home_team": "Curveless State", "away_team": "No Params Tech",
        "home_conference": "Big 12", "away_conference": "Big 12",
        "p_home_win": 0.55,
    }

    # 2 — no win probability, but a full distribution. The headline number is the one thing this
    #     surface leads with, so its absence has to be survivable on its own.
    no_wp = {
        **base, "game_id": 900000002, "commence_time": "2026-09-05T19:30:00.000Z",
        "start_time_tbd": False,
        "home_team": "Probabilityless A&M", "away_team": "Interval Normal",
        "home_conference": "SEC", "away_conference": "SEC",
        "mu_margin": 6.0, "sigma_margin": 16.5, "margin_interval_width": 42.3,
        **_ladder("margin", {0.05: -21.1, 0.10: -15.1, 0.25: -5.1, 0.50: 6.0,
                             0.75: 17.1, 0.90: 27.2, 0.95: 33.2}),
        "mu_total": 52.0, "sigma_total": 17.0, "total_interval_width": 43.6,
        **_ladder("total", {0.05: 24.0, 0.10: 30.2, 0.25: 40.5, 0.50: 52.0,
                            0.75: 63.5, 0.90: 73.8, 0.95: 80.0}),
    }

    # 3 — mu + sigma but NO quantile ladder: the curve's PARAMETRIC fallback, and the only fixture
    #     in the suite that can reach it. Note the served interval is absent too (it is read off
    #     the ladder), which is what makes "the band is served, never recomputed" testable.
    no_ladder = {
        **base, "game_id": 900000003, "commence_time": "2026-09-05T23:00:00.000Z",
        "start_time_tbd": False,
        "home_team": "Parametric Fallback U", "away_team": "Ladderless College",
        "home_conference": "ACC", "away_conference": "ACC",
        "p_home_win": 0.41,
        "mu_margin": -4.0, "sigma_margin": 16.8,
        "mu_total": 57.5, "sigma_total": 17.4,
    }

    # 4 — no team names, no kickoff instant, `start_time_tbd`, and the OTHER market-null cause.
    anonymous = {
        **base, "game_id": 900000004, "commence_time": None, "start_time_tbd": True,
        "p_home_win": 0.5,
        "mu_margin": 0.0, "sigma_margin": 16.6, "margin_interval_width": 42.5,
        **_ladder("margin", {0.05: -27.3, 0.10: -21.3, 0.25: -11.2, 0.50: 0.0,
                             0.75: 11.2, 0.90: 21.2, 0.95: 27.3}),
        "mu_total": 55.0, "sigma_total": 17.1,
        **_ladder("total", {0.05: 26.9, 0.10: 33.1, 0.25: 43.5, 0.50: 55.0,
                            0.75: 66.5, 0.90: 76.9, 0.95: 83.1}),
    }

    games = []
    for row in (no_dist, no_wp, no_ladder, anonymous):
        # `game_day_for` needs a kickoff instant; the TBD game has none, so the writer's own
        # `or ""` fallback would file it under "". The slate key is the day it was written under,
        # so set it explicitly here exactly as `build_slate_payloads` groups on it.
        payload = payloads.build_game_payload(
            row, market_row=None, market_read_failed=(row["game_id"] == 900000004))
        payload["game_day"] = day
        games.append(payload)

    slate = {
        "sport": "ncaaf", "game_day": day, "season": 2026,
        "generated_at": "2026-08-25T01:35:44.000Z", "n_games": len(games), "games": games,
        "framing": contract.NcaafHonestFraming().model_dump(),
    }
    return contract.NcaafSlate.model_validate(slate).model_dump()


def main() -> int:
    for out, blob in ((OUT_DEGRADED, build_degraded_slate()),):
        out.write_text(json.dumps(blob, indent=2) + "\n")
        print(f"wrote {out.relative_to(REPO)}  {out.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
