from pipeline.assets.dbt_assets import baseball_dbt_assets
from pipeline.assets.historical_matches_asset import parlay_historical_matches_catchup

all_assets = [baseball_dbt_assets, parlay_historical_matches_catchup]
