// auction-optimizer.ts — the LIVE auction optimizer (NF-C5). A faithful TS port of the validated
// Python engine (quant_sports_intel_models/fantasy_engine/auction.py), kept in lock-step with it.
//
// ⭐⭐ THE TWO ARE PINNED TO EACH OTHER BY A GOLDEN VECTOR FILE, NOT BY A COMMENT.
// `fantasy_engine/auction_vectors.json` is generated by the Python authority; the Python suite
// refuses any drift from the committed bytes, and `e2e/specs/fantasy-auction-optimizer.spec.ts`
// runs THIS module through the SAME file across the tree. If either side moves, one of them goes
// red. This repo has been bitten too often by one rule with two implementations (E9.61's two
// renderers, NF-EPIC 1's three scorers) to rely on discipline here.
//
// ══ WHY AN AUCTION NEEDS ITS OWN OPTIMIZER ══════════════════════════════════════════════════════
//
// A snake draft allocates a fixed sequence of PICKS. Nothing another team does changes what your
// pick is worth. An auction allocates a fixed pool of MONEY, and your purchasing power moves
// continuously as the room spends — which is why `draft-optimizer.ts` has no analog for the two
// quantities below and why bolting prices onto it would have been the wrong shape.
//
//   INFLATION    = dollars still in the room / value still on the board
//   MAX BID      = min(value x inflation, what you can pay without stranding a roster spot)
//
// ⛔ NOT AN EDGE CLAIM. These are OUR valuations of OUR projections, with no model of what the room
// will actually pay. `best_alpha = 0` throughout.

import {
  assignRoster,
  openStarterSlots,
  recommend,
  rosterRequirements,
  type LeagueConfigMeta,
  type Player,
  type Recommendation,
} from "@/lib/draft-optimizer"

/** One unit of the league's currency. A parameter (not a literal) because a league can run a $0
 *  minimum, and every derivation below is written in terms of it. */
export const DEFAULT_MIN_BID = 1

/**
 * The budget the published boards' `aucVal`/`aucLo`/`aucHi` are quoted at.
 *
 * ⭐ WHY THIS CLIENT RECOMPUTES RATHER THAN READING THE EXPORTED COLUMN, which is worth stating so
 * the column does not read as dead code. The board is exported once, quoted at ONE budget; a real
 * league can be on $100 or $300, and the values are not a linear rescale of each other (the
 * minimum-bid reserve does not scale with the budget). So reading `aucVal` would be right only for
 * a $200 league and quietly wrong for every other one.
 *
 * Recomputing from `vor` is exact at any budget and goes through the same formula the exporter
 * used — pinned to it by `auction_vectors.json` — so at $200 the two agree by construction rather
 * than by coincidence. The exported column remains the authoritative published value for any
 * consumer that is not this client.
 *
 * ⚠️ `manifest.auctionBudget` is what the exporter ACTUALLY used; this is the fallback for a
 * manifest that predates the field.
 */
export const DEFAULT_AUCTION_BUDGET = 200

/**
 * ⭐⭐ ROUND HALF UP — matching `auction.py::_round_half_up`, and it is a correctness requirement.
 *
 * Python's built-in `round` is BANKER'S rounding (`round(2.5) == 2`); JS `Math.round` is half up
 * (`Math.round(2.5) === 3`). Leaving each side on its native rounding makes the exported value and
 * the live recompute disagree by exactly $1 on every value landing on a half — invisible to the
 * eye, on the number a user is about to bid real money against. Every quantity here is
 * non-negative, so `Math.floor(x + 0.5)` is exactly half-up.
 *
 * ⚠️ `Math.round` happens to agree for non-negative inputs, so this is written out rather than
 * aliased: the next person to add a signed quantity must see the rule, not discover it.
 */
const roundHalfUp = (x: number): number => Math.floor(x + 0.5)

export interface AuctionPool {
  /** All the money in the room — `nTeams x budget`. */
  total: number
  /** Committed to minimum bids — `nTeams x rosterSpots x minBid`. Never contested. */
  reserve: number
  /** `total - reserve`. The only money a bidding war is actually about. */
  surplus: number
  rosterSpots: number
  nTeams: number
  budget: number
  minBid: number
  /** Roster spots across the whole league — how many players get bought. */
  spotsTotal: number
}

export function auctionPool(
  nTeams: number,
  rosterSpots: number,
  budget: number = DEFAULT_AUCTION_BUDGET,
  minBid: number = DEFAULT_MIN_BID,
): AuctionPool {
  const n = Math.max(1, Math.floor(nTeams))
  const spots = Math.max(1, Math.floor(rosterSpots))
  const b = Math.max(1, Math.floor(budget))
  const mb = Math.max(0, Math.floor(minBid))
  const total = n * b
  const reserve = n * spots * mb
  return {
    total,
    reserve,
    // ⚠️ Clamped at 0 rather than allowed to go negative. A league whose budget cannot cover its
    // own minimum bids is a misconfiguration; the honest degenerate answer is "everyone costs the
    // minimum", not a negative rate that would invert the whole board.
    surplus: Math.max(0, total - reserve),
    rosterSpots: spots,
    nTeams: n,
    budget: b,
    minBid: mb,
    spotsTotal: n * spots,
  }
}

/** Total spots on ONE team — starters AND bench. A bench spot still costs a dollar, so it belongs
 *  in the reserve. Mirrors `LeagueConfig.roster_spots()`. */
export const rosterSpotsOf = (config: LeagueConfigMeta): number =>
  config.roster.reduce((a, s) => a + s.count, 0)

/**
 * One player's dollar value.
 *
 * ⭐⭐ NO DOLLAR BAND, AND THE REASON IS MEASURED — see `fantasy_engine/auction.py::AuctionValue`
 * for the full record. In short: an auction dollar is a SHARE OF A FIXED POOL, so pricing the
 * projection's points interval through a rate and a replacement level computed for a different
 * world produces figures that are not on the dollar scale. On the served 2026 half-PPR 12-team
 * board the point values summed to the $2,400 pool exactly, while the low edges were $1 for all
 * 870 rows and the high edges summed to $9,882 — 412% of the money in the room.
 *
 * The projection's uncertainty is published where it is well-defined and correctly labelled: in
 * POINTS, on `Player.ptsP10`/`ptsP90`.
 */
export interface AuctionValue {
  id: string
  value: number
  /** Share of the board's total above-replacement value — the only budget-INDEPENDENT quantity
   *  here, which is what lets one exported board be re-priced for any league's budget. */
  share: number
}

/** Above-replacement value floored at zero; null/NaN reads as zero.
 *
 *  A genuinely unprojected gap-fill row carries `vor == null`. Treating it as 0 gives it the
 *  minimum bid — correct (he is free) and, unlike dropping him, keeps him visible on the board. */
const pos = (v: number | null | undefined): number =>
  v == null || !Number.isFinite(v) ? 0 : Math.max(0, v)

/**
 * Dollar-value every row of a board for one `pool`.
 *
 * `vorP10`/`vorP90` are deliberately NOT read — see `AuctionValue` above.
 */
export function auctionValues(board: Player[], pool: AuctionPool): AuctionValue[] {
  const vals = board.map((p) => pos(p.vor))

  // ⭐⭐ THE DENOMINATOR IS THE DRAFTABLE SET, NOT THE WHOLE BOARD. Only `spotsTotal` players are
  // ever BOUGHT, so only they can absorb the room's money; dividing by the whole board hands real
  // dollars to players nobody will roster and leaves the ones who ARE drafted worth less than the
  // money chasing them. Caught by the "inflation must open at ~1.00" check against the real board
  // fixture — 722 above-replacement rows against 180 roster spots opened the auction at 2.06x.
  //
  // The rate is still APPLIED to every row (a player outside the set is honestly worth what the
  // rate says); he is simply not part of the denominator. That makes the identity exact BY
  // CONSTRUCTION on any board shape: sum(value over the top `spotsTotal`) == pool.
  //
  // ⚠️ The ordering must match `auction.py` exactly. Both `Array.prototype.sort` (ES2019+) and
  // Python's `sorted` are STABLE, so ties fall back to the original row order on both sides.
  const draftable = vals
    .map((v, i) => i)
    .sort((a, b) => vals[b] - vals[a])
    .slice(0, pool.spotsTotal)
  const totalVor = draftable.reduce((a, i) => a + vals[i], 0)
  const rate = totalVor > 0 ? pool.surplus / totalVor : 0

  const price = (x: number) => Math.max(pool.minBid, roundHalfUp(pool.minBid + rate * x))

  return board.map((p, i) => ({
    id: p.id,
    value: price(vals[i]),
    share: totalVor > 0 ? Math.round((vals[i] / totalVor) * 1e6) / 1e6 : 0,
  }))
}

/** `{id -> value}` for O(1) lookup on every render. */
export function auctionValueMap(board: Player[], pool: AuctionPool): Map<string, AuctionValue> {
  const m = new Map<string, AuctionValue>()
  for (const v of auctionValues(board, pool)) m.set(v.id, v)
  return m
}

// ══ INFLATION ═══════════════════════════════════════════════════════════════════════════════════
//
// ⭐⭐ THE DYNAMIC A SNAKE OPTIMIZER HAS NO ANALOG FOR, and the half a reader most often gets
// backwards. Every dollar somebody OVERPAYS is a dollar no longer chasing the players still on the
// board, so everyone left gets CHEAPER — the multiplier goes BELOW 1. Bargains early leave
// purchasing power behind and push it ABOVE 1.
//
// It starts at ~1.00 by construction: the values were built to exhaust exactly this pool.

export interface Inflation {
  multiplier: number
  dollarsRemaining: number
  valueRemaining: number
  slotsRemaining: number
}

export function inflation(
  dollarsRemaining: number,
  remainingValues: number[],
  slotsRemaining: number,
): Inflation {
  const slots = Math.max(0, Math.floor(slotsRemaining))
  // ⚠️ THE DENOMINATOR IS THE DRAFTABLE REMAINDER, NOT THE WHOLE BOARD. A ~700-row board has a long
  // tail of minimum-bid players nobody will roster; counting them would drag the denominator up and
  // understate inflation for the entire draft.
  const top = [...remainingValues].sort((a, b) => b - a).slice(0, slots)
  const valueRemaining = top.reduce((a, b) => a + b, 0)
  const dollars = Math.max(0, dollarsRemaining)
  return {
    // A neutral 1.0 on a degenerate room is the only honest answer, and it keeps `value x
    // multiplier` finite. `Infinity` is a number in JS and would render as '∞' beside a dollar
    // sign — the `fullSeasonRate` lesson, one surface over.
    multiplier: valueRemaining > 0 ? dollars / valueRemaining : 1,
    dollarsRemaining: dollars,
    valueRemaining,
    slotsRemaining: slots,
  }
}

// ══ MAX BID ═════════════════════════════════════════════════════════════════════════════════════

export type BidBinding = "value" | "affordability" | "no_slot" | "roster_full"

export interface MaxBid {
  maxBid: number
  /** The board's sticker value. */
  value: number
  /** `value x inflation`, rounded — what he is worth at today's prices. */
  inflated: number
  /** The most you can bid and still put the minimum on every remaining spot. */
  affordable: number
  /** Your open roster spots BEFORE this player. */
  openSlots: number
  binding: BidBinding
}

/**
 * ⭐ THE NEVER-STRAND RULE — a correctness property, not a preference.
 *
 * An empty roster spot scores zero, so spending down to where a spot cannot be filled is not a
 * trade-off a drafter should make by accident. Whatever is left after this player must still cover
 * the minimum on every OTHER open spot:
 *
 *     affordable = budgetRemaining - minBid x (openSlots - 1)
 *
 * The cap is EXACT — with money to spare it is inert, and at the end of a draft it is total,
 * walking the last dollars down to $1 a spot. Deliberately no safety margin: a reserve above the
 * true minimum would be a made-up number overriding a real valuation.
 *
 * ⚠️ `no_slot` and `roster_full` are DISTINCT. "You have spots but none for a tight end" and "you
 * have no spots at all" are different facts, and rendering them identically is how a user ends up
 * re-checking the same thing twice.
 */
export function maxBid(
  value: number,
  inflationMultiplier: number,
  budgetRemaining: number,
  openSlots: number,
  opts: { minBid?: number; eligible?: boolean } = {},
): MaxBid {
  const minBid = opts.minBid ?? DEFAULT_MIN_BID
  const eligible = opts.eligible ?? true
  const slots = Math.max(0, Math.floor(openSlots))
  const budget = Math.max(0, Math.floor(budgetRemaining))
  const inflated = Math.max(minBid, roundHalfUp(value * inflationMultiplier))

  if (slots <= 0) {
    return { maxBid: 0, value, inflated, affordable: 0, openSlots: 0, binding: "roster_full" }
  }
  const affordable = budget - minBid * (slots - 1)
  if (!eligible) {
    return {
      maxBid: 0,
      value,
      inflated,
      affordable: Math.max(0, affordable),
      openSlots: slots,
      binding: "no_slot",
    }
  }
  if (affordable <= 0) {
    // Cannot even cover this spot's own minimum. Report 0, never a negative number.
    return { maxBid: 0, value, inflated, affordable: 0, openSlots: slots, binding: "affordability" }
  }
  return {
    maxBid: Math.min(inflated, affordable),
    value,
    inflated,
    affordable,
    openSlots: slots,
    binding: affordable < inflated ? "affordability" : "value",
  }
}

/**
 * What a BLANK price box records — ONE rule, shared by every surface that can record a sale.
 *
 * ⭐ It is deliberately the same number whoever won the player, because that is the only way a
 * single placeholder can be TRUTHFUL: the number the box shows greyed-out is exactly the number
 * that gets written. A per-button default (my max bid for "I won", his value for "Sold") reads
 * fine in code and lies on screen — one input, two silently different outcomes.
 *
 * `inflated` is his value at today's prices, floored at the minimum bid. It is a claim about the
 * PLAYER, not about my budget, which is what makes it answer both buttons. It can exceed what I
 * have left; that is not clamped, because a clamp that cannot announce itself makes "recorded what
 * you typed" and "recorded something else" pixel-identical (E9.62).
 */
export const defaultSalePrice = (bid: MaxBid): number => bid.inflated

/** `$X left for Y slots = $Z/slot` — the single most-used number at an auction table. */
export const dollarsPerSlot = (budgetRemaining: number, openSlots: number): number =>
  openSlots <= 0 ? 0 : Math.max(0, budgetRemaining) / Math.max(1, Math.floor(openSlots))

// ══ FORMATTING — ONE function, every surface ════════════════════════════════════════════════════
//
// ⭐ SHARED DELIBERATELY. The board column, the max-bid panel and the nomination list all render
// dollars, and three inline `$${x.toFixed(0)}` expressions are three rule sets that drift (the
// E9.61 "two renderers of one field" lesson). A null must render as an em-dash, never "$NaN" or
// "$0" — "we don't have a value" and "he is worth nothing" are different facts.

export const formatMoney = (v: number | null | undefined): string =>
  v == null || !Number.isFinite(v) ? "—" : `$${Math.round(v)}`

/**
 * The projection's own 80% interval, in POINTS — which is where this uncertainty is well-defined.
 *
 * ⭐ THE UNITS ARE THE WHOLE POINT. The retired `formatMoneyRange` rendered the same interval with
 * a `$` in front of it, and a dollar is a share of a fixed pool rather than a level, so the two
 * edges were not prices (see `AuctionValue`). In points the interval means exactly what it says:
 * eight seasons in ten land between these two numbers.
 */
export const formatPointsRange = (
  low: number | null | undefined,
  high: number | null | undefined,
): string => {
  if (low == null || high == null || !Number.isFinite(low) || !Number.isFinite(high)) return "—"
  const lo = Math.round(low)
  const hi = Math.round(high)
  return lo === hi ? `${lo} pts` : `${lo}–${hi} pts`
}

/** The inflation multiplier as the room would say it. */
export const formatInflation = (m: number): string => `${m.toFixed(2)}x`

// ══ THE LIVE STATE ══════════════════════════════════════════════════════════════════════════════

/** One completed auction: who went, to which team, for how much. */
export interface AuctionPick {
  id: string
  /** 1-indexed team number. */
  team: number
  price: number
}

export interface AuctionArgs {
  board: Player[]
  config: LeagueConfigMeta
  nTeams: number
  budget: number
  /** 1-indexed — which team is me. */
  myTeam: number
  picks: AuctionPick[]
  /** The budget the board's exported `aucVal` was quoted at. Unused by the math (values are
   *  recomputed from `vor` for the ACTUAL budget) but carried so a surface can say so. */
  quotedAtBudget?: number
  topN?: number
}

export interface AuctionCandidate {
  player: Player
  /** The full valuation, band included. */
  auction: AuctionValue
  bid: MaxBid
  /** The snake engine's roster-need reading, reused verbatim — see `auctionBoard`. */
  rec: Recommendation
  /** Whether one of MY open roster slots can accept this position. */
  eligible: boolean
  /** The "why this bid" sentence. ⚠️ Built here rather than in the component so the board, the
   *  panel and the tooltip cannot describe the same bid three different ways. */
  why: string
}

export interface TeamBudget {
  team: number
  /** What this team has actually paid out. Always honest, never clamped. */
  spent: number
  /** Money still available to bid with — floored at 0. See the note in `teamBudgets`. */
  remaining: number
  filled: number
  openSlots: number
  /** True when recorded prices exceed this team's budget. Surfaced so an entry mistake is
   *  VISIBLE rather than silently absorbed into the room's arithmetic. */
  overspent: boolean
}

export type NominationMode = "target" | "drain" | "balanced"

export interface NominationPlan {
  mode: NominationMode
  /** One sentence naming the mode and the observation behind it. */
  reason: string
  /** Who to put up, given the mode. Never more than a handful. */
  players: Player[]
}

export interface AuctionBoard {
  pool: AuctionPool
  values: Map<string, AuctionValue>
  inflation: Inflation
  /** Every team's money, mine included. */
  budgets: TeamBudget[]
  me: TeamBudget
  myPlayers: Player[]
  perSlot: number
  /** Ranked candidates for MY next bid. */
  candidates: AuctionCandidate[]
  nomination: NominationPlan
  /** Positions one of MY still-open roster slots can accept. */
  openEligibility: Set<string>
  /**
   * ⭐ THE MAX BID FOR **ANY** PLAYER, not just a ranked candidate — exposed because the
   * recommendation panel and the available-players table both show one.
   *
   * The first cut recomputed it inline in the table, and got a DIFFERENT answer: it applied the
   * affordability cap but neither the inflation multiplier nor the roster-eligibility check, so the
   * same player showed one number in the panel and another in the table three rows below. That is
   * the E9.61 "two renderers of one field are two rule sets" defect exactly, on the number a user
   * bids real money against. One function, every surface.
   */
  bidFor: (player: Player) => MaxBid
}

/**
 * The room's money and slots, team by team.
 *
 * ⚠️ `remaining` IS FLOORED AT 0, and the asymmetry with `openSlots` is the bug this fixes.
 * `openSlots` has always clamped at 0 (a team cannot hold more players than it has spots), while
 * `remaining` did not — so a team credited with more purchases than it can hold went NEGATIVE and
 * its negative buying power silently cancelled out other teams' real money in the room total.
 *
 * That was reachable because "Sold" hardcoded the winning team: EVERY rival purchase piled onto one
 * team. Measured on a 10-team/17-slot/$200 league, the room's DOLLARS stayed correct (the negative
 * offset exactly) but its SLOT count did not — past 17 purchases the surplus buys became invisible
 * to `openSlots`, and by the end of a draft the room would count ~136 open slots that do not exist,
 * which is the denominator `inflation` divides by.
 *
 * The UI now refuses to sell to a team with no open slot, so the state is unreachable from the
 * front — this floor is the arithmetic backstop for a hand-entered price that overshoots a budget.
 */
function teamBudgets(args: AuctionArgs, slotsPerTeam: number): TeamBudget[] {
  const out: TeamBudget[] = []
  for (let t = 1; t <= args.nTeams; t++) {
    const own = args.picks.filter((p) => p.team === t)
    const spent = own.reduce((a, p) => a + p.price, 0)
    out.push({
      team: t,
      spent,
      remaining: Math.max(0, args.budget - spent),
      filled: own.length,
      openSlots: Math.max(0, slotsPerTeam - own.length),
      overspent: spent > args.budget,
    })
  }
  return out
}

/**
 * Everything the auction screen renders, recomputed from scratch on every pick.
 *
 * ⭐ THE ROSTER-NEED ORDERING IS THE SNAKE ENGINE'S, REUSED VERBATIM. "Which player does my roster
 * want next" is the same question in both formats — VONA, tier cliffs, the flex seat's own
 * replacement, the K/DST deferral, the must-fill reserve — and none of it is about money. Only the
 * PRICE is auction-specific. Writing a second need model here would give the two surfaces different
 * opinions about the same roster, which is exactly the divergence `sortAvailable` and `assignRoster`
 * were pulled into the shared module to prevent.
 */
export function auctionBoard(args: AuctionArgs): AuctionBoard {
  const { board, config, nTeams, budget, myTeam, picks, topN = 8 } = args
  const slotsPerTeam = rosterSpotsOf(config)
  const pool = auctionPool(nTeams, slotsPerTeam, budget)
  const values = auctionValueMap(board, pool)

  const draftedIds = new Set(picks.map((p) => p.id))
  const myPlayerIds = picks.filter((p) => p.team === myTeam).map((p) => p.id)
  const byId = new Map(board.map((p) => [p.id, p]))
  const myPlayers = myPlayerIds.map((id) => byId.get(id)).filter(Boolean) as Player[]

  const budgets = teamBudgets(args, slotsPerTeam)
  const me = budgets[myTeam - 1] ?? {
    team: myTeam,
    spent: 0,
    remaining: budget,
    filled: 0,
    openSlots: slotsPerTeam,
    overspent: false,
  }

  const available = board.filter((p) => !draftedIds.has(p.id))
  const roomDollars = budgets.reduce((a, b) => a + b.remaining, 0)
  const roomSlots = budgets.reduce((a, b) => a + b.openSlots, 0)
  const infl = inflation(
    roomDollars,
    available.map((p) => values.get(p.id)?.value ?? pool.minBid),
    roomSlots,
  )

  // Which positions one of MY still-open slots can accept. `assignRoster` is the shared answer to
  // "which of my slots are open" — a second implementation here would let the panel and the bid
  // disagree about whether a slot exists.
  const myOpenEligibility = new Set<string>()
  for (const fs of assignRoster(myPlayers, config.roster)) {
    if (!fs.player) fs.eligible.forEach((e) => myOpenEligibility.add(e))
  }

  /** ⭐ THE ONE PLACE A MAX BID IS COMPUTED. Every surface calls this — see `bidFor` on the
   *  returned object for why that matters. */
  const bidFor = (player: Player): MaxBid =>
    maxBid(
      values.get(player.id)?.value ?? pool.minBid,
      infl.multiplier,
      me.remaining,
      me.openSlots,
      { minBid: pool.minBid, eligible: myOpenEligibility.has(player.pos) },
    )

  const recs = recommend({ board, config, draftedIds, myPlayerIds, topN: Math.max(topN, 24) })
  const candidates: AuctionCandidate[] = recs.map((rec) => {
    const v = values.get(rec.player.id) ?? { id: rec.player.id, value: pool.minBid, share: 0 }
    const bid = bidFor(rec.player)
    return {
      player: rec.player,
      auction: v,
      bid,
      rec,
      eligible: myOpenEligibility.has(rec.player.pos),
      why: bidExplanation(bid, infl, me.remaining),
    }
  })

  return {
    pool,
    values,
    inflation: infl,
    budgets,
    me,
    myPlayers,
    perSlot: dollarsPerSlot(me.remaining, me.openSlots),
    candidates: candidates.slice(0, topN),
    nomination: nominationPlan({ candidates, budgets, me, inflation: infl, available, values }),
    openEligibility: myOpenEligibility,
    bidFor,
  }
}

/**
 * The "why this bid" line — ONE function, so the row, the panel and the tooltip cannot disagree.
 *
 * ⚠️ SHORT ON PURPOSE. `truncate` sets `white-space: nowrap`, which makes a long sentence the
 * MIN-CONTENT width of its grid track and hands the whole page a horizontal scrollbar (measured on
 * the snake optimizer at 2129px). The mechanism belongs in the panel's tooltip; the row names the
 * numbers.
 */
export function bidExplanation(bid: MaxBid, infl: Inflation, budgetRemaining: number): string {
  switch (bid.binding) {
    case "roster_full":
      return "Your roster is full — no slot left to bid for"
    case "no_slot":
      return "No open slot on your roster fits this position"
    case "affordability": {
      // What the OTHER open slots have to keep back. Derived from the cap rather than recomputed
      // from `minBid`, so a league on a non-$1 minimum cannot make the sentence contradict the
      // number it is explaining.
      const reserved = Math.max(0, budgetRemaining - bid.affordable)
      const others = bid.openSlots - 1
      return bid.maxBid === 0
        ? `Can't bid — ${formatMoney(budgetRemaining)} left has to cover ${bid.openSlots} open slot${bid.openSlots === 1 ? "" : "s"}`
        : `Capped by your budget: worth ${formatMoney(bid.inflated)}, but ${others} other slot${others === 1 ? "" : "s"} must keep ${formatMoney(reserved)}`
    }
    default: {
      const drift = bid.inflated - bid.value
      if (drift === 0) return `Worth ${formatMoney(bid.value)}; prices are at par`
      return drift > 0
        ? `${formatMoney(bid.value)} value, ${formatMoney(bid.inflated)} at today's ${formatInflation(infl.multiplier)} prices — the room has money left`
        : `${formatMoney(bid.value)} value, ${formatMoney(bid.inflated)} at today's ${formatInflation(infl.multiplier)} prices — the room has overspent`
    }
  }
}

/**
 * NOMINATION STRATEGY — who to put up, and why.
 *
 * Three readings, in priority order. Each is a statement about the room that the numbers on screen
 * already show, never a claim about what anyone will pay:
 *
 *   SOFT market (inflation below par) — players are going for less than they are worth, so put up
 *     the ones YOU want and let the discount come to you.
 *   FLUSH (your money per slot is above the room's) — your advantage is relative, so spend other
 *     people's money first: nominate expensive players you do NOT need.
 *   BALANCED — no edge either way; nominate from your surplus positions.
 */
export function nominationPlan(args: {
  candidates: AuctionCandidate[]
  budgets: TeamBudget[]
  me: TeamBudget
  inflation: Inflation
  available: Player[]
  values: Map<string, AuctionValue>
}): NominationPlan {
  const { candidates, budgets, me, inflation: infl, available, values } = args
  const others = budgets.filter((b) => b.team !== me.team)
  const otherDollars = others.reduce((a, b) => a + b.remaining, 0)
  const otherSlots = others.reduce((a, b) => a + b.openSlots, 0)
  const roomPerSlot = otherSlots > 0 ? otherDollars / otherSlots : 0
  const myPerSlot = dollarsPerSlot(me.remaining, me.openSlots)

  const valueOf = (p: Player) => values.get(p.id)?.value ?? 0
  const byValue = [...available].sort((a, b) => valueOf(b) - valueOf(a))

  // ⚠️ A 5% band around parity, so a room sitting at exactly par does not flip the advice back and
  // forth between two opposite strategies on every pick.
  const SOFT = 0.97
  const FLUSH = 1.05

  if (infl.multiplier < SOFT && candidates.length) {
    return {
      mode: "target",
      reason: `Prices are ${formatInflation(infl.multiplier)} of value — the room has overspent, so what is left is going cheap. Nominate players you actually want.`,
      players: candidates.filter((c) => c.eligible && c.bid.maxBid > 0).slice(0, 5).map((c) => c.player),
    }
  }

  if (me.openSlots > 0 && roomPerSlot > 0 && myPerSlot > roomPerSlot * FLUSH) {
    const wanted = new Set(candidates.slice(0, 8).map((c) => c.player.id))
    return {
      mode: "drain",
      reason: `You have ${formatMoney(myPerSlot)} per open slot against the room's ${formatMoney(roomPerSlot)} — spend their money first. Nominate expensive players you do not need.`,
      players: byValue.filter((p) => !wanted.has(p.id)).slice(0, 5),
    }
  }

  const wanted = new Set(candidates.slice(0, 5).map((c) => c.player.id))
  return {
    mode: "balanced",
    reason: `Prices are near par (${formatInflation(infl.multiplier)}) and your ${formatMoney(myPerSlot)} per slot is in line with the room. Nominate from positions you are already deep at.`,
    players: byValue.filter((p) => !wanted.has(p.id)).slice(0, 5),
  }
}

/** My still-open starter slots, for the needs chips — the shared snake helper, unchanged. */
export function openSlotsFor(myPlayers: Player[], config: LeagueConfigMeta) {
  return openStarterSlots(myPlayers.map((p) => p.pos), rosterRequirements(config.roster))
}
